--Porject Name: Automation Files Center
--Author: Huang Moyue 
--Mail: mhuang1@ra.rockwell.com
--Date:07/08/2014
--Summary: Automation Files Center Job Logs and set up process
--Version: 0.5

1. Oracle Client Setup
	1.1 Net Service Name: data_analysis
		SERVICE_NAME: APAFC
		SID: APAFC
		HOST: APCNXMNGYKG422
		PORT: 1523
		PW:apafc198617
		Database Control URL :https://localhost:5500/em 
	1.2 DB LINK CREATE
		DB LINK NAME:ROCKWELL_DW_DBLINK
		Connection:	RA_DB_Oracle		Host_Name:	risop.mke.ra.rockwell.com
		User_Name:	INVANALYST		Port:	1522
		PWD:	Materials1		SID:	RISOP
    create table INV_SAP_PP_OPT_X_BK12 as 
		
    SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DW_DBLINK where plant IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');
    
    create table INV_SAP_PP_OPTIMIZATION_BK12 as 
		SELECT CATALOG_STRING1 FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG WHERE CATALOG_STRING1 = '889N-F4AFC-50F' AND PLANTID = '5040' AND EBELNPURCHDOCNO = '6301023325';
    SELECT MATERIALID,PLANTID,LOCATIONID,TOTAL_OH_QTY FROM DWQ$LIBRARIAN.INV_SAP_INVENTORY_BY_PLANT WHERE MATERIALID = '1756-OB32 A' AND PLANTID = '5040'
    
    
	1.3 Ini Setup
		DROP TABLE INV_SAP_PP_OPTIMIZATION;
		CREATE TABLE INV_SAP_PP_OPTIMIZATION AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DW_DBLINK WHERE MATERIALID = '1756-HYD02 A' AND PLANTID = '5140';
		
  

    
    select ANALYSIS_LINESPEED_X,SERVICE_LEVEL from INV_SAP_PP_SERVICE_LEVELS where LEVEL_VALUE = 'ACSA171' AND PLANTID = '5201' AND ANALYSIS_COST_X = '1-Expensive';
    select ANALYSIS_LINESPEED_X,SERVICE_LEVEL from INV_SAP_PP_SERVICE_LEVELS_0309 where LEVEL_VALUE = 'ACSA171' AND PLANTID = '5201' AND ANALYSIS_COST_X = '1-Expensive';

 		DROP TABLE INV_SAP_PP_SERVICE_LEVELS;
		CREATE TABLE INV_SAP_PP_SERVICE_LEVELS_IND AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_SERVICE_LEVELS@ROCKWELL_DW_DBLINK;   
    
    CREATE TABLE INV_SAP_PLAN_PARAM_USERLOG AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PLAN_PARAM_USERLOG@ROCKWELL_DW_DBLINK;
    SELECT * FROM INV_SAP_PLAN_PARAM_USERLOG;
    
		DROP TABLE INV_SAP_SALES_VBAK_VBAP_VBUP;
		CREATE TABLE INV_SAP_SALES_VBAK_VBAP_VBUP AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DW_DBLINK;


		DROP TABLE INV_SAP_PP_FRCST_PBIM_PBED;
		CREATE TABLE INV_SAP_PP_FRCST_PBIM_PBED AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

		DROP TABLE INV_SAP_LIKP_LIPS_DAILY; 
		CREATE TABLE INV_SAP_LIKP_LIPS_DAILY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY@ROCKWELL_DW_DBLINK WHERE CREATED_ON_DATE > SYSDATE - 91;

		DROP TABLE INV_SAP_INVENTORY_BY_PLANT;
		CREATE TABLE INV_SAP_INVENTORY_BY_PLANT AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_INVENTORY_BY_PLANT@ROCKWELL_DW_DBLINK;
    SELECT * FROM INV_SAP_INVENTORY_BY_PLANT;
		DROP TABLE INV_SAP_PP_PO_HISTORY;
		CREATE TABLE INV_SAP_PP_PO_HISTORY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');
    
    DROP TABLE INV_SAP_PP_PO_HISTORY_ALL;
    CREATE TABLE INV_SAP_PP_PO_HISTORY_ALL AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DW_DBLINK;
    
    
   'PN-141666'
		DROP TABLE INV_SAP_IO_INPUTS_DAILY;
		CREATE TABLE INV_SAP_IO_INPUTS_DAILY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_IO_INPUTS_DAILY@ROCKWELL_DW_DBLINK;
			
		DROP TABLE INV_SAP_SALES_HST;
		CREATE TABLE INV_SAP_SALES_HST AS
		SELECT COUNT(*) FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DW_DBLINK WHERE materialid = 'PN-141666';
    
		DROP TABLE INV_SAP_PP_MVKE;
		CREATE TABLE INV_SAP_PP_MVKE AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE@ROCKWELL_DW_DBLINK;

SELECT MATERIALID,DIRECT_SHIP_PLANT,SALES_ORG, ALLOWED_SCHED_RTRN  FROM INV_SAP_PP_MVKE WHERE SALES_ORG IN ('5003','5008','5014','5000')
SELECT * FROM INV_SAP_PP_PO_HISTORY_ALL where plantid in ('5040');

SELECT * FROM INV_SAP_SALES_HST_LC where BU in ('PBS','LGC') AND PLANT = '5040' AND CREATION_DATE BETWEEN SYSDATE - 300 AND SYSDATE;


2. Oracle Job Setup

--Daily Jobs
	2.1 Job Name: Job_Daily_INV_PP_OPT
		Job Time: 0:30 AM
		Job Repeat Frequency: Daily, 5 days per week
    Job running time: 90mins
      
		Job Procedure:		
    DECLARE
      TRUNCATE_TABLE_PP_OPTIMIZATION   VARCHAR2(1000);
      INSERT_TABLE_PP_OPTIMIZATION VARCHAR2(1000);
    BEGIN
      TRUNCATE_TABLE_PP_OPTIMIZATION   := 'TRUNCATE TABLE INV_SAP_PP_OPTIMIZATION';
      INSERT_TABLE_PP_OPTIMIZATION := 'INSERT INTO INV_SAP_PP_OPTIMIZATION 
      SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DW_DBLINK';
      EXECUTE IMMEDIATE TRUNCATE_TABLE_PP_OPTIMIZATION;
      EXECUTE IMMEDIATE INSERT_TABLE_PP_OPTIMIZATION;
    END;
    
    DROP TABLE INV_SAP_PP_OPTIMIZATION_STABLE;
    CREATE TABLE INV_SAP_PP_OPTIMIZATION_STABLE AS SELECT * FROM INV_SAP_PP_OPTIMIZATION_S_1019;
    
    SELECT  FROM INV_SAP_PP_OPTIMIZATION_STABLE;
		Job Initialization: 
		DROP TABLE INV_SAP_PP_OPTIMIZATION;
		CREATE TABLE INV_SAP_PP_OPTIMIZATION AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DW_DBLINK;
   
    SELECT * FROM INV_SAP_PP_OPTIMIZATION;
    
	2.2 Job Name: Job_Daily_PP_TABLE
		Job Time: 2:30 AM
		Job Repeat Frequency: Daily
		Job running time: 30mins
    
		Job Procedure:		
		DECLARE
		  TRUNCATE_TABLE_INV_PP_TABLE  VARCHAR2(1000);
		  INSERT_TABLE_INV_PP_TABLE  VARCHAR2(1000);
		BEGIN
		  TRUNCATE_TABLE_INV_PP_TABLE   := 'TRUNCATE TABLE INV_SAP_PP_OPT_X';
		  INSERT_TABLE_INV_PP_TABLE := 'INSERT INTO INV_SAP_PP_OPT_X SELECT * FROM VIEW_INV_SAP_PP_OPT_X';
		  EXECUTE IMMEDIATE TRUNCATE_TABLE_INV_PP_TABLE;
		  EXECUTE IMMEDIATE INSERT_TABLE_INV_PP_TABLE;
		END;

		Job Initialization: 
		DROP TABLE INV_SAP_PP_OPT_X;
		CREATE TABLE INV_SAP_PP_OPT_X AS SELECT * FROM VIEW_INV_SAP_PP_OPT_X;

		DROP TABLE INV_SAP_PP_OPT_X_STABLE;
		CREATE TABLE INV_SAP_PP_OPT_X_STABLE AS SELECT * FROM INV_SAP_PP_OPT_X;

    SELECT PLANTID, MATERIALID,STRATEGY_GRP FROM INV_SAP_PP_OPTIMIZATION WHERE STRATEGY_GRP = '40' AND PLANTID = '1090'
    SELECT * FROM INV_SAP_PP_OPT_X WHERE PLANT = '1090';

SELECT MATERIAL,STRATEGY_GRP FROM INV_SAP_PP_OPT_X WHERE STRATEGY_GRP = '40' AND PLANT IN  ('5040'), '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');


	2.3 Job Name: Job_Daily_INV_SO_OPEN
		Job Time: 3:00 AM
		Job Repeat Frequency: Daily
		Job running time: 5mins
    
		Job Procedure:
		DECLARE
		  TRUNCATE_TABLE_OPEN_SALES   VARCHAR2(1000);
		  INSERT_TABLE_OPEN_SALES  VARCHAR2(1000);
		BEGIN
		  TRUNCATE_TABLE_OPEN_SALES   := 'TRUNCATE TABLE INV_SAP_SALES_VBAK_VBAP_VBUP';
		  INSERT_TABLE_OPEN_SALES := 'INSERT INTO INV_SAP_SALES_VBAK_VBAP_VBUP SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DW_DBLINK';
		  EXECUTE IMMEDIATE TRUNCATE_TABLE_OPEN_SALES;
		  EXECUTE IMMEDIATE INSERT_TABLE_OPEN_SALES;
		END;
		
		Job Initialization:
    SELECT * FROM INV_SAP_SALES_VBAK_VBAP_VBUP;
		Drop table INV_SAP_SALES_VBAK_VBAP_VBUP;
		CREATE TABLE INV_SAP_SALES_VBAK_VBAP_VBUP AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DW_DBLINK;

	2.4 Job Name: Job_Daily_INV_PP_FCST
		Job Time: 3:20 AM
		Job Repeat Frequency: Daily
		Job running time: 5mins
		Job Procedure:
		DECLARE
		  TRUNCATE_TABLE_OPEN_FC   VARCHAR2(1000);
		  INSERT_TABLE_OPEN_FC  VARCHAR2(1000);
		BEGIN
		  TRUNCATE_TABLE_OPEN_FC   := 'TRUNCATE TABLE INV_SAP_PP_FRCST_PBIM_PBED';
		  INSERT_TABLE_OPEN_FC := 'INSERT INTO INV_SAP_PP_FRCST_PBIM_PBED 
		  SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('||5040||', '||5050||', '||5100||', '||5110||', '||5120||', '||5160||', '||5190||', '||5200||','||5070||','||5140||')';
		  EXECUTE IMMEDIATE TRUNCATE_TABLE_OPEN_FC;
		  EXECUTE IMMEDIATE INSERT_TABLE_OPEN_FC;
		END;
		
		Job Initialization:
		SELECT * FROM INV_SAP_PP_FRCST_PBIM_PBED;
    DROP TABLE INV_SAP_PP_FRCST_PBIM_PBED;
		CREATE TABLE INV_SAP_PP_FRCST_PBIM_PBED AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

	2.5 Job Name: Job_Daily_INV_DELY
		Job Time: 3:40 AM
		Job Repeat Frequency: Daily
		Job running time: 10 mins
		Job Procedure:
		DECLARE
		  TRUNCATE_TABLE_DELIVERY_REC  VARCHAR2(1000);
		  INSERT_TABLE_DELIVERY_REC  VARCHAR2(1000);
		BEGIN
		  TRUNCATE_TABLE_DELIVERY_REC   := 'TRUNCATE TABLE INV_SAP_LIKP_LIPS_DAILY';
		  INSERT_TABLE_DELIVERY_REC := 'INSERT INTO INV_SAP_LIKP_LIPS_DAILY 
		  SELECT * FROM DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY@ROCKWELL_DW_DBLINK WHERE CREATED_ON_DATE > SYSDATE - 91';
		  EXECUTE IMMEDIATE TRUNCATE_TABLE_DELIVERY_REC;
		  EXECUTE IMMEDIATE INSERT_TABLE_DELIVERY_REC;
		END;
		
		Job Initialization:
    SELECT * FROM INV_SAP_LIKP_LIPS_DAILY;
		DROP TABLE INV_SAP_LIKP_LIPS_DAILY; 
		CREATE TABLE INV_SAP_LIKP_LIPS_DAILY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY@ROCKWELL_DW_DBLINK WHERE CREATED_ON_DATE > SYSDATE - 91;

	2.6 Job Name: Job_Daily_INV_PLANT
		Job Time: 4:05 AM
		Job Repeat Frequency: Daily
		Job running time: 5mins
		Job Procedure:
		DECLARE
		  TRUNCATE_TABLE_INVENTORY_REC  VARCHAR2(1000);
		  INSERT_TABLE_INVENTORY_REC  VARCHAR2(1000);
		BEGIN
		  TRUNCATE_TABLE_INVENTORY_REC   := 'TRUNCATE TABLE INV_SAP_INVENTORY_BY_PLANT';
		  INSERT_TABLE_INVENTORY_REC := 'INSERT INTO INV_SAP_INVENTORY_BY_PLANT 
		  SELECT * FROM DWQ$LIBRARIAN.INV_SAP_INVENTORY_BY_PLANT@ROCKWELL_DW_DBLINK';
		  EXECUTE IMMEDIATE TRUNCATE_TABLE_INVENTORY_REC;
		  EXECUTE IMMEDIATE INSERT_TABLE_INVENTORY_REC;
		END;
		
		Job Initialization:
    SELECT * FROM INV_SAP_INVENTORY_BY_PLANT;
		DROP TABLE INV_SAP_INVENTORY_BY_PLANT;
		CREATE TABLE INV_SAP_INVENTORY_BY_PLANT AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_INVENTORY_BY_PLANT@ROCKWELL_DW_DBLINK;
    

	2.7 Job Name: Job_Daily_INV_PP_PO
		Job Time: 4:20 AM
		Job Repeat Frequency: Daily
		Job running time: 10mins
		Job Procedure:
		DECLARE
		  TRUNCATE_TABLE_PP_PO_HISTORY  VARCHAR2(1000);
		  INSERT_TABLE_PP_PO_HISTORY  VARCHAR2(1000);
		BEGIN
		  TRUNCATE_TABLE_PP_PO_HISTORY   := 'TRUNCATE TABLE INV_SAP_PP_PO_HISTORY';
		  INSERT_TABLE_PP_PO_HISTORY := 'INSERT INTO INV_SAP_PP_PO_HISTORY 
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('||5040||', '||5050||', '||5100||', '||5110||', '||5120||', '||5160||', '||5190||', '||5200||','||5070||','||5140||')';
		  EXECUTE IMMEDIATE TRUNCATE_TABLE_PP_PO_HISTORY;
		  EXECUTE IMMEDIATE INSERT_TABLE_PP_PO_HISTORY;
		END;
		
    SELECT * FROM INV_SAP_PP_PO_HISTORY_ALL;
    SELECT * FROM INV_SAP_PP_PO_HISTORY;
    
    
    DROP TABLE INV_SAP_PP_PO_HISTORY_ALL;
    CREATE TABLE INV_SAP_PP_PO_HISTORY_ALL AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DW_DBLINK;
    
    DECLARE
		  TRUNCATE_TABLE_PP_PO_HISTORY  VARCHAR2(1000);
		  INSERT_TABLE_PP_PO_HISTORY  VARCHAR2(1000);
		BEGIN
		  TRUNCATE_TABLE_PP_PO_HISTORY   := 'TRUNCATE TABLE INV_SAP_PP_PO_HISTORY';
		  INSERT_TABLE_PP_PO_HISTORY := 'INSERT INTO INV_SAP_PP_PO_HISTORY 
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('||5040||', '||5050||', '||5100||', '||5110||', '||5120||', '||5160||', '||5190||', '||5200||','||5070||','||5140||')';
		  EXECUTE IMMEDIATE TRUNCATE_TABLE_PP_PO_HISTORY;
		  EXECUTE IMMEDIATE INSERT_TABLE_PP_PO_HISTORY;
		END; 
    
		Job Initialization: 
		DROP TABLE INV_SAP_PP_PO_HISTORY;
		CREATE TABLE INV_SAP_PP_PO_HISTORY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

	2.8 Job Name: Job_Daily_INV_IO
		Job Time: 4:50 AM
		Job Repeat Frequency: Daily
    Job running time: 30mins
		Job Procedure:
    DECLARE
      TRUNCATE_TABLE_IO_REC  VARCHAR2(1000);
      INSERT_TABLE_IO_REC  VARCHAR2(1000);
    BEGIN
      TRUNCATE_TABLE_IO_REC   := 'TRUNCATE TABLE INV_SAP_IO_INPUTS_DAILY';
      INSERT_TABLE_IO_REC := 'INSERT INTO INV_SAP_IO_INPUTS_DAILY
    SELECT * FROM DWQ$LIBRARIAN.INV_SAP_IO_INPUTS_DAILY@ROCKWELL_DW_DBLINK';
      EXECUTE IMMEDIATE TRUNCATE_TABLE_IO_REC;
      EXECUTE IMMEDIATE INSERT_TABLE_IO_REC;
    END;
		
		Job Initialization:
    SELECT * FROM INV_SAP_IO_INPUTS_DAILY;
		DROP TABLE INV_SAP_IO_INPUTS_DAILY;
		CREATE TABLE INV_SAP_IO_INPUTS_DAILY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_IO_INPUTS_DAILY@ROCKWELL_DW_DBLINK;
				
	2.9 Job Name: Job_Daily_FCSTAT55_TABLE
		Job Time: 5:30 AM
		Job Repeat Frequency: Daily
    Job running time: 5mins
		Job Procedure: 
		DECLARE
		  TRUNCATE_TABLE_INV_FCSTAT  VARCHAR2(1000);
		  INSERT_TABLE_INV_FCSTAT  VARCHAR2(1000);
		BEGIN
		  TRUNCATE_TABLE_INV_FCSTAT   := 'TRUNCATE TABLE INV_SAP_FC55_STATS';
		  INSERT_TABLE_INV_FCSTAT := 'INSERT INTO INV_SAP_FC55_STATS SELECT * FROM VIEW_INV_SAP_FC55_STATS';
		  EXECUTE IMMEDIATE TRUNCATE_TABLE_INV_FCSTAT;
		  EXECUTE IMMEDIATE INSERT_TABLE_INV_FCSTAT;
		END;
  	
		Job Initialization:
    
		DROP TABLE INV_SAP_FC55_STATS;
		CREATE TABLE INV_SAP_FC55_STATS AS
		SELECT * FROM VIEW_INV_SAP_FC55_STATS;
		
	2.10 Job Name: Job_Daily_FCSTAT00_TABLE
		Job Time: 5:45 AM
		Job Repeat Frequency: Daily
    Job running time: 5mins
		Job Procedure: 
		DECLARE
		  TRUNCATE_TABLE_INV_FCSTAT  VARCHAR2(1000);
		  INSERT_TABLE_INV_FCSTAT  VARCHAR2(1000);
		BEGIN
		  TRUNCATE_TABLE_INV_FCSTAT   := 'TRUNCATE TABLE INV_SAP_FC00_STATS';
		  INSERT_TABLE_INV_FCSTAT := 'INSERT INTO INV_SAP_FC00_STATS SELECT * FROM VIEW_INV_SAP_FC00_STATS';
		  EXECUTE IMMEDIATE TRUNCATE_TABLE_INV_FCSTAT;
		  EXECUTE IMMEDIATE INSERT_TABLE_INV_FCSTAT;
		END;
    
		Job Initialization: 
		DROP TABLE INV_SAP_FC00_STATS;
		CREATE TABLE INV_SAP_FC00_STATS AS
		SELECT * FROM VIEW_INV_SAP_FC00_STATS;
		
	2.11 Job Name: Job_Daily_BLSO_TABLE
		Job Time: 5:55 AM
		Job Repeat Frequency: Daily
    Job running time: 5mins
		Job Procedure:
		DECLARE
		  TRUNCATE_TABLE_INV_BLSO_TABLE  VARCHAR2(1000);
		  INSERT_TABLE_INV_BLSO_TABLE  VARCHAR2(1000);
		BEGIN
		  TRUNCATE_TABLE_INV_BLSO_TABLE   := 'TRUNCATE TABLE INV_SAP_BACKLOG_SO';
		  INSERT_TABLE_INV_BLSO_TABLE := 'INSERT INTO INV_SAP_BACKLOG_SO SELECT * FROM VIEW_INV_SAP_BACKLOG_SO';
		  EXECUTE IMMEDIATE TRUNCATE_TABLE_INV_BLSO_TABLE;
		  EXECUTE IMMEDIATE INSERT_TABLE_INV_BLSO_TABLE;
		END;    
    
		Job Initialization:
    SELECT * FROM INV_SAP_BACKLOG_SO;
		DROP TABLE INV_SAP_BACKLOG_SO;
		CREATE TABLE INV_SAP_BACKLOG_SO AS
		SELECT * FROM VIEW_INV_SAP_BACKLOG_SO;
		
	2.12 Job Name: Job_Daily_BLINV_TABLE
		Job Time: 6:10 AM
		Job Repeat Frequency: Daily
    Job running time: 5mins
		Job Procedure:
		DECLARE
		  TRUNCATE_TABLE_INV_BLINV_TABLE  VARCHAR2(1000);
		  INSERT_TABLE_INV_BLINV_TABLE  VARCHAR2(1000);
		BEGIN
		  TRUNCATE_TABLE_INV_BLINV_TABLE   := 'TRUNCATE TABLE INV_SAP_BACKLOG_INV';
		  INSERT_TABLE_INV_BLINV_TABLE := 'INSERT INTO INV_SAP_BACKLOG_INV SELECT * FROM VIEW_INV_SAP_BACKLOG_INV';
		  EXECUTE IMMEDIATE TRUNCATE_TABLE_INV_BLINV_TABLE;
		  EXECUTE IMMEDIATE INSERT_TABLE_INV_BLINV_TABLE;
		END; 

		Job Initialization: 
		DROP TABLE INV_SAP_BACKLOG_INV;
		CREATE TABLE INV_SAP_BACKLOG_INV AS
		SELECT * FROM VIEW_INV_SAP_BACKLOG_INV;
			
	2.13 Job Name: Job_Daily_BLPO_TABLE
		Job Time: 6:20 AM
		Job Repeat Frequency: Daily
    Job running time: 5mins
		Job Procedure:
		DECLARE
		  TRUNCATE_TABLE_INV_BLPO_TABLE  VARCHAR2(1000);
		  INSERT_TABLE_INV_BLPO_TABLE  VARCHAR2(1000);
		BEGIN
		  TRUNCATE_TABLE_INV_BLPO_TABLE   := 'TRUNCATE TABLE INV_SAP_BACKLOG_PO';
		  INSERT_TABLE_INV_BLPO_TABLE := 'INSERT INTO INV_SAP_BACKLOG_PO SELECT * FROM VIEW_INV_SAP_BACKLOG_PO';
		  EXECUTE IMMEDIATE TRUNCATE_TABLE_INV_BLPO_TABLE;
		  EXECUTE IMMEDIATE INSERT_TABLE_INV_BLPO_TABLE;
		END;
    
		Job Initialization: 
		DROP TABLE INV_SAP_BACKLOG_PO;
		CREATE TABLE INV_SAP_BACKLOG_PO AS
		SELECT * FROM VIEW_INV_SAP_BACKLOG_PO;
	
	2.14 Job Name: Job_Daily_SOST_TABLE
		Job Time: 6:30 AM
		Job Repeat Frequency: Daily
    Job running time: 5mins
		Job Procedure:

    DECLARE
      TRUNCATE_TABLE_SOST  VARCHAR2(1000);
      INSERT_TABLE_SOST_A  VARCHAR2(1000);
      INSERT_TABLE_SOST_B  VARCHAR2(1000);
    BEGIN
      TRUNCATE_TABLE_SOST   := 'TRUNCATE TABLE INV_SAP_ITEM_SO_STAT';
      INSERT_TABLE_SOST_A := 'INSERT INTO INV_SAP_ITEM_SO_STAT SELECT * FROM VIEW_INV_SAP_IMSO_LTIN13TMP';
      INSERT_TABLE_SOST_B := 'INSERT INTO INV_SAP_ITEM_SO_STAT SELECT * FROM VIEW_INV_SAP_IMSO_LTOUT13TMP';
      
      EXECUTE IMMEDIATE TRUNCATE_TABLE_SOST;
      EXECUTE IMMEDIATE INSERT_TABLE_SOST_A;
      EXECUTE IMMEDIATE INSERT_TABLE_SOST_B;
    END;  
		
		Job Initialization: 
		TRUNCATE TABLE INV_SAP_ITEM_SO_STAT;
		INSERT INTO INV_SAP_ITEM_SO_STAT SELECT * FROM VIEW_INV_SAP_IMSO_LTIN13TMP;
		INSERT INTO INV_SAP_ITEM_SO_STAT SELECT * FROM VIEW_INV_SAP_IMSO_LTOUT13TMP;






-------
	2.15 Job Name: Job_Daily_SVD_TO_TABLE --
		Job Time: 8:15 AM
		Job Repeat Frequency: Daily
		Job Procedure:
		DECLARE
			TRUNCATE_SVD_TABLE  VARCHAR2(1000);
			INSERT_TABLE_SVD  VARCHAR2(1000);
		BEGIN
			TRUNCATE_SVD_TABLE   := 'TRUNCATE TABLE INV_SAP_SVD_REPORT';
			INSERT_TABLE_SVD := 'INSERT INTO INV_SAP_SVD_REPORT SELECT * FROM VIEW_INV_SAP_SVD_REPORT';
			EXECUTE IMMEDIATE TRUNCATE_SVD_TABLE;
			EXECUTE IMMEDIATE INSERT_TABLE_SVD;
		END;   		
		
		Job Initialization: 
		DROP TABLE INV_SAP_SVD_REPORT;
		CREATE TABLE INV_SAP_SVD_REPORT AS SELECT * FROM VIEW_INV_SAP_SVD_REPORT;
		
	2.16 Job Name: Job_Daily_JOB_LOG_TABLE
		Job Time: 9:00 AM
		Job Repeat Frequency: Daily
		Job Procedure:
		SELECT STATUS,REQ_START_DATE FROM user_scheduler_job_run_details WHERE STATUS = 'FAILED';
		CREATE TABLE INV_USER_SCHEDULE_JOB_LOG AS SELECT * FROM user_scheduler_job_log;
		CREATE TABLE INV_USER_SCHEDULE_JOB_DETAILS AS SELECT * FROM user_scheduler_job_run_details WHERE STATUS = 'FAILED';
		TRUNCATE TABLE INV_USER_SCHEDULE_JOB_LOG;
		TRUNCATE TABLE INV_USER_SCHEDULE_JOB_DETAILS;
		INSERT INTO INV_USER_SCHEDULE_JOB_LOG SELECT * FROM user_scheduler_job_log;
		INSERT INTO INV_USER_SCHEDULE_JOB_DETAILS SELECT * FROM user_scheduler_job_run_details;

		DECLARE
		  TRUNCATE_JOB_LOG  VARCHAR2(1000);
		  TRUNCATE_JOB_DETAILS  VARCHAR2(1000);
		  INSERT_TABLE_JOB_LOG  VARCHAR2(1000);
		  INSERT_TABLE_JOB_DETAILS  VARCHAR2(1000);
		BEGIN
		  TRUNCATE_JOB_LOG   := 'TRUNCATE TABLE INV_USER_SCHEDULE_JOB_LOG';
		  TRUNCATE_JOB_DETAILS := 'TRUNCATE TABLE INV_USER_SCHEDULE_JOB_DETAILS';
		  INSERT_TABLE_JOB_LOG := 'INSERT INTO INV_USER_SCHEDULE_JOB_LOG SELECT * FROM user_scheduler_job_log';
		  INSERT_TABLE_JOB_DETAILS := 'INSERT INTO INV_USER_SCHEDULE_JOB_DETAILS SELECT * FROM user_scheduler_job_run_details';
		  EXECUTE IMMEDIATE TRUNCATE_JOB_LOG;
		  EXECUTE IMMEDIATE TRUNCATE_JOB_DETAILS;
		  EXECUTE IMMEDIATE INSERT_TABLE_JOB_LOG;
		  EXECUTE IMMEDIATE INSERT_TABLE_JOB_DETAILS;
		END;

	2.17 Job Name: Job_Daily_SVD_CMS_STATS
		Job Time: 22:00 PM
		Job Repeat Frequency: Daily
		Job Procedure:
		DECLARE
		  INSERT_TABLE_SVD_CMS  VARCHAR2(1000);
		BEGIN
		  INSERT_TABLE_SVD_CMS := 'INSERT
			INTO INV_SAP_SVD_COMMENTS_STATS
			  (
				ID,
				COMMENTS,
				PLANNER,
				LAST_UPDATE_DATE,
				SNAPSHOT_DATE
			  )
			SELECT ID,
			  COMMENTS,
			  PLANNER,
			  LAST_UPDATE_DATE,
			  SYSDATE
			FROM INV_SAP_SVD_COMMENTS';
		  EXECUTE IMMEDIATE INSERT_TABLE_SVD_CMS;
		END;  
		
		Job Initialization: 
		DROP TABLE INV_SAP_SVD_COMMENTS_STATS;
		CREATE TABLE INV_SAP_SVD_COMMENTS_STATS AS
		SELECT * FROM INV_SAP_SVD_COMMENTS;
		
		INSERT
		INTO INV_SAP_SVD_COMMENTS_STATS
		  (
			ID,
			COMMENTS,
			PLANNER,
			LAST_UPDATE_DATE,
			SNAPSHOT_DATE
		  )
		SELECT ID,
		  COMMENTS,
		  PLANNER,
		  LAST_UPDATE_DATE,
		  SYSDATE
		FROM INV_SAP_SVD_COMMENTS;

		2.18 Job Name: Job_Daily_INV_SUM_STATS
		Job Time: 10:30 AM
		Job Repeat Frequency: Daily
		Job Procedure:
DECLARE
  INSERT_TABLE_INVS  VARCHAR2(4000);
BEGIN
  INSERT_TABLE_INVS := 'INSERT
    INTO INV_SAP_INV_SUM_STATS
    (
      PROC_TYPE,
      PLANT,
      MATERIAL,
      CATALOG_DASH,
      BU,
      UNIT_COST,
      STRATEGY_GRP,
      SAFETY_STOCK,
      LEAD_TIME,
      MATL_TYPE,
      MRP_TYPE,
      AVG13_USAGE_QTY,
      FC_AVG13_WEEK_QTY,
      AVG26_USAGE_QTY,
      FC_AVG26_WEEK_QTY,
      TOT_OPEN_QTY,
      SO_OPEN_VAL,
      PO_OPEN_QTY_ALL,
      STOCK_IN_TRANSIT_QTY,
      PO_OPEN_VAL,
      SIT_VAL,
      INV_TOTAL_QTY,
      INV_TOTAL_VAL,
      SNAPSHOT_DATE
    )
    SELECT PROC_TYPE,
    PLANT,
    MATERIAL,
    CATALOG_DASH,
    BU,
    CEIL(NVL(UNIT_COST,0)) AS UNIT_COST,
    STRATEGY_GRP,
    SAFETY_STOCK,
    LEAD_TIME,
    MATL_TYPE,
    MRP_TYPE,
    NVL(AVG13_USAGE_QTY,0) AS AVG13_USAGE_QTY,
    NVL(FC_AVG13_WEEK_QTY,0) AS FC_AVG13_WEEK_QTY,
    NVL(AVG26_USAGE_QTY,0) AS AVG26_USAGE_QTY,
    NVL(FC_AVG26_WEEK_QTY,0) AS FC_AVG26_WEEK_QTY,
    NVL(TOT_OPEN_QTY,0) AS TOT_OPEN_QTY,
    CEIL(NVL(SO_OPEN_VAL,0)) AS SO_OPEN_VAL,
    CEIL(NVL(PO_OPEN_QTY_ALL,0)) AS PO_OPEN_QTY_ALL,
    NVL(STOCK_IN_TRANSIT_QTY,0) AS STOCK_IN_TRANSIT_QTY,
    CEIL(NVL(PO_OPEN_VAL,0)) AS PO_OPEN_VAL,
    CEIL(NVL(SIT_VAL,0)) AS SIT_VAL,
    NVL(INV_TOTAL_QTY,0) AS INV_TOTAL_QTY,
    CEIL(NVL(INV_TOTAL_VAL,0)) AS INV_TOTAL_VAL,
    SYSDATE
    FROM VIEW_INV_SAP_INV_TREND
    WHERE KEY <> 0 AND PLANT  IN ('||5040||', '||5050||', '||5100||', '||5110||', '||5120||', '||5160||', '||5190||', '||5200||','||5070||','||5140||')';
    EXECUTE IMMEDIATE INSERT_TABLE_INVS;
END;   
		
		Job Initialization: 
      SELECT * FROM INV_SAP_INV_SUM_STATS;
      TRUNCATE TABLE INV_SAP_INV_SUM_STATS;
      --CREATE THE TABLE
      CREATE TABLE INV_SAP_INV_SUM_STATS AS
      SELECT PROC_TYPE,
        PLANT,
        MATERIAL,
        CATALOG_DASH,
        BU,
        CEIL(NVL(UNIT_COST,0)) AS UNIT_COST,
        STRATEGY_GRP,
        SAFETY_STOCK,
        LEAD_TIME,
        MATL_TYPE,
        MRP_TYPE,
        NVL(AVG13_USAGE_QTY,0) AS AVG13_USAGE_QTY,
        NVL(FC_AVG13_WEEK_QTY,0) AS FC_AVG13_WEEK_QTY,
        NVL(AVG26_USAGE_QTY,0) AS AVG26_USAGE_QTY,
        NVL(FC_AVG26_WEEK_QTY,0) AS FC_AVG26_WEEK_QTY,
        NVL(TOT_OPEN_QTY,0) AS TOT_OPEN_QTY,
        CEIL(NVL(SO_OPEN_VAL,0)) AS SO_OPEN_VAL,
        CEIL(NVL(PO_OPEN_QTY_ALL,0)) AS PO_OPEN_QTY_ALL,
        NVL(STOCK_IN_TRANSIT_QTY,0) AS STOCK_IN_TRANSIT_QTY,
        CEIL(NVL(PO_OPEN_VAL,0)) AS PO_OPEN_VAL,
        CEIL(NVL(SIT_VAL,0)) AS SIT_VAL,
        NVL(INV_TOTAL_QTY,0) AS INV_TOTAL_QTY,
        CEIL(NVL(INV_TOTAL_VAL,0)) AS INV_TOTAL_VAL
      FROM VIEW_INV_SAP_INV_TREND
      WHERE KEY <> 0
      AND PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140','5130','5150','5180');
      
      --INSERT THE RECORDS
      INSERT
      INTO INV_SAP_INV_SUM_STATS
        (
          PROC_TYPE,
          PLANT,
          MATERIAL,
          CATALOG_DASH,
          BU,
          UNIT_COST,
          STRATEGY_GRP,
          SAFETY_STOCK,
          LEAD_TIME,
          MATL_TYPE,
          MRP_TYPE,
          AVG13_USAGE_QTY,
          FC_AVG13_WEEK_QTY,
          AVG26_USAGE_QTY,
          FC_AVG26_WEEK_QTY,
          TOT_OPEN_QTY,
          SO_OPEN_VAL,
          PO_OPEN_QTY_ALL,
          STOCK_IN_TRANSIT_QTY,
          PO_OPEN_VAL,
          SIT_VAL,
          INV_TOTAL_QTY,
          INV_TOTAL_VAL,
          SNAPSHOT_DATE
        )
      SELECT PROC_TYPE,
        PLANT,
        MATERIAL,
        CATALOG_DASH,
        BU,
        CEIL(NVL(UNIT_COST,0)) AS UNIT_COST,
        STRATEGY_GRP,
        SAFETY_STOCK,
        LEAD_TIME,
        MATL_TYPE,
        MRP_TYPE,
        NVL(AVG13_USAGE_QTY,0) AS AVG13_USAGE_QTY,
        NVL(FC_AVG13_WEEK_QTY,0) AS FC_AVG13_WEEK_QTY,
        NVL(AVG26_USAGE_QTY,0) AS AVG26_USAGE_QTY,
        NVL(FC_AVG26_WEEK_QTY,0) AS FC_AVG26_WEEK_QTY,
        NVL(TOT_OPEN_QTY,0) AS TOT_OPEN_QTY,
        CEIL(NVL(SO_OPEN_VAL,0)) AS SO_OPEN_VAL,
        CEIL(NVL(PO_OPEN_QTY_ALL,0)) AS PO_OPEN_QTY_ALL,
        NVL(STOCK_IN_TRANSIT_QTY,0) AS STOCK_IN_TRANSIT_QTY,
        CEIL(NVL(PO_OPEN_VAL,0)) AS PO_OPEN_VAL,
        CEIL(NVL(SIT_VAL,0)) AS SIT_VAL,
        NVL(INV_TOTAL_QTY,0) AS INV_TOTAL_QTY,
        CEIL(NVL(INV_TOTAL_VAL,0)) AS INV_TOTAL_VAL,
        SYSDATE
      FROM VIEW_INV_SAP_INV_TREND
      WHERE KEY <> 0 AND PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140','5130','5150','5180');
      
      SELECT SNAPSHOT_DATE
      ||'_'
      ||MATERIAL
      ||'_'
      ||PLANT AS ID,
      STOCK_IN_TRANSIT_QTY
  DELETE  FROM INV_SAP_INV_SUM_STATS where SNAPSHOT_DATE between SYSDATE - 1 and sysdate;
  CREATE TABLE INV_SAP_INV_SUM_STATS_BK AS SELECT * FROM INV_SAP_INV_SUM_STATS;
------pending
  	2.18 Job Name: Job_Daily_AP_DELIERC_6MM
		Job Time: 21:00 PM
		Job Repeat Frequency: Daily
		Job Procedure:
		DECLARE
			INSERT_TABLE_DELI  VARCHAR2(1000);
      TRUNCATE_TABLE_DELI VARCHAR2(1000);
		BEGIN
      TRUNCATE_TABLE_DELI := 'TRUNCATE TABLE INV_SAP_LIKP_LIPS_DAILY_YEAR';
			INSERT_TABLE_DELI := 'INSERT INTO INV_SAP_LIKP_LIPS_DAILY_YEAR
        SELECT *
        FROM DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY@ROCKWELL_DW_DBLINK
        WHERE CREATED_ON_DATE > SYSDATE - 195
        AND PLANTID                              IN ('||5040||', '||5050||', '||5100||', '||5110||', '||5120||', '||5160||', '||5190||', '||5200||','||5070||','||5140||')';
      EXECUTE IMMEDIATE TRUNCATE_TABLE_DELI;
    	EXECUTE IMMEDIATE INSERT_TABLE_DELI;
		END;   		
		
		Job Initialization: 
    CREATE TABLE INV_SAP_LIKP_LIPS_DAILY_6MM AS
    SELECT * FROM INV_SAP_LIKP_LIPS_DAILY WHERE DELIVERY = '8014343294';
    TRUNCATE TABLE INV_SAP_LIKP_LIPS_DAILY_YEAR;
    INSERT INTO INV_SAP_LIKP_LIPS_DAILY_YEAR
    
    TRUNCATE TABLE INV_SAP_LIKP_LIPS_DAILY_6MM;
    
    INSERT INTO INV_SAP_LIKP_LIPS_DAILY_6MM
    SELECT *
    FROM DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY@ROCKWELL_DW_DBLINK
    WHERE CREATED_ON_DATE > SYSDATE - 195
     AND PLANTID                              IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140','1090','1180','4000')

     SELECT * FROM INV_SAP_LIKP_LIPS_DAILY_6MM;
     
     
 SELECT * FROM   
(    SELECT *
    FROM DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY@ROCKWELL_DW_DBLINK
    WHERE CREATED_ON_DATE > SYSDATE - 182
    AND PLANTID                              IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140','1090','1180','4000')
    AND MATERIALID IN ('PN-75426',
'PN-75423',
'PN-75437',
'PN-75418',
'PN-75416',
'PN-75422',
'PN-75421',
'PN-75434')
)DELI
LEFT JOIN
(
SELECT DISTINCT SALESDOC, SOLDTOPARTY,SHIPTOPARTY FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DW_DBLINK
)SO_HSI
ON SO_HSI.SALESDOC = DELI.REFERENCE_DOC_TRIM
                
          
          
    
    
    
    
    
    
    CREATE TABLE INV_SAP_PP_SERVICE_LEVELS_0522 AS
    SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_SERVICE_LEVELS@ROCKWELL_DW_DBLINK;
    
    
    
  2.2 PLANTID-SALESORG MAPPING TABLE
  		CREATE TABLE INV_SAP_PP_PLANT_SAOG AS
      SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_T001W@ROCKWELL_DW_DBLINK;
  
  2.2 INV_SAP_MRP_TYPE_DIS
      CREATE TABLE INV_SAP_MRP_TYPE_DIS AS
      SELECT * FROM DWQ$LIBRARIAN.INV_SAP_MRP_TYPE_DIS@ROCKWELL_DW_DBLINK;
  
  2.2 INV_SAP_MATL_TYPE_DIS
      CREATE TABLE INV_SAP_MATL_TYPE_DIS AS
      SELECT * FROM DWQ$LIBRARIAN.INV_SAP_MATL_TYPE_DIS@ROCKWELL_DW_DBLINK;
  
  2.2 INV_SAP_MRP_CONTROLLER_DIS
    CREATE TABLE INV_SAP_MRP_CONTROLLER_DIS AS
    SELECT * FROM DWQ$LIBRARIAN.INV_SAP_MRP_CONTROLLER_DIS@ROCKWELL_DW_DBLINK;


  2.2 INV_SAP_PLAN_PARAM_REVIEW
    SELECT * FROM INV_SAP_PLAN_PARAM_REVIEW;
    DROP TABLE INV_SAP_PLAN_PARAM_REVIEW;
    CREATE TABLE INV_SAP_PLAN_PARAM_REVIEW AS
    SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PLAN_PARAM_REVIEW@ROCKWELL_DW_DBLINK;


	2.X Job Name: Job_Daily_INV_PLANT_SLC
		Job Time:  
		Job Repeat Frequency: Daily
		Job running time: 5mins
		Job Procedure:
		DECLARE
		  TRUNCATE_TABLE_INV_SLC  VARCHAR2(1000);
		  INSERT_TABLE_INV_SLC  VARCHAR2(1000);
		BEGIN
		  TRUNCATE_TABLE_INV_SLC   := 'TRUNCATE TABLE INV_SAP_INV_BYPLT_SLC';
		  INSERT_TABLE_INV_SLC := 'INSERT INTO INV_SAP_INV_BYPLT_SLC 
		  SELECT * FROM DWQ$LIBRARIAN.INV_SAP_INVENTORY_BY_PLANT_SLC@ROCKWELL_DW_DBLINK';
		  EXECUTE IMMEDIATE TRUNCATE_TABLE_INV_SLC;
		  EXECUTE IMMEDIATE INSERT_TABLE_INV_SLC;
		END;
		
		Job Initialization:
		DROP TABLE INV_SAP_INV_BYPLT_SLC;
		CREATE TABLE INV_SAP_INV_BYPLT_SLC AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_INVENTORY_BY_PLANT_SLC@ROCKWELL_DW_DBLINK;








--Weekly Jobs
	3.1 Job Name: Job_Weekly_INV_SO_HST
		Job Time: 12:00 AM
		Job Repeat Frequency: Weekly.Every Tue.
		Job Procedure:
		DECLARE
		  TRUNCATE_TABLE_SALES_HST  VARCHAR2(1000);
		  INSERT_TABLE_SALES_HST  VARCHAR2(1000);
		BEGIN
		  TRUNCATE_TABLE_SALES_HST   := 'TRUNCATE TABLE INV_SAP_SALES_HST';
		  INSERT_TABLE_SALES_HST := 'INSERT INTO INV_SAP_SALES_HST
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('||5040||', '||5050||', '||5100||', '||5110||', '||5120||', '||5160||', '||5190||', '||5200||','||5070||','||5140||')';
		  EXECUTE IMMEDIATE TRUNCATE_TABLE_SALES_HST;
		  EXECUTE IMMEDIATE INSERT_TABLE_SALES_HST;
		END;
    		
		Job Initialization: 
		DROP TABLE INV_SAP_SALES_HST;
		CREATE TABLE INV_SAP_SALES_HST AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DW_DBLINK WHERE PLANT ID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

select * from INV_SAP_SALES_HST;
  3.2 Job Name: Job_Weekly_BK_STI -- Just back the Stock item metric weekly bu and item data
		Job Time: 8:00 AM
		Job Repeat Frequency: Weekly SAT
		Job Procedure:
		DECLARE
			TRUNCATE_BK_STI_WK  VARCHAR2(1000);
			TRUNCATE_BK_STI_ITEM  VARCHAR2(1000);
			INSERT_TABLE_BK_STI_WK  VARCHAR2(1000);
			INSERT_TABLE_BK_STI_ITEM  VARCHAR2(1000);
		BEGIN
			TRUNCATE_BK_STI_WK   := 'TRUNCATE TABLE STI_BY_BU_WEEK_TMP';
			TRUNCATE_BK_STI_ITEM := 'TRUNCATE TABLE STI_BY_ITEM_TMP';
			INSERT_TABLE_BK_STI_WK := 'INSERT INTO STI_BY_BU_WEEK_TMP SELECT * FROM STOCK_ITEM_STATUS_BY_BU_WEEK';
			INSERT_TABLE_BK_STI_ITEM := 'INSERT INTO STI_BY_ITEM_TMP SELECT * FROM STOCK_ITEM_STATUS_BY_ITEM';
			EXECUTE IMMEDIATE TRUNCATE_BK_STI_WK;
			EXECUTE IMMEDIATE TRUNCATE_BK_STI_ITEM;
			EXECUTE IMMEDIATE INSERT_TABLE_BK_STI_WK;
			EXECUTE IMMEDIATE INSERT_TABLE_BK_STI_ITEM;
		END;				
    
    Job Initialization: 
    TRUNCATE TABLE STI_BY_BU_WEEK_TMP;
    TRUNCATE TABLE STI_BY_ITEM_TMP;

    INSERT INTO STI_BY_BU_WEEK_TMP SELECT * FROM STOCK_ITEM_STATUS_BY_BU_WEEK;
    INSERT INTO STI_BY_ITEM_TMP AS SELECT * FROM STOCK_ITEM_STATUS_BY_ITEM;
				
        
  3.3 Job Name: Job_Weekly_INV_REC
		Job Time: 10:15 AM
		Job Repeat Frequency: Weekly.Every 5 times per week
		Job Procedure:
		DECLARE
    INSERT_TABLE_INV_REC  VARCHAR2(5000);
    BEGIN
      INSERT_TABLE_INV_REC := 'INSERT INTO INV_SAP_INV_REC
      SELECT
      DISTINCT
      INV.INV_ID                                                                           AS INV_ID,
      INV.ID                                                                               AS ID,
      INV.REC_DATE                                                                         AS REC_DATE,
      INV.PLANTID                                                                          AS PLANTID,
      INV.MATERIALID                                                                       AS MATERIAL,
      PP.CATALOG_DASH                                                                      AS CATALOG_DASH,
      PP.SAFETY_STOCK                                                                      AS SAFETY_STOCK,
      PP.UNIT_COST                                                                         AS UNIT_COST,
      PP.STRATEGY_GRP                                                                      AS STRATEGY_GRP,
      PP.PROD_BU                                                                           AS PROD_BU,
      PP.PROD_FAM                                                                          AS PROD_FAM,
      PP.MATL_TYPE                                                                         AS MATL_TYPE,
      NVL(INV.OH_QTY,0)                                                                    AS OH_QTY,
      NVL(PP.MIN_INV,0)                                                                    AS MIN_INV,
      NVL(PP.TARGET_INV,0)                                                                 AS TARGET_INV,
      NVL(PP.MAX_INV,0)                                                                    AS MAX_INV,
      (NVL(INV.OH_QTY,0)    *NVL(PP.UNIT_COST,0))                                          AS OH_VAL,
      (NVL(PP.MIN_INV,0)    *NVL(PP.UNIT_COST,0))                                          AS MIN_INV_VAL,
      (NVL(PP.TARGET_INV,0) *NVL(PP.UNIT_COST,0))                                          AS TARGET_INV_VAL,
      (NVL(PP.MAX_INV,0)    *NVL(PP.UNIT_COST,0))                                          AS MAX_INV_VAL,
      (NVL(INV.OH_QTY,0)    *NVL(PP.UNIT_COST,0) - NVL(PP.MAX_INV,0) *NVL(PP.UNIT_COST,0)) AS OVER_MAX_VAL
    FROM
      (SELECT 
        SYSDATE||''_''||MATERIALID||''_''||PLANTID AS INV_ID,
        MATERIALID||''_''||PLANTID AS ID,
        SYSDATE AS REC_DATE,
        MATERIALID,
        PLANTID,
        OH_QTY
      FROM VIEW_INV_SAP_INV_BY_PLANT WHERE PLANTID IN ('||5040||', '||5050||', '||5100||', '||5110||', '||5120||', '||5160||', '||5190||', '||5200||','||5070||','||5140||','||5180||','||5150||','||5130||')
      )INV
    LEFT JOIN
      (SELECT ID,
        MATERIAL,
        CATALOG_DASH,
        PLANT,
        SAFETY_STOCK,
        UNIT,
        UNIT_COST,
        STRATEGY_GRP,
        PROD_BU,
        PROD_FAM,
        MATL_TYPE,
        MIN_INV,
        TARGET_INV,
        MAX_INV,
        LEAD_TIME
      FROM INV_SAP_PP_OPT_X
      )PP
    ON PP.ID = INV.ID';
    EXECUTE IMMEDIATE INSERT_TABLE_INV_REC;
    END;
  
  
  SELECT count(*) FROM INV_SAP_INVENTORY_BY_PLANT WHERE PLANTID = '5100'
  
  SELECT * FROM INV_SAP_INVENTORY_BY_PLANT WHERE PLANTID = '5100' AND MATERIALID = '440F-A1302S A'

  
    		
		Job Initialization:   
    SELECT DISTINCT REC_DATE FROM INV_SAP_INV_REC;
    DROP TABLE INV_SAP_INV_REC;
    
    CREATE VIEW VIEW_INV_SAP_INV_REC AS
    SELECT DISTINCT INV.INV_ID                                                             AS INV_ID,
      INV.ID                                                                               AS ID,
      INV.REC_DATE                                                                         AS REC_DATE,
      INV.PLANTID                                                                          AS PLANTID,
      INV.MATERIALID                                                                       AS MATERIAL,
      PP.CATALOG_DASH                                                                      AS CATALOG_DASH,
      PP.SAFETY_STOCK                                                                      AS SAFETY_STOCK,
      PP.UNIT_COST                                                                         AS UNIT_COST,
      PP.STRATEGY_GRP                                                                      AS STRATEGY_GRP,
      PP.PROD_BU                                                                           AS PROD_BU,
      PP.PROD_FAM                                                                          AS PROD_FAM,
      PP.MATL_TYPE                                                                         AS MATL_TYPE,
      NVL(INV.OH_QTY,0)                                                                    AS OH_QTY,
      NVL(PP.MIN_INV,0)                                                                    AS MIN_INV,
      NVL(PP.TARGET_INV,0)                                                                 AS TARGET_INV,
      NVL(PP.MAX_INV,0)                                                                    AS MAX_INV,
      (NVL(INV.OH_QTY,0)    *NVL(PP.UNIT_COST,0))                                          AS OH_VAL,
      (NVL(PP.MIN_INV,0)    *NVL(PP.UNIT_COST,0))                                          AS MIN_INV_VAL,
      (NVL(PP.TARGET_INV,0) *NVL(PP.UNIT_COST,0))                                          AS TARGET_INV_VAL,
      (NVL(PP.MAX_INV,0)    *NVL(PP.UNIT_COST,0))                                          AS MAX_INV_VAL,
      (NVL(INV.OH_QTY,0)    *NVL(PP.UNIT_COST,0) - NVL(PP.MAX_INV,0) *NVL(PP.UNIT_COST,0)) AS OVER_MAX_VAL
    FROM
    
      (SELECT (SYSDATE)
        ||'_'
        ||MATERIALID
        ||'_'
        ||PLANTID AS INV_ID,
        MATERIALID
        ||'_'
        ||PLANTID AS ID,
        (SYSDATE)  AS REC_DATE,
        MATERIALID,
        PLANTID,
        OH_QTY
      FROM VIEW_INV_SAP_INV_BY_PLANT WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140','5180','5150','5130')
      )INV
    LEFT JOIN
      (SELECT ID,
        MATERIAL,
        CATALOG_DASH,
        PLANT,
        SAFETY_STOCK,
        UNIT,
        UNIT_COST,
        STRATEGY_GRP,
        PROD_BU,
        PROD_FAM,
        MATL_TYPE,
        MIN_INV,
        TARGET_INV,
        MAX_INV,
        LEAD_TIME
      FROM INV_SAP_PP_OPT_X 
      )PP
    ON PP.ID = INV.ID;
    
    
    DELETE FROM INV_SAP_INV_REC WHERE REC_DATE BETWEEN TO_CHAR(SYSDATE)  AND TO_CHAR(SYSDATE + 1);
    SELECT distinct REC_DATE FROM INV_SAP_INV_REC WHERE REC_DATE BETWEEN TO_CHAR(SYSDATE - 4)  AND TO_CHAR(SYSDATE + 1);
    
    SELECT * FROM VIEW_INV_SAP_INV_REC WHERE MATERIAL = '1797-TPS B'
  
      
    select distinct REC_DATE from INV_SAP_INV_REC WHERE PLANTID IN ('5040') and MATERIAL = '1797-TPS B'
    
    
    DROP TABLE INV_SAP_INV_REC_J;
    CREATE TABLE INV_SAP_INV_REC_J AS SELECT MATERIAL AS MATERIALID, PLANTID, OH_QTY FROM INV_SAP_INV_REC_BK WHERE REC_DATE BETWEEN TO_CHAR(SYSDATE - 3)  AND TO_CHAR(SYSDATE - 2);
     SELECT * FROM INV_SAP_INV_REC_J WHERE MATERIALID = '1756-HYD02 A' AND PLANTid = '5040'

    CREATE TABLE INV_SAP_INV_REC_BK AS SELECT * FROM INV_SAP_INV_REC;
    DELETE FROM INV_SAP_INV_REC WHERE REC_DATE BETWEEN TO_CHAR(SYSDATE - 3)  AND TO_CHAR(SYSDATE - 2);
    
    
    
    
    
  3.4 Job Name: Job_Weekly_INV_PP_MVKE
      Job Time: 10:00 AM SAT
      Job Repeat Frequency: Weekly
      Job Procedure:
      DECLARE
        TRUNCATE_TABLE_INV_SAP_PP_MVKE   VARCHAR2(1000);
        INSERT_TABLE_INV_SAP_PP_MVKE VARCHAR2(1000);
      BEGIN
        TRUNCATE_TABLE_INV_SAP_PP_MVKE   := 'TRUNCATE TABLE INV_SAP_PP_MVKE';
        INSERT_TABLE_INV_SAP_PP_MVKE := 'INSERT INTO INV_SAP_PP_MVKE SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE@ROCKWELL_DW_DBLINK';
        EXECUTE IMMEDIATE TRUNCATE_TABLE_INV_SAP_PP_MVKE;
        EXECUTE IMMEDIATE INSERT_TABLE_INV_SAP_PP_MVKE;
      END;
      
      Job Initialization: 
      DROP TABLE INV_SAP_PP_MVKE;
      CREATE TABLE INV_SAP_PP_MVKE AS
      SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE@ROCKWELL_DW_DBLINK;
    
    
  3.4.1 Job Name: Job_Weekly_INV_SI_SOG_X
      Job Time: 
      Job Repeat Frequency: Weekly
      Job Procedure:
      DECLARE
        TRUNCATE_TABLE_INV_SI_SOG_X   VARCHAR2(1000);
        INSERT_TABLE_INV_SI_SOG_X VARCHAR2(1000);
      BEGIN
        TRUNCATE_TABLE_INV_SI_SOG_X   := 'TRUNCATE TABLE INV_SAP_ITEM_SOG_X';
        INSERT_TABLE_INV_SI_SOG_X := 'INSERT INTO INV_SAP_ITEM_SOG_X SELECT * FROM VIEW_INV_SAP_ITEM_SOG_X';
        EXECUTE IMMEDIATE TRUNCATE_TABLE_INV_SI_SOG_X;
        EXECUTE IMMEDIATE INSERT_TABLE_INV_SI_SOG_X;
      END;
      
      Job Initialization: 
      DROP VIEW VIEW_INV_SAP_ITEM_SOG_X;
      DROP TABLE INV_SAP_ITEM_SOG_X;
      CREATE TABLE INV_SAP_ITEM_SOG_X AS SELECT * FROM VIEW_INV_SAP_ITEM_SOG_X;
      select * from VIEW_INV_SAP_ITEM_SOG_X where material = '140U-J-RVM21B C'
      
      
      
 
  
  3.5 Job Name: Job_Weekly_INV_PRO_PARAM
      Job Time: 11:00 AM SAT 
      Job Repeat Frequency: Weekly
      Job Procedure:
      DECLARE
        TRUNCATE_TABLE_INV_PROP   VARCHAR2(1000);
        INSERT_TABLE_INV_PROP VARCHAR2(1000);
      BEGIN
        TRUNCATE_TABLE_INV_PROP   := 'TRUNCATE TABLE INV_SAP_PRODUCTION_PARAMETERS';
        INSERT_TABLE_INV_PROP := 'INSERT INTO INV_SAP_PRODUCTION_PARAMETERS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PRODUCTION_PARAMETERS@ROCKWELL_DW_DBLINK';
        EXECUTE IMMEDIATE TRUNCATE_TABLE_INV_PROP;
        EXECUTE IMMEDIATE INSERT_TABLE_INV_PROP;
      END;
      
      Job Initialization: 
      DROP TABLE INV_SAP_PRODUCTION_PARAMETERS;
      CREATE TABLE INV_SAP_PRODUCTION_PARAMETERS AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PRODUCTION_PARAMETERS@ROCKWELL_DW_DBLINK;  
  
  3.X Job Name: Job_Weekly_INV_SR_SGCHECK
      Job Time: 14:00 PM SAT 
      Job Repeat Frequency: Weekly
      Job Procedure:
      DECLARE
        TRUNCATE_SGCHECK_TABLE  VARCHAR2(1000);
        INSERT_SGCHECK_5140  VARCHAR2(1000);
        INSERT_SGCHECK_5040  VARCHAR2(1000);
        INSERT_SGCHECK_5050  VARCHAR2(1000);
        INSERT_SGCHECK_5100  VARCHAR2(1000);
        INSERT_SGCHECK_5110  VARCHAR2(1000);
        INSERT_SGCHECK_5120  VARCHAR2(1000);
        INSERT_SGCHECK_5160  VARCHAR2(1000);
        INSERT_SGCHECK_5190  VARCHAR2(1000);
        INSERT_SGCHECK_5070  VARCHAR2(1000);
        INSERT_SGCHECK_5200  VARCHAR2(1000);
      BEGIN
        TRUNCATE_SGCHECK_TABLE   := 'TRUNCATE TABLE INV_SAP_SR_SGCHECK';
        INSERT_SGCHECK_5140 := 'INSERT INTO INV_SAP_SR_SGCHECK SELECT * FROM VIEW_INV_SAP_SGC_5140';
        INSERT_SGCHECK_5040 := 'INSERT INTO INV_SAP_SR_SGCHECK SELECT * FROM VIEW_INV_SAP_SGC_5040';
        INSERT_SGCHECK_5050 := 'INSERT INTO INV_SAP_SR_SGCHECK SELECT * FROM VIEW_INV_SAP_SGC_5050';
        INSERT_SGCHECK_5100 := 'INSERT INTO INV_SAP_SR_SGCHECK SELECT * FROM VIEW_INV_SAP_SGC_5100';
        INSERT_SGCHECK_5110 := 'INSERT INTO INV_SAP_SR_SGCHECK SELECT * FROM VIEW_INV_SAP_SGC_5110';
        INSERT_SGCHECK_5120 := 'INSERT INTO INV_SAP_SR_SGCHECK SELECT * FROM VIEW_INV_SAP_SGC_5120';
        INSERT_SGCHECK_5160 := 'INSERT INTO INV_SAP_SR_SGCHECK SELECT * FROM VIEW_INV_SAP_SGC_5160';
        INSERT_SGCHECK_5190 := 'INSERT INTO INV_SAP_SR_SGCHECK SELECT * FROM VIEW_INV_SAP_SGC_5190';
        INSERT_SGCHECK_5070 := 'INSERT INTO INV_SAP_SR_SGCHECK SELECT * FROM VIEW_INV_SAP_SGC_5070';
        INSERT_SGCHECK_5200 := 'INSERT INTO INV_SAP_SR_SGCHECK SELECT * FROM VIEW_INV_SAP_SGC_5200';
        EXECUTE IMMEDIATE TRUNCATE_SGCHECK_TABLE;
        EXECUTE IMMEDIATE INSERT_SGCHECK_5140;
        EXECUTE IMMEDIATE INSERT_SGCHECK_5040;
        EXECUTE IMMEDIATE INSERT_SGCHECK_5050;
        EXECUTE IMMEDIATE INSERT_SGCHECK_5100;
        EXECUTE IMMEDIATE INSERT_SGCHECK_5110;
        EXECUTE IMMEDIATE INSERT_SGCHECK_5120;
        EXECUTE IMMEDIATE INSERT_SGCHECK_5160;
        EXECUTE IMMEDIATE INSERT_SGCHECK_5190;
        EXECUTE IMMEDIATE INSERT_SGCHECK_5070;
        EXECUTE IMMEDIATE INSERT_SGCHECK_5200;
      END;   
      
		
SELECT * FROM INV_SAP_SR_SGCHECK;
--Monthly Jobs
	4.1 Job Name: Job_Monthly_INV_SHIPSOLD
		Job Time: Every month 9th 23:00 
		Job Repeat Frequency: Monthly
		Job Procedure:		
		DECLARE
		  DROP_TABLE_INV_SS  VARCHAR2(1000);
      CREATE_TABLE_INV_SS_DW  VARCHAR2(1000);
		  CREATE_TABLE_INV_SS_LO  VARCHAR2(1000);
      TRUN_INV_SHIP_SOLD  VARCHAR2(1000);
      INSERT_INV_SS_A  VARCHAR2(1000);
      INSERT_INV_SS_B  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_INV_SS   := 'TRUNCATE TABLE INV_SAP_SHIP_SOLD_TO_PARTYID';
		  CREATE_TABLE_INV_SS_DW := 'INSERT INTO INV_SAP_SHIP_SOLD_TO_PARTYID 
      SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SHIP_SOLD_TO_PARTYID@ROCKWELL_DW_DBLINK';
      CREATE_TABLE_INV_SS_LO := 'INSERT INTO INV_SAP_SHIP_SOLD_TO_PARTYID
      SELECT * FROM SYSTEM.INV_SAP_SHIP_SOLD_TO_PARTYID@ROCKWELL_LOCAL_BK';
      TRUN_INV_SHIP_SOLD := 'TRUNCATE TABLE INV_SAP_SHIP_SOLD_TO';
      INSERT_INV_SS_A := 'INSERT INTO INV_SAP_SHIP_SOLD_TO 
          SELECT LPAD(SHIP_SOLD_TOPARTY,10,''0''),
          SHIP_TO_PARTY_NAME,
          SHIP_TO_CITY,
          SHIP_TO_POSTAL_CODE,
          SHIP_TO_COUNTRY
        FROM INV_SAP_SHIP_SOLD_TO_PARTYID WHERE SHIP_TO_PARTY_NAME IS NOT NULL';
      INSERT_INV_SS_B := 'INSERT INTO INV_SAP_SHIP_SOLD_TO 
        SELECT 
        LPAD(SHIP_SOLD_TOPARTY,10,''0''),
        SOLD_TO_PARTY_NAME,
        SOLD_TO_CITY,
        SOLD_TO_POSTAL_CODE,
        SOLD_TO_COUNTRY
        FROM INV_SAP_SHIP_SOLD_TO_PARTYID WHERE SHIP_TO_PARTY_NAME IS NULL';
		  EXECUTE IMMEDIATE DROP_TABLE_INV_SS;
		  EXECUTE IMMEDIATE CREATE_TABLE_INV_SS_DW;
      --EXECUTE IMMEDIATE CREATE_TABLE_INV_SS_LO;
      EXECUTE IMMEDIATE TRUN_INV_SHIP_SOLD;
      EXECUTE IMMEDIATE INSERT_INV_SS_A;
      EXECUTE IMMEDIATE INSERT_INV_SS_B;
		END;
   
		DROP TABLE INV_SAP_SHIP_SOLD_TO_PARTYID;
		CREATE TABLE INV_SAP_SHIP_SOLD_TO_PARTYID AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SHIP_SOLD_TO_PARTYID@ROCKWELL_DW_DBLINK;
    CREATE TABLE INV_SAP_SHIP_SOLD_TO_TMP AS SELECT * FROM INV_SAP_SHIP_SOLD_TO; -- Schedule BK in DW.
    
    
4.2 Job Name: Job_Monthly_INV_PP_CATA
		Job Time: 12:00 AM SAT
		Job Repeat Frequency: Monthly
		Job Procedure:
		DECLARE
		  CREATE_INV_SAP_MATL_CATA        VARCHAR2(1000);
		  DROP_INV_SAP_MATL_CATA            VARCHAR2(1000);
      DROP_INV_SAP_NODASH VARCHAR2(1000);
      CREATE_INV_SAP_NODASH VARCHAR2(1000);
      
		BEGIN
		  DROP_INV_SAP_MATL_CATA:= 'DROP TABLE INV_SAP_MATERIAL_CATALOG';
		  CREATE_INV_SAP_MATL_CATA:= 'CREATE TABLE INV_SAP_MATERIAL_CATALOG AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG@ROCKWELL_DW_DBLINK';
		  EXECUTE IMMEDIATE DROP_INV_SAP_MATL_CATA;
		  EXECUTE IMMEDIATE CREATE_INV_SAP_MATL_CATA;
		END;
		
		Job Initialization:
    SELECT * FROM INV_SAP_MATERIAL_CATALOG;
		DROP TABLE INV_SAP_MATERIAL_CATALOG;
		CREATE TABLE INV_SAP_MATERIAL_CATALOG AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG@ROCKWELL_DW_DBLINK;

    SELECT * FROM INV_SAP_NODASH_MAT_CATA;
    
		DROP TABLE INV_SAP_NODASH_MAT_CATA;
		CREATE TABLE INV_SAP_NODASH_MAT_CATA AS SELECT * FROM INV_SAP_MATERIAL_CATALOG;
		DECLARE
		  CURSOR cur
		  IS
			SELECT a.CATALOG_STRING1,
			  b.ROWID ROW_ID
			FROM INV_SAP_MATERIAL_CATALOG a,
			  INV_SAP_NODASH_MAT_CATA b
			WHERE a.MATERIALID = b.MATERIALID
			ORDER BY b.ROWID; ---order by rowid
		  V_COUNTER NUMBER;
		BEGIN
		  V_COUNTER := 0;
		  FOR row IN cur
		  LOOP
			UPDATE INV_SAP_NODASH_MAT_CATA SET CATALOG_STRING2 = REPLACE(row.CATALOG_STRING1, '-') WHERE ROWID = row.ROW_ID;
			V_COUNTER     := V_COUNTER + 1;
			IF (V_COUNTER >= 1000) THEN
			  COMMIT;
			  V_COUNTER := 0;
			END IF;
		  END LOOP;
		  COMMIT;
		END;
    
    
    DECLARE
      CREATE_INV_SAP_MATL_CATA        VARCHAR2(1000);
      DROP_INV_SAP_MATL_CATA            VARCHAR2(1000);
    BEGIN
      DROP_INV_SAP_MATL_CATA:= 'DROP TABLE INV_SAP_MATERIAL_CATALOG';
      CREATE_INV_SAP_MATL_CATA:= 'CREATE TABLE INV_SAP_MATERIAL_CATALOG AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG@ROCKWELL_DW_DBLINK';
      EXECUTE IMMEDIATE DROP_TABLE;
      EXECUTE IMMEDIATE STR_CREATE_TABLE;
    END;
    


SELECT * FROM INV_SAP_MATERIAL_CATALOG where CATALOG_STRING1 = 'PN-141666';

  3.3 Job Name: Job_Daily_Inv_PP_X
		Job Time: 2:25 PM
		Job Repeat Frequency: Weekly.Every 5 times per week
		Job Procedure:
		DECLARE
    INSERT_TABLE_INV_OPT  VARCHAR2(5000);
    BEGIN
      INSERT_TABLE_INV_OPT := 'INSERT INTO INV_SAP_PP_OPT_X_STORE 
      SELECT SYSDATE AS REC_DATE, ID,
      TMP_ID,
      LAST_REVIEW,
      MATERIAL,
      CATALOG_DASH,
      CATALOG_NO_DASH,
      PLANT,
      SALES_ORG,
      PLANTID_DESC,
      MAT_DESC,
      SAFETY_STOCK,
      OH_QTY,
      UNIT,
      UNIT_COST,
      OH_QTY_INTRANSIT,
      PROD_BU,
      PROD_FAM,
      PROD_HIERARCHY,
      PROC_TYPE,
      STRATEGY_GRP,
      MRP_TYPE,
      PROD_SCHEDULER,
      PLANT_SP_MATL_STA,
      VENDOR_KEY,
      VENDOR_ITEM,
      MIN_INV,
      TARGET_INV,
      MAX_INV,
      LOT_SIZE_QTY,
      LOT_ROUNDING_VALUE,
      LOT_SIZE_DISLS,
      LOT_MIN_BUY,
      AVG52_USAGE_QTY,
      STDEV52_USAGE,
      AVG26_USAGE_QTY,
      STDEV26_USAGE,
      AVG13_USAGE_QTY,
      STDEV13_USAGE,
      Q1_LINES,
      Q2_LINES,
      Q3_LINES,
      Q4_LINES,
      Q1_FREQ_COUNT,
      Q2_FREQ_COUNT,
      Q3_FREQ_COUNT,
      Q4_FREQ_COUNT,
      EXCHANGE_RATE,
      LEVEL_TYPE,
      OUT_QTY_W01,
      OUT_QTY_W02,
      OUT_QTY_W03,
      OUT_QTY_W04,
      OUT_QTY_W05,
      OUT_QTY_W06,
      OUT_QTY_W07,
      OUT_QTY_W08,
      OUT_QTY_W09,
      OUT_QTY_W10,
      OUT_QTY_W11,
      OUT_QTY_W12,
      OUT_QTY_W13,
      OUT_QTY_W14,
      OUT_QTY_W15,
      OUT_QTY_W16,
      OUT_QTY_W17,
      OUT_QTY_W18,
      OUT_QTY_W19,
      OUT_QTY_W20,
      OUT_QTY_W21,
      OUT_QTY_W22,
      OUT_QTY_W23,
      OUT_QTY_W24,
      OUT_QTY_W25,
      OUT_QTY_W26,
      IN_QTY_W01,
      IN_QTY_W02,
      IN_QTY_W03,
      IN_QTY_W04,
      IN_QTY_W05,
      IN_QTY_W06,
      IN_QTY_W07,
      IN_QTY_W08,
      IN_QTY_W09,
      IN_QTY_W10,
      IN_QTY_W11,
      IN_QTY_W12,
      IN_QTY_W13,
      IN_QTY_W14,
      IN_QTY_W15,
      IN_QTY_W16,
      IN_QTY_W17,
      IN_QTY_W18,
      IN_QTY_W19,
      IN_QTY_W20,
      IN_QTY_W21,
      IN_QTY_W22,
      IN_QTY_W23,
      IN_QTY_W24,
      IN_QTY_W25,
      IN_QTY_W26,
      MATERIAL_LEVEL_VALUE,
      MRP_CONTROLLER,
      MRP_CONTROLLER_KEY,
      PURCH_GROUP,
      PURCH_GROUP_KEY,
      PROD_SCHED_KEY,
      RECORDER_POINT,
      LEAD_TIME,
      PDT,
      GRT,
      SALES_ORG_COUNT,
      DIRECT_SHIP_PLANT,
      DELIVERY_PLANT,
      DMI_MANAGED,
      ABC,
      AVG_MONTHLY_DEM,
      STDEV_MONTHLY_DEM,
      DIST_CHL,
      D_CHAIN_BLK,
      DELIVERY_UNIT,
      ISSUE_UOM_NUMERATOR,
      PO_UOM_NUMERATOR,
      MATL_TYPE,
      CURRENT_SERIES,
      ULTIMATE_SOURCE
      FROM INV_SAP_PP_OPT_X WHERE PLANT IN  ('||5040||', '||5050||', '||5100||', '||5110||', '||5120||', '||5160||', '||5190||', '||5200||','||5070||','||5140||','||5180||','||5150||','||5130||','||1090||')';
    EXECUTE IMMEDIATE INSERT_TABLE_INV_OPT;
    END;
    
    