--Disributor_Cus Usage Stats
--AUTHOR:Huang Moyue
--DATE:12/16/2014

--1.Every Distributor items usage
--2.Line count
--3.PERCENT
DROP TABLE INV_SAP_SALES_HST_LC;
DROP TABLE INV_SAP_DSTR_STATS;
DROP TABLE INV_SAP_DSTR_QSTATSLIST;
CREATE TABLE  INV_SAP_SALES_HST_LC AS SELECT * FROM VIEW_INV_SAP_SALES_HST_LC;
CREATE TABLE  INV_SAP_DSTR_STATS AS SELECT * FROM VIEW_INV_SAP_DSTR_STATS;
CREATE TABLE  INV_SAP_DSTR_QSTATSLIST AS SELECT * FROM VIEW_INV_SAP_DSTR_QSTATSLIST;
select * from INV_SAP_SALES_HST_LC where sales_doc = '6502225141' and MATERIAL ='PN-128147'

SELECT * FROM INV_SAP_SALES_HST_LC WHERE ID = 'PN-128147_5040' AND sales_doc = '6502225141'

DROP VIEW VIEW_INV_SAP_SALES_HST_LC;
CREATE VIEW VIEW_INV_SAP_SALES_HST_LC AS
SELECT SOH_SOSH.ID,
  SOH_SOSH.MATERIAL,
  SOH_SOSH.CATALOG,
  SOH_SOSH.SALES_DOC,
  SOH_SOSH.ITEM,
  ITEM_BSC.SAFETY_STOCK,
  ITEM_BSC.OH_QTY,
  ITEM_BSC.STRATEGY_GRP,
  ITEM_BSC.MRP_TYPE,
  ITEM_BSC.VENDOR,
  ITEM_BSC.BU,
  ITEM_BSC.LEAD_TIME,
  ITEM_BSC.PDT,
  ITEM_BSC.UNIT_COST,
  ITEM_BSC.MRP_CONTROLLER,
  SOH_SOSH.SOLD_TO_PARTY,
  SOH_SOSH.SOLD_TO_NAME,
  SOH_SOSH.SHIP_TO_PARTY,
  SOH_SOSH.SHIP_TO_NAME,
  SOH_SOSH.COMMITTED_DATE,
  SOH_SOSH.LAST_GI_DATE,
  SOH_SOSH.CREATION_DATE,
  SOH_SOSH.REQUEST_DATE,
  SOH_SOSH.PLANT,
  SOH_SOSH.SO_TYPE,
  SOH_SOSH.ORDER_QTY,
  SOH_SOSH.OPEN_QTY,
  SOH_SOSH.SALES_ORG,
  SOH_SOSH.CURRENCY,
  SOH_SOSH.SALES_PRICE_EX,
  SOH_SOSH.SHIP_TO_COUNTRY,
  SOH_SOSH.SHIPPING_POINT,
  ITEM_BSC.ULTIMATE_SOURCE
FROM
  (SELECT SO_HST_SOLD.ID,
    SO_HST_SOLD.MATERIAL,
    SO_HST_SOLD.CATALOG,
    SO_HST_SOLD.SALES_DOC,
    SO_HST_SOLD.ITEM,
    SO_HST_SOLD.SOLD_TO_PARTY,
    SO_HST_SOLD.SOLD_TO_NAME,
    SO_HST_SOLD.SHIP_TO_PARTY,
    ADDRESS_SHIP.SHIP_SOLD_TO_PARTY_NAME AS SHIP_TO_NAME,
    SO_HST_SOLD.COMMITTED_DATE,
    SO_HST_SOLD.LAST_GI_DATE,
    SO_HST_SOLD.CREATION_DATE,
    SO_HST_SOLD.REQUEST_DATE,
    SO_HST_SOLD.PLANT,
    SO_HST_SOLD.SO_TYPE,
    SO_HST_SOLD.ORDER_QTY,
    SO_HST_SOLD.OPEN_QTY,
    SO_HST_SOLD.SALES_ORG,
    SO_HST_SOLD.SALES_PRICE_EX,
    SO_HST_SOLD.CURRENCY,
    ADDRESS_SHIP.SHIP_SOLD_TO_COUNTRY AS SHIP_TO_COUNTRY,
    SO_HST_SOLD.SHIPPING_POINT
  FROM
    (SELECT SO_HST.ID,
      SO_HST.MATERIAL,
      SO_HST.CATALOG,
      SO_HST.SALES_DOC,
      SO_HST.ITEM,
      SO_HST.SOLD_TO_PARTY,
      ADDRESS.SHIP_SOLD_TO_PARTY_NAME AS SOLD_TO_NAME,
      SO_HST.SHIP_TO_PARTY,
      SO_HST.COMMITTED_DATE,
      SO_HST.LAST_GI_DATE,
      SO_HST.CREATION_DATE,
      SO_HST.REQUEST_DATE,
      SO_HST.PLANT,
      SO_HST.SO_TYPE,
      SO_HST.ORDER_QTY,
      SO_HST.OPEN_QTY,
      SO_HST.SALES_ORG,
      SO_HST.SALES_PRICE_EX,
      SO_HST.CURRENCY,
      SO_HST.SHIPPING_POINT
    FROM
      (SELECT MATERIALID
        ||'_'
        ||PLANTID            AS ID,
        MATERIALID           AS MATERIAL,
        CATALOGID            AS CATALOG,
        SALESDOC             AS SALES_DOC,
        SALESDOCITEM         AS ITEM,
        LPAD(SOLDTOPARTY,10,'0')          AS SOLD_TO_PARTY,
        LPAD(SHIPTOPARTY,10,'0')          AS SHIP_TO_PARTY,
        COMMITTEDDATE        AS COMMITTED_DATE,
        LASTACTGIDATE        AS LAST_GI_DATE,
        LINECREATIONDATE     AS CREATION_DATE,
        REQUIREDDELIVERYDATE AS REQUEST_DATE,
        PLANTID              AS PLANT,
        SALESDOCTYPE         AS SO_TYPE,
        ORDERQTY             AS ORDER_QTY,
        OPENQTY              AS OPEN_QTY,
        SALES_ORG            AS SALES_ORG,
        GBBB_SALES_AMT       AS SALES_PRICE_EX,
        CURRENCY             AS CURRENCY,
        SHIPPING_POINT       AS SHIPPING_POINT
      FROM INV_SAP_SALES_HST
      )SO_HST
    LEFT JOIN
      (SELECT LPAD(SHIP_SOLD_TO_PARTY,10,'0') AS SHIP_SOLD_TO_PARTY,
        SHIP_SOLD_TO_PARTY_NAME
      FROM INV_SAP_SHIP_SOLD_TO
      )ADDRESS
    ON ADDRESS.SHIP_SOLD_TO_PARTY = SO_HST.SOLD_TO_PARTY
    )SO_HST_SOLD
  LEFT JOIN
    (SELECT LPAD(SHIP_SOLD_TO_PARTY,10,'0') AS SHIP_SOLD_TO_PARTY,
      SHIP_SOLD_TO_PARTY_NAME,
      SHIP_SOLD_TO_COUNTRY
    FROM INV_SAP_SHIP_SOLD_TO
    )ADDRESS_SHIP
  ON ADDRESS_SHIP.SHIP_SOLD_TO_PARTY = SO_HST_SOLD.SHIP_TO_PARTY
  )SOH_SOSH
LEFT JOIN
  (SELECT ID,
    MATERIAL,
    PLANT,
    CATALOG_DASH,
    SAFETY_STOCK,
    OH_QTY,
    STRATEGY_GRP,
    MRP_TYPE,
    SUBSTR(VENDOR_KEY,0,4) AS VENDOR,
    SUBSTR(PROD_BU,0,3)    AS BU,
    LEAD_TIME,
    PDT,
    UNIT_COST,
    MRP_CONTROLLER,
    ULTIMATE_SOURCE
  FROM INV_SAP_PP_OPT_X
  )ITEM_BSC
ON ITEM_BSC.ID = SOH_SOSH.ID;

SELECT ID,
  PLANT,
  MATERIAL,
  CATALOG,
  SALES_DOC,
  ITEM,
  STRATEGY_GRP,
  LEAD_TIME,
  PDT,
  SOLD_TO_PARTY,
  SOLD_TO_NAME,
  SHIP_TO_PARTY,
  SHIP_TO_NAME,
  COMMITTED_DATE,
  LAST_GI_DATE,
  CREATION_DATE,
  REQUEST_DATE,
  ORDER_QTY,
  OPEN_QTY,
  SALES_ORG,
  CURRENCY
FROM VIEW_INV_SAP_SALES_HST_LC
WHERE PLANT = '5040'
AND CREATION_DATE BETWEEN 'From_Date' AND 'To_Date';

SELECT * FROM INV_SAP_SALES_HST_LC WHERE ID = 'id_1' AND REQUEST_DATE BETWEEN SYSDATE - 365 AND SYSDATE;


SELECT ID,
  PLANT,

  SOLD_TO_PARTY,
  SOLD_TO_NAME,
  SHIP_TO_PARTY,
  SHIP_TO_NAME

FROM INV_SAP_SALES_HST_LC
WHERE PLANT = '5040';
---------------------------------------------------------------------------------------------------------------------------------
--1.One year data
--2.Last GI date
----Distributor stats
--One year so history stats.
SELECT * FROM VIEW_INV_SAP_DSTR_STATS;
SELECT * FROM VIEW_INV_SAP_DSTR_QSTATSLIST;


DROP VIEW VIEW_INV_SAP_DSTR_STATS;
CREATE VIEW VIEW_INV_SAP_DSTR_STATS AS
SELECT DIS_TOTUS.ID           AS ID,
  DIS_TOTUS.DIS_NAME          AS MAX_DIS_NAME,
  DIS_TOTUS.MAX_USAGE_QTY     AS MAX_DIS_USAGE_QTY,
  DIS_TOTUS.TOT_USAGE_QTY     AS TOT_USAGE_QTY,
  DIS_TOTUS.PERSENTAGE        AS PERSENTAGE,
  ROUND(DIS_COUNT.DISTRIBUTOR_COUNT,2) AS DISTRIBUTOR_COUNT
FROM
  (SELECT DIS_MAX_USAGE.ID                                    AS ID,
    DIS_MAX_USAGE.SOLD_TO_NAME                                AS DIS_NAME,
    DIS_MAX_USAGE.MAX_USAGE_QTY                               AS MAX_USAGE_QTY,
    TOT_USAGE.TOT_USAGE_QTY                                   AS TOT_USAGE_QTY,
    DIS_MAX_USAGE.MAX_USAGE_QTY/TOT_USAGE.TOT_USAGE_QTY AS PERSENTAGE
  FROM
    (SELECT DISTINCT DIS_USAGE_MAX.ID AS ID,
      DIS_USAGE.SOLD_TO_NAME          AS SOLD_TO_NAME,
      DIS_USAGE.DISTRIBUTOR_USAGE_QTY AS DISTRIBUTOR_USAGE_QTY,
      DIS_USAGE_MAX.MAX_USAGE_QTY     AS MAX_USAGE_QTY
    FROM
      (SELECT DISTINCT ID
        ||'_'
        ||MAX(DISTRIBUTOR_USAGE_QTY) AS IDS,
        ID,
        MAX(DISTRIBUTOR_USAGE_QTY) AS MAX_USAGE_QTY
      FROM
        (SELECT ID,
          SOLD_TO_NAME,
          SUM(ORDER_QTY) AS DISTRIBUTOR_USAGE_QTY
        FROM INV_SAP_SALES_HST_LC
        WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 365) AND TO_CHAR(SYSDATE)
        AND OPEN_QTY = 0
        GROUP BY ID,
          SOLD_TO_NAME
        )
      GROUP BY ID
      )DIS_USAGE_MAX
    LEFT JOIN
      (SELECT ID
        ||'_'
        ||SUM(ORDER_QTY) AS IDS,
        ID,
        SOLD_TO_NAME,
        SUM(ORDER_QTY) AS DISTRIBUTOR_USAGE_QTY
      FROM INV_SAP_SALES_HST_LC
      WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 365) AND TO_CHAR(SYSDATE)
      AND OPEN_QTY = 0
      GROUP BY ID,
        SOLD_TO_NAME
      )DIS_USAGE
    ON DIS_USAGE_MAX.IDS = DIS_USAGE.IDS
    )DIS_MAX_USAGE
  LEFT JOIN
    (SELECT ID,
      SUM(ORDER_QTY) AS TOT_USAGE_QTY
    FROM INV_SAP_SALES_HST_LC
    WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 365) AND TO_CHAR(SYSDATE)
    AND OPEN_QTY = 0
    GROUP BY ID
    )TOT_USAGE
  ON TOT_USAGE.ID = DIS_MAX_USAGE.ID
  )DIS_TOTUS
LEFT JOIN
  (SELECT ID,
    SUM(KEY) AS DISTRIBUTOR_COUNT
  FROM
    ( SELECT DISTINCT ID,
      SOLD_TO_NAME,
      1 AS KEY
    FROM INV_SAP_SALES_HST_LC
    WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 365) AND TO_CHAR(SYSDATE)
    AND OPEN_QTY = 0
    )
  GROUP BY ID
  )DIS_COUNT
ON DIS_COUNT.ID = DIS_TOTUS.ID;

---Dis 4Q Line count&usage
--Dis so detail list
DROP VIEW VIEW_INV_SAP_DSTR_QSTATSLIST;
CREATE VIEW VIEW_INV_SAP_DSTR_QSTATSLIST AS
SELECT 
DIS_USTQ123.IDD AS IDD,
DIS_USTQ123.ID AS ID,
DIS_USTQ123.MATERIAL AS MATERIAL,
DIS_USTQ123.CATALOG AS CATALOG,
DIS_USTQ123.SOLD_TO_NAME AS SOLD_TO_NAME,
DIS_USTQ123.DISTRIBUTOR_USAGE_QTY AS DISTRIBUTOR_USAGE_QTY,
NVL(DIS_USTQ123.Q1_DIS_USAGE_QTY,0) AS Q1_DIS_USAGE_QTY,
NVL(DIS_USTQ123.Q2_DIS_USAGE_QTY,0) AS Q2_DIS_USAGE_QTY,
NVL(DIS_USTQ123.Q3_DIS_USAGE_QTY,0) AS Q3_DIS_USAGE_QTY,
NVL(DIS_USAGE_Q4.Q4_DIS_USAGE_QTY,0) AS Q4_DIS_USAGE_QTY
FROM
(
SELECT 
DIS_USTQ12.IDD AS IDD,
DIS_USTQ12.ID AS ID,
DIS_USTQ12.MATERIAL AS MATERIAL,
DIS_USTQ12.CATALOG AS CATALOG,
DIS_USTQ12.SOLD_TO_NAME AS SOLD_TO_NAME,
DIS_USTQ12.DISTRIBUTOR_USAGE_QTY AS DISTRIBUTOR_USAGE_QTY,
DIS_USTQ12.Q1_DIS_USAGE_QTY AS Q1_DIS_USAGE_QTY,
DIS_USTQ12.Q2_DIS_USAGE_QTY AS Q2_DIS_USAGE_QTY,
DIS_USAGE_Q3.Q3_DIS_USAGE_QTY AS Q3_DIS_USAGE_QTY
FROM
(
SELECT 
DIS_USTQ1.IDD AS IDD,
DIS_USTQ1.ID AS ID,
DIS_USTQ1.MATERIAL AS MATERIAL,
DIS_USTQ1.CATALOG AS CATALOG,
DIS_USTQ1.SOLD_TO_NAME AS SOLD_TO_NAME,
DIS_USTQ1.DISTRIBUTOR_USAGE_QTY AS DISTRIBUTOR_USAGE_QTY,
DIS_USTQ1.Q1_DIS_USAGE_QTY AS Q1_DIS_USAGE_QTY,
DIS_USAGE_Q2.Q2_DIS_USAGE_QTY AS Q2_DIS_USAGE_QTY
FROM
(
SELECT 
DIS_USAGE_TOT.IDD AS IDD,
DIS_USAGE_TOT.ID AS ID,
DIS_USAGE_TOT.MATERIAL AS MATERIAL,
DIS_USAGE_TOT.CATALOG AS CATALOG,
DIS_USAGE_TOT.SOLD_TO_NAME AS SOLD_TO_NAME,
DIS_USAGE_TOT.DISTRIBUTOR_USAGE_QTY AS DISTRIBUTOR_USAGE_QTY,
DIS_USAGE_Q1.Q1_DIS_USAGE_QTY AS Q1_DIS_USAGE_QTY
FROM
(
SELECT 
      ID||'_'||SOLD_TO_NAME AS IDD,
      ID,
      MATERIAL,
      CATALOG,
      SOLD_TO_NAME,
      SUM(ORDER_QTY) AS DISTRIBUTOR_USAGE_QTY
    FROM INV_SAP_SALES_HST_LC
    WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 365) AND TO_CHAR(SYSDATE)
    AND OPEN_QTY = 0
    GROUP BY ID,
      SOLD_TO_NAME,
      MATERIAL,
      CATALOG
)DIS_USAGE_TOT
LEFT JOIN
(
--Q1
SELECT 
      ID||'_'||SOLD_TO_NAME AS IDD,
      ID,
      SOLD_TO_NAME,
      SUM(ORDER_QTY) AS Q1_DIS_USAGE_QTY
    FROM INV_SAP_SALES_HST_LC
    WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 365) AND TO_CHAR(SYSDATE - 271)
    AND OPEN_QTY = 0
    GROUP BY ID,
      SOLD_TO_NAME
)DIS_USAGE_Q1
ON DIS_USAGE_Q1.IDD = DIS_USAGE_TOT.IDD
)DIS_USTQ1
LEFT JOIN
(
--Q2
SELECT 
      ID||'_'||SOLD_TO_NAME AS IDD,
      ID,
      SOLD_TO_NAME,
      SUM(ORDER_QTY) AS Q2_DIS_USAGE_QTY
    FROM INV_SAP_SALES_HST_LC
    WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 270) AND TO_CHAR(SYSDATE - 181)
    AND OPEN_QTY = 0
    GROUP BY ID,
      SOLD_TO_NAME
)DIS_USAGE_Q2
ON DIS_USAGE_Q2.IDD = DIS_USTQ1.IDD
)DIS_USTQ12
LEFT JOIN
(
--Q3
SELECT 
      ID||'_'||SOLD_TO_NAME AS IDD,
      ID,
      SOLD_TO_NAME,
      SUM(ORDER_QTY) AS Q3_DIS_USAGE_QTY
    FROM INV_SAP_SALES_HST_LC
    WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 180) AND TO_CHAR(SYSDATE - 91)
    AND OPEN_QTY = 0
    GROUP BY ID,
      SOLD_TO_NAME
)DIS_USAGE_Q3
ON DIS_USAGE_Q3.IDD = DIS_USTQ12.IDD
)DIS_USTQ123
LEFT JOIN
(
--Q4
SELECT 
      ID||'_'||SOLD_TO_NAME AS IDD,
      ID,
      SOLD_TO_NAME,
      SUM(ORDER_QTY) AS Q4_DIS_USAGE_QTY
    FROM INV_SAP_SALES_HST_LC
    WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 90) AND TO_CHAR(SYSDATE)
    AND OPEN_QTY = 0
    GROUP BY ID,
      SOLD_TO_NAME
)DIS_USAGE_Q4
ON DIS_USAGE_Q4.IDD = DIS_USTQ123.IDD;






