--DATE:6/26/2014
--AUTHOR: HUANG MO YUE
--DMT_FRD_REPORT
---Product Line Des
---Need Product Line Des SQL file to init.
DROP TABLE INV_SAP_DMT_FRD_P12;
DROP TABLE INV_SAP_DMT_FRD_P15;
  
SELECT count(*) FROM INV_SAP_DMT_FRD_P15;
CREATE TABLE INV_SAP_DMT_FRD_P12 AS 
SELECT * FROM INV_SAP_DMT_FRD;

CREATE TABLE INV_SAP_DMT_FRD_P15 AS 
SELECT * FROM INV_SAP_DMT_FRD;

DROP TABLE INV_SAP_DMT_FRD;
CREATE TABLE INV_SAP_DMT_FRD 
(
  ASOFDATE DATE 
, TYPE VARCHAR2(200) 
, MATERIAL VARCHAR2(200) 
, PLANT VARCHAR2(200) 
, UNIT VARCHAR2(20) 
, MONTH_1 NUMBER 
, MONTH_2 NUMBER 
, MONTH_3 NUMBER 
, MONTH_4 NUMBER 
, MONTH_5 NUMBER 
, MONTH_6 NUMBER 
, MONTH_7 NUMBER 
, MONTH_8 NUMBER 
, MONTH_9 NUMBER 
, MONTH_10 NUMBER 
, MONTH_11 NUMBER 
, MONTH_12 NUMBER 
, MONTH_13 NUMBER 
, MONTH_14 NUMBER 
, MONTH_15 NUMBER 
, MONTH_16 NUMBER 
, MONTH_17 NUMBER 
, MONTH_18 NUMBER 
, MONTH_19 NUMBER 
, MONTH_20 NUMBER 
, MONTH_21 NUMBER 
, MONTH_22 NUMBER 
, MONTH_23 NUMBER 
, MONTH_24 NUMBER 
, MONTH_25 NUMBER 
, MONTH_26 NUMBER 
, MONTH_27 NUMBER 
, MONTH_28 NUMBER 
, MONTH_29 NUMBER
, MONTH_30 NUMBER 
, MONTH_31 NUMBER 
, MONTH_32 NUMBER 
, MONTH_33 NUMBER 
, MONTH_34 NUMBER 
, MONTH_35 NUMBER 
, MONTH_36 NUMBER 
, MONTH_37 NUMBER 
, MONTH_38 NUMBER 
, MONTH_39 NUMBER
, MONTH_40 NUMBER 
, MONTH_41 NUMBER 
, MONTH_42 NUMBER 
, MONTH_43 NUMBER 
, MONTH_44 NUMBER 
, MONTH_45 NUMBER 
, MONTH_46 NUMBER 
, MONTH_47 NUMBER 
, MONTH_48 NUMBER 
, MONTH_49 NUMBER
, MONTH_50 NUMBER 
, MONTH_51 NUMBER 
, MONTH_52 NUMBER 
, MONTH_53 NUMBER 
, MONTH_54 NUMBER 
);

--ADD FM
DROP TABLE INV_SAP_DMT_FRD;
CREATE TABLE INV_SAP_DMT_FRD 
(
  ASOFDATE DATE 
, TYPE VARCHAR2(200) 
, MATERIAL VARCHAR2(200) 
, PLANT VARCHAR2(200) 
, UNIT VARCHAR2(20) 
, MONTH_1 VARCHAR2(200) 
, MONTH_2 VARCHAR2(200) 
, MONTH_3 VARCHAR2(200) 
, MONTH_4 VARCHAR2(200) 
, MONTH_5 VARCHAR2(200) 
, MONTH_6 VARCHAR2(200) 
, MONTH_7 VARCHAR2(200) 
, MONTH_8 VARCHAR2(200) 
, MONTH_9 VARCHAR2(200) 
, MONTH_10 VARCHAR2(200) 
, MONTH_11 VARCHAR2(200) 
, MONTH_12 VARCHAR2(200) 
, MONTH_13 VARCHAR2(200) 
, MONTH_14 VARCHAR2(200) 
, MONTH_15 VARCHAR2(200) 
, MONTH_16 VARCHAR2(200) 
, MONTH_17 VARCHAR2(200) 
, MONTH_18 VARCHAR2(200) 
, MONTH_19 VARCHAR2(200) 
, MONTH_20 VARCHAR2(200) 
, MONTH_21 VARCHAR2(200) 
, MONTH_22 VARCHAR2(200) 
, MONTH_23 VARCHAR2(200) 
, MONTH_24 VARCHAR2(200) 
, MONTH_25 VARCHAR2(200) 
, MONTH_26 VARCHAR2(200) 
, MONTH_27 VARCHAR2(200) 
, MONTH_28 VARCHAR2(200) 
, MONTH_29 VARCHAR2(200)
, MONTH_30 VARCHAR2(200) 
, MONTH_31 VARCHAR2(200) 
, MONTH_32 VARCHAR2(200) 
, MONTH_33 VARCHAR2(200) 
, MONTH_34 VARCHAR2(200) 
, MONTH_35 VARCHAR2(200) 
, MONTH_36 VARCHAR2(200) 
, MONTH_37 VARCHAR2(200) 
, MONTH_38 VARCHAR2(200) 
, MONTH_39 VARCHAR2(200)
, MONTH_40 VARCHAR2(200) 
, MONTH_41 VARCHAR2(200) 
, MONTH_42 VARCHAR2(200) 
, MONTH_43 VARCHAR2(200) 
, MONTH_44 VARCHAR2(200) 
, MONTH_45 VARCHAR2(200) 
, MONTH_46 VARCHAR2(200) 
, MONTH_47 VARCHAR2(200) 
, MONTH_48 VARCHAR2(200) 
, MONTH_49 VARCHAR2(200)
, MONTH_50 VARCHAR2(200) 
, MONTH_51 VARCHAR2(200) 
, MONTH_52 VARCHAR2(200) 
, MONTH_53 VARCHAR2(200) 
, MONTH_54 VARCHAR2(200) 
);


SELECT COUNT(*) FROM INV_SAP_DMT_FRD; 
TRUNCATE TABLE INV_SAP_DMT_FRD;

SELECT * FROM VIEW_INV_SAP_DMT_FRD_P15;

--DMT_FRD_REPORT
DROP VIEW VIEW_INV_SAP_DMT_FRD;
SELECT * FROM VIEW_INV_SAP_DMT_FRD;
CREATE VIEW VIEW_INV_SAP_DMT_FRD AS 
SELECT 
  DMT_PRD.ID,
  DMT_PRD.TYPE,
  DMT_PRD.MATERIAL,
  DMT_PRD.PLANT,
  PP_BASIC.CATALOG_DASH,
  PP_BASIC.MAT_DESC,
  PP_BASIC.SAFETY_STOCK,
  PP_BASIC.PROD_BU,
  PP_BASIC.PROD_FAM,
  PP_BASIC.PROD_HIERARCHY,
  SUBSTR(PP_BASIC.PROD_HIERARCHY, 20)||' '||PP_BASIC.VENDOR_KEY AS PROD_LINE,
  PP_BASIC.PROC_TYPE,
  PP_BASIC.STRATEGY_GRP,
  PP_BASIC.MATL_TYPE,
  PP_BASIC.VENDOR_KEY,
  CASE WHEN DMT_PRD.TYPE = 'RA Historical Demand'
  THEN CEIL((DMT_PRD.MONTH_34+DMT_PRD.MONTH_35+DMT_PRD.MONTH_36)/3)
  ELSE 0
  END AVG_3MONTHS,
  DMT_PRD.UNIT,
  DMT_PRD.MONTH_1,
  DMT_PRD.MONTH_2,
  DMT_PRD.MONTH_3,
  DMT_PRD.MONTH_4,
  DMT_PRD.MONTH_5,
  DMT_PRD.MONTH_6,
  DMT_PRD.MONTH_7,
  DMT_PRD.MONTH_8,
  DMT_PRD.MONTH_9,
  DMT_PRD.MONTH_10,
  DMT_PRD.MONTH_11,
  DMT_PRD.MONTH_12,
  DMT_PRD.MONTH_13,
  DMT_PRD.MONTH_14,
  DMT_PRD.MONTH_15,
  DMT_PRD.MONTH_16,
  DMT_PRD.MONTH_17,
  DMT_PRD.MONTH_18,
  DMT_PRD.MONTH_19,
  DMT_PRD.MONTH_20,
  DMT_PRD.MONTH_21,
  DMT_PRD.MONTH_22,
  DMT_PRD.MONTH_23,
  DMT_PRD.MONTH_24,
  DMT_PRD.MONTH_25,
  DMT_PRD.MONTH_26,
  DMT_PRD.MONTH_27,
  DMT_PRD.MONTH_28,
  DMT_PRD.MONTH_29,
  DMT_PRD.MONTH_30,
  DMT_PRD.MONTH_31,
  DMT_PRD.MONTH_32,
  DMT_PRD.MONTH_33,
  DMT_PRD.MONTH_34,
  DMT_PRD.MONTH_35,
  DMT_PRD.MONTH_36,
  DMT_PRD.MONTH_37,
  DMT_PRD.MONTH_38,
  DMT_PRD.MONTH_39,
  DMT_PRD.MONTH_40,
  DMT_PRD.MONTH_41,
  DMT_PRD.MONTH_42,
  DMT_PRD.MONTH_43,
  DMT_PRD.MONTH_44,
  DMT_PRD.MONTH_45,
  DMT_PRD.MONTH_46,
  DMT_PRD.MONTH_47,
  DMT_PRD.MONTH_48,
  DMT_PRD.MONTH_49,
  DMT_PRD.MONTH_50,
  DMT_PRD.MONTH_51,
  DMT_PRD.MONTH_52,
  DMT_PRD.MONTH_53,
  DMT_PRD.MONTH_54
FROM
  (SELECT MATERIAL
    ||'_'
    ||PLANT AS ID,
    TYPE,
    MATERIAL,
    PLANT,
    UNIT,
    MONTH_1,
    MONTH_2,
    MONTH_3,
    MONTH_4,
    MONTH_5,
    MONTH_6,
    MONTH_7,
    MONTH_8,
    MONTH_9,
    MONTH_10,
    MONTH_11,
    MONTH_12,
    MONTH_13,
    MONTH_14,
    MONTH_15,
    MONTH_16,
    MONTH_17,
    MONTH_18,
    MONTH_19,
    MONTH_20,
    MONTH_21,
    MONTH_22,
    MONTH_23,
    MONTH_24,
    MONTH_25,
    MONTH_26,
    MONTH_27,
    MONTH_28,
    MONTH_29,
    MONTH_30,
    MONTH_31,
    MONTH_32,
    MONTH_33,
    MONTH_34,
    MONTH_35,
    MONTH_36,
    MONTH_37,
    MONTH_38,
    MONTH_39,
    MONTH_40,
    MONTH_41,
    MONTH_42,
    MONTH_43,
    MONTH_44,
    MONTH_45,
    MONTH_46,
    MONTH_47,
    MONTH_48,
    MONTH_49,
    MONTH_50,
    MONTH_51,
    MONTH_52,
    MONTH_53,
    MONTH_54
  FROM INV_SAP_DMT_FRD
  )DMT_PRD
LEFT JOIN
  (SELECT ID,
    CATALOG_DASH,
    MAT_DESC,
    SAFETY_STOCK,
    PROD_BU,
    PROD_FAM,
    PROD_HIERARCHY,
    PROC_TYPE,
    STRATEGY_GRP,
    MATL_TYPE,
    VENDOR_KEY
  FROM INV_SAP_PP_OPT_X
  )PP_BASIC
ON DMT_PRD.ID = PP_BASIC.ID;



CREATE TABLE INV_SAP_DMT_FRD_REP AS SELECT * FROM VIEW_INV_SAP_DMT_FRD;
SELECT * FROM INV_SAP_DMT_FRD_REP;
TRUNCATE TABLE INV_SAP_DMT_FRD_REP;
INSERT INTO INV_SAP_DMT_FRD_REP SELECT * FROM VIEW_INV_SAP_DMT_FRD;


SELECT 
ID,
TYPE,
MATERIAL,
PLANT,
CATALOG_DASH,
MAT_DESC,
SAFETY_STOCK,
PROD_BU,
PROD_FAM,
PROD_HIERARCHY,
PROD_LINE,
PROC_TYPE,
STRATEGY_GRP,
MATL_TYPE,
VENDOR_KEY,
AVG_3MONTHS
FROM INV_SAP_DMT_FRD_REP WHERE MATERIAL = '700-HLS11Z24 A';




----VIEW_INV_SAP_DMT_FRD_P12
DROP TABLE INV_SAP_DMT_FRD_REPP12;
CREATE TABLE INV_SAP_DMT_FRD_REPP12 AS SELECT * FROM VIEW_INV_SAP_DMT_FRD_P12;
TRUNCATE TABLE INV_SAP_DMT_FRD_REPP12;
INSERT INTO INV_SAP_DMT_FRD_REPP12 SELECT * FROM VIEW_INV_SAP_DMT_FRD_P12;
DROP VIEW VIEW_INV_SAP_DMT_FRD_P12;
CREATE VIEW VIEW_INV_SAP_DMT_FRD_P12 AS
SELECT 
  DMT_PP_BS.ID,
  DMT_PP_BS.TYPE,
  DMT_PP_BS.MATERIAL,
  DMT_PP_BS.PLANT,
  DMT_PP_BS.CATALOG_DASH,
  DMT_PP_BS.BULLETIN,
  DMT_PP_BS.MAT_DESC,
  DMT_PP_BS.SAFETY_STOCK,
  DMT_PP_BS.PROD_BU,
  DMT_PP_BS.PROD_FAM,
  DMT_PP_BS.PROD_HIERARCHY,
  DMT_PP_BS.PROD_LINE,
  PRO_DES.PRO_LINE_DES,
  DMT_PP_BS.PROC_TYPE,
  DMT_PP_BS.STRATEGY_GRP,
  DMT_PP_BS.MATL_TYPE,
  DMT_PP_BS.VENDOR_KEY,
  DMT_PP_BS.AVG_3MONTHS,
  DMT_PP_BS.UNIT,
  DMT_PP_BS.MONTH_1,
  DMT_PP_BS.MONTH_2,
  DMT_PP_BS.MONTH_3,
  DMT_PP_BS.MONTH_4,
  DMT_PP_BS.MONTH_5,
  DMT_PP_BS.MONTH_6,
  DMT_PP_BS.MONTH_7,
  DMT_PP_BS.MONTH_8,
  DMT_PP_BS.MONTH_9,
  DMT_PP_BS.MONTH_10,
  DMT_PP_BS.MONTH_11,
  DMT_PP_BS.MONTH_12,
  DMT_PP_BS.MONTH_13,
  DMT_PP_BS.MONTH_14,
  DMT_PP_BS.MONTH_15,
  DMT_PP_BS.MONTH_16,
  DMT_PP_BS.MONTH_17,
  DMT_PP_BS.MONTH_18,
  DMT_PP_BS.MONTH_19,
  DMT_PP_BS.MONTH_20,
  DMT_PP_BS.MONTH_21,
  DMT_PP_BS.MONTH_22,
  DMT_PP_BS.MONTH_23,
  DMT_PP_BS.MONTH_24,
  DMT_PP_BS.MONTH_25,
  DMT_PP_BS.MONTH_26,
  DMT_PP_BS.MONTH_27,
  DMT_PP_BS.MONTH_28,
  DMT_PP_BS.MONTH_29,
  DMT_PP_BS.MONTH_30,
  DMT_PP_BS.MONTH_31,
  DMT_PP_BS.MONTH_32,
  DMT_PP_BS.MONTH_33,
  DMT_PP_BS.MONTH_34,
  DMT_PP_BS.MONTH_35,
  DMT_PP_BS.MONTH_36,
  DMT_PP_BS.MONTH_37,
  DMT_PP_BS.MONTH_38,
  DMT_PP_BS.MONTH_39,
  DMT_PP_BS.MONTH_40,
  DMT_PP_BS.MONTH_41,
  DMT_PP_BS.MONTH_42,
  DMT_PP_BS.MONTH_43,
  DMT_PP_BS.MONTH_44,
  DMT_PP_BS.MONTH_45,
  DMT_PP_BS.MONTH_46,
  DMT_PP_BS.MONTH_47,
  DMT_PP_BS.MONTH_48,
  DMT_PP_BS.MONTH_49,
  DMT_PP_BS.MONTH_50,
  DMT_PP_BS.MONTH_51,
  DMT_PP_BS.MONTH_52,
  DMT_PP_BS.MONTH_53,
  DMT_PP_BS.MONTH_54
FROM 
(
SELECT DMT_PRD.ID,
  DMT_PRD.TYPE,
  DMT_PRD.MATERIAL,
  DMT_PRD.PLANT,
  PP_BASIC.CATALOG_DASH,
  SUBSTR(PP_BASIC.CATALOG_DASH,0,4) AS BULLETIN,
  PP_BASIC.MAT_DESC,
  PP_BASIC.SAFETY_STOCK,
  PP_BASIC.PROD_BU,
  PP_BASIC.PROD_FAM,
  PP_BASIC.PROD_HIERARCHY,
  SUBSTR(PP_BASIC.PROD_HIERARCHY,0,12) AS PROD_LINE,
  PP_BASIC.PROC_TYPE,
  PP_BASIC.STRATEGY_GRP,
  PP_BASIC.MATL_TYPE,
  PP_BASIC.VENDOR_KEY,
  CASE
    WHEN DMT_PRD.TYPE = 'RA Historical Demand'
    THEN CEIL((DMT_PRD.MONTH_34+DMT_PRD.MONTH_35+DMT_PRD.MONTH_36)/3)
    ELSE 0
  END AVG_3MONTHS,
  DMT_PRD.UNIT,
  DMT_PRD.MONTH_1,
  DMT_PRD.MONTH_2,
  DMT_PRD.MONTH_3,
  DMT_PRD.MONTH_4,
  DMT_PRD.MONTH_5,
  DMT_PRD.MONTH_6,
  DMT_PRD.MONTH_7,
  DMT_PRD.MONTH_8,
  DMT_PRD.MONTH_9,
  DMT_PRD.MONTH_10,
  DMT_PRD.MONTH_11,
  DMT_PRD.MONTH_12,
  DMT_PRD.MONTH_13,
  DMT_PRD.MONTH_14,
  DMT_PRD.MONTH_15,
  DMT_PRD.MONTH_16,
  DMT_PRD.MONTH_17,
  DMT_PRD.MONTH_18,
  DMT_PRD.MONTH_19,
  DMT_PRD.MONTH_20,
  DMT_PRD.MONTH_21,
  DMT_PRD.MONTH_22,
  DMT_PRD.MONTH_23,
  DMT_PRD.MONTH_24,
  DMT_PRD.MONTH_25,
  DMT_PRD.MONTH_26,
  DMT_PRD.MONTH_27,
  DMT_PRD.MONTH_28,
  DMT_PRD.MONTH_29,
  DMT_PRD.MONTH_30,
  DMT_PRD.MONTH_31,
  DMT_PRD.MONTH_32,
  DMT_PRD.MONTH_33,
  DMT_PRD.MONTH_34,
  DMT_PRD.MONTH_35,
  DMT_PRD.MONTH_36,
  DMT_PRD.MONTH_37,
  DMT_PRD.MONTH_38,
  DMT_PRD.MONTH_39,
  DMT_PRD.MONTH_40,
  DMT_PRD.MONTH_41,
  DMT_PRD.MONTH_42,
  DMT_PRD.MONTH_43,
  DMT_PRD.MONTH_44,
  DMT_PRD.MONTH_45,
  DMT_PRD.MONTH_46,
  DMT_PRD.MONTH_47,
  DMT_PRD.MONTH_48,
  DMT_PRD.MONTH_49,
  DMT_PRD.MONTH_50,
  DMT_PRD.MONTH_51,
  DMT_PRD.MONTH_52,
  DMT_PRD.MONTH_53,
  DMT_PRD.MONTH_54
FROM
  (SELECT MATERIAL
    ||'_'
    ||PLANT AS ID,
    TYPE,
    MATERIAL,
    PLANT,
    UNIT,
    MONTH_1,
    MONTH_2,
    MONTH_3,
    MONTH_4,
    MONTH_5,
    MONTH_6,
    MONTH_7,
    MONTH_8,
    MONTH_9,
    MONTH_10,
    MONTH_11,
    MONTH_12,
    MONTH_13,
    MONTH_14,
    MONTH_15,
    MONTH_16,
    MONTH_17,
    MONTH_18,
    MONTH_19,
    MONTH_20,
    MONTH_21,
    MONTH_22,
    MONTH_23,
    MONTH_24,
    MONTH_25,
    MONTH_26,
    MONTH_27,
    MONTH_28,
    MONTH_29,
    MONTH_30,
    MONTH_31,
    MONTH_32,
    MONTH_33,
    MONTH_34,
    MONTH_35,
    MONTH_36,
    MONTH_37,
    MONTH_38,
    MONTH_39,
    MONTH_40,
    MONTH_41,
    MONTH_42,
    MONTH_43,
    MONTH_44,
    MONTH_45,
    MONTH_46,
    MONTH_47,
    MONTH_48,
    MONTH_49,
    MONTH_50,
    MONTH_51,
    MONTH_52,
    MONTH_53,
    MONTH_54
  FROM INV_SAP_DMT_FRD_P12
  )DMT_PRD
LEFT JOIN
  (SELECT ID,
    CATALOG_DASH,
    MAT_DESC,
    SAFETY_STOCK,
    PROD_BU,
    PROD_FAM,
    PROD_HIERARCHY,
    PROC_TYPE,
    STRATEGY_GRP,
    MATL_TYPE,
    VENDOR_KEY
  FROM INV_SAP_PP_OPT_X
  )PP_BASIC
ON DMT_PRD.ID = PP_BASIC.ID
)DMT_PP_BS
LEFT JOIN
(
SELECT PRO_LINE_NAME,PRO_LINE_DES FROM INV_SAP_DMT_FRD_PLDES
)PRO_DES
ON PRO_DES.PRO_LINE_NAME = DMT_PP_BS.PROD_LINE;


select * From INV_SAP_DMT_FRD_P12 where plant = '5070' and material = '0041-5077';
----VIEW_INV_SAP_DMT_FRD_P15
DROP TABLE INV_SAP_DMT_FRD_REPP15;
CREATE TABLE INV_SAP_DMT_FRD_REPP15 AS SELECT * FROM VIEW_INV_SAP_DMT_FRD_P15;
TRUNCATE TABLE INV_SAP_DMT_FRD_REPP15;
INSERT INTO INV_SAP_DMT_FRD_REPP15 SELECT * FROM VIEW_INV_SAP_DMT_FRD_P15;

DROP VIEW VIEW_INV_SAP_DMT_FRD_P15;
CREATE VIEW VIEW_INV_SAP_DMT_FRD_P15 AS 
SELECT 
  DMT_PP_BS.ID,
  DMT_PP_BS.TYPE,
  DMT_PP_BS.MATERIAL,
  DMT_PP_BS.PLANT,
  DMT_PP_BS.CATALOG_DASH,
  DMT_PP_BS.BULLETIN,
  DMT_PP_BS.MAT_DESC,
  DMT_PP_BS.SAFETY_STOCK,
  DMT_PP_BS.PROD_BU,
  DMT_PP_BS.PROD_FAM,
  DMT_PP_BS.PROD_HIERARCHY,
  DMT_PP_BS.PROD_LINE,
  PRO_DES.PRO_LINE_DES,
  DMT_PP_BS.PROC_TYPE,
  DMT_PP_BS.STRATEGY_GRP,
  DMT_PP_BS.MATL_TYPE,
  DMT_PP_BS.VENDOR_KEY,
  DMT_PP_BS.AVG_3MONTHS,
  DMT_PP_BS.UNIT,
  DMT_PP_BS.MONTH_1,
  DMT_PP_BS.MONTH_2,
  DMT_PP_BS.MONTH_3,
  DMT_PP_BS.MONTH_4,
  DMT_PP_BS.MONTH_5,
  DMT_PP_BS.MONTH_6,
  DMT_PP_BS.MONTH_7,
  DMT_PP_BS.MONTH_8,
  DMT_PP_BS.MONTH_9,
  DMT_PP_BS.MONTH_10,
  DMT_PP_BS.MONTH_11,
  DMT_PP_BS.MONTH_12,
  DMT_PP_BS.MONTH_13,
  DMT_PP_BS.MONTH_14,
  DMT_PP_BS.MONTH_15,
  DMT_PP_BS.MONTH_16,
  DMT_PP_BS.MONTH_17,
  DMT_PP_BS.MONTH_18,
  DMT_PP_BS.MONTH_19,
  DMT_PP_BS.MONTH_20,
  DMT_PP_BS.MONTH_21,
  DMT_PP_BS.MONTH_22,
  DMT_PP_BS.MONTH_23,
  DMT_PP_BS.MONTH_24,
  DMT_PP_BS.MONTH_25,
  DMT_PP_BS.MONTH_26,
  DMT_PP_BS.MONTH_27,
  DMT_PP_BS.MONTH_28,
  DMT_PP_BS.MONTH_29,
  DMT_PP_BS.MONTH_30,
  DMT_PP_BS.MONTH_31,
  DMT_PP_BS.MONTH_32,
  DMT_PP_BS.MONTH_33,
  DMT_PP_BS.MONTH_34,
  DMT_PP_BS.MONTH_35,
  DMT_PP_BS.MONTH_36,
  DMT_PP_BS.MONTH_37,
  DMT_PP_BS.MONTH_38,
  DMT_PP_BS.MONTH_39,
  DMT_PP_BS.MONTH_40,
  DMT_PP_BS.MONTH_41,
  DMT_PP_BS.MONTH_42,
  DMT_PP_BS.MONTH_43,
  DMT_PP_BS.MONTH_44,
  DMT_PP_BS.MONTH_45,
  DMT_PP_BS.MONTH_46,
  DMT_PP_BS.MONTH_47,
  DMT_PP_BS.MONTH_48,
  DMT_PP_BS.MONTH_49,
  DMT_PP_BS.MONTH_50,
  DMT_PP_BS.MONTH_51,
  DMT_PP_BS.MONTH_52,
  DMT_PP_BS.MONTH_53,
  DMT_PP_BS.MONTH_54
FROM 
(
SELECT DMT_PRD.ID,
  DMT_PRD.TYPE,
  DMT_PRD.MATERIAL,
  DMT_PRD.PLANT,
  PP_BASIC.CATALOG_DASH,
  SUBSTR(PP_BASIC.CATALOG_DASH,0,4) AS BULLETIN,
  PP_BASIC.MAT_DESC,
  PP_BASIC.SAFETY_STOCK,
  PP_BASIC.PROD_BU,
  PP_BASIC.PROD_FAM,
  PP_BASIC.PROD_HIERARCHY,
  SUBSTR(PP_BASIC.PROD_HIERARCHY,0,12) AS PROD_LINE,
  PP_BASIC.PROC_TYPE,
  PP_BASIC.STRATEGY_GRP,
  PP_BASIC.MATL_TYPE,
  PP_BASIC.VENDOR_KEY,
  CASE
    WHEN DMT_PRD.TYPE = 'RA Historical Demand'
    THEN CEIL((DMT_PRD.MONTH_34+DMT_PRD.MONTH_35+DMT_PRD.MONTH_36)/3)
    ELSE 0
  END AVG_3MONTHS,
  DMT_PRD.UNIT,
  DMT_PRD.MONTH_1,
  DMT_PRD.MONTH_2,
  DMT_PRD.MONTH_3,
  DMT_PRD.MONTH_4,
  DMT_PRD.MONTH_5,
  DMT_PRD.MONTH_6,
  DMT_PRD.MONTH_7,
  DMT_PRD.MONTH_8,
  DMT_PRD.MONTH_9,
  DMT_PRD.MONTH_10,
  DMT_PRD.MONTH_11,
  DMT_PRD.MONTH_12,
  DMT_PRD.MONTH_13,
  DMT_PRD.MONTH_14,
  DMT_PRD.MONTH_15,
  DMT_PRD.MONTH_16,
  DMT_PRD.MONTH_17,
  DMT_PRD.MONTH_18,
  DMT_PRD.MONTH_19,
  DMT_PRD.MONTH_20,
  DMT_PRD.MONTH_21,
  DMT_PRD.MONTH_22,
  DMT_PRD.MONTH_23,
  DMT_PRD.MONTH_24,
  DMT_PRD.MONTH_25,
  DMT_PRD.MONTH_26,
  DMT_PRD.MONTH_27,
  DMT_PRD.MONTH_28,
  DMT_PRD.MONTH_29,
  DMT_PRD.MONTH_30,
  DMT_PRD.MONTH_31,
  DMT_PRD.MONTH_32,
  DMT_PRD.MONTH_33,
  DMT_PRD.MONTH_34,
  DMT_PRD.MONTH_35,
  DMT_PRD.MONTH_36,
  DMT_PRD.MONTH_37,
  DMT_PRD.MONTH_38,
  DMT_PRD.MONTH_39,
  DMT_PRD.MONTH_40,
  DMT_PRD.MONTH_41,
  DMT_PRD.MONTH_42,
  DMT_PRD.MONTH_43,
  DMT_PRD.MONTH_44,
  DMT_PRD.MONTH_45,
  DMT_PRD.MONTH_46,
  DMT_PRD.MONTH_47,
  DMT_PRD.MONTH_48,
  DMT_PRD.MONTH_49,
  DMT_PRD.MONTH_50,
  DMT_PRD.MONTH_51,
  DMT_PRD.MONTH_52,
  DMT_PRD.MONTH_53,
  DMT_PRD.MONTH_54
FROM
  (SELECT MATERIAL
    ||'_'
    ||PLANT AS ID,
    TYPE,
    MATERIAL,
    PLANT,
    UNIT,
    MONTH_1,
    MONTH_2,
    MONTH_3,
    MONTH_4,
    MONTH_5,
    MONTH_6,
    MONTH_7,
    MONTH_8,
    MONTH_9,
    MONTH_10,
    MONTH_11,
    MONTH_12,
    MONTH_13,
    MONTH_14,
    MONTH_15,
    MONTH_16,
    MONTH_17,
    MONTH_18,
    MONTH_19,
    MONTH_20,
    MONTH_21,
    MONTH_22,
    MONTH_23,
    MONTH_24,
    MONTH_25,
    MONTH_26,
    MONTH_27,
    MONTH_28,
    MONTH_29,
    MONTH_30,
    MONTH_31,
    MONTH_32,
    MONTH_33,
    MONTH_34,
    MONTH_35,
    MONTH_36,
    MONTH_37,
    MONTH_38,
    MONTH_39,
    MONTH_40,
    MONTH_41,
    MONTH_42,
    MONTH_43,
    MONTH_44,
    MONTH_45,
    MONTH_46,
    MONTH_47,
    MONTH_48,
    MONTH_49,
    MONTH_50,
    MONTH_51,
    MONTH_52,
    MONTH_53,
    MONTH_54
  FROM INV_SAP_DMT_FRD_P15
  )DMT_PRD
LEFT JOIN
  (SELECT ID,
    CATALOG_DASH,
    MAT_DESC,
    SAFETY_STOCK,
    PROD_BU,
    PROD_FAM,
    PROD_HIERARCHY,
    PROC_TYPE,
    STRATEGY_GRP,
    MATL_TYPE,
    VENDOR_KEY
  FROM INV_SAP_PP_OPT_X where id = 'PN-172138_5190'
  )PP_BASIC
ON DMT_PRD.ID = PP_BASIC.ID
)DMT_PP_BS
LEFT JOIN
(
SELECT PRO_LINE_NAME,PRO_LINE_DES FROM INV_SAP_DMT_FRD_PLDES
)PRO_DES
ON PRO_DES.PRO_LINE_NAME = DMT_PP_BS.PROD_LINE;

SELECT * FROM INV_SAP_DMT_FRD_PLDES;


---Remove Spike Order in product line level
---Last two months

DROP TABLE INV_SAP_DMT_FRD_P12;
DROP TABLE INV_SAP_DMT_FRD_P15;



(
SELECT 
  PLANT||'_'||
  PROD_LINE AS PP_ID,
  PLANT,
  PROD_LINE,
    MONTH_25,
    MONTH_26,
    MONTH_27,
    MONTH_28,
    MONTH_29,
    MONTH_30,
    MONTH_31,
    MONTH_32,
    MONTH_33,
    MONTH_34,
    MONTH_35,
    MONTH_36
FROM INV_SAP_DMT_FRD_REPP15 WHERE TYPE = 'RA Historical Demand'
)PP_MM12
LEFT JOIN
(
SELECT 
  PLANT||'_'||
  PROD_LINE AS PP_ID,
  PLANT,
  PROD_LINE,
  SUM(PRODLINE_SUMMM12)/12 AS PRODLINE_MM12_AVG
  FROM
  (SELECT PLANT,
    PROD_LINE,
    (MONTH_25+ MONTH_26+ MONTH_27+ MONTH_28+ MONTH_29+ MONTH_30+ MONTH_31+ MONTH_32+ MONTH_33+ MONTH_34+ MONTH_35+ MONTH_36) AS PRODLINE_SUMMM12
  FROM INV_SAP_DMT_FRD_REPP15
  WHERE TYPE = 'RA Historical Demand'
  )
GROUP BY PLANT,
  PROD_LINE
)PP_MM12_AVG

select * from INV_SAP_DMT_FRD_REPP15;


DECLARE
    v_name EMPLOYEE_NAME_BIRTHDAY.NAME%TYPE;
    CURSOR c_cursor IS SELECT NAME FROM EMPLOYEE_NAME_BIRTHDAY;
    v_date VARCHAR2(20 CHAR);
  BEGIN
    v_date := SYSDATE;
    OPEN c_cursor;
    FETCH c_cursor INTO v_name;
    SYS.DBMS_OUTPUT.PUT_LINE(v_name);
    UPDATE EMPLOYEE_NAME_BIRTHDAY SET BIRTHDAY = v_date WHERE NAME = v_name;
    CLOSE c_cursor;
END;

CREATE OR REPLACE PROCEDURE APAFC_CACL_STD()
IS
V_PLANT INV_SAP_DMT_FRD_REPP15.PLANT%TYPE;
V_PROD_LINE INV_SAP_DMT_FRD_REPP15.PROD_LINE%TYPE;
V_MM25 INV_SAP_DMT_FRD_REPP15.MONTH_25%TYPE;
V_MM26 INV_SAP_DMT_FRD_REPP15.MONTH_26%TYPE;
V_MM27 INV_SAP_DMT_FRD_REPP15.MONTH_27%TYPE;
V_MM28 INV_SAP_DMT_FRD_REPP15.MONTH_28%TYPE;
V_MM29 INV_SAP_DMT_FRD_REPP15.MONTH_29%TYPE;
V_MM30 INV_SAP_DMT_FRD_REPP15.MONTH_30%TYPE;
V_MM31 INV_SAP_DMT_FRD_REPP15.MONTH_31%TYPE;
V_MM32 INV_SAP_DMT_FRD_REPP15.MONTH_32%TYPE;
V_MM33 INV_SAP_DMT_FRD_REPP15.MONTH_33%TYPE;
V_MM34 INV_SAP_DMT_FRD_REPP15.MONTH_34%TYPE;
V_MM35 INV_SAP_DMT_FRD_REPP15.MONTH_35%TYPE;
V_MM36 INV_SAP_DMT_FRD_REPP15.MONTH_36%TYPE;


CURSOR  C_CURSOR IS SELECT 
  PLANT,
  PROD_LINE,
    MONTH_25,
    MONTH_26,
    MONTH_27,
    MONTH_28,
    MONTH_29,
    MONTH_30,
    MONTH_31,
    MONTH_32,
    MONTH_33,
    MONTH_34,
    MONTH_35,
    MONTH_36
FROM INV_SAP_DMT_FRD_REPP15 WHERE TYPE = 'RA Historical Demand';
BEGIN

END;



SELECT PLANT,
  PROD_LINE,
  SUM(MONTH_25) AS SUM_MONTH25
FROM INV_SAP_DMT_FRD_REPP15
WHERE TYPE = 'RA Historical Demand'
GROUP BY PLANT,
  PROD_LINE


select * from inv_sap_sales_hst_lc where material = 'PN-145756' and plant = '5200';



truncate table INV_SAP_DMT_FRD_PLDES;
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ACSA1713A675','Component Design Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ACSA1713A676','Architecture Design Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ACSA1713A677','Misc Automation Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ACSA1733A684','Toolkits');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ACSA1823A679','Connectivity Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ACSA1823A680','Process Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ACSA1823A681','Condition Based Monitoring Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CCTA0983A382','DirectConnect 8x5');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CCTA0993A392','Bronze');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CCTA1003A472','Support Products');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CCTA1043A484','Application Support');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CDSA0283A115','PowerFlex 4');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CDSA0283A116','PowerFlex 4M');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CDSA0283A117','PowerFlex 40');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CDSA0283A118','PowerFlex 40P');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CDSA0283A119','PowerFlex 400');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CDSA0283A663','PowerFlex 400N');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CDSA0283A664','PowerFlex 400P');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CDSA0283A852','PowerFlex 523');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CDSA0283A853','PowerFlex 525');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CDSA0283B067','PowerFlex 527');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CDSA0293A122','PF Cmpnt Cls HIMs,Comm,Opts,Accs, Spares');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CDSA1583A581','PowerFlex 4 Packaged');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CDSA1583A583','PowerFlex 40 Packaged');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CDSA1603A648','PowerFlex 400 Packaged');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CDSA2313B053','F500 Component Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CLXA0403A154','Brand Label');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CLXA0403A155','1756 Logix I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CLXA0403A156','CLX Motion Controller Related');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CLXA0403A159','Netlinx Comms');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CLXA0403A160','ControlLogix');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CLXA0403A162','ProcessLogix');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CLXA0403A164','SoftLogix');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CLXA0403A850','1715 Redundant I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CLXA0403A927','EMEA Kits');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CMXA1323A525','1768/1769 CompactLogix');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CMXA1323A526','1769 CompactLogix I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CMXA1323A527','FlexLogix');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CMXA1323A921','1769 CompactLogix Processors - Denso');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CMXA1323A922','1769 CompactLogix I/O - Denso');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CMXA1323A926','Compact 5000 I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CPBA1853A753','Enclosed IEC Starter');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CPBA1853A754','Enclosed NEMA Starter');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CPBA1853A755','Enclosed SMC Starter');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CPBA1853A757','Enclosed Disconnects');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CPBA1853A759','Enclosures');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CPBA1853B093','Pump Panels');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CPBA1853B095','Enclosed Circuit Breakers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CPBA2443A785','Open IEC Starters');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CPBA2453B096','Bus Bar Systems');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('DIOA0613A229','1790 CompactBlock LDX');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('DIOA0613A230','1791 CompactBlock');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('DIOA0613A916','1791 CompactBlock - Denso');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('DIOA0623A231','1734 POINT I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('DIOA0623A232','1794 FLEX I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('DIOA0623A233','1797 FLEX Ex I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('DIOA0623A917','1794 FLEX I/O - Denso');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('DIOA0633A234','1732 ArmorBlock I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('DIOA0633A236','1792D ArmorBlock MaXum I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('DIOA0643A237','1738 ArmorPoint I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('DIOA1283A507','1799 Standard');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('DIOA1283A511','OEM Wiring Component');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('DIOA1293A512','I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('EOIA0453A180','PanelView Standard Platforms');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('EOIA0453A181','PanelView Enhanced Platforms');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('EOIA0453A182','PVP 700-1500');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('EOIA0453A183','Message Displays Platforms');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('EOIA0453A674','PVP 400-600');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('EOIA0453A789','PanelView 5500');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('EOIA0453A854','PVP 6 700-1500');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('EOIA0453A898','PanelView 5300');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('EOIA0453B034','PanelView Plus 7');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('EOIA0453B035','PanelView Plus 7M');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('EOIA0453B082','MobileView');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('EPCA0133A031','Smart Motor Controllers (Open Style)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('EPCA0133A033','IEC Networked Starters');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('EPCA0133A034','Power Solid State Contactors');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('EPCA0143A035','NEMA Electronic Protective Devices');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('EPCA0143A036','IEC Electronic Protective Devices');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('EPCA2093A961','Hardware');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('EPCA2093A962','Miscellaneous');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ESBA0203A082','421 - IEC Terminal Blocks');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ESBA0203A084','Signal Assemblies');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ESBA0213A727','AMAT');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ESBA0213A730','Ingersal Rand (I-R)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ESBA0213A735','Small OEM');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ESBA0213A740','Transportation');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ESBA0213A817','ESB Raw Material Extensions');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ESBA0223A742','ElectroGuard Accessories');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ESBA0223A743','Safety assemblies');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('GIAA0013A001','GP Relays and Timers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('GIAA0013A938','LGC Misc S+S Product');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('GIAA0023A003','Signaling Products');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('GIAA0033A004','IEC Terminal Blocks');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('GIAA0033A005','Wiring Systems');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('GIAA0053A007','Digital Temp Controller');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('GIAA0053A716','Signal Conditioning');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('GIAA0053A749','NEMA Condition Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('GIAA0083A016','NEMA Relays andTimers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('GIAA0093A019','IEC Control Relays');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICBA0433A176','Integrated Display Computers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICBA0433A177','Non-Display Computers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICBA0433A179','Monitors');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICBA0433A521','Accessories');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICMA0903A434','Portable Data collection');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICMA0913A435','ProtectionSystems');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICMA0923A436','On-Line Surveillance');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICMA0933A437','Sensors and Accessories');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICPA0103A019','IEC Control Relays');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICPA0103A780','IEC Bimetal Overload Relays');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICPA0103A781','IEC Contactors (< 85 Amps)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICPA0103A782','IEC Bus Bar Systems and Components');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICPA0103A784','IEC Sm. Mtr Protect and Circuit Brk <100A');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICPA0103A785','IEC Open Starters');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICPA0103A937','ICP Misc S+S Products');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICPA0103B023','IEC X-Series Control Relays');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICPA0103B024','IEC X-Series Contactors (< 97 Amps)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICPA0123A022','IEC Contactors (> 85 Amps)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICPA0123A023','IEC Disconnects and Load Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICPA0123A029','IEC Lg Motor Protect and Circuit Break>100A');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICPA0123B026','IEC X-Series Contactors (> 97 Amps)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('ICPA0123B027','IEC X-Series MCCBs (16..400A)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0723A252','MPF');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0723A253','MPS');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0723A254','MPC');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0723A256','1326AB');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0723A258','TL/TLY  Series');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0723A260','HPK');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0723A262','H / S');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0723A487','MPL Small');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0723A488','MPL');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0723A691','MPM');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0723A725','RDB');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0723A870','VPL');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0723A951','MPMA');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0733A266','MPAI');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0733A517','MPAS');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0733A666','Linear Motors');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0733A668','MP/TLAR');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0733A884','Anorad Linear Motors');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0743A268','Kinetix 7000');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0743A269','Kinetix 6000');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0743A270','Kinetix 2000');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0743A271','Ultra5000');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0743A272','Ultra3000');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0743A273','Ultra1500');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0743A748','Kinetix 300');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0743A798','Kinetix 3');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0743A873','Kinetix 350 Servo Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0743A875','Kinetix Mid Range Drives');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0743B030','Kinetix 5700 Inverters');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0743B031','Kinetix 5700 Diode Power Supplies');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0743B032','Kinetix 5700 Dual Axis Inverters');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0743B033','Kinetix 5700 Accessory');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0743B092','Kinetix 6200/6500');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0753A277','DIN Non-Flex IP67');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0753A278','DIN High Flex IP67');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0753A280','H/F  Non-Flex');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0753A281','Bayonet Non-Flex');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0753A282','Bayonet High Flex');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0753A286','TL AMP  Non-Flex');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0753A290','Transition Non-Flex');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0753A291','Control');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0753A292','Communication');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0753A293','Fiber Optics');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0753A294','Connection');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0753A298','1326 C');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0753A871','2090-CS Single Cable, Non-Flex');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0753A872','2090-CS Single Cable, Flex');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0763A304','Ultraware');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA0763A309','Accessories');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA1863A799','Accessories Motors and Actuators, Rotary');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA1863A803','Accessories Motors and Actuators, Linear');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA1873A800','Accessories Drives');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA1883A805','Drives/ Miscellaneous');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA1973A886','LDAT-Series');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA1983A888','Accessories');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('KNXA2323B063','iTrak Products');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('LGCA0013A001','GP Relays and Timers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('LGCA0023A003','Signaling Products');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('LGCA0033A004','IEC Terminal Blocks');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('LGCA0033A005','Wiring Systems');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('LGCA0043A006','Circuit Protection');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('LGCA0043A965','DySC and I-Sense');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('LGCA0053A007','Digital Temp Controller');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('LGCA0053A749','NEMA Condition Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('LGCA0063A008','Power Supplies');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('LGCA0063A009','Uninterruptible Power Supplies');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('LGCA0063A750','Transformers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('LGCA1843A751','Surge and Filter');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('LGCA1843A752','Power Distribution Blocks');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('LVMA0193A061','2100 Units');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('LVMA0193A064','Inactive FY10');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('LVMA0193A630','2100 Parts');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('LVMA0193A770','2100 Materials');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('LVMA1653A641','2500 IEC LVMCC Assembled');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('LVMA1653A786','2500 IEC LVMCC Unassembled');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MCPA0073A011','NEMA Starters and Starter Components');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MCPA0073A013','NEMA Manual Starters');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MCPA0073B024','IEC X-Series Contactors (< 97 Amps)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MCPA0073B025','IEC X-Series Sm. Mtr Protect and Circuit B');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MCPA0073B026','IEC X-Series Contactors (> 97 Amps)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MCPA0073B028','IEC X-Series OLRs (0.1..330A)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MCPA0103A022','IEC Contactors (> 85 Amps)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MCPA0103A780','IEC Bimetal Overload Relays');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MCPA0103A781','IEC Contactors (< 85 Amps)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MCPA0103A782','IEC Bus Bar Systems and Components');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MCPA0103A784','IEC Sm. Mtr Protect and Circuit Brk <100A');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MCPA0103A937','ICP Misc S+S Products');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MCPA0133A031','Smart Motor Controll');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MCPA0133A034','Power Solid State Contactors');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MCPA0143A035','NEMA Electronic Protective Devices');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MCPA0143A036','IEC Electronic Protective Devices');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MVDA0233A091','Air Cooled A-Frame MV Drives');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MVDA0233A094','Miscellaneous MV Drives (811)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MVDA0233A095','MV Drive Parts (812)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MVDA0233A814','MVD Raw Material Extensions');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MVDA0233A905','Air Cooled B-Frame MV Drives');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MVDA0233A947','Extended Warranty');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MVDA0233B052','PowerFlex 6000 MV Drives');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MVDA0243A101','Third Party Equipment (824)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MVDA0243A904','MV Drive Isolation Transformers (821)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MVMA0173A047','NEMA Starters - Non-arc');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MVMA0173A049','NEMA Solid State Controllers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MVMA0173A054','OEM Parts (810)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MVMA0173A055','parts (812)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MVMA0173A059','MV MCC Miscellaneous');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('MVMA0183A060','Third Party Equipment (825)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('NETA2333B070','Stratix Cisco Branded');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('NETA2333B071','Stratix Non-Cisco Branded');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('NETA2333B072','EtherNet/IP Enablers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('NETA2343B073','ControlNet Platforms');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('NETA2343B074','ContlNet Enablers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('NETA2353B075','DeviceNet Platforms');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('NETA2353B076','DeviceNet Enablers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('NETA2363B077','Process Modules');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('NETA2363B078','Specialty Modules');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('NPLA0073A011','NEMA Starters and Starter Components');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('NPLA0073A013','NEMA Manual Starters');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('NPLA0073A014','NEMA Disconnects (Open Style)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('NPLA0073A015','NEMA Repair Parts');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('NPLA0083A016','NEMA Relays and -Timers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('NPLA1853A753','IEC Enclosed Starters');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('NPLA1853A754','NEMA Enclosed Starters');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('NPLA1853A755','Smart Motor Controllers (Enclosed Style)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('NPLA1853A757','Disconnects (Enclosed)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('NPLA1853A759','Enclosures');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PBSA0153A038','NEMA Pushbuttons - 30mm');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PBSA0153A039','IEC Pushbuttons - 22.5mm');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PBSA0153A040','NEMA  Pushbuttons - 22.5mm');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PBSA0153A041','IEC Pushbuttons - < 22.5mm');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PBSA0153A042','NEMA Hazardous Location Pushbuttons');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PBSA0153A043','Touch Buttons');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PBSA0153A044','Zone Rated Hazardous Location');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PBSA0153A505','PushButton Repair Parts');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PBSA0153B044','Piezo Pushbuttons');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PBSA0163A045','NEMA Terminal Blocks');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLCA0413A165','1771 I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLCA0413A166','PLC Comms');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLCA0413A167','PLC-5 Processors');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLCA0413A931','EMEA Kits');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0263A108','PowerFlex DC Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0283A120','PowerFlex Component Class Spare Parts');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0293A121','PowerFlex Arch Cls HIMs,Comm,Opts,Accs');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0333A131','1336 Family General Purpose');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0333A132','1336 Family High Performance');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0333A133','1336 Options and Acc');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0333A135','1395 DC Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0333A136','1397 DC Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0333A137','Legacy HIMs,Comm,Opts,Accs, Spares');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0853A820','PLS Raw Material Extensions');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0853A874','Remanufacturing Services');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A259','Y Series');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A528','1336 Classic Inactive - Do Not Use');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A529','SLC 100/150');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A531','IMC S-Class Basic');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A533','9 Series CNC');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A535','Ultra 100 Drive Inactive - Do Not Use');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A538','1394 Servo Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A539','Servo Drive Cables and Misc');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A541','IMC12x');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A542','Low Volume Parts Inactive - Do Not Use');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A543','PLC-2');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A544','PLC-3');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A545','RFID');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A546','1791 Global Block I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A548','1305 Standard Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A549','160 Standard Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A553','AutoMax');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A554','Electro-Craft Drives');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A555','Oil Analysis');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A557','N-Series - NEMA-Style Brushless Servomot');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A558','RE Legacy AC Drives');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A559','RE Common Platform AC Drives');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A560','RE Legacy DC Drive Inactive - Do Not Use');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A561','Reliance Electric: Drive System Spare Pa');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A563','Reliance Electric: Misc Drive Spare Part');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A564','Smart Motor Controllers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A565','Overload Relay');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A580','1336 Plus/Force/Montgomery Elevator');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A891','Medium Voltage Parts');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA0893A892','Legacy Consumable Materials');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA1343A578','Encompass Partner Product Sales Program');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PLSA1603A607','LiquiFlo');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PMCA0653A240','Permanent Magnet');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PVCA1703A184','Component HMI Platforms');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PVCA1703B083','Component HMI Platforms-Wistron');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SCBA0423A171','1760 Pico and Pico GFX - HJ');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SCBA0423A172','1761 MicroLogix 1000 - HC');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SCBA0423A173','1762 MicroLogix 1200 - HE');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SCBA0423A174','1763 MicroLogix 1100 - HG');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SCBA0423A175','1764 MicroLogix 1500 - HD');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SCBA0423A643','1766 MicroLogix 1400');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SCBA0423A644','1758 DataSite RTU');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SCBA0423A849','2080 Micro810 Family');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SCBA0423A859','2080 Micro830 Family');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SCBA0423A860','2080 Micro850 Family');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SCBA0423A861','2080 Micro800 Plug-Ins');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SCBA0423A918','1762 MicroLogix 1200 - HE - Denso');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SCBA0423A950','2085 Expansion I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SCBA0423B022','2080 Micro820 Family');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SCBA1683A645','2001 NX7 PLC');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0263A103','PowerFlex 70');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0263A104','PowerFlex 700');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0263A105','PowerFlex 700H');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0263A106','PowerFlex 700S');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0263A108','PowerFlex DC Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0263A523','PowerFlex 753');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0263A524','PowerFlex 755');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0263A790','PowerFlex 755 High Power');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0273A110','PowerFlex Diode Bus Supplies');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0273A111','PowerFlex SCR Bus Supplies');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0273A112','PowerFlex Active Front End (AFE)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0293A121','PowerFlex Arch Cls HIMs,Comm,Opts,Accs');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0303A123','Drive Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0313A124','Line Reactors');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0313A125','Transformers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0313A126','Output Devices');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0323A127','Dynamic Brakes and Choppers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0333A130','1305 Family General Purpose');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0333A133','1336 Options and Acc');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0333A135','1395 DC Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0333A136','1397 DC Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0333A137','Legacy HIMs,Comm,Opts,Accs, Spares');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA0353A141','Reliance DC Drives');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA1583A586','PowerFlex 70 Packaged');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA1583A793','PowerFlex 755 Packaged High Power');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA1603A607','LiquiFlo');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA1603A766','Carrier');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA2403A033','ArmorStart');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SDBA2413A965','DYSC');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA0553A209','Cordsets');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA0553A210','Distribution Boxes');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA0553A211','Connection Systems Accessories');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA0553A212','Safety Connection Systems');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA0563A213','DeviceNet Media');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA0563A214','Ethernet Media');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA0573A215','Photoelectric Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA0573A216','Label Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA0573A217','Color Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA0583A221','Proximity Sensors - General Purpose');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA0583A222','Proximity Sensors - Specialty and Classic');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA0593A223','Pressure Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA0593A224','Temperature Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA0593A225','Flow Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA0593A746','840E Level Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA0603A227','Nema Limit Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA0603A228','IEC Limit Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA1663A640','Light Duty Industrial');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA1663A641','RFID Cables and Accessories');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA2033A924','Ultrasonic Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA2043A219','Advanced Optical Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SENA2053A220','Encoders');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFCA0493A192','General Safety Relays');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFCA0493A193','Specialty Safety Relays');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFCA0493A194','Modular Safety Relays');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFCA0493A868','Logic Safety Relays (LSR)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFCA0503A195','Cable Pull Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFCA0503A196','Guard Locking Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFCA0503A197','Hinge Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFCA0503A198','Interlock Tongue Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFCA0503A199','Enabling Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFCA0513A200','SensaGuard Non Contact Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFCA0513A201','Non Contact Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFCA0523A202','GuardShield Light Curtains');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFCA0523A204','Perimeter&Area Access Single and MultiBeam');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFCA0523A205','Area Scanners');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFCA0523A914','Guardmaster SC300 Safety Cameras');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFCA0523A935','440R/445L: Light Curtain Controllers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFCA0533A206','Safety Edges');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFCA0533A207','Safety Mats');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFCA0543A208','Prosafe');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFSA0463A185','Safety Distributed I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFSA0473A186','Small Packaged Safety Controllers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFSA0473A187','Packaged Safety Controllers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFSA0473A188','Modular GuardPLC');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFSA0483A189','GuardLogix');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFSA0483A673','Compact GuardLogix');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFSA2103A840','AAdvance');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SFSA2103A841','Trusted');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SLCA0413A168','SLC 500 Processors');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SLCA0413A169','SLC 500 Comms');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SLCA0413A170','SLC 500 I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SLCA0413A919','SLC 500 Processors - Denso');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SLCA0413A920','SLC 500 I/O - Denso');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SOPA0043A006','Circuit Protection');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SOPA0063A008','Power Supplies');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SOPA0063A009','Uninterruptible Power Supplies');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SOPA0063A750','Transformers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SOPA0123A014','NEMA Disconnects (Open Style)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SOPA0123A015','NEMA Disconnect Repair Parts');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SOPA0123A023','IEC Disconnects and Load Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SOPA0123A029','IEC Lg Motor Protect');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SOPA0123B027','IEC X-Series MCCBs (16..400A)');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SOPA1843A751','Surge and Filter');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SOPA1843A752','Power Distribution Blocks');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SOPA2093A961','Metering Devices');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SOPA2093A962','Application Devices');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SSBA1903A845','Heavy Industries Business');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SSBA1903B021','Custom Conformal Coated Products');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SSBA1933A839','GEMS');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SSBA1933A843','Solution Enabler/Migration Products');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SSBA1933A848','Packaged Application');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SSBA1933A867','System Work in Process');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('SSBA1933B079','Safety System');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('TRNA1073A477','E-Learning');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('TRNA1103A876','Training Advisor');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('TRNA2003A895','Products');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('VISA1743A686','FactoryTalk View ME');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('VISA1743A687','FactoryTalk View SE');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('VISA1743A688','View32 Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('VISA1743A690','Misc View Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('VISA1743A720','ViewPoint');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('VISA1753A692','MES');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('VISA1753A693','Historian');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('VISA1753A696','Packaged EMI');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('VISA1753A966','Energy Management Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('VISA1753B069','Info Servers');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('VISA2023A694','AssetCentre');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('PBSA0153B097','Palm Buttons');
INSERT INTO INV_SAP_DMT_FRD_PLDES (PRO_LINE_NAME, PRO_LINE_DES) VALUES ('CPBA2433A758','Modified Industrial Control');
