--DATE:6/26/2014
--AUTHOR: HUANG MO YUE
--DMT_FRD_REPORT
---Product Line Des
---Need Product Line Des SQL file to init.
DROP TABLE INV_SAP_DMT_FRD_P12;
DROP TABLE INV_SAP_DMT_FRD_P15;
  
SELECT count(*) FROM INV_SAP_DMT_FRD_P15;
CREATE TABLE INV_SAP_DMT_FRD_P12 AS 
SELECT * FROM INV_SAP_DMT_FRD;

CREATE TABLE INV_SAP_DMT_FRD_P15 AS 
SELECT * FROM INV_SAP_DMT_FRD;

DROP TABLE INV_SAP_DMT_FRD;
CREATE TABLE INV_SAP_DMT_FRD 
(
  ASOFDATE DATE 
, TYPE VARCHAR2(200) 
, MATERIAL VARCHAR2(200) 
, PLANT VARCHAR2(200) 
, UNIT VARCHAR2(20) 
, MONTH_1 NUMBER 
, MONTH_2 NUMBER 
, MONTH_3 NUMBER 
, MONTH_4 NUMBER 
, MONTH_5 NUMBER 
, MONTH_6 NUMBER 
, MONTH_7 NUMBER 
, MONTH_8 NUMBER 
, MONTH_9 NUMBER 
, MONTH_10 NUMBER 
, MONTH_11 NUMBER 
, MONTH_12 NUMBER 
, MONTH_13 NUMBER 
, MONTH_14 NUMBER 
, MONTH_15 NUMBER 
, MONTH_16 NUMBER 
, MONTH_17 NUMBER 
, MONTH_18 NUMBER 
, MONTH_19 NUMBER 
, MONTH_20 NUMBER 
, MONTH_21 NUMBER 
, MONTH_22 NUMBER 
, MONTH_23 NUMBER 
, MONTH_24 NUMBER 
, MONTH_25 NUMBER 
, MONTH_26 NUMBER 
, MONTH_27 NUMBER 
, MONTH_28 NUMBER 
, MONTH_29 NUMBER
, MONTH_30 NUMBER 
, MONTH_31 NUMBER 
, MONTH_32 NUMBER 
, MONTH_33 NUMBER 
, MONTH_34 NUMBER 
, MONTH_35 NUMBER 
, MONTH_36 NUMBER 
, MONTH_37 NUMBER 
, MONTH_38 NUMBER 
, MONTH_39 NUMBER
, MONTH_40 NUMBER 
, MONTH_41 NUMBER 
, MONTH_42 NUMBER 
, MONTH_43 NUMBER 
, MONTH_44 NUMBER 
, MONTH_45 NUMBER 
, MONTH_46 NUMBER 
, MONTH_47 NUMBER 
, MONTH_48 NUMBER 
, MONTH_49 NUMBER
, MONTH_50 NUMBER 
, MONTH_51 NUMBER 
, MONTH_52 NUMBER 
, MONTH_53 NUMBER 
, MONTH_54 NUMBER 
);

--ADD FM
DROP TABLE INV_SAP_DMT_FRD;
CREATE TABLE INV_SAP_DMT_FRD 
(
  ASOFDATE DATE 
, TYPE VARCHAR2(200) 
, MATERIAL VARCHAR2(200) 
, PLANT VARCHAR2(200) 
, UNIT VARCHAR2(20) 
, MONTH_1 VARCHAR2(200) 
, MONTH_2 VARCHAR2(200) 
, MONTH_3 VARCHAR2(200) 
, MONTH_4 VARCHAR2(200) 
, MONTH_5 VARCHAR2(200) 
, MONTH_6 VARCHAR2(200) 
, MONTH_7 VARCHAR2(200) 
, MONTH_8 VARCHAR2(200) 
, MONTH_9 VARCHAR2(200) 
, MONTH_10 VARCHAR2(200) 
, MONTH_11 VARCHAR2(200) 
, MONTH_12 VARCHAR2(200) 
, MONTH_13 VARCHAR2(200) 
, MONTH_14 VARCHAR2(200) 
, MONTH_15 VARCHAR2(200) 
, MONTH_16 VARCHAR2(200) 
, MONTH_17 VARCHAR2(200) 
, MONTH_18 VARCHAR2(200) 
, MONTH_19 VARCHAR2(200) 
, MONTH_20 VARCHAR2(200) 
, MONTH_21 VARCHAR2(200) 
, MONTH_22 VARCHAR2(200) 
, MONTH_23 VARCHAR2(200) 
, MONTH_24 VARCHAR2(200) 
, MONTH_25 VARCHAR2(200) 
, MONTH_26 VARCHAR2(200) 
, MONTH_27 VARCHAR2(200) 
, MONTH_28 VARCHAR2(200) 
, MONTH_29 VARCHAR2(200)
, MONTH_30 VARCHAR2(200) 
, MONTH_31 VARCHAR2(200) 
, MONTH_32 VARCHAR2(200) 
, MONTH_33 VARCHAR2(200) 
, MONTH_34 VARCHAR2(200) 
, MONTH_35 VARCHAR2(200) 
, MONTH_36 VARCHAR2(200) 
, MONTH_37 VARCHAR2(200) 
, MONTH_38 VARCHAR2(200) 
, MONTH_39 VARCHAR2(200)
, MONTH_40 VARCHAR2(200) 
, MONTH_41 VARCHAR2(200) 
, MONTH_42 VARCHAR2(200) 
, MONTH_43 VARCHAR2(200) 
, MONTH_44 VARCHAR2(200) 
, MONTH_45 VARCHAR2(200) 
, MONTH_46 VARCHAR2(200) 
, MONTH_47 VARCHAR2(200) 
, MONTH_48 VARCHAR2(200) 
, MONTH_49 VARCHAR2(200)
, MONTH_50 VARCHAR2(200) 
, MONTH_51 VARCHAR2(200) 
, MONTH_52 VARCHAR2(200) 
, MONTH_53 VARCHAR2(200) 
, MONTH_54 VARCHAR2(200) 
);


SELECT COUNT(*) FROM INV_SAP_DMT_FRD; 
TRUNCATE TABLE INV_SAP_DMT_FRD;

SELECT * FROM VIEW_INV_SAP_DMT_FRD_P15;

--DMT_FRD_REPORT
DROP VIEW VIEW_INV_SAP_DMT_FRD;
SELECT * FROM VIEW_INV_SAP_DMT_FRD;
CREATE VIEW VIEW_INV_SAP_DMT_FRD AS 
SELECT 
  DMT_PRD.ID,
  DMT_PRD.TYPE,
  DMT_PRD.MATERIAL,
  DMT_PRD.PLANT,
  PP_BASIC.CATALOG_DASH,
  PP_BASIC.MAT_DESC,
  PP_BASIC.SAFETY_STOCK,
  PP_BASIC.PROD_BU,
  PP_BASIC.PROD_FAM,
  PP_BASIC.PROD_HIERARCHY,
  SUBSTR(PP_BASIC.PROD_HIERARCHY, 20)||' '||PP_BASIC.VENDOR_KEY AS PROD_LINE,
  PP_BASIC.PROC_TYPE,
  PP_BASIC.STRATEGY_GRP,
  PP_BASIC.MATL_TYPE,
  PP_BASIC.VENDOR_KEY,
  CASE WHEN DMT_PRD.TYPE = 'RA Historical Demand'
  THEN CEIL((DMT_PRD.MONTH_34+DMT_PRD.MONTH_35+DMT_PRD.MONTH_36)/3)
  ELSE 0
  END AVG_3MONTHS,
  DMT_PRD.UNIT,
  DMT_PRD.MONTH_1,
  DMT_PRD.MONTH_2,
  DMT_PRD.MONTH_3,
  DMT_PRD.MONTH_4,
  DMT_PRD.MONTH_5,
  DMT_PRD.MONTH_6,
  DMT_PRD.MONTH_7,
  DMT_PRD.MONTH_8,
  DMT_PRD.MONTH_9,
  DMT_PRD.MONTH_10,
  DMT_PRD.MONTH_11,
  DMT_PRD.MONTH_12,
  DMT_PRD.MONTH_13,
  DMT_PRD.MONTH_14,
  DMT_PRD.MONTH_15,
  DMT_PRD.MONTH_16,
  DMT_PRD.MONTH_17,
  DMT_PRD.MONTH_18,
  DMT_PRD.MONTH_19,
  DMT_PRD.MONTH_20,
  DMT_PRD.MONTH_21,
  DMT_PRD.MONTH_22,
  DMT_PRD.MONTH_23,
  DMT_PRD.MONTH_24,
  DMT_PRD.MONTH_25,
  DMT_PRD.MONTH_26,
  DMT_PRD.MONTH_27,
  DMT_PRD.MONTH_28,
  DMT_PRD.MONTH_29,
  DMT_PRD.MONTH_30,
  DMT_PRD.MONTH_31,
  DMT_PRD.MONTH_32,
  DMT_PRD.MONTH_33,
  DMT_PRD.MONTH_34,
  DMT_PRD.MONTH_35,
  DMT_PRD.MONTH_36,
  DMT_PRD.MONTH_37,
  DMT_PRD.MONTH_38,
  DMT_PRD.MONTH_39,
  DMT_PRD.MONTH_40,
  DMT_PRD.MONTH_41,
  DMT_PRD.MONTH_42,
  DMT_PRD.MONTH_43,
  DMT_PRD.MONTH_44,
  DMT_PRD.MONTH_45,
  DMT_PRD.MONTH_46,
  DMT_PRD.MONTH_47,
  DMT_PRD.MONTH_48,
  DMT_PRD.MONTH_49,
  DMT_PRD.MONTH_50,
  DMT_PRD.MONTH_51,
  DMT_PRD.MONTH_52,
  DMT_PRD.MONTH_53,
  DMT_PRD.MONTH_54
FROM
  (SELECT MATERIAL
    ||'_'
    ||PLANT AS ID,
    TYPE,
    MATERIAL,
    PLANT,
    UNIT,
    MONTH_1,
    MONTH_2,
    MONTH_3,
    MONTH_4,
    MONTH_5,
    MONTH_6,
    MONTH_7,
    MONTH_8,
    MONTH_9,
    MONTH_10,
    MONTH_11,
    MONTH_12,
    MONTH_13,
    MONTH_14,
    MONTH_15,
    MONTH_16,
    MONTH_17,
    MONTH_18,
    MONTH_19,
    MONTH_20,
    MONTH_21,
    MONTH_22,
    MONTH_23,
    MONTH_24,
    MONTH_25,
    MONTH_26,
    MONTH_27,
    MONTH_28,
    MONTH_29,
    MONTH_30,
    MONTH_31,
    MONTH_32,
    MONTH_33,
    MONTH_34,
    MONTH_35,
    MONTH_36,
    MONTH_37,
    MONTH_38,
    MONTH_39,
    MONTH_40,
    MONTH_41,
    MONTH_42,
    MONTH_43,
    MONTH_44,
    MONTH_45,
    MONTH_46,
    MONTH_47,
    MONTH_48,
    MONTH_49,
    MONTH_50,
    MONTH_51,
    MONTH_52,
    MONTH_53,
    MONTH_54
  FROM INV_SAP_DMT_FRD
  )DMT_PRD
LEFT JOIN
  (SELECT ID,
    CATALOG_DASH,
    MAT_DESC,
    SAFETY_STOCK,
    PROD_BU,
    PROD_FAM,
    PROD_HIERARCHY,
    PROC_TYPE,
    STRATEGY_GRP,
    MATL_TYPE,
    VENDOR_KEY
  FROM INV_SAP_PP_OPT_X
  )PP_BASIC
ON DMT_PRD.ID = PP_BASIC.ID;



CREATE TABLE INV_SAP_DMT_FRD_REP AS SELECT * FROM VIEW_INV_SAP_DMT_FRD;
SELECT * FROM INV_SAP_DMT_FRD_REP;
TRUNCATE TABLE INV_SAP_DMT_FRD_REP;
INSERT INTO INV_SAP_DMT_FRD_REP SELECT * FROM VIEW_INV_SAP_DMT_FRD;


SELECT 
ID,
TYPE,
MATERIAL,
PLANT,
CATALOG_DASH,
MAT_DESC,
SAFETY_STOCK,
PROD_BU,
PROD_FAM,
PROD_HIERARCHY,
PROD_LINE,
PROC_TYPE,
STRATEGY_GRP,
MATL_TYPE,
VENDOR_KEY,
AVG_3MONTHS
FROM INV_SAP_DMT_FRD_REP WHERE MATERIAL = '700-HLS11Z24 A';




----VIEW_INV_SAP_DMT_FRD_P12
DROP TABLE INV_SAP_DMT_FRD_REPP12;
CREATE TABLE INV_SAP_DMT_FRD_REPP12 AS SELECT * FROM VIEW_INV_SAP_DMT_FRD_P12;
TRUNCATE TABLE INV_SAP_DMT_FRD_REPP12;
INSERT INTO INV_SAP_DMT_FRD_REPP12 SELECT * FROM VIEW_INV_SAP_DMT_FRD_P12;
DROP VIEW VIEW_INV_SAP_DMT_FRD_P12;
CREATE VIEW VIEW_INV_SAP_DMT_FRD_P12 AS
SELECT 
  DMT_PP_BS.ID,
  DMT_PP_BS.TYPE,
  DMT_PP_BS.MATERIAL,
  DMT_PP_BS.PLANT,
  DMT_PP_BS.CATALOG_DASH,
  DMT_PP_BS.BULLETIN,
  DMT_PP_BS.MAT_DESC,
  DMT_PP_BS.SAFETY_STOCK,
  DMT_PP_BS.PROD_BU,
  DMT_PP_BS.PROD_FAM,
  DMT_PP_BS.PROD_HIERARCHY,
  DMT_PP_BS.PROD_LINE,
  PRO_DES.PRO_LINE_DES,
  DMT_PP_BS.PROC_TYPE,
  DMT_PP_BS.STRATEGY_GRP,
  DMT_PP_BS.MATL_TYPE,
  DMT_PP_BS.VENDOR_KEY,
  DMT_PP_BS.AVG_3MONTHS,
  DMT_PP_BS.UNIT,
  DMT_PP_BS.MONTH_1,
  DMT_PP_BS.MONTH_2,
  DMT_PP_BS.MONTH_3,
  DMT_PP_BS.MONTH_4,
  DMT_PP_BS.MONTH_5,
  DMT_PP_BS.MONTH_6,
  DMT_PP_BS.MONTH_7,
  DMT_PP_BS.MONTH_8,
  DMT_PP_BS.MONTH_9,
  DMT_PP_BS.MONTH_10,
  DMT_PP_BS.MONTH_11,
  DMT_PP_BS.MONTH_12,
  DMT_PP_BS.MONTH_13,
  DMT_PP_BS.MONTH_14,
  DMT_PP_BS.MONTH_15,
  DMT_PP_BS.MONTH_16,
  DMT_PP_BS.MONTH_17,
  DMT_PP_BS.MONTH_18,
  DMT_PP_BS.MONTH_19,
  DMT_PP_BS.MONTH_20,
  DMT_PP_BS.MONTH_21,
  DMT_PP_BS.MONTH_22,
  DMT_PP_BS.MONTH_23,
  DMT_PP_BS.MONTH_24,
  DMT_PP_BS.MONTH_25,
  DMT_PP_BS.MONTH_26,
  DMT_PP_BS.MONTH_27,
  DMT_PP_BS.MONTH_28,
  DMT_PP_BS.MONTH_29,
  DMT_PP_BS.MONTH_30,
  DMT_PP_BS.MONTH_31,
  DMT_PP_BS.MONTH_32,
  DMT_PP_BS.MONTH_33,
  DMT_PP_BS.MONTH_34,
  DMT_PP_BS.MONTH_35,
  DMT_PP_BS.MONTH_36,
  DMT_PP_BS.MONTH_37,
  DMT_PP_BS.MONTH_38,
  DMT_PP_BS.MONTH_39,
  DMT_PP_BS.MONTH_40,
  DMT_PP_BS.MONTH_41,
  DMT_PP_BS.MONTH_42,
  DMT_PP_BS.MONTH_43,
  DMT_PP_BS.MONTH_44,
  DMT_PP_BS.MONTH_45,
  DMT_PP_BS.MONTH_46,
  DMT_PP_BS.MONTH_47,
  DMT_PP_BS.MONTH_48,
  DMT_PP_BS.MONTH_49,
  DMT_PP_BS.MONTH_50,
  DMT_PP_BS.MONTH_51,
  DMT_PP_BS.MONTH_52,
  DMT_PP_BS.MONTH_53,
  DMT_PP_BS.MONTH_54
FROM 
(
SELECT DMT_PRD.ID,
  DMT_PRD.TYPE,
  DMT_PRD.MATERIAL,
  DMT_PRD.PLANT,
  PP_BASIC.CATALOG_DASH,
  SUBSTR(PP_BASIC.CATALOG_DASH,0,4) AS BULLETIN,
  PP_BASIC.MAT_DESC,
  PP_BASIC.SAFETY_STOCK,
  PP_BASIC.PROD_BU,
  PP_BASIC.PROD_FAM,
  PP_BASIC.PROD_HIERARCHY,
  SUBSTR(PP_BASIC.PROD_HIERARCHY,0,12) AS PROD_LINE,
  PP_BASIC.PROC_TYPE,
  PP_BASIC.STRATEGY_GRP,
  PP_BASIC.MATL_TYPE,
  PP_BASIC.VENDOR_KEY,
  CASE
    WHEN DMT_PRD.TYPE = 'RA Historical Demand'
    THEN CEIL((DMT_PRD.MONTH_34+DMT_PRD.MONTH_35+DMT_PRD.MONTH_36)/3)
    ELSE 0
  END AVG_3MONTHS,
  DMT_PRD.UNIT,
  DMT_PRD.MONTH_1,
  DMT_PRD.MONTH_2,
  DMT_PRD.MONTH_3,
  DMT_PRD.MONTH_4,
  DMT_PRD.MONTH_5,
  DMT_PRD.MONTH_6,
  DMT_PRD.MONTH_7,
  DMT_PRD.MONTH_8,
  DMT_PRD.MONTH_9,
  DMT_PRD.MONTH_10,
  DMT_PRD.MONTH_11,
  DMT_PRD.MONTH_12,
  DMT_PRD.MONTH_13,
  DMT_PRD.MONTH_14,
  DMT_PRD.MONTH_15,
  DMT_PRD.MONTH_16,
  DMT_PRD.MONTH_17,
  DMT_PRD.MONTH_18,
  DMT_PRD.MONTH_19,
  DMT_PRD.MONTH_20,
  DMT_PRD.MONTH_21,
  DMT_PRD.MONTH_22,
  DMT_PRD.MONTH_23,
  DMT_PRD.MONTH_24,
  DMT_PRD.MONTH_25,
  DMT_PRD.MONTH_26,
  DMT_PRD.MONTH_27,
  DMT_PRD.MONTH_28,
  DMT_PRD.MONTH_29,
  DMT_PRD.MONTH_30,
  DMT_PRD.MONTH_31,
  DMT_PRD.MONTH_32,
  DMT_PRD.MONTH_33,
  DMT_PRD.MONTH_34,
  DMT_PRD.MONTH_35,
  DMT_PRD.MONTH_36,
  DMT_PRD.MONTH_37,
  DMT_PRD.MONTH_38,
  DMT_PRD.MONTH_39,
  DMT_PRD.MONTH_40,
  DMT_PRD.MONTH_41,
  DMT_PRD.MONTH_42,
  DMT_PRD.MONTH_43,
  DMT_PRD.MONTH_44,
  DMT_PRD.MONTH_45,
  DMT_PRD.MONTH_46,
  DMT_PRD.MONTH_47,
  DMT_PRD.MONTH_48,
  DMT_PRD.MONTH_49,
  DMT_PRD.MONTH_50,
  DMT_PRD.MONTH_51,
  DMT_PRD.MONTH_52,
  DMT_PRD.MONTH_53,
  DMT_PRD.MONTH_54
FROM
  (SELECT MATERIAL
    ||'_'
    ||PLANT AS ID,
    TYPE,
    MATERIAL,
    PLANT,
    UNIT,
    MONTH_1,
    MONTH_2,
    MONTH_3,
    MONTH_4,
    MONTH_5,
    MONTH_6,
    MONTH_7,
    MONTH_8,
    MONTH_9,
    MONTH_10,
    MONTH_11,
    MONTH_12,
    MONTH_13,
    MONTH_14,
    MONTH_15,
    MONTH_16,
    MONTH_17,
    MONTH_18,
    MONTH_19,
    MONTH_20,
    MONTH_21,
    MONTH_22,
    MONTH_23,
    MONTH_24,
    MONTH_25,
    MONTH_26,
    MONTH_27,
    MONTH_28,
    MONTH_29,
    MONTH_30,
    MONTH_31,
    MONTH_32,
    MONTH_33,
    MONTH_34,
    MONTH_35,
    MONTH_36,
    MONTH_37,
    MONTH_38,
    MONTH_39,
    MONTH_40,
    MONTH_41,
    MONTH_42,
    MONTH_43,
    MONTH_44,
    MONTH_45,
    MONTH_46,
    MONTH_47,
    MONTH_48,
    MONTH_49,
    MONTH_50,
    MONTH_51,
    MONTH_52,
    MONTH_53,
    MONTH_54
  FROM INV_SAP_DMT_FRD_P12
  )DMT_PRD
LEFT JOIN
  (SELECT ID,
    CATALOG_DASH,
    MAT_DESC,
    SAFETY_STOCK,
    PROD_BU,
    PROD_FAM,
    PROD_HIERARCHY,
    PROC_TYPE,
    STRATEGY_GRP,
    MATL_TYPE,
    VENDOR_KEY
  FROM INV_SAP_PP_OPT_X
  )PP_BASIC
ON DMT_PRD.ID = PP_BASIC.ID
)DMT_PP_BS
LEFT JOIN
(
SELECT PRO_LINE_NAME,PRO_LINE_DES FROM INV_SAP_DMT_FRD_PLDES
)PRO_DES
ON PRO_DES.PRO_LINE_NAME = DMT_PP_BS.PROD_LINE;


select * From INV_SAP_DMT_FRD_P12 where plant = '5070' and material = '0041-5077';
----VIEW_INV_SAP_DMT_FRD_P15
DROP TABLE INV_SAP_DMT_FRD_REPP15;
CREATE TABLE INV_SAP_DMT_FRD_REPP15 AS SELECT * FROM VIEW_INV_SAP_DMT_FRD_P15;
TRUNCATE TABLE INV_SAP_DMT_FRD_REPP15;
INSERT INTO INV_SAP_DMT_FRD_REPP15 SELECT * FROM VIEW_INV_SAP_DMT_FRD_P15;

DROP VIEW VIEW_INV_SAP_DMT_FRD_P15;
CREATE VIEW VIEW_INV_SAP_DMT_FRD_P15 AS 
SELECT 
  DMT_PP_BS.ID,
  DMT_PP_BS.TYPE,
  DMT_PP_BS.MATERIAL,
  DMT_PP_BS.PLANT,
  DMT_PP_BS.CATALOG_DASH,
  DMT_PP_BS.BULLETIN,
  DMT_PP_BS.MAT_DESC,
  DMT_PP_BS.SAFETY_STOCK,
  DMT_PP_BS.PROD_BU,
  DMT_PP_BS.PROD_FAM,
  DMT_PP_BS.PROD_HIERARCHY,
  DMT_PP_BS.PROD_LINE,
  PRO_DES.PRO_LINE_DES,
  DMT_PP_BS.PROC_TYPE,
  DMT_PP_BS.STRATEGY_GRP,
  DMT_PP_BS.MATL_TYPE,
  DMT_PP_BS.VENDOR_KEY,
  DMT_PP_BS.AVG_3MONTHS,
  DMT_PP_BS.UNIT,
  DMT_PP_BS.MONTH_1,
  DMT_PP_BS.MONTH_2,
  DMT_PP_BS.MONTH_3,
  DMT_PP_BS.MONTH_4,
  DMT_PP_BS.MONTH_5,
  DMT_PP_BS.MONTH_6,
  DMT_PP_BS.MONTH_7,
  DMT_PP_BS.MONTH_8,
  DMT_PP_BS.MONTH_9,
  DMT_PP_BS.MONTH_10,
  DMT_PP_BS.MONTH_11,
  DMT_PP_BS.MONTH_12,
  DMT_PP_BS.MONTH_13,
  DMT_PP_BS.MONTH_14,
  DMT_PP_BS.MONTH_15,
  DMT_PP_BS.MONTH_16,
  DMT_PP_BS.MONTH_17,
  DMT_PP_BS.MONTH_18,
  DMT_PP_BS.MONTH_19,
  DMT_PP_BS.MONTH_20,
  DMT_PP_BS.MONTH_21,
  DMT_PP_BS.MONTH_22,
  DMT_PP_BS.MONTH_23,
  DMT_PP_BS.MONTH_24,
  DMT_PP_BS.MONTH_25,
  DMT_PP_BS.MONTH_26,
  DMT_PP_BS.MONTH_27,
  DMT_PP_BS.MONTH_28,
  DMT_PP_BS.MONTH_29,
  DMT_PP_BS.MONTH_30,
  DMT_PP_BS.MONTH_31,
  DMT_PP_BS.MONTH_32,
  DMT_PP_BS.MONTH_33,
  DMT_PP_BS.MONTH_34,
  DMT_PP_BS.MONTH_35,
  DMT_PP_BS.MONTH_36,
  DMT_PP_BS.MONTH_37,
  DMT_PP_BS.MONTH_38,
  DMT_PP_BS.MONTH_39,
  DMT_PP_BS.MONTH_40,
  DMT_PP_BS.MONTH_41,
  DMT_PP_BS.MONTH_42,
  DMT_PP_BS.MONTH_43,
  DMT_PP_BS.MONTH_44,
  DMT_PP_BS.MONTH_45,
  DMT_PP_BS.MONTH_46,
  DMT_PP_BS.MONTH_47,
  DMT_PP_BS.MONTH_48,
  DMT_PP_BS.MONTH_49,
  DMT_PP_BS.MONTH_50,
  DMT_PP_BS.MONTH_51,
  DMT_PP_BS.MONTH_52,
  DMT_PP_BS.MONTH_53,
  DMT_PP_BS.MONTH_54
FROM 
(
SELECT DMT_PRD.ID,
  DMT_PRD.TYPE,
  DMT_PRD.MATERIAL,
  DMT_PRD.PLANT,
  PP_BASIC.CATALOG_DASH,
  SUBSTR(PP_BASIC.CATALOG_DASH,0,4) AS BULLETIN,
  PP_BASIC.MAT_DESC,
  PP_BASIC.SAFETY_STOCK,
  PP_BASIC.PROD_BU,
  PP_BASIC.PROD_FAM,
  PP_BASIC.PROD_HIERARCHY,
  SUBSTR(PP_BASIC.PROD_HIERARCHY,0,12) AS PROD_LINE,
  PP_BASIC.PROC_TYPE,
  PP_BASIC.STRATEGY_GRP,
  PP_BASIC.MATL_TYPE,
  PP_BASIC.VENDOR_KEY,
  CASE
    WHEN DMT_PRD.TYPE = 'RA Historical Demand'
    THEN CEIL((DMT_PRD.MONTH_34+DMT_PRD.MONTH_35+DMT_PRD.MONTH_36)/3)
    ELSE 0
  END AVG_3MONTHS,
  DMT_PRD.UNIT,
  DMT_PRD.MONTH_1,
  DMT_PRD.MONTH_2,
  DMT_PRD.MONTH_3,
  DMT_PRD.MONTH_4,
  DMT_PRD.MONTH_5,
  DMT_PRD.MONTH_6,
  DMT_PRD.MONTH_7,
  DMT_PRD.MONTH_8,
  DMT_PRD.MONTH_9,
  DMT_PRD.MONTH_10,
  DMT_PRD.MONTH_11,
  DMT_PRD.MONTH_12,
  DMT_PRD.MONTH_13,
  DMT_PRD.MONTH_14,
  DMT_PRD.MONTH_15,
  DMT_PRD.MONTH_16,
  DMT_PRD.MONTH_17,
  DMT_PRD.MONTH_18,
  DMT_PRD.MONTH_19,
  DMT_PRD.MONTH_20,
  DMT_PRD.MONTH_21,
  DMT_PRD.MONTH_22,
  DMT_PRD.MONTH_23,
  DMT_PRD.MONTH_24,
  DMT_PRD.MONTH_25,
  DMT_PRD.MONTH_26,
  DMT_PRD.MONTH_27,
  DMT_PRD.MONTH_28,
  DMT_PRD.MONTH_29,
  DMT_PRD.MONTH_30,
  DMT_PRD.MONTH_31,
  DMT_PRD.MONTH_32,
  DMT_PRD.MONTH_33,
  DMT_PRD.MONTH_34,
  DMT_PRD.MONTH_35,
  DMT_PRD.MONTH_36,
  DMT_PRD.MONTH_37,
  DMT_PRD.MONTH_38,
  DMT_PRD.MONTH_39,
  DMT_PRD.MONTH_40,
  DMT_PRD.MONTH_41,
  DMT_PRD.MONTH_42,
  DMT_PRD.MONTH_43,
  DMT_PRD.MONTH_44,
  DMT_PRD.MONTH_45,
  DMT_PRD.MONTH_46,
  DMT_PRD.MONTH_47,
  DMT_PRD.MONTH_48,
  DMT_PRD.MONTH_49,
  DMT_PRD.MONTH_50,
  DMT_PRD.MONTH_51,
  DMT_PRD.MONTH_52,
  DMT_PRD.MONTH_53,
  DMT_PRD.MONTH_54
FROM
  (SELECT MATERIAL
    ||'_'
    ||PLANT AS ID,
    TYPE,
    MATERIAL,
    PLANT,
    UNIT,
    MONTH_1,
    MONTH_2,
    MONTH_3,
    MONTH_4,
    MONTH_5,
    MONTH_6,
    MONTH_7,
    MONTH_8,
    MONTH_9,
    MONTH_10,
    MONTH_11,
    MONTH_12,
    MONTH_13,
    MONTH_14,
    MONTH_15,
    MONTH_16,
    MONTH_17,
    MONTH_18,
    MONTH_19,
    MONTH_20,
    MONTH_21,
    MONTH_22,
    MONTH_23,
    MONTH_24,
    MONTH_25,
    MONTH_26,
    MONTH_27,
    MONTH_28,
    MONTH_29,
    MONTH_30,
    MONTH_31,
    MONTH_32,
    MONTH_33,
    MONTH_34,
    MONTH_35,
    MONTH_36,
    MONTH_37,
    MONTH_38,
    MONTH_39,
    MONTH_40,
    MONTH_41,
    MONTH_42,
    MONTH_43,
    MONTH_44,
    MONTH_45,
    MONTH_46,
    MONTH_47,
    MONTH_48,
    MONTH_49,
    MONTH_50,
    MONTH_51,
    MONTH_52,
    MONTH_53,
    MONTH_54
  FROM INV_SAP_DMT_FRD_P15
  )DMT_PRD
LEFT JOIN
  (SELECT ID,
    CATALOG_DASH,
    MAT_DESC,
    SAFETY_STOCK,
    PROD_BU,
    PROD_FAM,
    PROD_HIERARCHY,
    PROC_TYPE,
    STRATEGY_GRP,
    MATL_TYPE,
    VENDOR_KEY
  FROM INV_SAP_PP_OPT_X where id = 'PN-172138_5190'
  )PP_BASIC
ON DMT_PRD.ID = PP_BASIC.ID
)DMT_PP_BS
LEFT JOIN
(
SELECT PRO_LINE_NAME,PRO_LINE_DES FROM INV_SAP_DMT_FRD_PLDES
)PRO_DES
ON PRO_DES.PRO_LINE_NAME = DMT_PP_BS.PROD_LINE;

SELECT * FROM INV_SAP_DMT_FRD_PLDES;


---Remove Spike Order in product line level
---Last two months

DROP TABLE INV_SAP_DMT_FRD_P12;
DROP TABLE INV_SAP_DMT_FRD_P15;



(
SELECT 
  PLANT||'_'||
  PROD_LINE AS PP_ID,
  PLANT,
  PROD_LINE,
    MONTH_25,
    MONTH_26,
    MONTH_27,
    MONTH_28,
    MONTH_29,
    MONTH_30,
    MONTH_31,
    MONTH_32,
    MONTH_33,
    MONTH_34,
    MONTH_35,
    MONTH_36
FROM INV_SAP_DMT_FRD_REPP15 WHERE TYPE = 'RA Historical Demand'
)PP_MM12
LEFT JOIN
(
SELECT 
  PLANT||'_'||
  PROD_LINE AS PP_ID,
  PLANT,
  PROD_LINE,
  SUM(PRODLINE_SUMMM12)/12 AS PRODLINE_MM12_AVG
  FROM
  (SELECT PLANT,
    PROD_LINE,
    (MONTH_25+ MONTH_26+ MONTH_27+ MONTH_28+ MONTH_29+ MONTH_30+ MONTH_31+ MONTH_32+ MONTH_33+ MONTH_34+ MONTH_35+ MONTH_36) AS PRODLINE_SUMMM12
  FROM INV_SAP_DMT_FRD_REPP15
  WHERE TYPE = 'RA Historical Demand'
  )
GROUP BY PLANT,
  PROD_LINE
)PP_MM12_AVG

select * from INV_SAP_DMT_FRD_REPP15;


DECLARE
    v_name EMPLOYEE_NAME_BIRTHDAY.NAME%TYPE;
    CURSOR c_cursor IS SELECT NAME FROM EMPLOYEE_NAME_BIRTHDAY;
    v_date VARCHAR2(20 CHAR);
  BEGIN
    v_date := SYSDATE;
    OPEN c_cursor;
    FETCH c_cursor INTO v_name;
    SYS.DBMS_OUTPUT.PUT_LINE(v_name);
    UPDATE EMPLOYEE_NAME_BIRTHDAY SET BIRTHDAY = v_date WHERE NAME = v_name;
    CLOSE c_cursor;
END;

CREATE OR REPLACE PROCEDURE APAFC_CACL_STD()
IS
V_PLANT INV_SAP_DMT_FRD_REPP15.PLANT%TYPE;
V_PROD_LINE INV_SAP_DMT_FRD_REPP15.PROD_LINE%TYPE;
V_MM25 INV_SAP_DMT_FRD_REPP15.MONTH_25%TYPE;
V_MM26 INV_SAP_DMT_FRD_REPP15.MONTH_26%TYPE;
V_MM27 INV_SAP_DMT_FRD_REPP15.MONTH_27%TYPE;
V_MM28 INV_SAP_DMT_FRD_REPP15.MONTH_28%TYPE;
V_MM29 INV_SAP_DMT_FRD_REPP15.MONTH_29%TYPE;
V_MM30 INV_SAP_DMT_FRD_REPP15.MONTH_30%TYPE;
V_MM31 INV_SAP_DMT_FRD_REPP15.MONTH_31%TYPE;
V_MM32 INV_SAP_DMT_FRD_REPP15.MONTH_32%TYPE;
V_MM33 INV_SAP_DMT_FRD_REPP15.MONTH_33%TYPE;
V_MM34 INV_SAP_DMT_FRD_REPP15.MONTH_34%TYPE;
V_MM35 INV_SAP_DMT_FRD_REPP15.MONTH_35%TYPE;
V_MM36 INV_SAP_DMT_FRD_REPP15.MONTH_36%TYPE;


CURSOR  C_CURSOR IS SELECT 
  PLANT,
  PROD_LINE,
    MONTH_25,
    MONTH_26,
    MONTH_27,
    MONTH_28,
    MONTH_29,
    MONTH_30,
    MONTH_31,
    MONTH_32,
    MONTH_33,
    MONTH_34,
    MONTH_35,
    MONTH_36
FROM INV_SAP_DMT_FRD_REPP15 WHERE TYPE = 'RA Historical Demand';
BEGIN

END;



SELECT PLANT,
  PROD_LINE,
  SUM(MONTH_25) AS SUM_MONTH25
FROM INV_SAP_DMT_FRD_REPP15
WHERE TYPE = 'RA Historical Demand'
GROUP BY PLANT,
  PROD_LINE


select * from inv_sap_sales_hst_lc where material = 'PN-145756' and plant = '5200';





