--Product Line Des init
--Manual Upload the data 

INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ACSA1713A675','Component Design Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ACSA1713A676','Architecture Design Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ACSA1713A677','Misc Automation Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ACSA1733A684','Toolkits');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ACSA1823A679','Connectivity Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ACSA1823A680','Process Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ACSA1823A681','Condition Based Monitoring Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CCTA1003A472','Support Products');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CDSA0283A115','PowerFlex 4');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CDSA0283A116','PowerFlex 4M');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CDSA0283A117','PowerFlex 40');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CDSA0283A118','PowerFlex 40P');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CDSA0283A119','PowerFlex 400');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CDSA0283A120','PowerFlex Component Class Spare Parts');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CDSA0283A663','PowerFlex 400N');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CDSA0283A852','PowerFlex 523');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CDSA0283A853','PowerFlex 525');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CDSA0293A122','PF Cmpnt Cls HIMs,Comm,Opts,Accs, Spares');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CDSA1583A583','PowerFlex 40 Packaged');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CDSA1603A648','PowerFlex 400 Packaged');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CDSA2313B053','F500 Component Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CLXA0403A154','Brand Label');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CLXA0403A155','1756 Logix I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CLXA0403A156','CLX Motion Controller Related');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CLXA0403A159','Netlinx Comms');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CLXA0403A160','ControlLogix');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CLXA0403A162','ProcessLogix');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CLXA0403A164','SoftLogix');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CLXA0403A850','1715 Redundant I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CLXA0403A927','EMEA Kits');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CMXA1323A525','1768/1769 CompactLogix');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CMXA1323A526','1769 CompactLogix I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CMXA1323A921','1769 CompactLogix Processors - Denso');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CMXA1323A922','1769 CompactLogix I/O - Denso');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('CMXA1323A926','Compact 5000 I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('DIOA0613A229','1790 CompactBlock LDX');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('DIOA0613A916','1791 CompactBlock - Denso');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('DIOA0623A231','1734 POINT I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('DIOA0623A232','1794 FLEX I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('DIOA0623A233','1797 FLEX Ex I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('DIOA0623A917','1794 FLEX I/O - Denso');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('DIOA0633A234','1732 ArmorBlock I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('DIOA0633A236','1792D ArmorBlock MaXum I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('DIOA0643A237','1738 ArmorPoint I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('DIOA1283A507','1799 Standard');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('DIOA1293A512','I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('EOIA0453A180','PanelView Standard Platforms');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('EOIA0453A181','PanelView Enhanced Platforms');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('EOIA0453A182','PVP 700-1500');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('EOIA0453A183','Message Displays Platforms');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('EOIA0453A674','PVP 400-600');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('EOIA0453A854','PVP 6 700-1500');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('EPCA0133A031','Smart Motor Controllers (Open Style)');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('EPCA0133A033','IEC Networked Starters');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('EPCA0133A034','Power Solid State Contactors');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('EPCA0143A035','NEMA Electronic Protective Devices');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('EPCA0143A036','IEC Electronic Protective Devices');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('EPCA2093A961','Hardware');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('EPCA2093A962','Miscellaneous');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ESBA0203A082','421 - IEC Terminal Blocks');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ESBA0203A084','Signal Assemblies');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ESBA0213A735','Small OEM');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ESBA0213A740','Transportation');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ESBA0213A817','ESB Raw Material Extensions');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ESBA0223A742','ElectroGuard Accessories');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICBA0433A176','Integrated Display Computers');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICBA0433A177','Non-Display Computers');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICBA0433A179','Monitors');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICBA0433A521','Accessories');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICMA0903A434','Portable Data collection');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICMA0913A435','ProtectionSystems');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICMA0923A436','On-Line Surveillance');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICMA0933A437','Sensors and Accessories');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICPA0103A019','IEC Control Relays');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICPA0103A780','IEC Bimetal Overload Relays');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICPA0103A781','IEC Contactors (< 85 Amps)');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICPA0103A782','IEC Bus Bar Systems & Components');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICPA0103A784','IEC Sm. Mtr Protect & Circuit Brk <100A');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICPA0103A785','IEC Open Starters');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICPA0103A937','ICP Misc S+S Products');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICPA0103B023','IEC X-Series Control Relays');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICPA0103B024','IEC X-Series Contactors (< 97 Amps)');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICPA0103B025','IEC X-Series Sm. Mtr Protect & Circuit B');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICPA0103B028','IEC X-Series OLRs (0.1..330A)');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICPA0123A022','IEC Contactors (> 85 Amps)');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICPA0123A023','IEC Disconnects & Load Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICPA0123A029','IEC Lg Motor Protect&Circuit Break>100A');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICPA0123B026','IEC X-Series Contactors (> 97 Amps)');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('ICPA0123B027','IEC X-Series MCCBs (16..400A)');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0723A252','MPF');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0723A253','MPS');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0723A254','MPC');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0723A256','1326AB');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0723A258','TL/TLY  Series');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0723A260','HPK');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0723A487','MPL Small');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0723A488','MPL');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0723A691','MPM');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0723A870','VPL');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0733A266','MPAI');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0733A517','MPAS');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0733A666','Linear Motors');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0733A668','MP/TLAR');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0733A884','Anorad Linear Motors');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0743A268','Kinetix 7000');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0743A269','Kinetix 6000');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0743A270','Kinetix 2000');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0743A271','Ultra5000');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0743A272','Ultra3000');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0743A273','Ultra1500');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0743A748','Kinetix 300');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0743A798','Kinetix 3');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0743A873','Kinetix 350 Servo Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0743A875','Kinetix Mid Range Drives');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0753A277','DIN Non-Flex IP67');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0753A278','DIN High Flex IP67');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0753A280','H/F  Non-Flex');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0753A281','Bayonet Non-Flex');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0753A282','Bayonet High Flex');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0753A286','TL AMP  Non-Flex');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0753A290','Transition Non-Flex');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0753A291','Control');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0753A292','Communication');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0753A293','Fiber Optics');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0753A294','Connection');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0753A298','1326 C');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0753A871','2090-CS Single Cable, Non-Flex');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0753A872','2090-CS Single Cable, Flex');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA0763A309','Accessories');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA1863A799','Accessories Motors & Actuators, Rotary');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA1863A803','Accessories Motors & Actuators, Linear');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA1873A800','Accessories Drives');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA1883A805','Drives/ Miscellaneous');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA1973A886','LDAT-Series');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA1983A888','Accessories');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('KNXA2323B063','iTrak Products');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LGCA0013A001','GP Relays & Timers');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LGCA0013A938','LGC  Misc S+S Products');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LGCA0023A003','Signaling Products');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LGCA0033A004','IEC Terminal Blocks');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LGCA0033A005','Wiring Systems');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LGCA0043A006','Circuit Protection');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LGCA0043A965','DySC & I-Sense');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LGCA0053A007','Digital Temp Controller');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LGCA0053A716','Signal Conditioning');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LGCA0053A749','NEMA Condition Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LGCA0063A008','Power Supplies');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LGCA0063A009','Uninterruptible Power Supplies');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LGCA0063A750','Transformers');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LGCA1843A751','Surge and Filter');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LGCA1843A752','Power Distribution Blocks');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LVMA0193A061','2100 Units');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LVMA0193A064','Inactive FY10');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LVMA0193A630','2100 Parts');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LVMA0193A770','2100 Materials');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LVMA1653A641','2500 IEC LVMCC Assembled');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('LVMA1653A786','2500 IEC LVMCC Unassembled');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('MVDA0233A091','Air Cooled A-Frame MV Drives');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('MVDA0233A094','Miscellaneous MV Drives (811)');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('MVDA0233A095','MV Drive Parts (812)');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('MVDA0233A814','MVD Raw Material Extensions');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('MVDA0233A905','Air Cooled B-Frame MV Drives');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('MVDA0233A947','Extended Warranty');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('MVDA0233B052','PowerFlex 6000 MV Drives');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('MVDA0243A101','Third Party Equipment (824)');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('MVDA0243A904','MV Drive Isolation Transformers (821)');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('MVMA0173A047','NEMA Starters - Non-arc');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('MVMA0173A054','OEM Parts (810)');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('MVMA0173A059','MV MCC Miscellaneous');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('MVMA0183A060','Third Party Equipment (825)');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NETA2333B070','Stratix Cisco Branded');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NETA2333B071','Stratix Non-Cisco Branded');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NETA2333B072','EtherNet/IP Enablers');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NETA2343B073','ControlNet Platforms');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NETA2343B074','ContlNet Enablers');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NETA2353B075','DeviceNet Platforms');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NETA2353B076','DeviceNet Enablers');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NETA2363B077','Process Modules');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NETA2363B078','Specialty Modules');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NPLA0073A011','NEMA Starters & Starter Components');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NPLA0073A012','OBS moved to NPLA1853A754');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NPLA0073A013','NEMA Manual Starters');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NPLA0073A014','NEMA Disconnects (Open Style)');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NPLA0073A015','NEMA Repair Parts');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NPLA0083A016','NEMA Relays & Timers');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NPLA1853A753','IEC Enclosed Starters');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NPLA1853A754','NEMA Enclosed Starters');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NPLA1853A755','Smart Motor Controllers (Enclosed Style)');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NPLA1853A757','Disconnects (Enclosed)');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('NPLA1853A759','Enclosures');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('OTHA1343A515','ControlLogix');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('OTHA1353A515','CompactLogicix /FlexLogix');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('OTHA1513A515','Standard Drives');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('OTHA1523A515','Sensing & Connectivity');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('OTHA1533A515','Safety Components');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PBSA0153A038','NEMA Pushbuttons - 30mm');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PBSA0153A039','IEC Pushbuttons - 22.5mm');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PBSA0153A040','NEMA  Pushbuttons - 22.5mm');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PBSA0153A041','IEC Pushbuttons - < 22.5mm');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PBSA0153A042','NEMA Hazardous Location Pushbuttons');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PBSA0153A043','Touch Buttons');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PBSA0153A044','Zone Rated Hazardous Location');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PBSA0153A505','PushButton Repair Parts');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PBSA0163A045','NEMA Terminal Blocks');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLCA0413A165','1771 I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLCA0413A166','PLC Comms');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLCA0413A167','PLC-5 Processors');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLCA0413A931','EMEA Kits');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0263A108','PowerFlex DC Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0283A120','PowerFlex Component Class Spare Parts');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0293A121','PowerFlex Arch Cls HIMs,Comm,Opts,Accs');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0333A131','1336 Family General Purpose');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0333A132','1336 Family High Performance');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0333A133','1336 Options & Acc');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0333A135','1395 DC Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0333A136','1397 DC Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0333A137','Legacy HIMs,Comm,Opts,Accs, Spares');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0853A820','PLS Raw Material Extensions');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0853A874','Remanufacturing Services');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A259','Y Series');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A528','1336 Classic Inactive - Do Not Use');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A531','IMC S-Class Basic');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A535','Ultra 100 Drive Inactive - Do Not Use');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A538','1394 Servo Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A539','Servo Drive Cables & Misc');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A541','IMC12x');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A542','Low Volume Parts Inactive - Do Not Use');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A543','PLC-2');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A544','PLC-3');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A545','RFID');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A546','1791 Global Block I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A548','1305 Standard Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A549','160 Standard Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A553','AutoMax');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A554','Electro-Craft Drives');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A555','Oil Analysis');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A557','N-Series - NEMA-Style Brushless Servomot');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A558','RE Legacy AC Drives');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A559','RE Common Platform AC Drives');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A561','Reliance Electric: Drive System Spare Pa');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A563','Reliance Electric: Misc Drive Spare Part');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A564','Smart Motor Controllers');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A891','Medium Voltage Parts');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA0893A892','Legacy Consumable Materials');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA1343A578','Encompass Partner Product Sales Program');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA1603A607','LiquiFlo');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PLSA2253B015','Programmable System');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PMCA0653A240','Permanent Magnet');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('PVCA1703A184','Component HMI Platforms');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SCBA0423A171','1760 Pico & Pico GFX - HJ');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SCBA0423A172','1761 MicroLogix 1000 - HC');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SCBA0423A173','1762 MicroLogix 1200 - HE');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SCBA0423A174','1763 MicroLogix 1100 - HG');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SCBA0423A175','1764 MicroLogix 1500 - HD');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SCBA0423A643','1766 MicroLogix 1400');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SCBA0423A644','1758 DataSite RTU');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SCBA0423A849','2080 Micro810 Family');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SCBA0423A859','2080 Micro830 Family');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SCBA0423A860','2080 Micro850 Family');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SCBA0423A861','2080 Micro800 Plug-Ins');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SCBA0423A918','1762 MicroLogix 1200 - HE - Denso');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SCBA0423A950','2085 Expansion I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SCBA0423B022','2080 Micro820 Family');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0263A103','PowerFlex 70');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0263A104','PowerFlex 700');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0263A105','PowerFlex 700H');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0263A106','PowerFlex 700S');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0263A108','PowerFlex DC Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0263A523','PowerFlex 753');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0263A524','PowerFlex 755');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0263A790','PowerFlex 755 High Power');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0273A110','PowerFlex Diode Bus Supplies');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0273A111','PowerFlex SCR Bus Supplies');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0273A112','PowerFlex Active Front End (AFE)');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0293A121','PowerFlex Arch Cls HIMs,Comm,Opts,Accs');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0303A123','Drive Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0313A124','Line Reactors');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0313A125','Transformers');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0313A126','Output Devices');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0323A127','Dynamic Brakes & Choppers');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0333A130','1305 Family General Purpose');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0333A133','1336 Options & Acc');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0333A135','1395 DC Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0333A136','1397 DC Drive');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0333A137','Legacy HIMs,Comm,Opts,Accs, Spares');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA0353A141','Reliance DC Drives');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA1583A586','PowerFlex 70 Packaged');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA1583A793','PowerFlex 755 Packaged High Power');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA1603A607','LiquiFlo');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SDBA1603A766','Carrier');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA0553A209','Cordsets');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA0553A210','Distribution Boxes');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA0553A211','Connection Systems Accessories');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA0553A212','Safety Connection Systems');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA0563A213','DeviceNet Media');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA0563A214','Ethernet Media');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA0573A215','Photoelectric Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA0573A216','Label Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA0573A217','Color Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA0583A221','Proximity Sensors - General Purpose');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA0583A222','Proximity Sensors - Specialty & Classic');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA0593A223','Pressure Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA0593A224','Temperature Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA0593A225','Flow Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA0593A746','840E Level Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA0603A227','Nema Limit Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA0603A228','IEC Limit Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA1663A640','Light Duty Industrial');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA1663A641','RFID Cables and Accessories');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA2033A924','Ultrasonic Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA2043A219','Advanced Optical Sensors');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SENA2053A220','Encoders');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFCA0493A192','General Safety Relays');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFCA0493A193','Specialty Safety Relays');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFCA0493A194','Modular Safety Relays');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFCA0493A868','Logic Safety Relays (LSR)');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFCA0503A195','Cable Pull Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFCA0503A196','Guard Locking Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFCA0503A197','Hinge Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFCA0503A198','Interlock Tongue Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFCA0503A199','Enabling Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFCA0513A200','SensaGuard Non Contact Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFCA0513A201','Non Contact Switches');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFCA0523A202','GuardShield Light Curtains');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFCA0523A204','Perimeter&Area Access Single&MultiBeam');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFCA0523A205','Area Scanners');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFCA0523A914','Guardmaster SC300 Safety Cameras');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFCA0523A935','440R/445L: Light Curtain Controllers');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFCA0533A206','Safety Edges');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFCA0533A207','Safety Mats');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFCA0543A208','Prosafe');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFSA0463A185','Safety Distributed I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFSA0473A186','Small Packaged Safety Controllers');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFSA0473A187','Packaged Safety Controllers');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFSA0473A188','Modular GuardPLC');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFSA0483A189','GuardLogix');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFSA0483A673','Compact GuardLogix');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFSA2103A840','AAdvance');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFSA2103A841','Trusted');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SFWA1783A703','Arena');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SLCA0413A168','SLC 500 Processors');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SLCA0413A169','SLC 500 Comms');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SLCA0413A170','SLC 500 I/O');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SLCA0413A919','SLC 500 Processors - Denso');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SLCA0413A920','SLC 500 I/O - Denso');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SSBA1903A845','Heavy Industries Business');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SSBA1903B021','Custom Conformal Coated Products');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SSBA1933A843','Solution Enabler/Migration Products');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SSBA1933A867','System Work in Process');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('SSBA1933B079','Safety System');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('TRNA1073A477','E-Learning');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('TRNA2003A895','Products');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('VISA1743A686','FactoryTalk View ME');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('VISA1743A687','FactoryTalk View SE');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('VISA1743A688','View32 Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('VISA1743A690','Misc View Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('VISA1743A720','ViewPoint');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('VISA1753A692','MES');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('VISA1753A693','Historian');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('VISA1753A696','Packaged EMI');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('VISA1753A966','Energy Management Software');
INSERT INTO INV_SAP_DMT_FRD_PLDES(PRO_LINE_NAME,PRO_LINE_DES) VALUES
  ('VISA2023A694','AssetCentre');



SELECT count(*) FROM INV_SAP_DMT_FRD_PLDES;