--Porject Name: STO PO Prior
--Author: Huang Moyue 
--Mail: mhuang1@ra.rockwell.com
--Date:11/08/2014
--Summary: STO PO Prior
--VIEW_INV_SAP_ITEM_SOG_X 


SELECT
PLANTID,
MATERIALID,
LIFNR_VENDORNO,
EBELNPURCHDOCNO,
DELIVERY_PRIORITY
FROM INV_SAP_PP_PO_HISTORY
WHERE PLANTID IN ('5040','5050') AND DELIVERYCOMPLETE IS NULL;

