--DATE:20141029
--AUTHOR: HUANGMOYUE
--Plsql Challenge

--Int=-2147483648
--Int=1
select * from RALO.MATERIAL_LARGE_ORDER_RESULT;

DECLARE
  L_SIMPLE   SIMPLE_INTEGER := 2 ** 31 - 1 ;
  L_INT PLS_INTEGER := -2**31;
  l_INT1 PLS_INTEGER;
BEGIN
  l_INT1 := 1;
  DBMS_OUTPUT.put_line ('Int=' || l_simple);
  l_simple := l_simple + 1;
   DBMS_OUTPUT.put_line ('Int=' || l_simple);
  
  DBMS_OUTPUT.put_line ('Int=' || l_INT1);
END;


CREATE TABLE PLCH_EMPL
(
EMPL_ID INTEGER,
SAL NUMBER
);

BEGIN
  INSERT INTO PLCH_EMPL VALUES(138,10000);
  INSERT INTO PLCH_EMPL VALUES(140,19999);
  COMMIT;
END;

CREATE OR REPLACE
PROCEDURE PLCH_GIVE_RAISE(
    ID_IN     IN INTEGER,
    AMOUNT_IN IN NUMBER)
IS
  PRAGMA AUTONOMOUS_TRANSACTION;
  IMPACT_LN INTEGER;
BEGIN
  UPDATE PLCH_EMPL SET SAL = SAL + AMOUNT_IN WHERE EMPL_ID = ID_IN;
  IMPACT_LN := SQL%ROWCOUNT;
  SYS.DBMS_OUTPUT.PUT_LINE(IMPACT_LN);
  COMMIT;
  SYS.DBMS_OUTPUT.PUT_LINE(IMPACT_LN);
END;

CREATE TABLE test_a
(
EMPL_ID INTEGER
);


DECLARE
  n1 NUMBER;
  n2 NUMBER;
BEGIN
  INSERT INTO test_a
  SELECT level lv FROM dual CONNECT BY level<500;
  n1:=sql%rowcount;
  COMMIT;
  n2:=sql%rowcount;
  SYS.dbms_output.put_line(n1);
  SYS.dbms_output.put_line(n2);
END;

SELECT level lv FROM dual CONNECT BY level<500

BEGIN
PLCH_GIVE_RAISE(138,10000);
IF SQL%ROWCOUNT = 1
THEN
SYS.DBMS_OUTPUT.PUT_LINE('SAL UPDATE 138!');
ELSE
SYS.DBMS_OUTPUT.PUT_LINE('SAL NOT UPDATE 138!');
END IF;
END;


-- ''

BEGIN
SYS.DBMS_OUTPUT.PUT_LINE(Q'<'HELLO.>');
SYS.DBMS_OUTPUT.PUT_LINE(Q'*'HELLO.*');
SYS.DBMS_OUTPUT.PUT_LINE(Q'('HELLO.)');
SYS.DBMS_OUTPUT.PUT_LINE(Q'{'HELLO.}');
SYS.DBMS_OUTPUT.PUT_LINE(Q'['HELLO.]');
SYS.DBMS_OUTPUT.PUT_LINE('''HELLO.');
END;


--Using Like
CREATE OR REPLACE PROCEDURE PLCH_LIKE(VALUE_IN IN VARCHAR2)
IS
BEGIN
  SYS.DBMS_OUTPUT.PUT_LINE('1.');
  IF VALUE_IN LIKE '123_5_'
  THEN SYS.DBMS_OUTPUT.PUT_LINE(VALUE_IN);
  END IF;
  SYS.DBMS_OUTPUT.PUT_LINE('2.');
  IF VALUE_IN LIKE '12_3_5_'
  THEN SYS.DBMS_OUTPUT.PUT_LINE(VALUE_IN);
  END IF;
  SYS.DBMS_OUTPUT.PUT_LINE('3.');
  IF VALUE_IN LIKE '%3_5_'
  THEN SYS.DBMS_OUTPUT.PUT_LINE(VALUE_IN);
  END IF;
END;

BEGIN
PLCH_LIKE('123456');
END;


--Char length
DECLARE
L_STR CHAR(10) := '12345';
BEGIN
L_STR := ('12345'||L_STR);
SYS.DBMS_OUTPUT.PUT_LINE(L_STR);
END;


--Returning
DROP TABLE test_ar;
create table test_ar(
id int,
name varchar2(100)
);

CREATE OR REPLACE TYPE
ID_TYPE IS TABLE OF NUMBER;


DECLARE
V_ID INT;
BEGIN
INSERT INTO test_ar VALUES(2,'AA') RETURNING ID INTO V_ID;
SYS.DBMS_OUTPUT.PUT_LINE(V_ID);
SYS.DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);
END;


DECLARE
  IDS ID_TYPE;
BEGIN
  INSERT INTO test_ar VALUES
    (3,'AA'
    );
  INSERT INTO test_ar VALUES
    (4,'AA'
    );
  INSERT INTO test_ar VALUES
    (5,'AA'
    );
  UPDATE test_ar SET NAME = NAME || '_1' RETURNING ID BULK COLLECT INTO IDS; --BULK COLLEC, return back the info at array..
  FOR I IN IDS.FIRST .. IDS.LAST
  LOOP
    SYS.DBMS_OUTPUT.PUT_LINE('RECORD '||I||'='||IDS(I));
  END LOOP;
  SYS.DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);
END;


