-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Project Name : APAFC
-- Version : 1.0
-- Description:
-- Table Init
-- Revision History:
--    Date        Developer         Description
--    ---------   ---------------   ----------------------------------------------------
--    2014-12-24  Moyue           	SO Hst Stats view
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
--So hst local version.  

--VIEW_INV_SAP_DSTR_QSTATSLIST
CREATE VIEW VIEW_INV_SAP_DSTR_QSTATSLIST AS
SELECT 
DIS_USTQ123.IDD AS IDD,
DIS_USTQ123.ID AS ID,
DIS_USTQ123.MATERIAL AS MATERIAL,
DIS_USTQ123.CATALOG AS CATALOG,
DIS_USTQ123.SOLD_TO_NAME AS SOLD_TO_NAME,
DIS_USTQ123.DISTRIBUTOR_USAGE_QTY AS DISTRIBUTOR_USAGE_QTY,
NVL(DIS_USTQ123.Q1_DIS_USAGE_QTY,0) AS Q1_DIS_USAGE_QTY,
NVL(DIS_USTQ123.Q2_DIS_USAGE_QTY,0) AS Q2_DIS_USAGE_QTY,
NVL(DIS_USTQ123.Q3_DIS_USAGE_QTY,0) AS Q3_DIS_USAGE_QTY,
NVL(DIS_USAGE_Q4.Q4_DIS_USAGE_QTY,0) AS Q4_DIS_USAGE_QTY
FROM
(
SELECT 
DIS_USTQ12.IDD AS IDD,
DIS_USTQ12.ID AS ID,
DIS_USTQ12.MATERIAL AS MATERIAL,
DIS_USTQ12.CATALOG AS CATALOG,
DIS_USTQ12.SOLD_TO_NAME AS SOLD_TO_NAME,
DIS_USTQ12.DISTRIBUTOR_USAGE_QTY AS DISTRIBUTOR_USAGE_QTY,
DIS_USTQ12.Q1_DIS_USAGE_QTY AS Q1_DIS_USAGE_QTY,
DIS_USTQ12.Q2_DIS_USAGE_QTY AS Q2_DIS_USAGE_QTY,
DIS_USAGE_Q3.Q3_DIS_USAGE_QTY AS Q3_DIS_USAGE_QTY
FROM
(
SELECT 
DIS_USTQ1.IDD AS IDD,
DIS_USTQ1.ID AS ID,
DIS_USTQ1.MATERIAL AS MATERIAL,
DIS_USTQ1.CATALOG AS CATALOG,
DIS_USTQ1.SOLD_TO_NAME AS SOLD_TO_NAME,
DIS_USTQ1.DISTRIBUTOR_USAGE_QTY AS DISTRIBUTOR_USAGE_QTY,
DIS_USTQ1.Q1_DIS_USAGE_QTY AS Q1_DIS_USAGE_QTY,
DIS_USAGE_Q2.Q2_DIS_USAGE_QTY AS Q2_DIS_USAGE_QTY
FROM
(
SELECT 
DIS_USAGE_TOT.IDD AS IDD,
DIS_USAGE_TOT.ID AS ID,
DIS_USAGE_TOT.MATERIAL AS MATERIAL,
DIS_USAGE_TOT.CATALOG AS CATALOG,
DIS_USAGE_TOT.SOLD_TO_NAME AS SOLD_TO_NAME,
DIS_USAGE_TOT.DISTRIBUTOR_USAGE_QTY AS DISTRIBUTOR_USAGE_QTY,
DIS_USAGE_Q1.Q1_DIS_USAGE_QTY AS Q1_DIS_USAGE_QTY
FROM
(
SELECT 
      ID||'_'||SOLD_TO_NAME AS IDD,
      ID,
      MATERIAL,
      CATALOG,
      SOLD_TO_NAME,
      SUM(ORDER_QTY) AS DISTRIBUTOR_USAGE_QTY
    FROM INV_SAP_SALES_HST_LC
    WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 365) AND TO_CHAR(SYSDATE)
    AND OPEN_QTY = 0
    GROUP BY ID,
      SOLD_TO_NAME,
      MATERIAL,
      CATALOG
)DIS_USAGE_TOT
LEFT JOIN
(
--Q1
SELECT 
      ID||'_'||SOLD_TO_NAME AS IDD,
      ID,
      SOLD_TO_NAME,
      SUM(ORDER_QTY) AS Q1_DIS_USAGE_QTY
    FROM INV_SAP_SALES_HST_LC
    WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 365) AND TO_CHAR(SYSDATE - 271)
    AND OPEN_QTY = 0
    GROUP BY ID,
      SOLD_TO_NAME
)DIS_USAGE_Q1
ON DIS_USAGE_Q1.IDD = DIS_USAGE_TOT.IDD
)DIS_USTQ1
LEFT JOIN
(
--Q2
SELECT 
      ID||'_'||SOLD_TO_NAME AS IDD,
      ID,
      SOLD_TO_NAME,
      SUM(ORDER_QTY) AS Q2_DIS_USAGE_QTY
    FROM INV_SAP_SALES_HST_LC
    WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 270) AND TO_CHAR(SYSDATE - 181)
    AND OPEN_QTY = 0
    GROUP BY ID,
      SOLD_TO_NAME
)DIS_USAGE_Q2
ON DIS_USAGE_Q2.IDD = DIS_USTQ1.IDD
)DIS_USTQ12
LEFT JOIN
(
--Q3
SELECT 
      ID||'_'||SOLD_TO_NAME AS IDD,
      ID,
      SOLD_TO_NAME,
      SUM(ORDER_QTY) AS Q3_DIS_USAGE_QTY
    FROM INV_SAP_SALES_HST_LC
    WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 180) AND TO_CHAR(SYSDATE - 91)
    AND OPEN_QTY = 0
    GROUP BY ID,
      SOLD_TO_NAME
)DIS_USAGE_Q3
ON DIS_USAGE_Q3.IDD = DIS_USTQ12.IDD
)DIS_USTQ123
LEFT JOIN
(
--Q4
SELECT 
      ID||'_'||SOLD_TO_NAME AS IDD,
      ID,
      SOLD_TO_NAME,
      SUM(ORDER_QTY) AS Q4_DIS_USAGE_QTY
    FROM INV_SAP_SALES_HST_LC
    WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 90) AND TO_CHAR(SYSDATE)
    AND OPEN_QTY = 0
    GROUP BY ID,
      SOLD_TO_NAME
)DIS_USAGE_Q4
ON DIS_USAGE_Q4.IDD = DIS_USTQ123.IDD;
 
---VIEW_INV_SAP_DSTR_STATS

  CREATE VIEW VIEW_INV_SAP_DSTR_STATS
  SELECT DIS_TOTUS.ID           AS ID,
  DIS_TOTUS.DIS_NAME          AS MAX_DIS_NAME,
  DIS_TOTUS.MAX_USAGE_QTY     AS MAX_DIS_USAGE_QTY,
  DIS_TOTUS.TOT_USAGE_QTY     AS TOT_USAGE_QTY,
  DIS_TOTUS.PERSENTAGE        AS PERSENTAGE,
  ROUND(DIS_COUNT.DISTRIBUTOR_COUNT,2) AS DISTRIBUTOR_COUNT
FROM
  (SELECT DIS_MAX_USAGE.ID                                    AS ID,
    DIS_MAX_USAGE.SOLD_TO_NAME                                AS DIS_NAME,
    DIS_MAX_USAGE.MAX_USAGE_QTY                               AS MAX_USAGE_QTY,
    TOT_USAGE.TOT_USAGE_QTY                                   AS TOT_USAGE_QTY,
    DIS_MAX_USAGE.MAX_USAGE_QTY/TOT_USAGE.TOT_USAGE_QTY AS PERSENTAGE
  FROM
    (SELECT DISTINCT DIS_USAGE_MAX.ID AS ID,
      DIS_USAGE.SOLD_TO_NAME          AS SOLD_TO_NAME,
      DIS_USAGE.DISTRIBUTOR_USAGE_QTY AS DISTRIBUTOR_USAGE_QTY,
      DIS_USAGE_MAX.MAX_USAGE_QTY     AS MAX_USAGE_QTY
    FROM
      (SELECT DISTINCT ID
        ||'_'
        ||MAX(DISTRIBUTOR_USAGE_QTY) AS IDS,
        ID,
        MAX(DISTRIBUTOR_USAGE_QTY) AS MAX_USAGE_QTY
      FROM
        (SELECT ID,
          SOLD_TO_NAME,
          SUM(ORDER_QTY) AS DISTRIBUTOR_USAGE_QTY
        FROM INV_SAP_SALES_HST_LC
        WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 365) AND TO_CHAR(SYSDATE)
        AND OPEN_QTY = 0
        GROUP BY ID,
          SOLD_TO_NAME
        )
      GROUP BY ID
      )DIS_USAGE_MAX
    LEFT JOIN
      (SELECT ID
        ||'_'
        ||SUM(ORDER_QTY) AS IDS,
        ID,
        SOLD_TO_NAME,
        SUM(ORDER_QTY) AS DISTRIBUTOR_USAGE_QTY
      FROM INV_SAP_SALES_HST_LC
      WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 365) AND TO_CHAR(SYSDATE)
      AND OPEN_QTY = 0
      GROUP BY ID,
        SOLD_TO_NAME
      )DIS_USAGE
    ON DIS_USAGE_MAX.IDS = DIS_USAGE.IDS
    )DIS_MAX_USAGE
  LEFT JOIN
    (SELECT ID,
      SUM(ORDER_QTY) AS TOT_USAGE_QTY
    FROM INV_SAP_SALES_HST_LC
    WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 365) AND TO_CHAR(SYSDATE)
    AND OPEN_QTY = 0
    GROUP BY ID
    )TOT_USAGE
  ON TOT_USAGE.ID = DIS_MAX_USAGE.ID
  )DIS_TOTUS
LEFT JOIN
  (SELECT ID,
    SUM(KEY) AS DISTRIBUTOR_COUNT
  FROM
    ( SELECT DISTINCT ID,
      SOLD_TO_NAME,
      1 AS KEY
    FROM INV_SAP_SALES_HST_LC
    WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 365) AND TO_CHAR(SYSDATE)
    AND OPEN_QTY = 0
    )
  GROUP BY ID
  )DIS_COUNT
ON DIS_COUNT.ID = DIS_TOTUS.ID;
 

--SO LINE COUNT & SHIP QTY
SELECT * FROM VIEW_INV_SAP_AP_SOLNSH_STAT;
DROP VIEW VIEW_INV_SAP_AP_SOLNSH_STAT;

CREATE VIEW VIEW_INV_SAP_AP_SOLNSH_STAT AS 
SELECT ID,
  MATERIAL,
  CATALOG,
  PLANT,
  SUM(Q1)    AS Q1_SHIP_QTY,
  SUM(Q2)    AS Q2_SHIP_QTY,
  SUM(Q3)    AS Q3_SHIP_QTY,
  SUM(Q4)    AS Q4_SHIP_QTY,
  SUM(LN_Q1) AS Q1_LN_QTY,
  SUM(LN_Q2) AS Q2_LN_QTY,
  SUM(LN_Q3) AS Q3_LN_QTY,
  SUM(LN_Q4) AS Q4_LN_QTY
FROM
  (SELECT ID,
    MATERIAL,
    CATALOG,
    PLANT,
    CASE
      WHEN LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 365 ) AND TO_CHAR(SYSDATE - 273)
      THEN SHIP_QTY
      ELSE 0
    END Q1,
    CASE
      WHEN LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 273) AND TO_CHAR(SYSDATE - 182)
      THEN SHIP_QTY
      ELSE 0
    END Q2,
    CASE
      WHEN LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE- 182) AND TO_CHAR(SYSDATE - 91)
      THEN SHIP_QTY
      ELSE 0
    END Q3,
    CASE
      WHEN LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 91) AND TO_CHAR(SYSDATE)
      THEN SHIP_QTY
      ELSE 0
    END Q4,
    CASE
      WHEN LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 365 ) AND TO_CHAR(SYSDATE - 273)
      THEN COUNT_LINE
      ELSE 0
    END LN_Q1,
    CASE
      WHEN LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 273) AND TO_CHAR(SYSDATE - 182)
      THEN COUNT_LINE
      ELSE 0
    END LN_Q2,
    CASE
      WHEN LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE- 182) AND TO_CHAR(SYSDATE - 91)
      THEN COUNT_LINE
      ELSE 0
    END LN_Q3,
    CASE
      WHEN LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 91) AND TO_CHAR(SYSDATE)
      THEN COUNT_LINE
      ELSE 0
    END LN_Q4
  FROM
    (SELECT ID,
      MATERIAL,
      CATALOG,
      COMMITTED_DATE,
      LAST_GI_DATE,
      CREATION_DATE,
      REQUEST_DATE,
      PLANT,
      ORDER_QTY,
      (NVL(ORDER_QTY,0) - NVL(OPEN_QTY,0)) AS SHIP_QTY,
      1                                    AS COUNT_LINE
    FROM INV_SAP_SALES_HST_LC
    WHERE (LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 365) AND TO_CHAR(SYSDATE))
    )
  )
GROUP BY ID,
  MATERIAL,
  PLANT,
  CATALOG;
  
SELECT * FROM
(
 SELECT * FROM
( 
SELECT * FROM INV_SAP_SALES_HST_LC
)SOH
LEFT JOIN
(SELECT ID, MATL_TYPE FROM INV_SAP_PP_OPT_X)OPT
ON OPT.ID = SOH.ID
) WHERE MATL_TYPE IN ('ZTG','ZFG') AND STRATEGY_GRP = '40' and LAST_GI_DATE between to_char(sysdate - 365) and to_char(sysdate);





select * from INV_SAP_DSTR_STATS;












SELECT * FROM INV_SAP_SALES_HST_LC WHERE SALES_ORG IN ('5007','5003','5016')