-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Project Name : APAFC
-- Version : 1.0
-- Description:
-- Table Init
-- Revision History:
--    Date        Developer         Description
--    ---------   ---------------   ----------------------------------------------------
--    2014-12-24  Moyue           	Table Init.
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------

--Build DBLINK between local server and remote server.
CREATE OR REPLACE PROCEDURE APAFC_SAP_BUILD_DBLINK(DBLINKE_NAME IN VARCHAR2,USER_NAME IN VARCHAR2,PWD IN VARCHAR2,SERVICE_NAME IN VARCHAR2) AUTHID CURRENT_USER
IS	
PROCESS_TERMINATED EXCEPTION;
STEP_NAME VARCHAR2(100);
LINKE_SQL VARCHAR2(300);
BEGIN
	STEP_NAME := 'BUILD_DBLINK';
	LINKE_SQL := 'CREATE PUBLIC DATABASE LINK '||DBLINKE_NAME||' CONNECT TO '||USER_NAME||' IDENTIFIED BY '||PWD||' USING '''||SERVICE_NAME||'''';
    APAFC_SCRIPT_EXE_IMMEDIATE(LINKE_SQL);
    APAFC_MSG_PRINT('DBLink build done.');
EXCEPTION
  WHEN OTHERS THEN
	COMMIT;
	DBMS_OUTPUT.PUT_LINE('Execute Script:'||SUBSTR(LINKE_SQL,1,100));
	DBMS_OUTPUT.PUT_LINE('Execute Error:');
	DBMS_OUTPUT.PUT_LINE(SUBSTR(DBMS_UTILITY.FORMAT_ERROR_STACK,1,200)||SUBSTR(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,1,200));
	RAISE PROCESS_TERMINATED;
END;

--TABLE init, copy the table from the US server   
CREATE OR REPLACE PROCEDURE APAFC_SAP_TABLE_INIT
IS
STEP_NAME VARCHAR2(100);
PP_OPT_INIT VARCHAR2(2000); --Main table in the database. 
PP_SOBACKLOG_INIT VARCHAR2(2000); --Open SO table.
PP_FC_INIT VARCHAR2(2000); --Forecast table.
PP_DELI_INIT VARCHAR2(2000); --Delivery INFO TABLE.
PP_INV_INIT VARCHAR2(2000); --Inventory table.
PP_POSTO_INIT VARCHAR2(2000); --Inventory table.
PP_SOHST_INIT VARCHAR2(2000); --SO HISTORY table.
PP_IO_INIT VARCHAR2(2000); --IO table.
PP_MVK_INIT VARCHAR2(2000); --MM03 INFO table.
PP_PLMSG_INIT VARCHAR2(2000); --Plant and sale org mapping table.
PP_MRPTYPE_INIT VARCHAR2(2000); --MRP TYPE INFO table.
PP_PARAM_INIT VARCHAR2(2000); --PRODUCTION PARAMETERS
PP_MRPCONTROLLER_INIT VARCHAR2(2000); --MRP CONTROLLER.
PP_USERLOG_INIT VARCHAR2(2000);
PP_SOSSHIP_SOLDTO_INIT VARCHAR2(2000); --SO SHIP_SOLD_TO ADDRESS.
PP_ROP_INIT VARCHAR2(2000); --SO SHIP_SOLD_TO ADDRESS.
PP_PLTNAME_INIT VARCHAR2(2000); --5040.5041
PP_SPOKEY_PLAT_INIT VARCHAR2(2000); ----Table that houses Special Pro Key Plant to Plant Combinations. Used to take plant and special pro key and determine the sending plant

BEGIN
	STEP_NAME := 'Init tables from US server';
	PP_OPT_INIT := 'CREATE TABLE INV_SAP_PP_OPTIMIZATION AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DW_DBLINK';
	PP_SOBACKLOG_INIT := 'CREATE TABLE INV_SAP_SALES_VBAK_VBAP_VBUP AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DW_DBLINK';
	PP_FC_INIT := 'CREATE TABLE INV_SAP_PP_FRCST_PBIM_PBED AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED@ROCKWELL_DW_DBLINK WHERE PLANTID IN (''''5040'''', ''''5050'''', ''''5100'''', ''''5110'''', ''''5120'''', ''''5160'''', ''''5190'''', ''''5200'''',''''5070'''',''''5140'''')';
	PP_DELI_INIT := 'CREATE TABLE INV_SAP_LIKP_LIPS_DAILY AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY@ROCKWELL_DW_DBLINK WHERE CREATED_ON_DATE > SYSDATE - 91';
	PP_INV_INIT := 'CREATE TABLE INV_SAP_INVENTORY_BY_PLANT AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_INVENTORY_BY_PLANT@ROCKWELL_DW_DBLINK';
	PP_POSTO_INIT := 'CREATE TABLE INV_SAP_PP_PO_HISTORY AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DW_DBLINK WHERE PLANTID IN (''''5040'''', ''''5050'''', ''''5100'''', ''''5110'''', ''''5120'''', ''''5160'''', ''''5190'''', ''''5200'''',''''5070'''',''''5140'''')';
	PP_SOHST_INIT := 'CREATE TABLE INV_SAP_SALES_HST AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DW_DBLINK WHERE PLANTID IN (''''5040'''', ''''5050'''', ''''5100'''', ''''5110'''', ''''5120'''', ''''5160'''', ''''5190'''', ''''5200'''',''''5070'''',''''5140'''')';
	PP_IO_INIT := 'CREATE TABLE INV_SAP_IO_INPUTS_DAILY AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_IO_INPUTS_DAILY@ROCKWELL_DW_DBLINK';
	PP_MVK_INIT := 'CREATE TABLE INV_SAP_PP_MVKE AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE@ROCKWELL_DW_DBLINK';
	PP_PLMSG_INIT := 'CREATE TABLE INV_SAP_PP_PLANT_SAOG AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_T001W@ROCKWELL_DW_DBLINK';
	PP_MRPTYPE_INIT := 'CREATE TABLE INV_SAP_MRP_TYPE_DIS AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_MRP_TYPE_DIS@ROCKWELL_DW_DBLINK';
	PP_PARAM_INIT := 'CREATE TABLE INV_SAP_PRODUCTION_PARAMETERS AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PRODUCTION_PARAMETERS@ROCKWELL_DW_DBLINK';
	PP_USERLOG_INIT := 'CREATE TABLE INV_SAP_PLAN_PARAM_USERLOG AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PLAN_PARAM_USERLOG@ROCKWELL_DW_DBLINK';
	PP_MRPCONTROLLER_INIT := 'CREATE TABLE INV_SAP_MRP_CONTROLLER_DIS AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_MRP_CONTROLLER_DIS@ROCKWELL_DW_DBLINK';
	PP_SOSSHIP_SOLDTO_INIT := 'CREATE TABLE INV_SAP_SHIP_SOLD_TO_PARTYID AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SHIP_SOLD_TO_PARTYID@ROCKWELL_DW_DBLINK';
	PP_ROP_INIT := 'CREATE TABLE INV_SAP_PLAN_PARAM_REVIEW AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PLAN_PARAM_REVIEW@ROCKWELL_DW_DBLINK';
	PP_PLTNAME_INIT := 'CREATE TABLE INV_SAP_PP_ROUTING AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_ROUTING@ROCKWELL_DW_DBLINK';
  PP_SPOKEY_PLAT_INIT := 'CREATE TABLE INV_SAP_CODE_LOOKUP AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_CODE_LOOKUP@ROCKWELL_DW_DBLINK';
  --Create new tables
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_OPT_INIT);
  COMMIT;
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_SOBACKLOG_INIT);
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_FC_INIT);
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_DELI_INIT);
	COMMIT;
  APAFC_SCRIPT_EXE_IMMEDIATE(PP_INV_INIT);
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_POSTO_INIT);
  COMMIT;
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_SOHST_INIT);
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_IO_INIT);
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_MVK_INIT);
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_PLMSG_INIT);
  COMMIT;
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_MRPTYPE_INIT);
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_PARAM_INIT);
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_MRPCONTROLLER_INIT);
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_SOSSHIP_SOLDTO_INIT);
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_ROP_INIT);
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_PLTNAME_INIT);
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_SPOKEY_PLAT_INIT);
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_USERLOG_INIT);
  COMMIT;
EXCEPTION
WHEN OTHERS THEN
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Execute Script:'||SUBSTR(MSG,1,100));
  DBMS_OUTPUT.PUT_LINE('Execute Error:');
  DBMS_OUTPUT.PUT_LINE(SUBSTR(DBMS_UTILITY.FORMAT_ERROR_STACK,1,200)||SUBSTR(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,1,200));
  RAISE PROCESS_TERMINATED;
END APAFC_SAP_TABLE_INIT;

BEGIN
  APAFC_SAP_TABLE_INIT;
END;
