-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Project Name : APAFC
-- Version : 1.0
-- Description:
-- Table Init
-- Revision History:
--    Date        Developer         Description
--    ---------   ---------------   ----------------------------------------------------
--    2015-8-6  Moyue           	  5150.
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------

--Shipment data

--1. SO HST Value 2014.10-2015.7
SELECT * FROM INV_SAP_SALES_HST_LC WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140') AND LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 381) AND TO_CHAR(SYSDATE - 321);


--2. Ship from DC
--1. Complete Order Calculation
DROP VIEW VIEW_INV_SAP_AOP_DDC;
CREATE VIEW VIEW_INV_SAP_AOP_DDC AS
SELECT 
  LIFNR_VENDORNO,
  PLANTID,
  MATERIALID,
  EBELNPURCHDOCNO,
  EBELPPURCHITEMNO,
  TOTALRECIEVEDYQTY,
  WAERS_CURRENCYKEY,
  NETWRNETORDERVALUE,
  BUDATPOSTINGDATE,
  STRATEGY_GRP,
  UNIT_COST,
  PO_SO_SA_FLAG,
  DELIVERYCOMPLETE
FROM INV_SAP_PP_PO_HISTORY_ALL
WHERE BUDATPOSTINGDATE BETWEEN TO_CHAR(SYSDATE - 381) AND TO_CHAR(SYSDATE - 321)
AND TOTALRECIEVEDYQTY IS NOT NULL
AND PO_SO_SA_FLAG     IN ('STO')
AND DELIVERYCOMPLETE  IS NOT NULL
AND LIFNR_VENDORNO IN ('V5040','V5050', 'V5100', 'V5110', 'V5120', 'V5160', 'V5190', 'V5200','V5070','V5140');


SELECT * FROM VIEW_INV_SAP_AOP_DDC WHERE EBELNPURCHDOCNO = '6600036842' AND EBELPPURCHITEMNO = '230';


-- Partial Shippment
DROP VIEW VIEW_INV_SAP_AOP_DDC_P;
CREATE VIEW VIEW_INV_SAP_AOP_DDC_P AS
SELECT 
  PO_STO.LIFNR_VENDORNO,
  PO_STO.PLANTID,
  PO_STO.MATERIALID,
  P_PO_STO.EBELNPURCHDOCNO,
  PO_STO.EBELPPURCHITEMNO,
  PO_STO.MENGESCHEDULEDQTY,
  PO_STO.WEMNGRECEIVEDQTY,
  PO_STO.WAERS_CURRENCYKEY,
  PO_STO.NETWRNETORDERVALUE,
  PO_STO.SLFDTSTATDELIVERYDATE,
  PO_STO.BUDATPOSTINGDATE,
  PO_STO.STRATEGY_GRP,
  PO_STO.UNIT_COST,
  PO_STO.PO_SO_SA_FLAG,
  PO_STO.DELIVERYCOMPLETE
FROM
(
SELECT DISTINCT EBELNPURCHDOCNO
FROM INV_SAP_PP_PO_HISTORY_ALL
WHERE ETENRPURCHDELIVSCHLINESA = '1' AND TOTALRECIEVEDYQTY IS NULL  
AND PO_SO_SA_FLAG       IN ('STO')
AND LIFNR_VENDORNO IN ('V5040','V5050', 'V5100', 'V5110', 'V5120', 'V5160', 'V5190', 'V5200','V5070','V5140')
)P_PO_STO
LEFT JOIN
(SELECT 
  LIFNR_VENDORNO,
  PLANTID,
  MATERIALID,
  EBELNPURCHDOCNO,
  EBELPPURCHITEMNO,
  MENGESCHEDULEDQTY,
  WEMNGRECEIVEDQTY,
  WAERS_CURRENCYKEY,
  NETWRNETORDERVALUE,
  SLFDTSTATDELIVERYDATE,
  BUDATPOSTINGDATE,
  STRATEGY_GRP,
  UNIT_COST,
  PO_SO_SA_FLAG,
  DELIVERYCOMPLETE
FROM INV_SAP_PP_PO_HISTORY_ALL
)PO_STO
ON PO_STO.EBELNPURCHDOCNO = P_PO_STO.EBELNPURCHDOCNO;


SELECT *
FROM VIEW_INV_SAP_AOP_DDC_P
WHERE DELIVERYCOMPLETE IS NOT NULL
AND SLFDTSTATDELIVERYDATE BETWEEN TO_CHAR(SYSDATE - 316) AND TO_CHAR(SYSDATE - 13)
AND MENGESCHEDULEDQTY = '0'


SELECT * FROM VIEW_INV_SAP_AOP_DDC_P  WHERE EBELNPURCHDOCNO = '6600036842' AND DELIVERYCOMPLETE IS NOT NULL
AND SLFDTSTATDELIVERYDATE BETWEEN TO_CHAR(SYSDATE - 316) AND TO_CHAR(SYSDATE - 13)
AND MENGESCHEDULEDQTY = '0';
------------------------------------------------------------------------------------------------------------------------


--Receiving Data

SELECT * FROM INV_SAP_PP_PO_HISTORY_ALL  WHERE EBELNPURCHDOCNO = '6600036842' AND EBELPPURCHITEMNO = '20';

--1. Complete Order Calculation

CREATE VIEW VIEW_INV_SAP_AOP_STO_COMPLETE AS
SELECT PLANTID,
  MATERIALID,
  EBELNPURCHDOCNO,
  EBELPPURCHITEMNO,
  TOTALRECIEVEDYQTY,
  WAERS_CURRENCYKEY,
  NETWRNETORDERVALUE,
  BUDATPOSTINGDATE,
  STRATEGY_GRP,
  UNIT_COST,
  PO_SO_SA_FLAG,
  DELIVERYCOMPLETE
FROM INV_SAP_PP_PO_HISTORY_ALL
WHERE BUDATPOSTINGDATE BETWEEN TO_CHAR(SYSDATE - 381) AND TO_CHAR(SYSDATE - 321)
AND TOTALRECIEVEDYQTY IS NOT NULL
AND PO_SO_SA_FLAG     IN ('STO')
AND DELIVERYCOMPLETE  IS NOT NULL
AND PLANTID           IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');


SELECT * FROM VIEW_INV_SAP_AOP_STO_COMPLETE WHERE EBELNPURCHDOCNO = '6302093413'


--1.1 Partial Shippment
DROP VIEW VIEW_INV_SAP_AOP_STO_P;
CREATE VIEW VIEW_INV_SAP_AOP_STO_P AS
SELECT PO_STO.PLANTID,
  PO_STO.MATERIALID,
  P_PO_STO.EBELNPURCHDOCNO,
  PO_STO.EBELPPURCHITEMNO,
  PO_STO.MENGESCHEDULEDQTY,
  PO_STO.WEMNGRECEIVEDQTY,
  PO_STO.WAERS_CURRENCYKEY,
  PO_STO.NETWRNETORDERVALUE,
  PO_STO.SLFDTSTATDELIVERYDATE,
  PO_STO.BUDATPOSTINGDATE,
  PO_STO.STRATEGY_GRP,
  PO_STO.UNIT_COST,
  PO_STO.PO_SO_SA_FLAG,
  PO_STO.DELIVERYCOMPLETE
FROM
(
SELECT DISTINCT EBELNPURCHDOCNO
FROM INV_SAP_PP_PO_HISTORY_ALL
WHERE TOTALRECIEVEDYQTY IS NULL AND ETENRPURCHDELIVSCHLINESA = '1'
AND PO_SO_SA_FLAG       IN ('STO')
AND PLANTID             IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
)P_PO_STO
LEFT JOIN
(SELECT PLANTID,
  MATERIALID,
  EBELNPURCHDOCNO,
  EBELPPURCHITEMNO,
  MENGESCHEDULEDQTY,
  WEMNGRECEIVEDQTY,
  WAERS_CURRENCYKEY,
  NETWRNETORDERVALUE,
  SLFDTSTATDELIVERYDATE,
  BUDATPOSTINGDATE,
  STRATEGY_GRP,
  UNIT_COST,
  PO_SO_SA_FLAG,
  DELIVERYCOMPLETE
FROM INV_SAP_PP_PO_HISTORY_ALL
)PO_STO
ON PO_STO.EBELNPURCHDOCNO = P_PO_STO.EBELNPURCHDOCNO;


SELECT count(*)
FROM VIEW_INV_SAP_AOP_STO_P
WHERE DELIVERYCOMPLETE IS NOT NULL
AND SLFDTSTATDELIVERYDATE BETWEEN TO_CHAR(SYSDATE - 381) AND TO_CHAR(SYSDATE - 321)
AND MENGESCHEDULEDQTY = '0'


--2. 3rd Party
SELECT PLANTID,
  MATERIALID,
  EBELNPURCHDOCNO,
  EBELPPURCHITEMNO,
  TOTALRECIEVEDYQTY,
  WAERS_CURRENCYKEY,
  NETWRNETORDERVALUE,
  BUDATPOSTINGDATE,
  STRATEGY_GRP,
  UNIT_COST,
  PO_SO_SA_FLAG,
  DELIVERYCOMPLETE
FROM INV_SAP_PP_PO_HISTORY_ALL
WHERE BUDATPOSTINGDATE BETWEEN TO_CHAR(SYSDATE - 381) AND TO_CHAR(SYSDATE - 17)
AND BSART_PURCHDOCTYPE = 'ZNB'
AND PLANTID           IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
AND DELIVERYCOMPLETE  IS NOT NULL
AND TOTALRECIEVEDYQTY IS NOT NULL



--Monitor the vendor shippment status..

SELECT * FROM
(
SELECT 
  STO.ID, 
  STO.LIFNR_VENDORNO,
  STO.PLANTID,
  STO.MATERIALID,
  STO.EBELNPURCHDOCNO,
  STO.ETENRPURCHDELIVSCHLINESA,
  STO.BEDATSCHEDULELINEORDERDATE,
  STO.BUDATPOSTINGDATE,
  OPT.STRATEGY_GRP
FROM
(
SELECT 
  MATERIALID ||'_'||substr(LIFNR_VENDORNO, 2, 4) AS ID, 
  LIFNR_VENDORNO,
  PLANTID,
  MATERIALID,
  EBELNPURCHDOCNO,
  ETENRPURCHDELIVSCHLINESA,
  BEDATSCHEDULELINEORDERDATE,
  BUDATPOSTINGDATE
FROM INV_SAP_PP_PO_HISTORY_ALL
WHERE BUDATPOSTINGDATE BETWEEN TO_CHAR(SYSDATE - 180) AND TO_CHAR(SYSDATE)
AND TOTALRECIEVEDYQTY IS NOT NULL
AND PO_SO_SA_FLAG     IN ('STO')
AND DELIVERYCOMPLETE  IS NOT NULL
AND LIFNR_VENDORNO IN ('V1090') 
AND PLANTID           IN ('5100')
AND ETENRPURCHDELIVSCHLINESA = '1'
)STO
LEFT JOIN
(
SELECT ID, STRATEGY_GRP FROM INV_SAP_PP_OPT_X
)OPT
ON OPT.ID = STO.ID)
WHERE STRATEGY_GRP = '40'

select * from INV_SAP_PP_PO_HISTORY_ALL;


SELECT * FROM
(
SELECT 
  STO.ID, 
  STO.LIFNR_VENDORNO,
  STO.PLANTID,
  STO.MATERIALID,
  STO.EBELNPURCHDOCNO,
  STO.ETENRPURCHDELIVSCHLINESA,
  STO.BEDATSCHEDULELINEORDERDATE,
  STO.BUDATPOSTINGDATE,
  OPT.STRATEGY_GRP
FROM
(
SELECT 
  MATERIALID ||'_'||substr(LIFNR_VENDORNO, 2, 4) AS ID, 
  LIFNR_VENDORNO,
  PLANTID,
  MATERIALID,
  EBELNPURCHDOCNO,
  ETENRPURCHDELIVSCHLINESA,
  BEDATSCHEDULELINEORDERDATE,
  BUDATPOSTINGDATE
FROM INV_SAP_PP_PO_HISTORY_ALL
WHERE BUDATPOSTINGDATE BETWEEN TO_CHAR(SYSDATE - 41) AND TO_CHAR(SYSDATE - 12)
AND TOTALRECIEVEDYQTY IS NOT NULL
AND PO_SO_SA_FLAG     IN ('STO')
AND DELIVERYCOMPLETE  IS NOT NULL
AND LIFNR_VENDORNO IN ('V5200') 
AND PLANTID           IN ('5120', '5160', '5190')
AND ETENRPURCHDELIVSCHLINESA = '1'
)STO
LEFT JOIN
(
SELECT ID, STRATEGY_GRP FROM INV_SAP_PP_OPT_X
)OPT
ON OPT.ID = STO.ID)
WHERE STRATEGY_GRP = '40'


SELECT * FROM
(
SELECT 
  STO.ID, 
  STO.LIFNR_VENDORNO,
  STO.PLANTID,
  STO.MATERIALID,
  STO.EBELNPURCHDOCNO,
  STO.ETENRPURCHDELIVSCHLINESA,
  STO.BEDATSCHEDULELINEORDERDATE,
  STO.BUDATPOSTINGDATE,
  OPT.STRATEGY_GRP
FROM
(
SELECT 
  MATERIALID ||'_'||substr(LIFNR_VENDORNO, 2, 4) AS ID, 
  LIFNR_VENDORNO,
  PLANTID,
  MATERIALID,
  EBELNPURCHDOCNO,
  ETENRPURCHDELIVSCHLINESA,
  BEDATSCHEDULELINEORDERDATE,
  BUDATPOSTINGDATE
FROM INV_SAP_PP_PO_HISTORY_ALL
WHERE BUDATPOSTINGDATE BETWEEN TO_CHAR(SYSDATE - 41) AND TO_CHAR(SYSDATE - 12)
AND TOTALRECIEVEDYQTY IS NOT NULL
AND PO_SO_SA_FLAG     IN ('STO')
AND DELIVERYCOMPLETE  IS NOT NULL
AND LIFNR_VENDORNO IN ('V1180','V1090') 
AND PLANTID           IN ('5040', '5050', '5070','5110', '5140', '5200','5100')
AND ETENRPURCHDELIVSCHLINESA = '1'
)STO
LEFT JOIN
(
SELECT ID, STRATEGY_GRP FROM INV_SAP_PP_OPT_X
)OPT
ON OPT.ID = STO.ID)
WHERE STRATEGY_GRP = '40'