DROP TABLE INV_SAP_SALES_HST_PH;
CREATE TABLE INV_SAP_SALES_HST_PH AS
SELECT SO.ID,
  SO.SALES_DOC,
  SO.MATERIAL,
  SO.ITEM,
  SO.CATALOG,
  PH.PROD_HIERARCHY
FROM
  (SELECT ID,
    SALES_DOC,
    ITEM,
    MATERIAL,
    CATALOG
  FROM INV_SAP_SALES_HST_LC
  WHERE PLANT = '5040'
  )SO
LEFT JOIN
  (SELECT ID, substr(PROD_HIERARCHY,0,18) AS PROD_HIERARCHY FROM INV_SAP_PP_OPT_X
  )PH
ON PH.ID = SO.ID;
  
SELECT DISTINCT ID, SALES_DOC, PROD_HIERARCHY FROM INV_SAP_SALES_HST_PH;
    
--TRANSFER

SELECT * FROM INV_SAP_SALES_HST_LC
DROP TABLE SALES_DOC_T;
DROP VIEW V_SALES_DOC_T;
CREATE VIEW V_SALES_DOC_T AS
SELECT 
  SALES_DOC,
  CASE
    WHEN ITEM =1 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_1,
  CASE
    WHEN ITEM =2 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_2,
  CASE
    WHEN ITEM =3 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_3,
  CASE
    WHEN ITEM =4 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_4,
  CASE
    WHEN ITEM =5 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_5,
  CASE
    WHEN ITEM =6 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_6,
  CASE
    WHEN ITEM =7 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_7,
  CASE
    WHEN ITEM =8 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_8,
  CASE
    WHEN ITEM =9 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_9,
  CASE
    WHEN ITEM =10 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_10,
  CASE
    WHEN ITEM =11 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_11,
  CASE
    WHEN ITEM =12 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_12,
  CASE
    WHEN ITEM =13 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_13,
  CASE
    WHEN ITEM =14 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_14,
  CASE
    WHEN ITEM =15 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_15,
  CASE
    WHEN ITEM =16 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_16,
  CASE
    WHEN ITEM =17 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_17,
  CASE
    WHEN ITEM =18 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_18,
  CASE
    WHEN ITEM =19 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_19,
  CASE
    WHEN ITEM =20 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_20,
  CASE
    WHEN ITEM =21 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_21,
  CASE
    WHEN ITEM =22 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_22,
  CASE
    WHEN ITEM =23 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_23,
  CASE
    WHEN ITEM =24 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_24,
  CASE
    WHEN ITEM =25 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_25,
  CASE
    WHEN ITEM =26 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_26,
  CASE
    WHEN ITEM =27 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_27,
  CASE
    WHEN ITEM =28 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_28,
  CASE
    WHEN ITEM =29 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_29,
  CASE
    WHEN ITEM =30 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_30,
  CASE
    WHEN ITEM =31 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_31,
  CASE
    WHEN ITEM =32 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_32,
  CASE
    WHEN ITEM =33 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_33,
  CASE
    WHEN ITEM =34 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_34,
  CASE
    WHEN ITEM =35 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_35,
  CASE
    WHEN ITEM =36 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_36,
  CASE
    WHEN ITEM =37 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_37,
  CASE
    WHEN ITEM =38 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_38,
  CASE
    WHEN ITEM =39 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_39,
  CASE
    WHEN ITEM =40 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_40,
  CASE
    WHEN ITEM =41 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_41,
  CASE
    WHEN ITEM =42 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_42,
  CASE
    WHEN ITEM =43 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_43,
  CASE
    WHEN ITEM =44 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_44,
  CASE
    WHEN ITEM =45 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_45,
  CASE
    WHEN ITEM =46 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_46,
  CASE
    WHEN ITEM =47 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_47,
  CASE
    WHEN ITEM =48 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_48,
  CASE
    WHEN ITEM =49 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_49,
  CASE
    WHEN ITEM =50 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_50,
  CASE
    WHEN ITEM =51 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_51,
  CASE
    WHEN ITEM =52 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_52,
  CASE
    WHEN ITEM =53 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_53,
  CASE
    WHEN ITEM =54 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_54,
  CASE
    WHEN ITEM =55 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_55,
  CASE
    WHEN ITEM =56 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_56,
  CASE
    WHEN ITEM =57 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_57,
  CASE
    WHEN ITEM =58 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_58,
  CASE
    WHEN ITEM =59 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_59,
  CASE
    WHEN ITEM =60 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_60,
  CASE
    WHEN ITEM =61 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_61,
  CASE
    WHEN ITEM =62 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_62,
  CASE
    WHEN ITEM =63 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_63,
  CASE
    WHEN ITEM =64 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_64,
  CASE
    WHEN ITEM =65 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_65,
  CASE
    WHEN ITEM =66 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_66,
  CASE
    WHEN ITEM =67 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_67,
  CASE
    WHEN ITEM =68 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_68,
  CASE
    WHEN ITEM =69 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_69,
  CASE
    WHEN ITEM =70 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_70,
  CASE
    WHEN ITEM =71 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_71,
  CASE
    WHEN ITEM =72 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_72,
  CASE
    WHEN ITEM =73 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_73,
  CASE
    WHEN ITEM =74 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_74,
  CASE
    WHEN ITEM =75 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_75,
  CASE
    WHEN ITEM =76 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_76,
  CASE
    WHEN ITEM =77 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_77,
  CASE
    WHEN ITEM =78 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_78,
  CASE
    WHEN ITEM =79 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_79,
  CASE
    WHEN ITEM =80 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_80,
  CASE
    WHEN ITEM =81 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_81,
  CASE
    WHEN ITEM =82 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_82,
  CASE
    WHEN ITEM =83 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_83,
  CASE
    WHEN ITEM =84 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_84,
  CASE
    WHEN ITEM =85 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_85,
  CASE
    WHEN ITEM =86 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_86,
  CASE
    WHEN ITEM =87 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_87,
  CASE
    WHEN ITEM =88 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_88,
  CASE
    WHEN ITEM =89 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_89,
  CASE
    WHEN ITEM =90 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_90,
  CASE
    WHEN ITEM =91 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_91,
  CASE
    WHEN ITEM =92 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_92,
  CASE
    WHEN ITEM =93 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_93,
  CASE
    WHEN ITEM =94 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_94,
  CASE
    WHEN ITEM =95 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_95,
  CASE
    WHEN ITEM =96 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_96,
  CASE
    WHEN ITEM =97 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_97,
  CASE
    WHEN ITEM =98 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_98,
  CASE
    WHEN ITEM =99 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_99,
  CASE
    WHEN ITEM =100 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_100,
  CASE
    WHEN ITEM =101 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_101,
  CASE
    WHEN ITEM =102 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_102,
  CASE
    WHEN ITEM =103 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_103,
  CASE
    WHEN ITEM =104 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_104,
  CASE
    WHEN ITEM =105 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_105,
  CASE
    WHEN ITEM =106 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_106,
  CASE
    WHEN ITEM =107 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_107,
  CASE
    WHEN ITEM =108 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_108,
  CASE
    WHEN ITEM =109 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_109,
  CASE
    WHEN ITEM =110 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_110,
  CASE
    WHEN ITEM =111 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_111,
  CASE
    WHEN ITEM =112 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_112,
  CASE
    WHEN ITEM =113 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_113,
  CASE
    WHEN ITEM =114 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_114,
  CASE
    WHEN ITEM =115 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_115,
  CASE
    WHEN ITEM =116 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_116,
  CASE
    WHEN ITEM =117 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_117,
  CASE
    WHEN ITEM =118 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_118,
  CASE
    WHEN ITEM =119 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_119,
  CASE
    WHEN ITEM =120 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_120,
  CASE
    WHEN ITEM =121 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_121,
  CASE
    WHEN ITEM =122 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_122,
  CASE
    WHEN ITEM =123 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_123,
  CASE
    WHEN ITEM =124 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_124,
  CASE
    WHEN ITEM =125 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_125,
  CASE
    WHEN ITEM =126 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_126,
  CASE
    WHEN ITEM =127 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_127,
  CASE
    WHEN ITEM =128 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_128,
  CASE
    WHEN ITEM =129 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_129,
  CASE
    WHEN ITEM =130 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_130,
  CASE
    WHEN ITEM =131 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_131,
  CASE
    WHEN ITEM =132 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_132,
  CASE
    WHEN ITEM =133 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_133,
  CASE
    WHEN ITEM =134 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_134,
  CASE
    WHEN ITEM =135 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_135,
  CASE
    WHEN ITEM =136 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_136,
  CASE
    WHEN ITEM =137 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_137,
  CASE
    WHEN ITEM =138 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_138,
  CASE
    WHEN ITEM =139 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_139,
  CASE
    WHEN ITEM =140 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_140,
  CASE
    WHEN ITEM =141 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_141,
  CASE
    WHEN ITEM =142 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_142,
  CASE
    WHEN ITEM =143 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_143,
  CASE
    WHEN ITEM =144 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_144,
  CASE
    WHEN ITEM =145 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_145,
  CASE
    WHEN ITEM =146 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_146,
  CASE
    WHEN ITEM =147 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_147,
  CASE
    WHEN ITEM =148 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_148,
  CASE
    WHEN ITEM =149 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_149,
  CASE
    WHEN ITEM =150 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_150,
  CASE
    WHEN ITEM =151 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_151,
  CASE
    WHEN ITEM =152 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_152,
  CASE
    WHEN ITEM =153 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_153,
  CASE
    WHEN ITEM =154 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_154,
  CASE
    WHEN ITEM =155 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_155,
  CASE
    WHEN ITEM =156 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_156,
  CASE
    WHEN ITEM =157 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_157,
  CASE
    WHEN ITEM =158 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_158,
  CASE
    WHEN ITEM =159 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_159,
  CASE
    WHEN ITEM =160 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_160,
  CASE
    WHEN ITEM =161 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_161,
  CASE
    WHEN ITEM =162 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_162,
  CASE
    WHEN ITEM =163 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_163,
  CASE
    WHEN ITEM =164 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_164,
  CASE
    WHEN ITEM =165 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_165,
  CASE
    WHEN ITEM =166 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_166,
  CASE
    WHEN ITEM =167 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_167,
  CASE
    WHEN ITEM =168 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_168,
  CASE
    WHEN ITEM =169 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_169,
  CASE
    WHEN ITEM =170 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_170,
  CASE
    WHEN ITEM =171 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_171,
  CASE
    WHEN ITEM =172 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_172,
  CASE
    WHEN ITEM =173 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_173,
  CASE
    WHEN ITEM =174 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_174,
  CASE
    WHEN ITEM =175 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_175,
  CASE
    WHEN ITEM =176 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_176,
  CASE
    WHEN ITEM =177 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_177,
  CASE
    WHEN ITEM =178 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_178,
  CASE
    WHEN ITEM =179 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_179,
  CASE
    WHEN ITEM =180 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_180,
  CASE
    WHEN ITEM =181 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_181,
  CASE
    WHEN ITEM =182 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_182,
  CASE
    WHEN ITEM =183 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_183,
  CASE
    WHEN ITEM =184 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_184,
  CASE
    WHEN ITEM =185 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_185,
  CASE
    WHEN ITEM =186 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_186,
  CASE
    WHEN ITEM =187 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_187,
  CASE
    WHEN ITEM =188 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_188,
  CASE
    WHEN ITEM =189 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_189,
  CASE
    WHEN ITEM =190 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_190,
  CASE
    WHEN ITEM =191 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_191,
  CASE
    WHEN ITEM =192 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_192,
  CASE
    WHEN ITEM =193 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_193,
  CASE
    WHEN ITEM =194 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_194,
  CASE
    WHEN ITEM =195 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_195,
  CASE
    WHEN ITEM =196 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_196,
  CASE
    WHEN ITEM =197 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_197,
  CASE
    WHEN ITEM =198 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_198,
  CASE
    WHEN ITEM =199 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_199,
  CASE
    WHEN ITEM =200 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_200,
  CASE
    WHEN ITEM =201 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_201,
  CASE
    WHEN ITEM =202 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_202,
  CASE
    WHEN ITEM =203 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_203,
  CASE
    WHEN ITEM =204 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_204,
  CASE
    WHEN ITEM =205 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_205,
  CASE
    WHEN ITEM =206 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_206,
  CASE
    WHEN ITEM =207 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_207,
  CASE
    WHEN ITEM =208 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_208,
  CASE
    WHEN ITEM =209 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_209,
  CASE
    WHEN ITEM =210 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_210,
  CASE
    WHEN ITEM =211 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_211,
  CASE
    WHEN ITEM =212 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_212,
  CASE
    WHEN ITEM =213 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_213,
  CASE
    WHEN ITEM =214 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_214,
  CASE
    WHEN ITEM =215 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_215,
  CASE
    WHEN ITEM =216 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_216,
  CASE
    WHEN ITEM =217 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_217,
  CASE
    WHEN ITEM =218 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_218,
  CASE
    WHEN ITEM =219 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_219,
  CASE
    WHEN ITEM =220 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_220,
  CASE
    WHEN ITEM =221 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_221,
  CASE
    WHEN ITEM =222 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_222,
  CASE
    WHEN ITEM =223 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_223,
  CASE
    WHEN ITEM =224 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_224,
  CASE
    WHEN ITEM =225 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_225,
  CASE
    WHEN ITEM =226 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_226,
  CASE
    WHEN ITEM =227 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_227,
  CASE
    WHEN ITEM =228 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_228,
  CASE
    WHEN ITEM =229 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_229,
  CASE
    WHEN ITEM =230 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_230,
  CASE
    WHEN ITEM =231 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_231,
  CASE
    WHEN ITEM =232 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_232,
  CASE
    WHEN ITEM =233 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_233,
  CASE
    WHEN ITEM =234 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_234,
  CASE
    WHEN ITEM =235 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_235,
  CASE
    WHEN ITEM =236 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_236,
  CASE
    WHEN ITEM =237 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_237,
  CASE
    WHEN ITEM =238 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_238,
  CASE
    WHEN ITEM =239 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_239,
  CASE
    WHEN ITEM =240 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_240,
  CASE
    WHEN ITEM =241 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_241,
  CASE
    WHEN ITEM =242 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_242,
  CASE
    WHEN ITEM =243 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_243,
  CASE
    WHEN ITEM =244 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_244,
  CASE
    WHEN ITEM =245 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_245,
  CASE
    WHEN ITEM =246 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_246,
  CASE
    WHEN ITEM =247 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_247,
  CASE
    WHEN ITEM =248 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_248,
  CASE
    WHEN ITEM =249 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_249,
  CASE
    WHEN ITEM =250 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_250
FROM INV_SAP_SALES_HST_PH;

CREATE TABLE SALES_DOC_T as SELECT * FROM V_SALES_DOC_T;
SELECT * FROM SALES_DOC_T;


DROP VIEW V_SALES_DOC_TT;
CREATE VIEW V_SALES_DOC_TT AS
SELECT SALES_DOC,
  LISTAGG(PROD_HIERARCHY_1, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_1) AS PROD_HIERARCHY_1,
  LISTAGG(PROD_HIERARCHY_2, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_2) AS PROD_HIERARCHY_2,
  LISTAGG(PROD_HIERARCHY_3, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_3) AS PROD_HIERARCHY_3,
  LISTAGG(PROD_HIERARCHY_4, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_4) AS PROD_HIERARCHY_4,
  LISTAGG(PROD_HIERARCHY_5, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_5) AS PROD_HIERARCHY_5,
  LISTAGG(PROD_HIERARCHY_6, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_6) AS PROD_HIERARCHY_6,
  LISTAGG(PROD_HIERARCHY_7, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_7) AS PROD_HIERARCHY_7,
  LISTAGG(PROD_HIERARCHY_8, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_8) AS PROD_HIERARCHY_8,
  LISTAGG(PROD_HIERARCHY_9, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_9) AS PROD_HIERARCHY_9,
  LISTAGG(PROD_HIERARCHY_10, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_10) AS PROD_HIERARCHY_10,
  LISTAGG(PROD_HIERARCHY_11, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_11) AS PROD_HIERARCHY_11,
  LISTAGG(PROD_HIERARCHY_12, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_12) AS PROD_HIERARCHY_12,
  LISTAGG(PROD_HIERARCHY_13, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_13) AS PROD_HIERARCHY_13,
  LISTAGG(PROD_HIERARCHY_14, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_14) AS PROD_HIERARCHY_14,
  LISTAGG(PROD_HIERARCHY_15, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_15) AS PROD_HIERARCHY_15,
  LISTAGG(PROD_HIERARCHY_16, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_16) AS PROD_HIERARCHY_16,
  LISTAGG(PROD_HIERARCHY_17, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_17) AS PROD_HIERARCHY_17,
  LISTAGG(PROD_HIERARCHY_18, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_18) AS PROD_HIERARCHY_18,
  LISTAGG(PROD_HIERARCHY_19, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_19) AS PROD_HIERARCHY_19,
  LISTAGG(PROD_HIERARCHY_20, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_20) AS PROD_HIERARCHY_20,
  LISTAGG(PROD_HIERARCHY_21, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_21) AS PROD_HIERARCHY_21,
  LISTAGG(PROD_HIERARCHY_22, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_22) AS PROD_HIERARCHY_22,
  LISTAGG(PROD_HIERARCHY_23, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_23) AS PROD_HIERARCHY_23,
  LISTAGG(PROD_HIERARCHY_24, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_24) AS PROD_HIERARCHY_24,
  LISTAGG(PROD_HIERARCHY_25, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_25) AS PROD_HIERARCHY_25,
  LISTAGG(PROD_HIERARCHY_26, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_26) AS PROD_HIERARCHY_26,
  LISTAGG(PROD_HIERARCHY_27, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_27) AS PROD_HIERARCHY_27,
  LISTAGG(PROD_HIERARCHY_28, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_28) AS PROD_HIERARCHY_28,
  LISTAGG(PROD_HIERARCHY_29, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_29) AS PROD_HIERARCHY_29,
  LISTAGG(PROD_HIERARCHY_30, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_30) AS PROD_HIERARCHY_30,
  LISTAGG(PROD_HIERARCHY_31, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_31) AS PROD_HIERARCHY_31,
  LISTAGG(PROD_HIERARCHY_32, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_32) AS PROD_HIERARCHY_32,
  LISTAGG(PROD_HIERARCHY_33, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_33) AS PROD_HIERARCHY_33,
  LISTAGG(PROD_HIERARCHY_34, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_34) AS PROD_HIERARCHY_34,
  LISTAGG(PROD_HIERARCHY_35, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_35) AS PROD_HIERARCHY_35,
  LISTAGG(PROD_HIERARCHY_36, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_36) AS PROD_HIERARCHY_36,
  LISTAGG(PROD_HIERARCHY_37, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_37) AS PROD_HIERARCHY_37,
  LISTAGG(PROD_HIERARCHY_38, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_38) AS PROD_HIERARCHY_38,
  LISTAGG(PROD_HIERARCHY_39, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_39) AS PROD_HIERARCHY_39,
  LISTAGG(PROD_HIERARCHY_40, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_40) AS PROD_HIERARCHY_40,
  LISTAGG(PROD_HIERARCHY_41, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_41) AS PROD_HIERARCHY_41,
  LISTAGG(PROD_HIERARCHY_42, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_42) AS PROD_HIERARCHY_42,
  LISTAGG(PROD_HIERARCHY_43, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_43) AS PROD_HIERARCHY_43,
  LISTAGG(PROD_HIERARCHY_44, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_44) AS PROD_HIERARCHY_44,
  LISTAGG(PROD_HIERARCHY_45, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_45) AS PROD_HIERARCHY_45,
  LISTAGG(PROD_HIERARCHY_46, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_46) AS PROD_HIERARCHY_46,
  LISTAGG(PROD_HIERARCHY_47, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_47) AS PROD_HIERARCHY_47,
  LISTAGG(PROD_HIERARCHY_48, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_48) AS PROD_HIERARCHY_48,
  LISTAGG(PROD_HIERARCHY_49, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_49) AS PROD_HIERARCHY_49,
  LISTAGG(PROD_HIERARCHY_50, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_50) AS PROD_HIERARCHY_50,
  LISTAGG(PROD_HIERARCHY_51, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_51) AS PROD_HIERARCHY_51,
  LISTAGG(PROD_HIERARCHY_52, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_52) AS PROD_HIERARCHY_52,
  LISTAGG(PROD_HIERARCHY_53, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_53) AS PROD_HIERARCHY_53,
  LISTAGG(PROD_HIERARCHY_54, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_54) AS PROD_HIERARCHY_54,
  LISTAGG(PROD_HIERARCHY_55, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_55) AS PROD_HIERARCHY_55,
  LISTAGG(PROD_HIERARCHY_56, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_56) AS PROD_HIERARCHY_56,
  LISTAGG(PROD_HIERARCHY_57, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_57) AS PROD_HIERARCHY_57,
  LISTAGG(PROD_HIERARCHY_58, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_58) AS PROD_HIERARCHY_58,
  LISTAGG(PROD_HIERARCHY_59, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_59) AS PROD_HIERARCHY_59,
  LISTAGG(PROD_HIERARCHY_60, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_60) AS PROD_HIERARCHY_60,
  LISTAGG(PROD_HIERARCHY_61, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_61) AS PROD_HIERARCHY_61,
  LISTAGG(PROD_HIERARCHY_62, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_62) AS PROD_HIERARCHY_62,
  LISTAGG(PROD_HIERARCHY_63, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_63) AS PROD_HIERARCHY_63,
  LISTAGG(PROD_HIERARCHY_64, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_64) AS PROD_HIERARCHY_64,
  LISTAGG(PROD_HIERARCHY_65, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_65) AS PROD_HIERARCHY_65,
  LISTAGG(PROD_HIERARCHY_66, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_66) AS PROD_HIERARCHY_66,
  LISTAGG(PROD_HIERARCHY_67, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_67) AS PROD_HIERARCHY_67,
  LISTAGG(PROD_HIERARCHY_68, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_68) AS PROD_HIERARCHY_68,
  LISTAGG(PROD_HIERARCHY_69, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_69) AS PROD_HIERARCHY_69,
  LISTAGG(PROD_HIERARCHY_70, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_70) AS PROD_HIERARCHY_70,
  LISTAGG(PROD_HIERARCHY_71, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_71) AS PROD_HIERARCHY_71,
  LISTAGG(PROD_HIERARCHY_72, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_72) AS PROD_HIERARCHY_72,
  LISTAGG(PROD_HIERARCHY_73, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_73) AS PROD_HIERARCHY_73,
  LISTAGG(PROD_HIERARCHY_74, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_74) AS PROD_HIERARCHY_74,
  LISTAGG(PROD_HIERARCHY_75, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_75) AS PROD_HIERARCHY_75,
  LISTAGG(PROD_HIERARCHY_76, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_76) AS PROD_HIERARCHY_76,
  LISTAGG(PROD_HIERARCHY_77, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_77) AS PROD_HIERARCHY_77,
  LISTAGG(PROD_HIERARCHY_78, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_78) AS PROD_HIERARCHY_78,
  LISTAGG(PROD_HIERARCHY_79, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_79) AS PROD_HIERARCHY_79,
  LISTAGG(PROD_HIERARCHY_80, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_80) AS PROD_HIERARCHY_80,
  LISTAGG(PROD_HIERARCHY_81, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_81) AS PROD_HIERARCHY_81,
  LISTAGG(PROD_HIERARCHY_82, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_82) AS PROD_HIERARCHY_82,
  LISTAGG(PROD_HIERARCHY_83, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_83) AS PROD_HIERARCHY_83,
  LISTAGG(PROD_HIERARCHY_84, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_84) AS PROD_HIERARCHY_84,
  LISTAGG(PROD_HIERARCHY_85, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_85) AS PROD_HIERARCHY_85,
  LISTAGG(PROD_HIERARCHY_86, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_86) AS PROD_HIERARCHY_86,
  LISTAGG(PROD_HIERARCHY_87, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_87) AS PROD_HIERARCHY_87,
  LISTAGG(PROD_HIERARCHY_88, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_88) AS PROD_HIERARCHY_88,
  LISTAGG(PROD_HIERARCHY_89, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_89) AS PROD_HIERARCHY_89,
  LISTAGG(PROD_HIERARCHY_90, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_90) AS PROD_HIERARCHY_90,
  LISTAGG(PROD_HIERARCHY_91, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_91) AS PROD_HIERARCHY_91,
  LISTAGG(PROD_HIERARCHY_92, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_92) AS PROD_HIERARCHY_92,
  LISTAGG(PROD_HIERARCHY_93, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_93) AS PROD_HIERARCHY_93,
  LISTAGG(PROD_HIERARCHY_94, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_94) AS PROD_HIERARCHY_94,
  LISTAGG(PROD_HIERARCHY_95, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_95) AS PROD_HIERARCHY_95,
  LISTAGG(PROD_HIERARCHY_96, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_96) AS PROD_HIERARCHY_96,
  LISTAGG(PROD_HIERARCHY_97, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_97) AS PROD_HIERARCHY_97,
  LISTAGG(PROD_HIERARCHY_98, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_98) AS PROD_HIERARCHY_98,
  LISTAGG(PROD_HIERARCHY_99, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_99) AS PROD_HIERARCHY_99,
  LISTAGG(PROD_HIERARCHY_100, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_100) AS PROD_HIERARCHY_100,
  LISTAGG(PROD_HIERARCHY_101, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_101) AS PROD_HIERARCHY_101,
  LISTAGG(PROD_HIERARCHY_102, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_102) AS PROD_HIERARCHY_102,
  LISTAGG(PROD_HIERARCHY_103, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_103) AS PROD_HIERARCHY_103,
  LISTAGG(PROD_HIERARCHY_104, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_104) AS PROD_HIERARCHY_104,
  LISTAGG(PROD_HIERARCHY_105, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_105) AS PROD_HIERARCHY_105,
  LISTAGG(PROD_HIERARCHY_106, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_106) AS PROD_HIERARCHY_106,
  LISTAGG(PROD_HIERARCHY_107, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_107) AS PROD_HIERARCHY_107,
  LISTAGG(PROD_HIERARCHY_108, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_108) AS PROD_HIERARCHY_108,
  LISTAGG(PROD_HIERARCHY_109, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_109) AS PROD_HIERARCHY_109,
  LISTAGG(PROD_HIERARCHY_110, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_110) AS PROD_HIERARCHY_110,
  LISTAGG(PROD_HIERARCHY_111, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_111) AS PROD_HIERARCHY_111,
  LISTAGG(PROD_HIERARCHY_112, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_112) AS PROD_HIERARCHY_112,
  LISTAGG(PROD_HIERARCHY_113, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_113) AS PROD_HIERARCHY_113,
  LISTAGG(PROD_HIERARCHY_114, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_114) AS PROD_HIERARCHY_114,
  LISTAGG(PROD_HIERARCHY_115, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_115) AS PROD_HIERARCHY_115,
  LISTAGG(PROD_HIERARCHY_116, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_116) AS PROD_HIERARCHY_116,
  LISTAGG(PROD_HIERARCHY_117, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_117) AS PROD_HIERARCHY_117,
  LISTAGG(PROD_HIERARCHY_118, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_118) AS PROD_HIERARCHY_118,
  LISTAGG(PROD_HIERARCHY_119, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_119) AS PROD_HIERARCHY_119,
  LISTAGG(PROD_HIERARCHY_120, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_120) AS PROD_HIERARCHY_120,
  LISTAGG(PROD_HIERARCHY_121, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_121) AS PROD_HIERARCHY_121,
  LISTAGG(PROD_HIERARCHY_122, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_122) AS PROD_HIERARCHY_122,
  LISTAGG(PROD_HIERARCHY_123, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_123) AS PROD_HIERARCHY_123,
  LISTAGG(PROD_HIERARCHY_124, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_124) AS PROD_HIERARCHY_124,
  LISTAGG(PROD_HIERARCHY_125, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_125) AS PROD_HIERARCHY_125,
  LISTAGG(PROD_HIERARCHY_126, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_126) AS PROD_HIERARCHY_126,
  LISTAGG(PROD_HIERARCHY_127, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_127) AS PROD_HIERARCHY_127,
  LISTAGG(PROD_HIERARCHY_128, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_128) AS PROD_HIERARCHY_128,
  LISTAGG(PROD_HIERARCHY_129, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_129) AS PROD_HIERARCHY_129,
  LISTAGG(PROD_HIERARCHY_130, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_130) AS PROD_HIERARCHY_130,
  LISTAGG(PROD_HIERARCHY_131, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_131) AS PROD_HIERARCHY_131,
  LISTAGG(PROD_HIERARCHY_132, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_132) AS PROD_HIERARCHY_132,
  LISTAGG(PROD_HIERARCHY_133, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_133) AS PROD_HIERARCHY_133,
  LISTAGG(PROD_HIERARCHY_134, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_134) AS PROD_HIERARCHY_134,
  LISTAGG(PROD_HIERARCHY_135, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_135) AS PROD_HIERARCHY_135,
  LISTAGG(PROD_HIERARCHY_136, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_136) AS PROD_HIERARCHY_136,
  LISTAGG(PROD_HIERARCHY_137, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_137) AS PROD_HIERARCHY_137,
  LISTAGG(PROD_HIERARCHY_138, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_138) AS PROD_HIERARCHY_138,
  LISTAGG(PROD_HIERARCHY_139, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_139) AS PROD_HIERARCHY_139,
  LISTAGG(PROD_HIERARCHY_140, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_140) AS PROD_HIERARCHY_140,
  LISTAGG(PROD_HIERARCHY_141, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_141) AS PROD_HIERARCHY_141,
  LISTAGG(PROD_HIERARCHY_142, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_142) AS PROD_HIERARCHY_142,
  LISTAGG(PROD_HIERARCHY_143, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_143) AS PROD_HIERARCHY_143,
  LISTAGG(PROD_HIERARCHY_144, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_144) AS PROD_HIERARCHY_144,
  LISTAGG(PROD_HIERARCHY_145, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_145) AS PROD_HIERARCHY_145,
  LISTAGG(PROD_HIERARCHY_146, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_146) AS PROD_HIERARCHY_146,
  LISTAGG(PROD_HIERARCHY_147, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_147) AS PROD_HIERARCHY_147,
  LISTAGG(PROD_HIERARCHY_148, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_148) AS PROD_HIERARCHY_148,
  LISTAGG(PROD_HIERARCHY_149, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_149) AS PROD_HIERARCHY_149,
  LISTAGG(PROD_HIERARCHY_150, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_150) AS PROD_HIERARCHY_150,
  LISTAGG(PROD_HIERARCHY_151, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_151) AS PROD_HIERARCHY_151,
  LISTAGG(PROD_HIERARCHY_152, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_152) AS PROD_HIERARCHY_152,
  LISTAGG(PROD_HIERARCHY_153, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_153) AS PROD_HIERARCHY_153,
  LISTAGG(PROD_HIERARCHY_154, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_154) AS PROD_HIERARCHY_154,
  LISTAGG(PROD_HIERARCHY_155, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_155) AS PROD_HIERARCHY_155,
  LISTAGG(PROD_HIERARCHY_156, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_156) AS PROD_HIERARCHY_156,
  LISTAGG(PROD_HIERARCHY_157, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_157) AS PROD_HIERARCHY_157,
  LISTAGG(PROD_HIERARCHY_158, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_158) AS PROD_HIERARCHY_158,
  LISTAGG(PROD_HIERARCHY_159, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_159) AS PROD_HIERARCHY_159,
  LISTAGG(PROD_HIERARCHY_160, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_160) AS PROD_HIERARCHY_160,
  LISTAGG(PROD_HIERARCHY_161, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_161) AS PROD_HIERARCHY_161,
  LISTAGG(PROD_HIERARCHY_162, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_162) AS PROD_HIERARCHY_162,
  LISTAGG(PROD_HIERARCHY_163, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_163) AS PROD_HIERARCHY_163,
  LISTAGG(PROD_HIERARCHY_164, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_164) AS PROD_HIERARCHY_164,
  LISTAGG(PROD_HIERARCHY_165, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_165) AS PROD_HIERARCHY_165,
  LISTAGG(PROD_HIERARCHY_166, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_166) AS PROD_HIERARCHY_166,
  LISTAGG(PROD_HIERARCHY_167, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_167) AS PROD_HIERARCHY_167,
  LISTAGG(PROD_HIERARCHY_168, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_168) AS PROD_HIERARCHY_168,
  LISTAGG(PROD_HIERARCHY_169, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_169) AS PROD_HIERARCHY_169,
  LISTAGG(PROD_HIERARCHY_170, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_170) AS PROD_HIERARCHY_170,
  LISTAGG(PROD_HIERARCHY_171, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_171) AS PROD_HIERARCHY_171,
  LISTAGG(PROD_HIERARCHY_172, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_172) AS PROD_HIERARCHY_172,
  LISTAGG(PROD_HIERARCHY_173, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_173) AS PROD_HIERARCHY_173,
  LISTAGG(PROD_HIERARCHY_174, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_174) AS PROD_HIERARCHY_174,
  LISTAGG(PROD_HIERARCHY_175, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_175) AS PROD_HIERARCHY_175,
  LISTAGG(PROD_HIERARCHY_176, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_176) AS PROD_HIERARCHY_176,
  LISTAGG(PROD_HIERARCHY_177, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_177) AS PROD_HIERARCHY_177,
  LISTAGG(PROD_HIERARCHY_178, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_178) AS PROD_HIERARCHY_178,
  LISTAGG(PROD_HIERARCHY_179, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_179) AS PROD_HIERARCHY_179,
  LISTAGG(PROD_HIERARCHY_180, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_180) AS PROD_HIERARCHY_180,
  LISTAGG(PROD_HIERARCHY_181, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_181) AS PROD_HIERARCHY_181,
  LISTAGG(PROD_HIERARCHY_182, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_182) AS PROD_HIERARCHY_182,
  LISTAGG(PROD_HIERARCHY_183, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_183) AS PROD_HIERARCHY_183,
  LISTAGG(PROD_HIERARCHY_184, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_184) AS PROD_HIERARCHY_184,
  LISTAGG(PROD_HIERARCHY_185, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_185) AS PROD_HIERARCHY_185,
  LISTAGG(PROD_HIERARCHY_186, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_186) AS PROD_HIERARCHY_186,
  LISTAGG(PROD_HIERARCHY_187, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_187) AS PROD_HIERARCHY_187,
  LISTAGG(PROD_HIERARCHY_188, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_188) AS PROD_HIERARCHY_188,
  LISTAGG(PROD_HIERARCHY_189, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_189) AS PROD_HIERARCHY_189,
  LISTAGG(PROD_HIERARCHY_190, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_190) AS PROD_HIERARCHY_190,
  LISTAGG(PROD_HIERARCHY_191, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_191) AS PROD_HIERARCHY_191,
  LISTAGG(PROD_HIERARCHY_192, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_192) AS PROD_HIERARCHY_192,
  LISTAGG(PROD_HIERARCHY_193, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_193) AS PROD_HIERARCHY_193,
  LISTAGG(PROD_HIERARCHY_194, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_194) AS PROD_HIERARCHY_194,
  LISTAGG(PROD_HIERARCHY_195, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_195) AS PROD_HIERARCHY_195,
  LISTAGG(PROD_HIERARCHY_196, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_196) AS PROD_HIERARCHY_196,
  LISTAGG(PROD_HIERARCHY_197, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_197) AS PROD_HIERARCHY_197,
  LISTAGG(PROD_HIERARCHY_198, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_198) AS PROD_HIERARCHY_198,
  LISTAGG(PROD_HIERARCHY_199, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_199) AS PROD_HIERARCHY_199,
  LISTAGG(PROD_HIERARCHY_200, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_200) AS PROD_HIERARCHY_200,
  LISTAGG(PROD_HIERARCHY_201, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_201) AS PROD_HIERARCHY_201,
  LISTAGG(PROD_HIERARCHY_202, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_202) AS PROD_HIERARCHY_202,
  LISTAGG(PROD_HIERARCHY_203, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_203) AS PROD_HIERARCHY_203,
  LISTAGG(PROD_HIERARCHY_204, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_204) AS PROD_HIERARCHY_204,
  LISTAGG(PROD_HIERARCHY_205, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_205) AS PROD_HIERARCHY_205,
  LISTAGG(PROD_HIERARCHY_206, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_206) AS PROD_HIERARCHY_206,
  LISTAGG(PROD_HIERARCHY_207, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_207) AS PROD_HIERARCHY_207,
  LISTAGG(PROD_HIERARCHY_208, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_208) AS PROD_HIERARCHY_208,
  LISTAGG(PROD_HIERARCHY_209, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_209) AS PROD_HIERARCHY_209,
  LISTAGG(PROD_HIERARCHY_210, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_210) AS PROD_HIERARCHY_210,
  LISTAGG(PROD_HIERARCHY_211, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_211) AS PROD_HIERARCHY_211,
  LISTAGG(PROD_HIERARCHY_212, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_212) AS PROD_HIERARCHY_212,
  LISTAGG(PROD_HIERARCHY_213, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_213) AS PROD_HIERARCHY_213,
  LISTAGG(PROD_HIERARCHY_214, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_214) AS PROD_HIERARCHY_214,
  LISTAGG(PROD_HIERARCHY_215, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_215) AS PROD_HIERARCHY_215,
  LISTAGG(PROD_HIERARCHY_216, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_216) AS PROD_HIERARCHY_216,
  LISTAGG(PROD_HIERARCHY_217, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_217) AS PROD_HIERARCHY_217,
  LISTAGG(PROD_HIERARCHY_218, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_218) AS PROD_HIERARCHY_218,
  LISTAGG(PROD_HIERARCHY_219, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_219) AS PROD_HIERARCHY_219,
  LISTAGG(PROD_HIERARCHY_220, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_220) AS PROD_HIERARCHY_220,
  LISTAGG(PROD_HIERARCHY_221, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_221) AS PROD_HIERARCHY_221,
  LISTAGG(PROD_HIERARCHY_222, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_222) AS PROD_HIERARCHY_222,
  LISTAGG(PROD_HIERARCHY_223, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_223) AS PROD_HIERARCHY_223,
  LISTAGG(PROD_HIERARCHY_224, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_224) AS PROD_HIERARCHY_224,
  LISTAGG(PROD_HIERARCHY_225, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_225) AS PROD_HIERARCHY_225,
  LISTAGG(PROD_HIERARCHY_226, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_226) AS PROD_HIERARCHY_226,
  LISTAGG(PROD_HIERARCHY_227, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_227) AS PROD_HIERARCHY_227,
  LISTAGG(PROD_HIERARCHY_228, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_228) AS PROD_HIERARCHY_228,
  LISTAGG(PROD_HIERARCHY_229, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_229) AS PROD_HIERARCHY_229,
  LISTAGG(PROD_HIERARCHY_230, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_230) AS PROD_HIERARCHY_230,
  LISTAGG(PROD_HIERARCHY_231, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_231) AS PROD_HIERARCHY_231,
  LISTAGG(PROD_HIERARCHY_232, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_232) AS PROD_HIERARCHY_232,
  LISTAGG(PROD_HIERARCHY_233, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_233) AS PROD_HIERARCHY_233,
  LISTAGG(PROD_HIERARCHY_234, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_234) AS PROD_HIERARCHY_234,
  LISTAGG(PROD_HIERARCHY_235, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_235) AS PROD_HIERARCHY_235,
  LISTAGG(PROD_HIERARCHY_236, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_236) AS PROD_HIERARCHY_236,
  LISTAGG(PROD_HIERARCHY_237, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_237) AS PROD_HIERARCHY_237,
  LISTAGG(PROD_HIERARCHY_238, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_238) AS PROD_HIERARCHY_238,
  LISTAGG(PROD_HIERARCHY_239, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_239) AS PROD_HIERARCHY_239,
  LISTAGG(PROD_HIERARCHY_240, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_240) AS PROD_HIERARCHY_240,
  LISTAGG(PROD_HIERARCHY_241, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_241) AS PROD_HIERARCHY_241,
  LISTAGG(PROD_HIERARCHY_242, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_242) AS PROD_HIERARCHY_242,
  LISTAGG(PROD_HIERARCHY_243, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_243) AS PROD_HIERARCHY_243,
  LISTAGG(PROD_HIERARCHY_244, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_244) AS PROD_HIERARCHY_244,
  LISTAGG(PROD_HIERARCHY_245, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_245) AS PROD_HIERARCHY_245,
  LISTAGG(PROD_HIERARCHY_246, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_246) AS PROD_HIERARCHY_246,
  LISTAGG(PROD_HIERARCHY_247, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_247) AS PROD_HIERARCHY_247,
  LISTAGG(PROD_HIERARCHY_248, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_248) AS PROD_HIERARCHY_248,
  LISTAGG(PROD_HIERARCHY_249, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_249) AS PROD_HIERARCHY_249,
  LISTAGG(PROD_HIERARCHY_250, '')WITHIN GROUP (
ORDER BY PROD_HIERARCHY_250) AS PROD_HIERARCHY_250
FROM SALES_DOC_T
GROUP BY SALES_DOC;

DROP TABLE SALES_DOC_TT;
CREATE TABLE SALES_DOC_TT as SELECT * FROM V_SALES_DOC_TT;
SELECT * FROM SALES_DOC_TT;


