-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Project Name : APAFC
-- Version : 1.0
-- Description:
-- Table Init
-- Revision History:
--    Date        Developer         Description
--    ---------   ---------------   ----------------------------------------------------
--    2014-12-24  Moyue           	SO Hst local version.
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
--So hst local version.  
CREATE OR REPLACE PROCEDURE APAFC_SOHST_LC_INIT
IS
LOG_ID VARCHAR2(100);
STEP_NAME VARCHAR2(100);
PROCEDURE_NAME VARCHAR2(100);
PROCEDURE_DETAILS VARCHAR2(1000);
PROCEDURE_BEGINTIME VARCHAR2(1000);
PROCEDURE_RUNNINGTIME VARCHAR2(1000);
SCRIPT_RUNNING_STATUS VARCHAR2(1000);
PROCESS_TERMINATED EXCEPTION;
COUNT_LC NUMBER;
COUNT_DSTRS NUMBER;
COUNT_DSTRQ NUMBER;

BEGIN
	STEP_NAME := 'So hst local version init';
  LOG_ID := APAFC_LOGGING_SEQ.NEXTVAL;
  PROCEDURE_NAME := 'APAFC_SOHST_LC_INIT';
  PROCEDURE_DETAILS := 'Init the "INV_SAP_SALES_HST_LC", "INV_SAP_DSTR_STATS", "INV_SAP_DSTR_QSTATSLIST" tables.';
  PROCEDURE_BEGINTIME := sysdate;
  
  TIME.START_TIMER;
  SELECT COUNT(*) INTO COUNT_LC FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_SALES_HST_LC';
  SELECT COUNT(*) INTO COUNT_DSTRS FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_DSTR_STATS';
  SELECT COUNT(*) INTO COUNT_DSTRQ FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_DSTR_QSTATSLIST';
  
  IF COUNT_LC > 0 THEN
    APAFC_DROP('INV_SAP_SALES_HST_LC','TABLE');
    COMMIT;
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE  INV_SAP_SALES_HST_LC AS SELECT * FROM VIEW_INV_SAP_SALES_HST_LC'); -- SOHST VIEW TO TABLE.
    COMMIT;
  ELSE
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE  INV_SAP_SALES_HST_LC AS SELECT * FROM VIEW_INV_SAP_SALES_HST_LC'); -- SOHST VIEW TO TABLE.
    COMMIT;
  END IF;
  
  IF COUNT_DSTRS > 0 THEN
    APAFC_DROP('INV_SAP_DSTR_STATS','TABLE');
    COMMIT;
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE  INV_SAP_DSTR_STATS AS SELECT * FROM VIEW_INV_SAP_DSTR_STATS'); --Distributor item max usage.
    COMMIT;
  ELSE
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE  INV_SAP_DSTR_STATS AS SELECT * FROM VIEW_INV_SAP_DSTR_STATS'); --Distributor item max usage.
    COMMIT;
  END IF;
  
  IF COUNT_DSTRQ > 0 THEN
    APAFC_DROP('INV_SAP_DSTR_QSTATSLIST','TABLE');
    COMMIT;
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE  INV_SAP_DSTR_QSTATSLIST AS SELECT * FROM VIEW_INV_SAP_DSTR_QSTATSLIST');--Distributor item usage list by quarter.
    COMMIT;
  ELSE
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE  INV_SAP_DSTR_QSTATSLIST AS SELECT * FROM VIEW_INV_SAP_DSTR_QSTATSLIST');--Distributor item usage list by quarter.
    COMMIT;
  END IF;
  
	APAFC_CREATE_INDEX('INDEX_LC_SOHST_MATL','INV_SAP_SALES_HST_LC','MATERIAL');
	APAFC_CREATE_INDEX('INDEX_DSTR_QSLIST_MATL','INV_SAP_DSTR_QSTATSLIST','MATERIAL');
	APAFC_CREATE_INDEX('INDEX_LC_SOHST_SOD','INV_SAP_SALES_HST_LC','SALES_DOC');
	APAFC_CREATE_INDEX('INDEX_LC_SOHST_PLT','INV_SAP_SALES_HST_LC','PLANT');
	APAFC_CREATE_INDEX('INDEX_LC_SOHST_STP','INV_SAP_SALES_HST_LC','SOLD_TO_PARTY');
	APAFC_CREATE_INDEX('INDEX_DSTR_QSLIST_STP','INV_SAP_DSTR_QSTATSLIST','SOLD_TO_NAME');
	APAFC_CREATE_INDEX('INDEX_LC_SOHST_CD','INV_SAP_SALES_HST_LC','CREATION_DATE');
	APAFC_CREATE_INDEX('INDEX_LC_SOHST_LSTGID','INV_SAP_SALES_HST_LC','LAST_GI_DATE');
	COMMIT;
  
  TIMER.SHOW_ELAPSED(PROCEDURE_NAME,PROCEDURE_RUNNINGTIME);
  
EXCEPTION
WHEN OTHERS THEN
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Execute Error:');
  DBMS_OUTPUT.PUT_LINE(SUBSTR(DBMS_UTILITY.FORMAT_ERROR_STACK,1,200)||SUBSTR(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,1,200));
  RAISE PROCESS_TERMINATED;
END APAFC_SOHST_LC_INIT;

----Weekly Update
---Step 1 Download data from the US server.
---Details: SO Hst Data & Ship To Data CLOSED
CREATE OR REPLACE PROCEDURE APAFC_REFH_WKLY_SOHST
IS
  STEP_NAME          VARCHAR2(100);
  PROCESS_TERMINATED EXCEPTION;
  CHK_SOHST NUMBER;
BEGIN
  STEP_NAME := 'Refresh SO Hst Data by weekly. Tue 11:30AM..';
  
  SELECT COUNT(*) INTO CHK_SOHST FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_SALES_HST';
  
  IF CHK_SOHST > 0 THEN
    APAFC_TRUNCATE('INV_SAP_SALES_HST'); -- SOHST
    COMMIT;
      APAFC_SCRIPT_EXE_IMMEDIATE('INSERT INTO INV_SAP_SALES_HST                                  
  SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('||5040||', '||5050||', '||5100||', '||5110||', '||5120||', '||5160||', '||5190||', '||5200||','||5070||','||5140||','||1090||')');
    COMMIT;
  ELSE
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE INV_SAP_SALES_HST AS                                
    SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('||5040||', '||5050||', '||5100||', '||5110||', '||5120||', '||5160||', '||5190||', '||5200||','||5070||','||5140||','||1090||')');
    COMMIT;
  END IF;
  
EXCEPTION
WHEN OTHERS THEN
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Execute Error:');
  DBMS_OUTPUT.PUT_LINE(SUBSTR(DBMS_UTILITY.FORMAT_ERROR_STACK,1,200)||SUBSTR(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,1,200));
  RAISE PROCESS_TERMINATED;
END APAFC_REFH_WKLY_SOHST;

----Ship to& Sold to. Closed
CREATE OR REPLACE PROCEDURE APAFC_REFH_WKLY_SHIPSOLDTO
IS
  STEP_NAME          VARCHAR2(100);
  PROCESS_TERMINATED EXCEPTION;
  INSERT_INV_SS_A  VARCHAR2(1000);
  INSERT_INV_SS_B  VARCHAR2(1000);
  SOLDTO_INIT VARCHAR2(1000);
  CHK_PARTYID NUMBER;
  CHK_SOLDTO NUMBER;
  
BEGIN
  STEP_NAME := 'Refresh ship to and sold to id data..';
  
  SELECT COUNT(*) INTO CHK_PARTYID FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_SHIP_SOLD_TO_PARTYID';
  SELECT COUNT(*) INTO CHK_SOLDTO FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_SHIP_SOLD_TO';
  
  INSERT_INV_SS_A := 'INSERT INTO INV_SAP_SHIP_SOLD_TO 
      SELECT LPAD(SHIP_SOLD_TOPARTY,10,''0''),
      SHIP_TO_PARTY_NAME,
      SHIP_TO_CITY,
      SHIP_TO_POSTAL_CODE,
      SHIP_TO_COUNTRY
    FROM INV_SAP_SHIP_SOLD_TO_PARTYID WHERE SHIP_TO_PARTY_NAME IS NOT NULL';
  INSERT_INV_SS_B := 'INSERT INTO INV_SAP_SHIP_SOLD_TO 
    SELECT 
    LPAD(SHIP_SOLD_TOPARTY,10,''0''),
    SOLD_TO_PARTY_NAME,
    SOLD_TO_CITY,
    SOLD_TO_POSTAL_CODE,
    SOLD_TO_COUNTRY
    FROM INV_SAP_SHIP_SOLD_TO_PARTYID WHERE SHIP_TO_PARTY_NAME IS NULL';
  SOLDTO_INIT := 'CREATE TABLE INV_SAP_SHIP_SOLD_TO
    (
      SHIP_SOLD_TOPARTY       VARCHAR2(2000),
      SHIP_SOLD_TO_PARTY_NAME  VARCHAR2(2000),
      SHIP_SOLD_TO_CITY        VARCHAR2(200),
      SHIP_SOLD_TO_POSTAL_CODE VARCHAR2(200),
      SHIP_SOLD_TO_COUNTRY     VARCHAR2(200)
    )';
    
  IF CHK_PARTYID > 0 THEN
		APAFC_TRUNCATE('INV_SAP_SHIP_SOLD_TO_PARTYID'); -- SOHST
      COMMIT;
        APAFC_SCRIPT_EXE_IMMEDIATE('INSERT INTO INV_SAP_SHIP_SOLD_TO_PARTYID SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SHIP_SOLD_TO_PARTYID@ROCKWELL_DW_DBLINK');
      COMMIT;
  ELSE
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE INV_SAP_SHIP_SOLD_TO_PARTYID AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SHIP_SOLD_TO_PARTYID@ROCKWELL_DW_DBLINK');
    COMMIT;
  END IF;    

  IF CHK_SOLDTO > 0 THEN
      APAFC_TRUNCATE('INV_SAP_SHIP_SOLD_TO'); -- SOHST
      COMMIT;
        APAFC_SCRIPT_EXE_IMMEDIATE(INSERT_INV_SS_A);
        APAFC_SCRIPT_EXE_IMMEDIATE(INSERT_INV_SS_B);
      COMMIT;
  ELSE
      APAFC_SCRIPT_EXE_IMMEDIATE(SOLDTO_INIT);
      COMMIT;
      APAFC_SCRIPT_EXE_IMMEDIATE(INSERT_INV_SS_A);
      APAFC_SCRIPT_EXE_IMMEDIATE(INSERT_INV_SS_B);
      COMMIT;
  END IF;   
  
EXCEPTION
WHEN OTHERS THEN
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Execute Error:');
  DBMS_OUTPUT.PUT_LINE(SUBSTR(DBMS_UTILITY.FORMAT_ERROR_STACK,1,200)||SUBSTR(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,1,200));
  RAISE PROCESS_TERMINATED;
END APAFC_REFH_WKLY_SHIPSOLDTO;

SELECT * FROM INV_SAP_SHIP_SOLD_TO;

---Step 2
CREATE OR REPLACE PROCEDURE APAFC_REFH_WKLY_SOHST_LC
IS
STEP_NAME VARCHAR2(100);
PROCESS_TERMINATED EXCEPTION;

CHK_LS NUMBER;
CHK_DSTRS NUMBER;
CHK_DSTRQ NUMBER;
CHK_SOLNSH NUMBER;

COUNT_IDX_SOHST_MATL NUMBER;
COUNT_IDX_QSLIST_MATL NUMBER;
COUNT_IDX_SOHST_PLT NUMBER;
COUNT_IDX_SOHST_STP NUMBER;
COUNT_IDX_QSLIST_STP NUMBER;
COUNT_IDX_SOHST_CD NUMBER;
COUNT_IDX_SOHST_LSTGID NUMBER;
COUNT_IDX_SOHST_SOD NUMBER;

BEGIN
	STEP_NAME := 'So hst local version';
	SELECT COUNT(*) INTO CHK_LS FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_SALES_HST_LC';
	SELECT COUNT(*) INTO CHK_DSTRS FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_DSTR_STATS';
	SELECT COUNT(*) INTO CHK_DSTRQ FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_DSTR_QSTATSLIST';
	SELECT COUNT(*) INTO CHK_SOLNSH FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_AP_SOLNSH_STAT';
	
	SELECT COUNT(*) INTO COUNT_IDX_SOHST_MATL FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_MATL';
	SELECT COUNT(*) INTO COUNT_IDX_QSLIST_MATL FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_DSTR_QSLIST_MATL';
	SELECT COUNT(*) INTO COUNT_IDX_SOHST_SOD FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_SOD';
	SELECT COUNT(*) INTO COUNT_IDX_SOHST_PLT FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_PLT';
	SELECT COUNT(*) INTO COUNT_IDX_SOHST_STP FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_STP';
	SELECT COUNT(*) INTO COUNT_IDX_QSLIST_STP FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_DSTR_QSLIST_STP';
	SELECT COUNT(*) INTO COUNT_IDX_SOHST_CD FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_CD';
	SELECT COUNT(*) INTO COUNT_IDX_SOHST_LSTGID FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_LSTGID';

  --Remove the Index
  IF COUNT_IDX_SOHST_MATL > 0 THEN
    APAFC_DROP('INDEX_LC_SOHST_MATL','INDEX');
  END IF;
  
  IF COUNT_IDX_QSLIST_MATL > 0 THEN
    APAFC_DROP('INDEX_DSTR_QSLIST_MATL','INDEX');
  END IF;
  
  IF COUNT_IDX_SOHST_SOD > 0 THEN 
    APAFC_DROP('INDEX_LC_SOHST_SOD','INDEX');
  END IF;
  
  IF COUNT_IDX_SOHST_PLT > 0 THEN 
    APAFC_DROP('INDEX_LC_SOHST_PLT','INDEX');
  END IF;

  IF COUNT_IDX_SOHST_STP > 0 THEN 
    APAFC_DROP('INDEX_LC_SOHST_STP','INDEX');
  END IF;
  
  IF COUNT_IDX_QSLIST_STP > 0 THEN 
    APAFC_DROP('INDEX_DSTR_QSLIST_STP','INDEX');
  END IF;
  
  IF COUNT_IDX_SOHST_CD > 0 THEN 
    APAFC_DROP('INDEX_LC_SOHST_CD','INDEX');
  END IF;
  
  IF COUNT_IDX_SOHST_LSTGID > 0 THEN 
    APAFC_DROP('INDEX_LC_SOHST_LSTGID','INDEX');
  END IF;  
  
  COMMIT;
  
  
    IF CHK_LS > 0 THEN
      APAFC_TRUNCATE('INV_SAP_SALES_HST_LC'); -- SOHST
      COMMIT;
      APAFC_INSERT('VIEW_INV_SAP_SALES_HST_LC','INV_SAP_SALES_HST_LC');
      COMMIT;
    ELSE
      APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE INV_SAP_SALES_HST_LC AS SELECT * FROM VIEW_INV_SAP_SALES_HST_LC');
      COMMIT;
    END IF;
  
    IF CHK_DSTRS > 0 THEN
      APAFC_TRUNCATE('INV_SAP_DSTR_STATS'); -- SOHST
       COMMIT;
      APAFC_INSERT('VIEW_INV_SAP_DSTR_STATS','INV_SAP_DSTR_STATS');
      COMMIT;
    ELSE
      APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE INV_SAP_DSTR_STATS AS SELECT * FROM VIEW_INV_SAP_DSTR_STATS');
      COMMIT;
    END IF;
    
    IF CHK_DSTRQ > 0 THEN
      APAFC_TRUNCATE('INV_SAP_DSTR_QSTATSLIST'); -- SOHST
       COMMIT;
      APAFC_INSERT('VIEW_INV_SAP_DSTR_QSTATSLIST','INV_SAP_DSTR_QSTATSLIST');
      COMMIT;
    ELSE
      APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE INV_SAP_DSTR_QSTATSLIST AS SELECT * FROM VIEW_INV_SAP_DSTR_QSTATSLIST');
      COMMIT;
    END IF;
 
    IF CHK_SOLNSH > 0 THEN
      APAFC_TRUNCATE('INV_SAP_AP_SOLNSH_STAT'); -- SOHST
       COMMIT;
      APAFC_INSERT('VIEW_INV_SAP_AP_SOLNSH_STAT','INV_SAP_AP_SOLNSH_STAT');
      COMMIT;
    ELSE
      APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE INV_SAP_AP_SOLNSH_STAT AS SELECT * FROM VIEW_INV_SAP_AP_SOLNSH_STAT');
      COMMIT;
    END IF;
	
  --Build Index
	APAFC_CREATE_INDEX('INDEX_LC_SOHST_MATL','INV_SAP_SALES_HST_LC','MATERIAL');
	APAFC_CREATE_INDEX('INDEX_DSTR_QSLIST_MATL','INV_SAP_DSTR_QSTATSLIST','MATERIAL');
	APAFC_CREATE_INDEX('INDEX_LC_SOHST_SOD','INV_SAP_SALES_HST_LC','SALES_DOC');
	APAFC_CREATE_INDEX('INDEX_LC_SOHST_PLT','INV_SAP_SALES_HST_LC','PLANT');
	APAFC_CREATE_INDEX('INDEX_LC_SOHST_STP','INV_SAP_SALES_HST_LC','SOLD_TO_PARTY');
	APAFC_CREATE_INDEX('INDEX_DSTR_QSLIST_STP','INV_SAP_DSTR_QSTATSLIST','SOLD_TO_NAME');
	APAFC_CREATE_INDEX('INDEX_LC_SOHST_CD','INV_SAP_SALES_HST_LC','CREATION_DATE');
	APAFC_CREATE_INDEX('INDEX_LC_SOHST_LSTGID','INV_SAP_SALES_HST_LC','LAST_GI_DATE');
	COMMIT;
  
EXCEPTION
WHEN OTHERS THEN
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Execute Error:');
  DBMS_OUTPUT.PUT_LINE(SUBSTR(DBMS_UTILITY.FORMAT_ERROR_STACK,1,200)||SUBSTR(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,1,200));
  RAISE PROCESS_TERMINATED;
END APAFC_REFH_WKLY_SOHST_LC;

--Upload the stat data in the inv rep weekly
CREATE OR REPLACE PROCEDURE APAFC_JOB_WKLY_INVREP
IS
STEP_NAME VARCHAR2(100);
BEGIN
STEP_NAME := 'Weekly Job schedule for SO Hst..';
APAFC_SCRIPT_EXE_IMMEDIATE('INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT SYSDATE AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 91) AND TO_CHAR(SYSDATE) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL'); --Distributor item max usage.
COMMIT;
END APAFC_JOB_WKLY_INVREP;

BEGIN
APAFC_JOB_WKLY_INVREP;
END;

--Job Schedule
CREATE OR REPLACE PROCEDURE APAFC_JOB_WKLY_SOHST
IS
STEP_NAME VARCHAR2(100);
BEGIN
STEP_NAME := 'Weekly Job schedule for SO Hst..';
APAFC_REFH_WKLY_SOHST;
APAFC_REFH_WKLY_SHIPSOLDTO;
APAFC_REFH_WKLY_SOHST_LC;
APAFC_JOB_WKLY_INVREP;
END APAFC_JOB_WKLY_SOHST;

BEGIN
APAFC_JOB_WKLY_SOHST;
END;

BEGIN
APAFC_REFH_WKLY_SHIPSOLDTO;
END;

SELECT * FROM INV_SAP_SALES_HST_LC;
SELECT * FROM INV_SAP_DSTR_QSTATSLIST;
SELECT * FROM INV_SAP_DSTR_STATS;
SELECT * FROM INV_SAP_AP_SOLNSH_STAT;
SELECT * FROM INV_SAP_SALES_HST;

DROP TABLE INV_SAP_SALES_HST_LC;
DROP TABLE INV_SAP_DSTR_QSTATSLIST;
DROP TABLE INV_SAP_DSTR_STATS;
DROP TABLE INV_SAP_AP_SOLNSH_STAT;
DROP TABLE INV_SAP_SALES_HST;


DELETE FROM INV_SAP_PP_SO_13WKUSG WHERE REC_DATE_USG > TO_CHAR(SYSDATE - 2);

INSERT INTO INV_SAP_PP_SO_13WKUSG
SELECT SYSDATE - 1 AS REC_DATE_USG,
  ID,
  MATERIAL,
  SUM(ORDER_QTY) AS WK13_USAGE_QTY
FROM INV_SAP_SALES_HST_LC
WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 91) AND TO_CHAR(SYSDATE)
AND OPEN_QTY = 0
GROUP BY ID,
  MATERIAL

