-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Project Name : APAFC
-- Version : 1.0
-- Description:
-- Table Init
-- Revision History:
--    Date        Developer         Description
--    ---------   ---------------   ----------------------------------------------------
--    2014-12-24  Moyue           	Mfg So hst.
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
--MFG SO HST DATA FROM THE US SERVER.   
CREATE OR REPLACE PROCEDURE APAFC_SAP_MFG_SOHST
IS
STEP_NAME VARCHAR2(100);
PROCESS_TERMINATED EXCEPTION;
PP_R7B_INIT VARCHAR2(2000); --MFG DATA WAREHOUSE SO DATA 5120,5190,5200,5160. 
PP_R8_INIT VARCHAR2(2000); --MFG DATA WAREHOUSE SO DATA 5040,5050,5110,5100.
PP_R9_INIT VARCHAR2(2000); --MFG DATA WAREHOUSE SO DATA 5070,5140.

BEGIN
	STEP_NAME := 'MFG SO HST DATA FROM THE US SERVER';
	PP_R7B_INIT := 'CREATE TABLE INV_SAP_R7B_SALES_SEA_HST AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_R7B_SALES_SEA_HST@ROCKWELL_DW_DBLINK';
	PP_R8_INIT := 'CREATE TABLE INV_SAP_R8_SALES_DC_HST AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_R8_SALES_DC_HST@ROCKWELL_DW_DBLINK';
	PP_R9_INIT := 'CREATE TABLE INV_SAP_R9_SALES_DC_HST AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_R9_SALES_DC_HST@ROCKWELL_DW_DBLINK';
	
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_R7B_INIT);
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_R8_INIT);
	APAFC_SCRIPT_EXE_IMMEDIATE(PP_R9_INIT);
	COMMIT;
  --MaterialId
	APAFC_CREATE_INDEX('INDEX_R7B_SOHST_MATLID','INV_SAP_R7B_SALES_SEA_HST','MATERIALID');
	APAFC_CREATE_INDEX('INDEX_R8_SOHST_MATLID','INV_SAP_R8_SALES_DC_HST','MATERIALID');
  APAFC_CREATE_INDEX('INDEX_R9_SOHST_MATLID','INV_SAP_R9_SALES_DC_HST','MATERIALID');
  COMMIT;
  --So number
  APAFC_CREATE_INDEX('INDEX_R7B_SOHST_SO','INV_SAP_R7B_SALES_SEA_HST','SALESDOC');
	APAFC_CREATE_INDEX('INDEX_R8_SOHST_SO','INV_SAP_R8_SALES_DC_HST','SALESDOC');
  APAFC_CREATE_INDEX('INDEX_R9_SOHST_SO','INV_SAP_R9_SALES_DC_HST','SALESDOC');
  COMMIT;
  --PLANTID
  APAFC_CREATE_INDEX('INDEX_R7B_SOHST_PLT','INV_SAP_R7B_SALES_SEA_HST','PLANTID');
	APAFC_CREATE_INDEX('INDEX_R8_SOHST_PLT','INV_SAP_R8_SALES_DC_HST','PLANTID');
  APAFC_CREATE_INDEX('INDEX_R9_SOHST_PLT','INV_SAP_R9_SALES_DC_HST','PLANTID');  
  COMMIT;
  --SOLDTOPARTY
  APAFC_CREATE_INDEX('INDEX_R7B_SOHST_STP','INV_SAP_R7B_SALES_SEA_HST','SOLDTOPARTY');
	APAFC_CREATE_INDEX('INDEX_R8_SOHST_STP','INV_SAP_R8_SALES_DC_HST','SOLDTOPARTY');
  APAFC_CREATE_INDEX('INDEX_R9_SOHST_STP','INV_SAP_R9_SALES_DC_HST','SOLDTOPARTY'); 
  COMMIT;
EXCEPTION
WHEN OTHERS THEN
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Execute Error:');
  DBMS_OUTPUT.PUT_LINE(SUBSTR(DBMS_UTILITY.FORMAT_ERROR_STACK,1,200)||SUBSTR(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,1,200));
  RAISE PROCESS_TERMINATED;
END APAFC_SAP_MFG_SOHST;


--TEST
BEGIN
  APAFC_SAP_MFG_SOHST;
END;


		
		

