-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Project Name : APAFC
-- Version : 1.0
-- Description:
-- Table Init
-- Revision History:
--    Date        Developer         Description
--    ---------   ---------------   ----------------------------------------------------
--    2015-11-17    Moyue           	Stock Out Comments Rep
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
SELECT * FROM INV_SAP_STKOUT_COMMENTS_T;
DROP TABLE INV_SAP_STKOUT_COMMENTS_BK;
CREATE TABLE INV_SAP_STKOUT_COMMENTS_BK AS
SELECT COUNT(*) FROM INV_SAP_STKOUT_COMMENTS;

SELECT COUNT(*) FROM (
SELECT DISTINCT ID, COMMENTS, PLANNER, TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK FROM INV_SAP_STKOUT_COMMENTS_BK)

SELECT COUNT(*) FROM INV_SAP_STKOUT_COMMENTS_BK;

SELECT COUNT(*) FROM (SELECT DISTINCT * FROM INV_SAP_STKOUT_COMMENTS_BK)

---Rep
--Comments
TRUNCATE TABLE INV_SAP_STKOUT_COMMENTS_TMP;

--Insert Comments
INSERT
INTO INV_SAP_STKOUT_COMMENTS_TMP
  (
    ID,
    IDD,
    COMMENTS,
    PLANNER,
    LAST_UPDATE_DATE
  )
  VALUES
  (
    'ID_1',
    'IDHQ_DAHQ',
    'COMMENTS_1',
    'PLANNER_1',
    SYSDATE_2
  );

--Merge
MERGE INTO INV_SAP_STKOUT_COMMENTS SVD_COM USING
(SELECT IDD,
  ID,
  COMMENTS,
  PLANNER,
  LAST_UPDATE_DATE
FROM INV_SAP_STKOUT_COMMENTS_TMP
) TMP ON (SVD_COM.IDD=TMP.IDD)
WHEN MATCHED THEN
  UPDATE
  SET SVD_COM.COMMENTS       = TMP.COMMENTS,
    SVD_COM.PLANNER          = TMP.PLANNER,
    SVD_COM.LAST_UPDATE_DATE = TMP.LAST_UPDATE_DATE WHEN NOT MATCHED THEN
  INSERT VALUES
    (
      TMP.IDD,
      TMP.ID,
      TMP.COMMENTS,
      TMP.PLANNER,
      TMP.LAST_UPDATE_DATE
    );

--Delete    
delete from INV_SAP_STKOUT_COMMENTS where IDD = 'IDHQ_DAHQ';

--Monthly Stock Out Comments Status
SELECT 
  DISTINCT
  STOCKOUT.UPDATE_WK, 
  STOCKOUT.ID,
  STOCKOUT.PLANT,
  STOCKOUT.MATERIAL,
  STOCKOUT.MRP_CONTROLLER,
  STOCKOUT.MON,
  STOCKOUT.TUE,
  STOCKOUT.WED,
  STOCKOUT.THU,
  STOCKOUT.FRI,
  COMT.PLANNER, COMT.COMMENTS
FROM
  (SELECT TO_CHAR(UPLOADDATE,'iw') AS UPDATE_WK,
    ID,
    PLANT,
    MATERIAL,
    MRP_CONTROLLER,
    MON,
    TUE,
    WED,
    THU,
    FRI
  FROM INV_SAP_STOCK_OUT_REPSTORE WHERE UPLOADDATE BETWEEN trunc(add_months(sysdate,-1),'mm') AND last_day(add_months(sysdate,-1))
  )STOCKOUT
LEFT JOIN
  (SELECT ID, COMMENTS, PLANNER, TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK FROM INV_SAP_STKOUT_COMMENTS
  )COMT
ON COMT.ID = STOCKOUT.ID AND COMT.CM_UPDATE_WK = STOCKOUT.UPDATE_WK;


--Weekly Align
SELECT 
  DISTINCT
  MM_ID_OTTF.ID,
  MM_ID_OTTF.PLANNER,
  MM_ID_OTTF.WK_ONE_COMMENTS,
  MM_ID_OTTF.WK_TWO_COMMENTS,
  MM_ID_OTTF.WK_THREE_COMMENTS,
  MM_ID_OTTF.WK_FOUR_COMMENTS,
  WK_FIVE.COMMENTS AS WK_FIVE_COMMENTS
FROM
  (SELECT MM_ID_OTT.ID,
    MM_ID_OTT.PLANNER,
    MM_ID_OTT.WK_ONE_COMMENTS,
    MM_ID_OTT.WK_TWO_COMMENTS,
    MM_ID_OTT.WK_THREE_COMMENTS,
    WK_FOUR.COMMENTS AS WK_FOUR_COMMENTS
  FROM
    (SELECT MM_ID_OT.ID,
      MM_ID_OT.PLANNER,
      MM_ID_OT.WK_ONE_COMMENTS,
      MM_ID_OT.WK_TWO_COMMENTS,
      WK_THREE.COMMENTS AS WK_THREE_COMMENTS
    FROM
      (SELECT MM_ID_ONE.ID,
        MM_ID_ONE.PLANNER,
        MM_ID_ONE.WK_ONE_COMMENTS,
        WK_TWO.COMMENTS AS WK_TWO_COMMENTS
      FROM
        (SELECT MM_ID.ID,
          MM_ID.PLANNER,
          WK_ONE.COMMENTS AS WK_ONE_COMMENTS
        FROM
          (SELECT ID,
            PLANNER
          FROM INV_SAP_STKOUT_COMMENTS
          WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND TO_CHAR(SYSDATE)
          )MM_ID
        LEFT JOIN
          (SELECT ID,
            COMMENTS,
            CM_UPDATE_WK
          FROM
            (SELECT ID,
              COMMENTS,
              TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
            FROM INV_SAP_STKOUT_COMMENTS
            WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND TO_CHAR(SYSDATE)
            )
          WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw')
          )WK_ONE
        ON WK_ONE.ID = MM_ID.ID
        )MM_ID_ONE
      LEFT JOIN
        (SELECT ID,
          COMMENTS
        FROM
          (SELECT ID,
            COMMENTS,
            TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
          FROM INV_SAP_STKOUT_COMMENTS
          WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND TO_CHAR(SYSDATE)
          )
        WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw') + 1
        )WK_TWO
      ON MM_ID_ONE.ID = WK_TWO.ID
      )MM_ID_OT
    LEFT JOIN
      (SELECT ID,
        COMMENTS
      FROM
        (SELECT ID,
          COMMENTS,
          TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
        FROM INV_SAP_STKOUT_COMMENTS
        WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND TO_CHAR(SYSDATE)
        )
      WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw') + 2
      )WK_THREE
    ON MM_ID_OT.ID = WK_THREE.ID
    )MM_ID_OTT
  LEFT JOIN
    (SELECT ID,
      COMMENTS
    FROM
      (SELECT ID,
        COMMENTS,
        TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
      FROM INV_SAP_STKOUT_COMMENTS
      WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND TO_CHAR(SYSDATE)
      )
    WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw') + 3
    )WK_FOUR
  ON MM_ID_OTT.ID = WK_FOUR.ID
  )MM_ID_OTTF
LEFT JOIN
  (SELECT ID,
    COMMENTS
  FROM
    (SELECT ID,
      COMMENTS,
      TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND TO_CHAR(SYSDATE)
    )
  WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw') + 4
  )WK_FIVE
ON MM_ID_OTTF.ID = WK_FIVE.ID;





