-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Project Name : APAFC
-- Version : 1.0
-- Description:
-- Table Init
-- Revision History:
--    Date        Developer         Description
--    ---------   ---------------   ----------------------------------------------------
--    2014-12-24  Moyue           	SCHEDULE RETURN SG CHECK.
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------

--SG CHECK VIEW
 CREATE OR REPLACE FORCE VIEW "SYSTEM"."VIEW_INV_SAP_SGC_5040" ("ID", "MATERIAL", "SG_CHECK") AS 
  SELECT DISTINCT BS.ID AS ID,
  BS.MATERIAL         AS MATERIAL,
  CASE
    WHEN SG_CHECK.STRATEGY_GRP_CHECK IS NULL
    THEN 'NO'
    ELSE 'YES'
  END SG_CHECK
FROM
  (SELECT ID,
    MATERIAL
  FROM INV_SAP_PP_OPT_X
  WHERE PLANT       = '5040'
  )BS
LEFT JOIN
  (SELECT ID,
    CASE
      WHEN STRATEGY_GRP = '40'
      THEN 'YES'
      ELSE 'NO'
    END STRATEGY_GRP_CHECK,
    MATERIAL
  FROM
    (SELECT ID,
      PLANT,
      STRATEGY_GRP,
      MATERIAL
    FROM INV_SAP_PP_OPT_X
    WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
    )
  WHERE PLANT NOT IN '5040'
  AND STRATEGY_GRP = '40'
  )SG_CHECK
ON BS.MATERIAL = SG_CHECK.MATERIAL;


  CREATE OR REPLACE FORCE VIEW "SYSTEM"."VIEW_INV_SAP_SGC_5050" ("ID", "MATERIAL", "SG_CHECK") AS 
  SELECT DISTINCT BS.ID AS ID,
  BS.MATERIAL         AS MATERIAL,
  CASE
    WHEN SG_CHECK.STRATEGY_GRP_CHECK IS NULL
    THEN 'NO'
    ELSE 'YES'
  END SG_CHECK
FROM
  (SELECT ID,
    MATERIAL
  FROM INV_SAP_PP_OPT_X
  WHERE PLANT       = '5050'
  )BS
LEFT JOIN
  (SELECT ID,
    CASE
      WHEN STRATEGY_GRP = '40'
      THEN 'YES'
      ELSE 'NO'
    END STRATEGY_GRP_CHECK,
    MATERIAL
  FROM
    (SELECT ID,
      PLANT,
      STRATEGY_GRP,
      MATERIAL
    FROM INV_SAP_PP_OPT_X
    WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
    )
  WHERE PLANT NOT IN '5050'
  AND STRATEGY_GRP = '40'
  )SG_CHECK
ON BS.MATERIAL = SG_CHECK.MATERIAL;



  CREATE OR REPLACE FORCE VIEW "SYSTEM"."VIEW_INV_SAP_SGC_5070" ("ID", "MATERIAL", "SG_CHECK") AS 
  SELECT DISTINCT BS.ID AS ID,
  BS.MATERIAL         AS MATERIAL,
  CASE
    WHEN SG_CHECK.STRATEGY_GRP_CHECK IS NULL
    THEN 'NO'
    ELSE 'YES'
  END SG_CHECK
FROM
  (SELECT ID,
    MATERIAL
  FROM INV_SAP_PP_OPT_X
  WHERE PLANT       = '5070'
  )BS
LEFT JOIN
  (SELECT ID,
    CASE
      WHEN STRATEGY_GRP = '40'
      THEN 'YES'
      ELSE 'NO'
    END STRATEGY_GRP_CHECK,
    MATERIAL
  FROM
    (SELECT ID,
      PLANT,
      STRATEGY_GRP,
      MATERIAL
    FROM INV_SAP_PP_OPT_X
    WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
    )
  WHERE PLANT NOT IN '5070'
  AND STRATEGY_GRP = '40'
  )SG_CHECK
ON BS.MATERIAL = SG_CHECK.MATERIAL;


  CREATE OR REPLACE FORCE VIEW "SYSTEM"."VIEW_INV_SAP_SGC_5100" ("ID", "MATERIAL", "SG_CHECK") AS 
  SELECT DISTINCT BS.ID AS ID,
  BS.MATERIAL         AS MATERIAL,
  CASE
    WHEN SG_CHECK.STRATEGY_GRP_CHECK IS NULL
    THEN 'NO'
    ELSE 'YES'
  END SG_CHECK
FROM
  (SELECT ID,
    MATERIAL
  FROM INV_SAP_PP_OPT_X
  WHERE PLANT       = '5100'
  )BS
LEFT JOIN
  (SELECT ID,
    CASE
      WHEN STRATEGY_GRP = '40'
      THEN 'YES'
      ELSE 'NO'
    END STRATEGY_GRP_CHECK,
    MATERIAL
  FROM
    (SELECT ID,
      PLANT,
      STRATEGY_GRP,
      MATERIAL
    FROM INV_SAP_PP_OPT_X
    WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
    )
  WHERE PLANT NOT IN '5100'
  AND STRATEGY_GRP = '40'
  )SG_CHECK
ON BS.MATERIAL = SG_CHECK.MATERIAL;


  CREATE OR REPLACE FORCE VIEW "SYSTEM"."VIEW_INV_SAP_SGC_5110" ("ID", "MATERIAL", "SG_CHECK") AS 
  SELECT DISTINCT BS.ID AS ID,
  BS.MATERIAL         AS MATERIAL,
  CASE
    WHEN SG_CHECK.STRATEGY_GRP_CHECK IS NULL
    THEN 'NO'
    ELSE 'YES'
  END SG_CHECK
FROM
  (SELECT ID,
    MATERIAL
  FROM INV_SAP_PP_OPT_X
  WHERE PLANT       = '5110'
  )BS
LEFT JOIN
  (SELECT ID,
    CASE
      WHEN STRATEGY_GRP = '40'
      THEN 'YES'
      ELSE 'NO'
    END STRATEGY_GRP_CHECK,
    MATERIAL
  FROM
    (SELECT ID,
      PLANT,
      STRATEGY_GRP,
      MATERIAL
    FROM INV_SAP_PP_OPT_X
    WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
    )
  WHERE PLANT NOT IN '5110'
  AND STRATEGY_GRP = '40'
  )SG_CHECK
ON BS.MATERIAL = SG_CHECK.MATERIAL;
 
 
   CREATE OR REPLACE FORCE VIEW "SYSTEM"."VIEW_INV_SAP_SGC_5120" ("ID", "MATERIAL", "SG_CHECK") AS 
  SELECT DISTINCT BS.ID AS ID,
  BS.MATERIAL         AS MATERIAL,
  CASE
    WHEN SG_CHECK.STRATEGY_GRP_CHECK IS NULL
    THEN 'NO'
    ELSE 'YES'
  END SG_CHECK
FROM
  (SELECT ID,
    MATERIAL
  FROM INV_SAP_PP_OPT_X
  WHERE PLANT       = '5120'
  )BS
LEFT JOIN
  (SELECT ID,
    CASE
      WHEN STRATEGY_GRP = '40'
      THEN 'YES'
      ELSE 'NO'
    END STRATEGY_GRP_CHECK,
    MATERIAL
  FROM
    (SELECT ID,
      PLANT,
      STRATEGY_GRP,
      MATERIAL
    FROM INV_SAP_PP_OPT_X
    WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
    )
  WHERE PLANT NOT IN '5120'
  AND STRATEGY_GRP = '40'
  )SG_CHECK
ON BS.MATERIAL = SG_CHECK.MATERIAL;


  CREATE OR REPLACE FORCE VIEW "SYSTEM"."VIEW_INV_SAP_SGC_5140" ("ID", "MATERIAL", "SG_CHECK") AS 
  SELECT DISTINCT BS.ID AS ID,
  BS.MATERIAL         AS MATERIAL,
  CASE
    WHEN SG_CHECK.STRATEGY_GRP_CHECK IS NULL
    THEN 'NO'
    ELSE 'YES'
  END SG_CHECK
FROM
  (SELECT ID,
    MATERIAL
  FROM INV_SAP_PP_OPT_X
  WHERE PLANT       = '5140'
  )BS
LEFT JOIN
  (SELECT ID,
    CASE
      WHEN STRATEGY_GRP = '40'
      THEN 'YES'
      ELSE 'NO'
    END STRATEGY_GRP_CHECK,
    MATERIAL
  FROM
    (SELECT ID,
      PLANT,
      STRATEGY_GRP,
      MATERIAL
    FROM INV_SAP_PP_OPT_X
    WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
    )
  WHERE PLANT NOT IN '5140'
  AND STRATEGY_GRP = '40'
  )SG_CHECK
ON BS.MATERIAL = SG_CHECK.MATERIAL;

  CREATE OR REPLACE FORCE VIEW "SYSTEM"."VIEW_INV_SAP_SGC_5160" ("ID", "MATERIAL", "SG_CHECK") AS 
  SELECT DISTINCT BS.ID AS ID,
  BS.MATERIAL         AS MATERIAL,
  CASE
    WHEN SG_CHECK.STRATEGY_GRP_CHECK IS NULL
    THEN 'NO'
    ELSE 'YES'
  END SG_CHECK
FROM
  (SELECT ID,
    MATERIAL
  FROM INV_SAP_PP_OPT_X
  WHERE PLANT       = '5160'
  )BS
LEFT JOIN
  (SELECT ID,
    CASE
      WHEN STRATEGY_GRP = '40'
      THEN 'YES'
      ELSE 'NO'
    END STRATEGY_GRP_CHECK,
    MATERIAL
  FROM
    (SELECT ID,
      PLANT,
      STRATEGY_GRP,
      MATERIAL
    FROM INV_SAP_PP_OPT_X
    WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
    )
  WHERE PLANT NOT IN '5160'
  AND STRATEGY_GRP = '40'
  )SG_CHECK
ON BS.MATERIAL = SG_CHECK.MATERIAL;

  CREATE OR REPLACE FORCE VIEW "SYSTEM"."VIEW_INV_SAP_SGC_5190" ("ID", "MATERIAL", "SG_CHECK") AS 
  SELECT DISTINCT BS.ID AS ID,
  BS.MATERIAL         AS MATERIAL,
  CASE
    WHEN SG_CHECK.STRATEGY_GRP_CHECK IS NULL
    THEN 'NO'
    ELSE 'YES'
  END SG_CHECK
FROM
  (SELECT ID,
    MATERIAL
  FROM INV_SAP_PP_OPT_X
  WHERE PLANT       = '5190'
  )BS
LEFT JOIN
  (SELECT ID,
    CASE
      WHEN STRATEGY_GRP = '40'
      THEN 'YES'
      ELSE 'NO'
    END STRATEGY_GRP_CHECK,
    MATERIAL
  FROM
    (SELECT ID,
      PLANT,
      STRATEGY_GRP,
      MATERIAL
    FROM INV_SAP_PP_OPT_X
    WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
    )
  WHERE PLANT NOT IN '5190'
  AND STRATEGY_GRP = '40'
  )SG_CHECK
ON BS.MATERIAL = SG_CHECK.MATERIAL;

  CREATE OR REPLACE FORCE VIEW "SYSTEM"."VIEW_INV_SAP_SGC_5200" ("ID", "MATERIAL", "SG_CHECK") AS 
  SELECT DISTINCT BS.ID AS ID,
  BS.MATERIAL         AS MATERIAL,
  CASE
    WHEN SG_CHECK.STRATEGY_GRP_CHECK IS NULL
    THEN 'NO'
    ELSE 'YES'
  END SG_CHECK
FROM
  (SELECT ID,
    MATERIAL
  FROM INV_SAP_PP_OPT_X
  WHERE PLANT       = '5200'
  )BS
LEFT JOIN
  (SELECT ID,
    CASE
      WHEN STRATEGY_GRP = '40'
      THEN 'YES'
      ELSE 'NO'
    END STRATEGY_GRP_CHECK,
    MATERIAL
  FROM
    (SELECT ID,
      PLANT,
      STRATEGY_GRP,
      MATERIAL
    FROM INV_SAP_PP_OPT_X
    WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
    )
  WHERE PLANT NOT IN '5200'
  AND STRATEGY_GRP = '40'
  )SG_CHECK
ON BS.MATERIAL = SG_CHECK.MATERIAL;

