 -----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Description:
--
--  This file just use for spike order analysis
--
-- Revision History:
--
--    Date        Developer         Description
--    ---------   ---------------   ----------------------------------------------------
--    2014-12-24  Moyue           	Spike order analysis
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------

--Upload data from historical demand 21 days

SELECT COUNT(*) FROM INV_SAP_HSTDE_DS;
SELECT * FROM INV_SAP_HSTDE_DS where material = 'PN-145756';
DROP TABLE INV_SAP_HSTDE_DS;
CREATE TABLE INV_SAP_HSTDE_DS 
(
  ASOFDATE DATE 
, TYPE VARCHAR2(200) 
, MATERIAL VARCHAR2(200) 
, PLANT VARCHAR2(200) 
, UNIT VARCHAR2(20) 
, MONTH_1 NUMBER 
, MONTH_2 NUMBER 
, MONTH_3 NUMBER 
, MONTH_4 NUMBER 
, MONTH_5 NUMBER 
, MONTH_6 NUMBER 
, MONTH_7 NUMBER 
, MONTH_8 NUMBER 
, MONTH_9 NUMBER 
, MONTH_10 NUMBER 
, MONTH_11 NUMBER 
, MONTH_12 NUMBER 
, MONTH_13 NUMBER 
, MONTH_14 NUMBER 
, MONTH_15 NUMBER 
, MONTH_16 NUMBER 
, MONTH_17 NUMBER 
, MONTH_18 NUMBER 
, MONTH_19 NUMBER 
, MONTH_20 NUMBER 
, MONTH_21 NUMBER 
, MONTH_22 NUMBER 
, MONTH_23 NUMBER 
, MONTH_24 NUMBER 
, MONTH_25 NUMBER 
, MONTH_26 NUMBER 
, MONTH_27 NUMBER 
, MONTH_28 NUMBER 
, MONTH_29 NUMBER
, MONTH_30 NUMBER 
, MONTH_31 NUMBER 
, MONTH_32 NUMBER 
, MONTH_33 NUMBER 
, MONTH_34 NUMBER 
, MONTH_35 NUMBER 
, MONTH_36 NUMBER 
, MONTH_37 NUMBER 
, MONTH_38 NUMBER 
, MONTH_39 NUMBER
, MONTH_40 NUMBER 
, MONTH_41 NUMBER 
, MONTH_42 NUMBER 
, MONTH_43 NUMBER 
, MONTH_44 NUMBER 
, MONTH_45 NUMBER 
, MONTH_46 NUMBER 
, MONTH_47 NUMBER 
, MONTH_48 NUMBER 
, MONTH_49 NUMBER
, MONTH_50 NUMBER 
, MONTH_51 NUMBER 
, MONTH_52 NUMBER 
, MONTH_53 NUMBER 
, MONTH_54 NUMBER 
);


--Spike order report
DROP TABLE INV_SAP_SPIKE_ANALYSIS;
CREATE TABLE INV_SAP_SPIKE_ANALYSIS AS SELECT * FROM VIEW_INV_SAP_SPIKE_ANALYSIS;
DROP VIEW VIEW_INV_SAP_SPIKE_ANALYSIS;
SELECT * FROM INV_SAP_SPIKE_ANALYSIS;
SELECT * FROM VIEW_INV_SAP_SPIKE_ANALYSIS where PROD_LINE = 'SFSA0483A189';
CREATE VIEW VIEW_INV_SAP_SPIKE_ANALYSIS AS
SELECT DMT_PP_BS.ID,
  DMT_PP_BS.TYPE,
  DMT_PP_BS.MATERIAL,
  DMT_PP_BS.PLANT,
  DMT_PP_BS.CATALOG_DASH,
  DMT_PP_BS.BULLETIN,
  DMT_PP_BS.MAT_DESC,
  DMT_PP_BS.SAFETY_STOCK,
  DMT_PP_BS.PROD_BU,
  DMT_PP_BS.PROD_FAM,
  DMT_PP_BS.PROD_HIERARCHY,
  DMT_PP_BS.PROD_LINE,
  PRO_DES.PRO_LINE_DES,
  DMT_PP_BS.PROC_TYPE,
  DMT_PP_BS.STRATEGY_GRP,
  DMT_PP_BS.MATL_TYPE,
  DMT_PP_BS.VENDOR_KEY,
  DMT_PP_BS.UNIT,
  DMT_PP_BS.MONTH_1,
  DMT_PP_BS.MONTH_2,
  DMT_PP_BS.MONTH_3,
  DMT_PP_BS.MONTH_4,
  DMT_PP_BS.MONTH_5,
  DMT_PP_BS.MONTH_6,
  DMT_PP_BS.MONTH_7,
  DMT_PP_BS.MONTH_8,
  DMT_PP_BS.MONTH_9,
  DMT_PP_BS.MONTH_10,
  DMT_PP_BS.MONTH_11,
  DMT_PP_BS.MONTH_12,
  DMT_PP_BS.MONTH_13,
  DMT_PP_BS.MONTH_14,
  DMT_PP_BS.MONTH_15,
  DMT_PP_BS.MONTH_16,
  DMT_PP_BS.MONTH_17,
  DMT_PP_BS.MONTH_18,
  DMT_PP_BS.MONTH_19,
  DMT_PP_BS.MONTH_20,
  DMT_PP_BS.MONTH_21,
  DMT_PP_BS.MONTH_22,
  DMT_PP_BS.MONTH_23,
  DMT_PP_BS.MONTH_24,
  DMT_PP_BS.MONTH_25,
  DMT_PP_BS.MONTH_26,
  DMT_PP_BS.MONTH_27,
  DMT_PP_BS.MONTH_28,
  DMT_PP_BS.MONTH_29,
  DMT_PP_BS.MONTH_30,
  DMT_PP_BS.MONTH_31,
  DMT_PP_BS.MONTH_32,
  DMT_PP_BS.MONTH_33,
  DMT_PP_BS.MONTH_34,
  DMT_PP_BS.MONTH_35,
  DMT_PP_BS.MONTH_36,
  DMT_PP_BS.MONTH_37,
  DMT_PP_BS.MONTH_38,
  DMT_PP_BS.MONTH_39,
  DMT_PP_BS.MONTH_40,
  DMT_PP_BS.MONTH_41,
  DMT_PP_BS.MONTH_42,
  DMT_PP_BS.MONTH_43,
  DMT_PP_BS.MONTH_44,
  DMT_PP_BS.MONTH_45,
  DMT_PP_BS.MONTH_46,
  DMT_PP_BS.MONTH_47,
  DMT_PP_BS.MONTH_48,
  DMT_PP_BS.MONTH_49,
  DMT_PP_BS.MONTH_50,
  DMT_PP_BS.MONTH_51,
  DMT_PP_BS.MONTH_52,
  DMT_PP_BS.MONTH_53,
  DMT_PP_BS.MONTH_54
FROM
  (SELECT DMT_PRD.ID,
    DMT_PRD.TYPE,
    DMT_PRD.MATERIAL,
    DMT_PRD.PLANT,
    PP_BASIC.CATALOG_DASH,
    SUBSTR(PP_BASIC.CATALOG_DASH,0,4) AS BULLETIN,
    PP_BASIC.MAT_DESC,
    PP_BASIC.SAFETY_STOCK,
    PP_BASIC.PROD_BU,
    PP_BASIC.PROD_FAM,
    PP_BASIC.PROD_HIERARCHY,
    SUBSTR(PP_BASIC.PROD_HIERARCHY,0,12) AS PROD_LINE,
    PP_BASIC.PROC_TYPE,
    PP_BASIC.STRATEGY_GRP,
    PP_BASIC.MATL_TYPE,
    PP_BASIC.VENDOR_KEY,
    DMT_PRD.UNIT,
    DMT_PRD.MONTH_1,
    DMT_PRD.MONTH_2,
    DMT_PRD.MONTH_3,
    DMT_PRD.MONTH_4,
    DMT_PRD.MONTH_5,
    DMT_PRD.MONTH_6,
    DMT_PRD.MONTH_7,
    DMT_PRD.MONTH_8,
    DMT_PRD.MONTH_9,
    DMT_PRD.MONTH_10,
    DMT_PRD.MONTH_11,
    DMT_PRD.MONTH_12,
    DMT_PRD.MONTH_13,
    DMT_PRD.MONTH_14,
    DMT_PRD.MONTH_15,
    DMT_PRD.MONTH_16,
    DMT_PRD.MONTH_17,
    DMT_PRD.MONTH_18,
    DMT_PRD.MONTH_19,
    DMT_PRD.MONTH_20,
    DMT_PRD.MONTH_21,
    DMT_PRD.MONTH_22,
    DMT_PRD.MONTH_23,
    DMT_PRD.MONTH_24,
    DMT_PRD.MONTH_25,
    DMT_PRD.MONTH_26,
    DMT_PRD.MONTH_27,
    DMT_PRD.MONTH_28,
    DMT_PRD.MONTH_29,
    DMT_PRD.MONTH_30,
    DMT_PRD.MONTH_31,
    DMT_PRD.MONTH_32,
    DMT_PRD.MONTH_33,
    DMT_PRD.MONTH_34,
    DMT_PRD.MONTH_35,
    DMT_PRD.MONTH_36,
    DMT_PRD.MONTH_37,
    DMT_PRD.MONTH_38,
    DMT_PRD.MONTH_39,
    DMT_PRD.MONTH_40,
    DMT_PRD.MONTH_41,
    DMT_PRD.MONTH_42,
    DMT_PRD.MONTH_43,
    DMT_PRD.MONTH_44,
    DMT_PRD.MONTH_45,
    DMT_PRD.MONTH_46,
    DMT_PRD.MONTH_47,
    DMT_PRD.MONTH_48,
    DMT_PRD.MONTH_49,
    DMT_PRD.MONTH_50,
    DMT_PRD.MONTH_51,
    DMT_PRD.MONTH_52,
    DMT_PRD.MONTH_53,
    DMT_PRD.MONTH_54
  FROM
    (SELECT MATERIAL
      ||'_'
      ||PLANT AS ID,
      TYPE,
      MATERIAL,
      PLANT,
      UNIT,
      MONTH_1,
      MONTH_2,
      MONTH_3,
      MONTH_4,
      MONTH_5,
      MONTH_6,
      MONTH_7,
      MONTH_8,
      MONTH_9,
      MONTH_10,
      MONTH_11,
      MONTH_12,
      MONTH_13,
      MONTH_14,
      MONTH_15,
      MONTH_16,
      MONTH_17,
      MONTH_18,
      MONTH_19,
      MONTH_20,
      MONTH_21,
      MONTH_22,
      MONTH_23,
      MONTH_24,
      MONTH_25,
      MONTH_26,
      MONTH_27,
      MONTH_28,
      MONTH_29,
      MONTH_30,
      MONTH_31,
      MONTH_32,
      MONTH_33,
      MONTH_34,
      MONTH_35,
      MONTH_36,
      MONTH_37,
      MONTH_38,
      MONTH_39,
      MONTH_40,
      MONTH_41,
      MONTH_42,
      MONTH_43,
      MONTH_44,
      MONTH_45,
      MONTH_46,
      MONTH_47,
      MONTH_48,
      MONTH_49,
      MONTH_50,
      MONTH_51,
      MONTH_52,
      MONTH_53,
      MONTH_54
    FROM INV_SAP_HSTDE_DS
    )DMT_PRD
  LEFT JOIN
    (SELECT ID,
      CATALOG_DASH,
      MAT_DESC,
      SAFETY_STOCK,
      PROD_BU,
      PROD_FAM,
      PROD_HIERARCHY,
      PROC_TYPE,
      STRATEGY_GRP,
      MATL_TYPE,
      VENDOR_KEY
    FROM INV_SAP_PP_OPT_X
    )PP_BASIC
  ON DMT_PRD.ID = PP_BASIC.ID
  )DMT_PP_BS
LEFT JOIN
  ( SELECT PRO_LINE_NAME,PRO_LINE_DES FROM INV_SAP_DMT_FRD_PLDES
  )PRO_DES
ON PRO_DES.PRO_LINE_NAME = DMT_PP_BS.PROD_LINE;

DROP VIEW VIEW_INV_SAP_SPPTPD_MM1;
DROP VIEW VIEW_INV_SAP_SPPTPD_MM2;
DROP VIEW VIEW_INV_SAP_SPPTPD_MM3;
DROP VIEW VIEW_INV_SAP_SPPTPD_MM4;
DROP VIEW VIEW_INV_SAP_SPPTPD_MM5;
DROP VIEW VIEW_INV_SAP_SPPTPD_MM6;
DROP VIEW VIEW_INV_SAP_SPPTPD_MM7;
DROP VIEW VIEW_INV_SAP_SPPTPD_MM8;
DROP VIEW VIEW_INV_SAP_SPPTPD_MM9;
DROP VIEW VIEW_INV_SAP_SPPTPD_MM10;
DROP VIEW VIEW_INV_SAP_SPPTPD_MM11;
DROP VIEW VIEW_INV_SAP_SPPTPD_MM12;


CREATE VIEW VIEW_INV_SAP_SPPTPD_MM1 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID,PLANT,PROD_LINE,SUM(MONTH_25) AS SUM_MONTH25 FROM INV_SAP_SPIKE_ANALYSIS GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPD_MM2 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_26) AS SUM_MONTH26 FROM INV_SAP_SPIKE_ANALYSIS GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPD_MM3 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_27) AS SUM_MONTH27 FROM INV_SAP_SPIKE_ANALYSIS GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPD_MM4 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_28) AS SUM_MONTH28 FROM INV_SAP_SPIKE_ANALYSIS GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPD_MM5 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_29) AS SUM_MONTH29 FROM INV_SAP_SPIKE_ANALYSIS GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPD_MM6 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_30) AS SUM_MONTH30 FROM INV_SAP_SPIKE_ANALYSIS GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPD_MM7 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_31) AS SUM_MONTH31 FROM INV_SAP_SPIKE_ANALYSIS GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPD_MM8 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_32) AS SUM_MONTH32 FROM INV_SAP_SPIKE_ANALYSIS GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPD_MM9 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_33) AS SUM_MONTH33 FROM INV_SAP_SPIKE_ANALYSIS GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPD_MM10 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_34) AS SUM_MONTH34 FROM INV_SAP_SPIKE_ANALYSIS GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPD_MM11 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_35) AS SUM_MONTH35 FROM INV_SAP_SPIKE_ANALYSIS GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPD_MM12 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_36) AS SUM_MONTH36 FROM INV_SAP_SPIKE_ANALYSIS GROUP BY PLANT,PROD_LINE;


--PA12
DROP VIEW VIEW_INV_SAP_SPPTPDPA12_MM1;
DROP VIEW VIEW_INV_SAP_SPPTPDPA12_MM2;
DROP VIEW VIEW_INV_SAP_SPPTPDPA12_MM3;
DROP VIEW VIEW_INV_SAP_SPPTPDPA12_MM4;
DROP VIEW VIEW_INV_SAP_SPPTPDPA12_MM5;
DROP VIEW VIEW_INV_SAP_SPPTPDPA12_MM6;
DROP VIEW VIEW_INV_SAP_SPPTPDPA12_MM7;
DROP VIEW VIEW_INV_SAP_SPPTPDPA12_MM8;
DROP VIEW VIEW_INV_SAP_SPPTPDPA12_MM9;
DROP VIEW VIEW_INV_SAP_SPPTPDPA12_MM10;
DROP VIEW VIEW_INV_SAP_SPPTPDPA12_MM11;
DROP VIEW VIEW_INV_SAP_SPPTPDPA12_MM12;


CREATE VIEW VIEW_INV_SAP_SPPTPDPA12_MM1 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_25) AS SUM_MONTH25 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT NOT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA12_MM2 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_26) AS SUM_MONTH26 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT NOT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA12_MM3 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_27) AS SUM_MONTH27 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT NOT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA12_MM4 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_28) AS SUM_MONTH28 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT NOT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA12_MM5 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_29) AS SUM_MONTH29 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT NOT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA12_MM6 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_30) AS SUM_MONTH30 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT NOT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA12_MM7 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_31) AS SUM_MONTH31 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT NOT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA12_MM8 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_32) AS SUM_MONTH32 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT NOT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA12_MM9 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_33) AS SUM_MONTH33 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT NOT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA12_MM10 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_34) AS SUM_MONTH34 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT NOT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA12_MM11 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_35) AS SUM_MONTH35 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT NOT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA12_MM12 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_36) AS SUM_MONTH36 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT NOT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;

--PA15
DROP VIEW VIEW_INV_SAP_SPPTPDPA15_MM1;
DROP VIEW VIEW_INV_SAP_SPPTPDPA15_MM2;
DROP VIEW VIEW_INV_SAP_SPPTPDPA15_MM3;
DROP VIEW VIEW_INV_SAP_SPPTPDPA15_MM4;
DROP VIEW VIEW_INV_SAP_SPPTPDPA15_MM5;
DROP VIEW VIEW_INV_SAP_SPPTPDPA15_MM6;
DROP VIEW VIEW_INV_SAP_SPPTPDPA15_MM7;
DROP VIEW VIEW_INV_SAP_SPPTPDPA15_MM8;
DROP VIEW VIEW_INV_SAP_SPPTPDPA15_MM9;
DROP VIEW VIEW_INV_SAP_SPPTPDPA15_MM10;
DROP VIEW VIEW_INV_SAP_SPPTPDPA15_MM11;
DROP VIEW VIEW_INV_SAP_SPPTPDPA15_MM12;

CREATE VIEW VIEW_INV_SAP_SPPTPDPA15_MM1 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_25) AS SUM_MONTH25 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA15_MM2 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_26) AS SUM_MONTH26 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA15_MM3 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_27) AS SUM_MONTH27 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA15_MM4 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_28) AS SUM_MONTH28 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA15_MM5 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_29) AS SUM_MONTH29 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA15_MM6 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_30) AS SUM_MONTH30 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA15_MM7 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_31) AS SUM_MONTH31 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA15_MM8 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_32) AS SUM_MONTH32 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA15_MM9 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_33) AS SUM_MONTH33 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA15_MM10 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_34) AS SUM_MONTH34 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA15_MM11 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_35) AS SUM_MONTH35 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPPTPDPA15_MM12 AS 
SELECT PLANT||'_'||PROD_LINE AS PP_ID, PLANT,PROD_LINE,SUM(MONTH_36) AS SUM_MONTH36 FROM INV_SAP_SPIKE_ANALYSIS WHERE PLANT IN ('5050','5040') GROUP BY PLANT,PROD_LINE;



SELECT 
  PLANT||'_'||PROD_LINE,
  TYPE,
  ID,
  MATERIAL,
  PLANT,
  CATALOG_DASH,
  BULLETIN,
  MAT_DESC,
  SAFETY_STOCK,
  PROD_BU,
  PROD_FAM,
  PROD_HIERARCHY,
  PROD_LINE,
  PRO_LINE_DES,
  PROC_TYPE,
  STRATEGY_GRP,
  MATL_TYPE,
  VENDOR_KEY,
  UNIT,
  MONTH_25,
  MONTH_26,
  MONTH_27,
  MONTH_28,
  MONTH_29,
  MONTH_30,
  MONTH_31,
  MONTH_32,
  MONTH_33,
  MONTH_34,
  MONTH_35,
  MONTH_36
FROM VIEW_INV_SAP_SPIKE_ANALYSIS WHERE PLANT IN ('5040','5050') and PROD_LINE = 'SFSA0483A189'
--Plant-Prod line.
DROP VIEW VIEW_INV_SAP_SPIKEPLANT;
SELECT * FROM VIEW_INV_SAP_SPIKEPLANT  where PROD_LINE = 'SFSA0483A189';
CREATE VIEW VIEW_INV_SAP_SPIKEPLANT AS
SELECT 
PP_ID,
PLANT,
PROD_LINE,
SUM_MONTH25,
SUM_MONTH26,
SUM_MONTH27,
SUM_MONTH28,
SUM_MONTH29,
SUM_MONTH30,
SUM_MONTH31,
SUM_MONTH32,
SUM_MONTH33,
SUM_MONTH34,
SUM_MONTH35,
SUM_MONTH36
FROM
(SELECT SPPTPD_MM1.PP_ID,
SPPTPD_MM1.PLANT,
SPPTPD_MM1.PROD_LINE,
SPPTPD_MM1.SUM_MONTH25,
SPPTPD_MM2.SUM_MONTH26,
SPPTPD_MM3.SUM_MONTH27,
SPPTPD_MM4.SUM_MONTH28,
SPPTPD_MM5.SUM_MONTH29,
SPPTPD_MM6.SUM_MONTH30,
SPPTPD_MM7.SUM_MONTH31,
SPPTPD_MM8.SUM_MONTH32,
SPPTPD_MM9.SUM_MONTH33,
SPPTPD_MM10.SUM_MONTH34,
SPPTPD_MM11.SUM_MONTH35,
SPPTPD_MM12.SUM_MONTH36
FROM VIEW_INV_SAP_SPPTPD_MM1 SPPTPD_MM1,
VIEW_INV_SAP_SPPTPD_MM2 SPPTPD_MM2,
VIEW_INV_SAP_SPPTPD_MM3 SPPTPD_MM3,
VIEW_INV_SAP_SPPTPD_MM4 SPPTPD_MM4,
VIEW_INV_SAP_SPPTPD_MM5 SPPTPD_MM5,
VIEW_INV_SAP_SPPTPD_MM6 SPPTPD_MM6,
VIEW_INV_SAP_SPPTPD_MM7 SPPTPD_MM7,
VIEW_INV_SAP_SPPTPD_MM8 SPPTPD_MM8,
VIEW_INV_SAP_SPPTPD_MM9 SPPTPD_MM9,
VIEW_INV_SAP_SPPTPD_MM10 SPPTPD_MM10,
VIEW_INV_SAP_SPPTPD_MM11 SPPTPD_MM11,
VIEW_INV_SAP_SPPTPD_MM12 SPPTPD_MM12
WHERE SPPTPD_MM1.PP_ID = SPPTPD_MM2.PP_ID
AND SPPTPD_MM2.PP_ID = SPPTPD_MM3.PP_ID
AND SPPTPD_MM3.PP_ID = SPPTPD_MM4.PP_ID
AND SPPTPD_MM4.PP_ID = SPPTPD_MM5.PP_ID
AND SPPTPD_MM5.PP_ID = SPPTPD_MM6.PP_ID
AND SPPTPD_MM6.PP_ID = SPPTPD_MM7.PP_ID
AND SPPTPD_MM7.PP_ID = SPPTPD_MM8.PP_ID
AND SPPTPD_MM8.PP_ID = SPPTPD_MM9.PP_ID
AND SPPTPD_MM9.PP_ID = SPPTPD_MM10.PP_ID
AND SPPTPD_MM10.PP_ID = SPPTPD_MM11.PP_ID
AND SPPTPD_MM11.PP_ID = SPPTPD_MM12.PP_ID
);


--PA12
CREATE VIEW VIEW_INV_SAP_SPIKEPLANTPA12 AS
SELECT 
PP_ID,
PLANT,
PROD_LINE,
SUM_MONTH25,
SUM_MONTH26,
SUM_MONTH27,
SUM_MONTH28,
SUM_MONTH29,
SUM_MONTH30,
SUM_MONTH31,
SUM_MONTH32,
SUM_MONTH33,
SUM_MONTH34,
SUM_MONTH35,
SUM_MONTH36
FROM
(SELECT SPPTPD_MM1.PP_ID,
SPPTPD_MM1.PLANT,
SPPTPD_MM1.PROD_LINE,
SPPTPD_MM1.SUM_MONTH25,
SPPTPD_MM2.SUM_MONTH26,
SPPTPD_MM3.SUM_MONTH27,
SPPTPD_MM4.SUM_MONTH28,
SPPTPD_MM5.SUM_MONTH29,
SPPTPD_MM6.SUM_MONTH30,
SPPTPD_MM7.SUM_MONTH31,
SPPTPD_MM8.SUM_MONTH32,
SPPTPD_MM9.SUM_MONTH33,
SPPTPD_MM10.SUM_MONTH34,
SPPTPD_MM11.SUM_MONTH35,
SPPTPD_MM12.SUM_MONTH36
FROM VIEW_INV_SAP_SPPTPDPA12_MM1 SPPTPD_MM1,
VIEW_INV_SAP_SPPTPDPA12_MM2 SPPTPD_MM2,
VIEW_INV_SAP_SPPTPDPA12_MM3 SPPTPD_MM3,
VIEW_INV_SAP_SPPTPDPA12_MM4 SPPTPD_MM4,
VIEW_INV_SAP_SPPTPDPA12_MM5 SPPTPD_MM5,
VIEW_INV_SAP_SPPTPDPA12_MM6 SPPTPD_MM6,
VIEW_INV_SAP_SPPTPDPA12_MM7 SPPTPD_MM7,
VIEW_INV_SAP_SPPTPDPA12_MM8 SPPTPD_MM8,
VIEW_INV_SAP_SPPTPDPA12_MM9 SPPTPD_MM9,
VIEW_INV_SAP_SPPTPDPA12_MM10 SPPTPD_MM10,
VIEW_INV_SAP_SPPTPDPA12_MM11 SPPTPD_MM11,
VIEW_INV_SAP_SPPTPDPA12_MM12 SPPTPD_MM12
WHERE SPPTPD_MM1.PP_ID = SPPTPD_MM2.PP_ID
AND SPPTPD_MM2.PP_ID = SPPTPD_MM3.PP_ID
AND SPPTPD_MM3.PP_ID = SPPTPD_MM4.PP_ID
AND SPPTPD_MM4.PP_ID = SPPTPD_MM5.PP_ID
AND SPPTPD_MM5.PP_ID = SPPTPD_MM6.PP_ID
AND SPPTPD_MM6.PP_ID = SPPTPD_MM7.PP_ID
AND SPPTPD_MM7.PP_ID = SPPTPD_MM8.PP_ID
AND SPPTPD_MM8.PP_ID = SPPTPD_MM9.PP_ID
AND SPPTPD_MM9.PP_ID = SPPTPD_MM10.PP_ID
AND SPPTPD_MM10.PP_ID = SPPTPD_MM11.PP_ID
AND SPPTPD_MM11.PP_ID = SPPTPD_MM12.PP_ID
);


--PA15

SELECT 
DISTINCT
PLANT
FROM VIEW_INV_SAP_SPIKEPLANTPA15;
CREATE VIEW VIEW_INV_SAP_SPIKEPLANTPA15 AS
SELECT 
PP_ID,
PLANT,
PROD_LINE,
SUM_MONTH25,
SUM_MONTH26,
SUM_MONTH27,
SUM_MONTH28,
SUM_MONTH29,
SUM_MONTH30,
SUM_MONTH31,
SUM_MONTH32,
SUM_MONTH33,
SUM_MONTH34,
SUM_MONTH35,
SUM_MONTH36
FROM
(SELECT SPPTPD_MM1.PP_ID,
SPPTPD_MM1.PLANT,
SPPTPD_MM1.PROD_LINE,
SPPTPD_MM1.SUM_MONTH25,
SPPTPD_MM2.SUM_MONTH26,
SPPTPD_MM3.SUM_MONTH27,
SPPTPD_MM4.SUM_MONTH28,
SPPTPD_MM5.SUM_MONTH29,
SPPTPD_MM6.SUM_MONTH30,
SPPTPD_MM7.SUM_MONTH31,
SPPTPD_MM8.SUM_MONTH32,
SPPTPD_MM9.SUM_MONTH33,
SPPTPD_MM10.SUM_MONTH34,
SPPTPD_MM11.SUM_MONTH35,
SPPTPD_MM12.SUM_MONTH36
FROM VIEW_INV_SAP_SPPTPDPA15_MM1 SPPTPD_MM1,
VIEW_INV_SAP_SPPTPDPA15_MM2 SPPTPD_MM2,
VIEW_INV_SAP_SPPTPDPA15_MM3 SPPTPD_MM3,
VIEW_INV_SAP_SPPTPDPA15_MM4 SPPTPD_MM4,
VIEW_INV_SAP_SPPTPDPA15_MM5 SPPTPD_MM5,
VIEW_INV_SAP_SPPTPDPA15_MM6 SPPTPD_MM6,
VIEW_INV_SAP_SPPTPDPA15_MM7 SPPTPD_MM7,
VIEW_INV_SAP_SPPTPDPA15_MM8 SPPTPD_MM8,
VIEW_INV_SAP_SPPTPDPA15_MM9 SPPTPD_MM9,
VIEW_INV_SAP_SPPTPDPA15_MM10 SPPTPD_MM10,
VIEW_INV_SAP_SPPTPDPA15_MM11 SPPTPD_MM11,
VIEW_INV_SAP_SPPTPDPA15_MM12 SPPTPD_MM12
WHERE SPPTPD_MM1.PP_ID = SPPTPD_MM2.PP_ID
AND SPPTPD_MM2.PP_ID = SPPTPD_MM3.PP_ID
AND SPPTPD_MM3.PP_ID = SPPTPD_MM4.PP_ID
AND SPPTPD_MM4.PP_ID = SPPTPD_MM5.PP_ID
AND SPPTPD_MM5.PP_ID = SPPTPD_MM6.PP_ID
AND SPPTPD_MM6.PP_ID = SPPTPD_MM7.PP_ID
AND SPPTPD_MM7.PP_ID = SPPTPD_MM8.PP_ID
AND SPPTPD_MM8.PP_ID = SPPTPD_MM9.PP_ID
AND SPPTPD_MM9.PP_ID = SPPTPD_MM10.PP_ID
AND SPPTPD_MM10.PP_ID = SPPTPD_MM11.PP_ID
AND SPPTPD_MM11.PP_ID = SPPTPD_MM12.PP_ID
) where PROD_LINE = 'SFSA0483A189';

SELECT 
PP_ID,
PLANT,
PROD_LINE,
SUM_MONTH35,
SUM_MONTH36
FROM VIEW_INV_SAP_SPIKEPLANT;

DROP VIEW VIEW_INV_SAP_SPIKEPL_MM1;
DROP VIEW VIEW_INV_SAP_SPIKEPL_MM2;
DROP VIEW VIEW_INV_SAP_SPIKEPL_MM3;
DROP VIEW VIEW_INV_SAP_SPIKEPL_MM4;
DROP VIEW VIEW_INV_SAP_SPIKEPL_MM5;
DROP VIEW VIEW_INV_SAP_SPIKEPL_MM6;
DROP VIEW VIEW_INV_SAP_SPIKEPL_MM7;
DROP VIEW VIEW_INV_SAP_SPIKEPL_MM8;
DROP VIEW VIEW_INV_SAP_SPIKEPL_MM9;
DROP VIEW VIEW_INV_SAP_SPIKEPL_MM10;
DROP VIEW VIEW_INV_SAP_SPIKEPL_MM11;
DROP VIEW VIEW_INV_SAP_SPIKEPL_MM12;

CREATE VIEW VIEW_INV_SAP_SPIKEPL_MM1 AS 
SELECT PROD_LINE,SUM(SUM_MONTH25) AS SUM_MONTH25 FROM VIEW_INV_SAP_SPIKEPLANT GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPL_MM2 AS 
SELECT PROD_LINE,SUM(SUM_MONTH26) AS SUM_MONTH26 FROM VIEW_INV_SAP_SPIKEPLANT GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPL_MM3 AS 
SELECT PROD_LINE,SUM(SUM_MONTH27) AS SUM_MONTH27 FROM VIEW_INV_SAP_SPIKEPLANT GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPL_MM4 AS 
SELECT PROD_LINE,SUM(SUM_MONTH28) AS SUM_MONTH28 FROM VIEW_INV_SAP_SPIKEPLANT GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPL_MM5 AS 
SELECT PROD_LINE,SUM(SUM_MONTH29) AS SUM_MONTH29 FROM VIEW_INV_SAP_SPIKEPLANT GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPL_MM6 AS 
SELECT PROD_LINE,SUM(SUM_MONTH30) AS SUM_MONTH30 FROM VIEW_INV_SAP_SPIKEPLANT GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPL_MM7 AS 
SELECT PROD_LINE,SUM(SUM_MONTH31) AS SUM_MONTH31 FROM VIEW_INV_SAP_SPIKEPLANT GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPL_MM8 AS 
SELECT PROD_LINE,SUM(SUM_MONTH32) AS SUM_MONTH32 FROM VIEW_INV_SAP_SPIKEPLANT GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPL_MM9 AS 
SELECT PROD_LINE,SUM(SUM_MONTH33) AS SUM_MONTH33 FROM VIEW_INV_SAP_SPIKEPLANT GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPL_MM10 AS 
SELECT PROD_LINE,SUM(SUM_MONTH34) AS SUM_MONTH34 FROM VIEW_INV_SAP_SPIKEPLANT GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPL_MM11 AS 
SELECT PROD_LINE,SUM(SUM_MONTH35) AS SUM_MONTH35 FROM VIEW_INV_SAP_SPIKEPLANT GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPL_MM12 AS 
SELECT PROD_LINE,SUM(SUM_MONTH36) AS SUM_MONTH36 FROM VIEW_INV_SAP_SPIKEPLANT GROUP BY PROD_LINE;

--PA12
DROP VIEW VIEW_INV_SAP_SPIKEPLPA12_MM1;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA12_MM2;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA12_MM3;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA12_MM4;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA12_MM5;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA12_MM6;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA12_MM7;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA12_MM8;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA12_MM9;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA12_MM10;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA12_MM11;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA12_MM12;

CREATE VIEW VIEW_INV_SAP_SPIKEPLPA12_MM1 AS 
SELECT PROD_LINE,SUM(SUM_MONTH25) AS SUM_MONTH25 FROM VIEW_INV_SAP_SPIKEPLANTPA12 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA12_MM2 AS 
SELECT PROD_LINE,SUM(SUM_MONTH26) AS SUM_MONTH26 FROM VIEW_INV_SAP_SPIKEPLANTPA12 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA12_MM3 AS 
SELECT PROD_LINE,SUM(SUM_MONTH27) AS SUM_MONTH27 FROM VIEW_INV_SAP_SPIKEPLANTPA12 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA12_MM4 AS 
SELECT PROD_LINE,SUM(SUM_MONTH28) AS SUM_MONTH28 FROM VIEW_INV_SAP_SPIKEPLANTPA12 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA12_MM5 AS 
SELECT PROD_LINE,SUM(SUM_MONTH29) AS SUM_MONTH29 FROM VIEW_INV_SAP_SPIKEPLANTPA12 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA12_MM6 AS 
SELECT PROD_LINE,SUM(SUM_MONTH30) AS SUM_MONTH30 FROM VIEW_INV_SAP_SPIKEPLANTPA12 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA12_MM7 AS 
SELECT PROD_LINE,SUM(SUM_MONTH31) AS SUM_MONTH31 FROM VIEW_INV_SAP_SPIKEPLANTPA12 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA12_MM8 AS 
SELECT PROD_LINE,SUM(SUM_MONTH32) AS SUM_MONTH32 FROM VIEW_INV_SAP_SPIKEPLANTPA12 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA12_MM9 AS 
SELECT PROD_LINE,SUM(SUM_MONTH33) AS SUM_MONTH33 FROM VIEW_INV_SAP_SPIKEPLANTPA12 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA12_MM10 AS 
SELECT PROD_LINE,SUM(SUM_MONTH34) AS SUM_MONTH34 FROM VIEW_INV_SAP_SPIKEPLANTPA12 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA12_MM11 AS 
SELECT PROD_LINE,SUM(SUM_MONTH35) AS SUM_MONTH35 FROM VIEW_INV_SAP_SPIKEPLANTPA12 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA12_MM12 AS 
SELECT PROD_LINE,SUM(SUM_MONTH36) AS SUM_MONTH36 FROM VIEW_INV_SAP_SPIKEPLANTPA12 GROUP BY PROD_LINE;

--PA15
DROP VIEW VIEW_INV_SAP_SPIKEPLPA15_MM1;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA15_MM2;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA15_MM3;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA15_MM4;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA15_MM5;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA15_MM6;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA15_MM7;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA15_MM8;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA15_MM9;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA15_MM10;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA15_MM11;
DROP VIEW VIEW_INV_SAP_SPIKEPLPA15_MM12;

CREATE VIEW VIEW_INV_SAP_SPIKEPLPA15_MM1 AS 
SELECT PROD_LINE,SUM(SUM_MONTH25) AS SUM_MONTH25 FROM VIEW_INV_SAP_SPIKEPLANTPA15 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA15_MM2 AS 
SELECT PROD_LINE,SUM(SUM_MONTH26) AS SUM_MONTH26 FROM VIEW_INV_SAP_SPIKEPLANTPA15 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA15_MM3 AS 
SELECT PROD_LINE,SUM(SUM_MONTH27) AS SUM_MONTH27 FROM VIEW_INV_SAP_SPIKEPLANTPA15 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA15_MM4 AS 
SELECT PROD_LINE,SUM(SUM_MONTH28) AS SUM_MONTH28 FROM VIEW_INV_SAP_SPIKEPLANTPA15 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA15_MM5 AS 
SELECT PROD_LINE,SUM(SUM_MONTH29) AS SUM_MONTH29 FROM VIEW_INV_SAP_SPIKEPLANTPA15 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA15_MM6 AS 
SELECT PROD_LINE,SUM(SUM_MONTH30) AS SUM_MONTH30 FROM VIEW_INV_SAP_SPIKEPLANTPA15 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA15_MM7 AS 
SELECT PROD_LINE,SUM(SUM_MONTH31) AS SUM_MONTH31 FROM VIEW_INV_SAP_SPIKEPLANTPA15 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA15_MM8 AS 
SELECT PROD_LINE,SUM(SUM_MONTH32) AS SUM_MONTH32 FROM VIEW_INV_SAP_SPIKEPLANTPA15 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA15_MM9 AS 
SELECT PROD_LINE,SUM(SUM_MONTH33) AS SUM_MONTH33 FROM VIEW_INV_SAP_SPIKEPLANTPA15 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA15_MM10 AS 
SELECT PROD_LINE,SUM(SUM_MONTH34) AS SUM_MONTH34 FROM VIEW_INV_SAP_SPIKEPLANTPA15 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA15_MM11 AS 
SELECT PROD_LINE,SUM(SUM_MONTH35) AS SUM_MONTH35 FROM VIEW_INV_SAP_SPIKEPLANTPA15 GROUP BY PROD_LINE;
CREATE VIEW VIEW_INV_SAP_SPIKEPLPA15_MM12 AS 
SELECT PROD_LINE,SUM(SUM_MONTH36) AS SUM_MONTH36 FROM VIEW_INV_SAP_SPIKEPLANTPA15 GROUP BY PROD_LINE;



DROP VIEW VIEW_INV_SAP_SPIKEPROD;
CREATE VIEW VIEW_INV_SAP_SPIKEPROD AS 
SELECT 
PROD_LINE,
SUM_MONTH35,
SUM_MONTH36,
ROUND((DEMD_12AVG+ 3*SQRT((SUM_MONTH25-DEMD_12AVG)*(SUM_MONTH25-DEMD_12AVG)+
(SUM_MONTH26-DEMD_12AVG)*(SUM_MONTH26-DEMD_12AVG)+
(SUM_MONTH27-DEMD_12AVG)*(SUM_MONTH27-DEMD_12AVG)+
(SUM_MONTH28-DEMD_12AVG)*(SUM_MONTH28-DEMD_12AVG)+
(SUM_MONTH29-DEMD_12AVG)*(SUM_MONTH29-DEMD_12AVG)+
(SUM_MONTH30-DEMD_12AVG)*(SUM_MONTH30-DEMD_12AVG)+
(SUM_MONTH31-DEMD_12AVG)*(SUM_MONTH31-DEMD_12AVG)+
(SUM_MONTH32-DEMD_12AVG)*(SUM_MONTH32-DEMD_12AVG)+
(SUM_MONTH33-DEMD_12AVG)*(SUM_MONTH33-DEMD_12AVG)+
(SUM_MONTH34-DEMD_12AVG)*(SUM_MONTH34-DEMD_12AVG)+
(SUM_MONTH35-DEMD_12AVG)*(SUM_MONTH35-DEMD_12AVG)+
(SUM_MONTH36-DEMD_12AVG)*(SUM_MONTH36-DEMD_12AVG))/12),2) AS VAR_CHECK
FROM
(SELECT 
SPIKEPL_MM1.PROD_LINE,
SPIKEPL_MM1.SUM_MONTH25,
SPIKEPL_MM2.SUM_MONTH26,
SPIKEPL_MM3.SUM_MONTH27,
SPIKEPL_MM4.SUM_MONTH28,
SPIKEPL_MM5.SUM_MONTH29,
SPIKEPL_MM6.SUM_MONTH30,
SPIKEPL_MM7.SUM_MONTH31,
SPIKEPL_MM8.SUM_MONTH32,
SPIKEPL_MM9.SUM_MONTH33,
SPIKEPL_MM10.SUM_MONTH34,
SPIKEPL_MM11.SUM_MONTH35,
SPIKEPL_MM12.SUM_MONTH36,
ROUND((SPIKEPL_MM1.SUM_MONTH25+
SPIKEPL_MM2.SUM_MONTH26+
SPIKEPL_MM3.SUM_MONTH27+
SPIKEPL_MM4.SUM_MONTH28+
SPIKEPL_MM5.SUM_MONTH29+
SPIKEPL_MM6.SUM_MONTH30+
SPIKEPL_MM7.SUM_MONTH31+
SPIKEPL_MM8.SUM_MONTH32+
SPIKEPL_MM9.SUM_MONTH33+
SPIKEPL_MM10.SUM_MONTH34+
SPIKEPL_MM11.SUM_MONTH35+
SPIKEPL_MM12.SUM_MONTH36)/12,2) AS DEMD_12AVG
FROM VIEW_INV_SAP_SPIKEPL_MM1 SPIKEPL_MM1,
VIEW_INV_SAP_SPIKEPL_MM2 SPIKEPL_MM2,
VIEW_INV_SAP_SPIKEPL_MM3 SPIKEPL_MM3,
VIEW_INV_SAP_SPIKEPL_MM4 SPIKEPL_MM4,
VIEW_INV_SAP_SPIKEPL_MM5 SPIKEPL_MM5,
VIEW_INV_SAP_SPIKEPL_MM6 SPIKEPL_MM6,
VIEW_INV_SAP_SPIKEPL_MM7 SPIKEPL_MM7,
VIEW_INV_SAP_SPIKEPL_MM8 SPIKEPL_MM8,
VIEW_INV_SAP_SPIKEPL_MM9 SPIKEPL_MM9,
VIEW_INV_SAP_SPIKEPL_MM10 SPIKEPL_MM10,
VIEW_INV_SAP_SPIKEPL_MM11 SPIKEPL_MM11,
VIEW_INV_SAP_SPIKEPL_MM12 SPIKEPL_MM12
WHERE SPIKEPL_MM1.PROD_LINE = SPIKEPL_MM2.PROD_LINE
AND SPIKEPL_MM2.PROD_LINE = SPIKEPL_MM3.PROD_LINE
AND SPIKEPL_MM3.PROD_LINE = SPIKEPL_MM4.PROD_LINE
AND SPIKEPL_MM4.PROD_LINE = SPIKEPL_MM5.PROD_LINE
AND SPIKEPL_MM5.PROD_LINE = SPIKEPL_MM6.PROD_LINE
AND SPIKEPL_MM6.PROD_LINE = SPIKEPL_MM7.PROD_LINE
AND SPIKEPL_MM7.PROD_LINE = SPIKEPL_MM8.PROD_LINE
AND SPIKEPL_MM8.PROD_LINE = SPIKEPL_MM9.PROD_LINE
AND SPIKEPL_MM9.PROD_LINE = SPIKEPL_MM10.PROD_LINE
AND SPIKEPL_MM10.PROD_LINE = SPIKEPL_MM11.PROD_LINE
AND SPIKEPL_MM11.PROD_LINE = SPIKEPL_MM12.PROD_LINE
);


--PA12
DROP VIEW VIEW_INV_SAP_SPIKEPRODPA12;
CREATE VIEW VIEW_INV_SAP_SPIKEPRODPA12 AS 
SELECT 
PROD_LINE,
SUM_MONTH35,
SUM_MONTH36,
ROUND((3*SQRT(((SUM_MONTH25-DEMD_12AVG)*(SUM_MONTH25-DEMD_12AVG)+
(SUM_MONTH26-DEMD_12AVG)*(SUM_MONTH26-DEMD_12AVG)+
(SUM_MONTH27-DEMD_12AVG)*(SUM_MONTH27-DEMD_12AVG)+
(SUM_MONTH28-DEMD_12AVG)*(SUM_MONTH28-DEMD_12AVG)+
(SUM_MONTH29-DEMD_12AVG)*(SUM_MONTH29-DEMD_12AVG)+
(SUM_MONTH30-DEMD_12AVG)*(SUM_MONTH30-DEMD_12AVG)+
(SUM_MONTH31-DEMD_12AVG)*(SUM_MONTH31-DEMD_12AVG)+
(SUM_MONTH32-DEMD_12AVG)*(SUM_MONTH32-DEMD_12AVG)+
(SUM_MONTH33-DEMD_12AVG)*(SUM_MONTH33-DEMD_12AVG)+
(SUM_MONTH34-DEMD_12AVG)*(SUM_MONTH34-DEMD_12AVG)+
(SUM_MONTH35-DEMD_12AVG)*(SUM_MONTH35-DEMD_12AVG)+
(SUM_MONTH36-DEMD_12AVG)*(SUM_MONTH36-DEMD_12AVG))/11)),2) AS VAR_CHECK
FROM
(SELECT 
SPIKEPL_MM1.PROD_LINE,
SPIKEPL_MM1.SUM_MONTH25,
SPIKEPL_MM2.SUM_MONTH26,
SPIKEPL_MM3.SUM_MONTH27,
SPIKEPL_MM4.SUM_MONTH28,
SPIKEPL_MM5.SUM_MONTH29,
SPIKEPL_MM6.SUM_MONTH30,
SPIKEPL_MM7.SUM_MONTH31,
SPIKEPL_MM8.SUM_MONTH32,
SPIKEPL_MM9.SUM_MONTH33,
SPIKEPL_MM10.SUM_MONTH34,
SPIKEPL_MM11.SUM_MONTH35,
SPIKEPL_MM12.SUM_MONTH36,
ROUND((SPIKEPL_MM1.SUM_MONTH25+
SPIKEPL_MM2.SUM_MONTH26+
SPIKEPL_MM3.SUM_MONTH27+
SPIKEPL_MM4.SUM_MONTH28+
SPIKEPL_MM5.SUM_MONTH29+
SPIKEPL_MM6.SUM_MONTH30+
SPIKEPL_MM7.SUM_MONTH31+
SPIKEPL_MM8.SUM_MONTH32+
SPIKEPL_MM9.SUM_MONTH33+
SPIKEPL_MM10.SUM_MONTH34+
SPIKEPL_MM11.SUM_MONTH35+
SPIKEPL_MM12.SUM_MONTH36)/12,2) AS DEMD_12AVG
FROM VIEW_INV_SAP_SPIKEPLPA12_MM1 SPIKEPL_MM1,
VIEW_INV_SAP_SPIKEPLPA12_MM2 SPIKEPL_MM2,
VIEW_INV_SAP_SPIKEPLPA12_MM3 SPIKEPL_MM3,
VIEW_INV_SAP_SPIKEPLPA12_MM4 SPIKEPL_MM4,
VIEW_INV_SAP_SPIKEPLPA12_MM5 SPIKEPL_MM5,
VIEW_INV_SAP_SPIKEPLPA12_MM6 SPIKEPL_MM6,
VIEW_INV_SAP_SPIKEPLPA12_MM7 SPIKEPL_MM7,
VIEW_INV_SAP_SPIKEPLPA12_MM8 SPIKEPL_MM8,
VIEW_INV_SAP_SPIKEPLPA12_MM9 SPIKEPL_MM9,
VIEW_INV_SAP_SPIKEPLPA12_MM10 SPIKEPL_MM10,
VIEW_INV_SAP_SPIKEPLPA12_MM11 SPIKEPL_MM11,
VIEW_INV_SAP_SPIKEPLPA12_MM12 SPIKEPL_MM12
WHERE SPIKEPL_MM1.PROD_LINE = SPIKEPL_MM2.PROD_LINE
AND SPIKEPL_MM2.PROD_LINE = SPIKEPL_MM3.PROD_LINE
AND SPIKEPL_MM3.PROD_LINE = SPIKEPL_MM4.PROD_LINE
AND SPIKEPL_MM4.PROD_LINE = SPIKEPL_MM5.PROD_LINE
AND SPIKEPL_MM5.PROD_LINE = SPIKEPL_MM6.PROD_LINE
AND SPIKEPL_MM6.PROD_LINE = SPIKEPL_MM7.PROD_LINE
AND SPIKEPL_MM7.PROD_LINE = SPIKEPL_MM8.PROD_LINE
AND SPIKEPL_MM8.PROD_LINE = SPIKEPL_MM9.PROD_LINE
AND SPIKEPL_MM9.PROD_LINE = SPIKEPL_MM10.PROD_LINE
AND SPIKEPL_MM10.PROD_LINE = SPIKEPL_MM11.PROD_LINE
AND SPIKEPL_MM11.PROD_LINE = SPIKEPL_MM12.PROD_LINE
);

--PA15
DROP VIEW VIEW_INV_SAP_SPIKEPRODPA15;
CREATE VIEW VIEW_INV_SAP_SPIKEPRODPA15 AS 
SELECT 
PROD_LINE,
SUM_MONTH35,
SUM_MONTH36,
ROUND((3*SQRT(((SUM_MONTH25-DEMD_12AVG)*(SUM_MONTH25-DEMD_12AVG)+
(SUM_MONTH26-DEMD_12AVG)*(SUM_MONTH26-DEMD_12AVG)+
(SUM_MONTH27-DEMD_12AVG)*(SUM_MONTH27-DEMD_12AVG)+
(SUM_MONTH28-DEMD_12AVG)*(SUM_MONTH28-DEMD_12AVG)+
(SUM_MONTH29-DEMD_12AVG)*(SUM_MONTH29-DEMD_12AVG)+
(SUM_MONTH30-DEMD_12AVG)*(SUM_MONTH30-DEMD_12AVG)+
(SUM_MONTH31-DEMD_12AVG)*(SUM_MONTH31-DEMD_12AVG)+
(SUM_MONTH32-DEMD_12AVG)*(SUM_MONTH32-DEMD_12AVG)+
(SUM_MONTH33-DEMD_12AVG)*(SUM_MONTH33-DEMD_12AVG)+
(SUM_MONTH34-DEMD_12AVG)*(SUM_MONTH34-DEMD_12AVG)+
(SUM_MONTH35-DEMD_12AVG)*(SUM_MONTH35-DEMD_12AVG)+
(SUM_MONTH36-DEMD_12AVG)*(SUM_MONTH36-DEMD_12AVG))/11)),2) AS VAR_CHECK
FROM
(SELECT 
SPIKEPL_MM1.PROD_LINE,
SPIKEPL_MM1.SUM_MONTH25,
SPIKEPL_MM2.SUM_MONTH26,
SPIKEPL_MM3.SUM_MONTH27,
SPIKEPL_MM4.SUM_MONTH28,
SPIKEPL_MM5.SUM_MONTH29,
SPIKEPL_MM6.SUM_MONTH30,
SPIKEPL_MM7.SUM_MONTH31,
SPIKEPL_MM8.SUM_MONTH32,
SPIKEPL_MM9.SUM_MONTH33,
SPIKEPL_MM10.SUM_MONTH34,
SPIKEPL_MM11.SUM_MONTH35,
SPIKEPL_MM12.SUM_MONTH36,
ROUND((SPIKEPL_MM1.SUM_MONTH25+
SPIKEPL_MM2.SUM_MONTH26+
SPIKEPL_MM3.SUM_MONTH27+
SPIKEPL_MM4.SUM_MONTH28+
SPIKEPL_MM5.SUM_MONTH29+
SPIKEPL_MM6.SUM_MONTH30+
SPIKEPL_MM7.SUM_MONTH31+
SPIKEPL_MM8.SUM_MONTH32+
SPIKEPL_MM9.SUM_MONTH33+
SPIKEPL_MM10.SUM_MONTH34+
SPIKEPL_MM11.SUM_MONTH35+
SPIKEPL_MM12.SUM_MONTH36)/11,2) AS DEMD_12AVG
FROM VIEW_INV_SAP_SPIKEPLPA15_MM1 SPIKEPL_MM1,
VIEW_INV_SAP_SPIKEPLPA15_MM2 SPIKEPL_MM2,
VIEW_INV_SAP_SPIKEPLPA15_MM3 SPIKEPL_MM3,
VIEW_INV_SAP_SPIKEPLPA15_MM4 SPIKEPL_MM4,
VIEW_INV_SAP_SPIKEPLPA15_MM5 SPIKEPL_MM5,
VIEW_INV_SAP_SPIKEPLPA15_MM6 SPIKEPL_MM6,
VIEW_INV_SAP_SPIKEPLPA15_MM7 SPIKEPL_MM7,
VIEW_INV_SAP_SPIKEPLPA15_MM8 SPIKEPL_MM8,
VIEW_INV_SAP_SPIKEPLPA15_MM9 SPIKEPL_MM9,
VIEW_INV_SAP_SPIKEPLPA15_MM10 SPIKEPL_MM10,
VIEW_INV_SAP_SPIKEPLPA15_MM11 SPIKEPL_MM11,
VIEW_INV_SAP_SPIKEPLPA15_MM12 SPIKEPL_MM12
WHERE SPIKEPL_MM1.PROD_LINE = SPIKEPL_MM2.PROD_LINE
AND SPIKEPL_MM2.PROD_LINE = SPIKEPL_MM3.PROD_LINE
AND SPIKEPL_MM3.PROD_LINE = SPIKEPL_MM4.PROD_LINE
AND SPIKEPL_MM4.PROD_LINE = SPIKEPL_MM5.PROD_LINE
AND SPIKEPL_MM5.PROD_LINE = SPIKEPL_MM6.PROD_LINE
AND SPIKEPL_MM6.PROD_LINE = SPIKEPL_MM7.PROD_LINE
AND SPIKEPL_MM7.PROD_LINE = SPIKEPL_MM8.PROD_LINE
AND SPIKEPL_MM8.PROD_LINE = SPIKEPL_MM9.PROD_LINE
AND SPIKEPL_MM9.PROD_LINE = SPIKEPL_MM10.PROD_LINE
AND SPIKEPL_MM10.PROD_LINE = SPIKEPL_MM11.PROD_LINE
AND SPIKEPL_MM11.PROD_LINE = SPIKEPL_MM12.PROD_LINE
);






SELECT 
  PLANT||'_'||PROD_LINE,
  TYPE,
  ID,
  MATERIAL,
  PLANT,
  CATALOG_DASH,
  BULLETIN,
  MAT_DESC,
  SAFETY_STOCK,
  PROD_BU,
  PROD_FAM,
  PROD_HIERARCHY,
  PROD_LINE,
  PRO_LINE_DES,
  PROC_TYPE,
  STRATEGY_GRP,
  MATL_TYPE,
  VENDOR_KEY,
  UNIT,
  MONTH_25,
  MONTH_26,
  MONTH_27,
  MONTH_28,
  MONTH_29,
  MONTH_30,
  MONTH_31,
  MONTH_32,
  MONTH_33,
  MONTH_34,
  MONTH_35,
  MONTH_36
FROM VIEW_INV_SAP_SPIKE_ANALYSIS WHERE PLANT IN ('5040','5050')

