


SELECT

  CASE
    WHEN ITEM =13 THEN PROD_HIERARCHY
    ELSE NULL
  END PROD_HIERARCHY_13
  
 SELECT *  FROM INV_SAP_PP_OPT_X;
  
  
CREATE TABLE RALO_BASE_DATA AS
SELECT SALES_PP_X.ID,
  SALES_PP_X.MATERIAL,
  SALES_PP_X.CATALOG_DASH,
  SALES_PP_X.PLANT,
  SALES_PP_X.VENDOR,
  SALES_PP_X.BU,
  SALES_PP_X.STRATEGY_GRP,
  SALES_PP_X.MRP_TYPE,
  SALES_PP_X.SAFETY_STOCK,
  SALES_PP_X.AVG13_USAGE_QTY,
  SALES_PP_X.AVG26_USAGE_QTY,
  SALES_PP_X.LEAD_TIME,
  SALES_PP_X.UNIT_COST,
  SALES_PP_X.UNIT,
  SALES_PP_X.MRP_CONTROLLER,
  FC_AVG13_WEEK.FC_AVG13_WEEK_QTY,
  SALES_PP_X.OH_QTY,
  SALES_PP_X.ULTIMATE_SOURCE
FROM
  (SELECT ID,
    MATERIAL,
    PLANT,
    CATALOG_DASH,
    SAFETY_STOCK,
    OH_QTY,
    STRATEGY_GRP,
    MRP_TYPE,
    SUBSTR(VENDOR_KEY,0,4) AS VENDOR,
    SUBSTR(PROD_BU,0,3)    AS BU,
    AVG13_USAGE_QTY,
    AVG26_USAGE_QTY,
    LEAD_TIME,
    UNIT_COST,
    UNIT,
    MRP_CONTROLLER,
    ULTIMATE_SOURCE
  FROM INV_SAP_PP_OPT_X
  )SALES_PP_X
LEFT JOIN
  ---FC 13 WEEKS AVG
  (
  SELECT MATERIALID
    ||'_'
    ||PLANTID                           AS ID,
    MATERIALID                          AS MATERIALID,
    PLANTID                             AS PLANTID,
    CEIL(SUM(PLNMG_PLANNEDQUANTITY)/13) AS FC_AVG13_WEEK_QTY
  FROM INV_SAP_PP_FRCST_PBIM_ALL
  WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 91))
  AND VERSBP_VERSION = '00'
  GROUP BY MATERIALID,
    PLANTID
  )FC_AVG13_WEEK
ON SALES_PP_X.ID = FC_AVG13_WEEK.ID;


--MAX NUM
SELECT ID,
  MATERIAL,
  PLANT,
  AVG26_USAGE_QTY,
  FC_AVG13_WEEK_QTY,
  SAFETY_STOCK,
  CASE
    WHEN AVG26_USAGE_QTY > NVL(FC_AVG13_WEEK_QTY,0)
    THEN AVG26_USAGE_QTY + 0.5*SAFETY_STOCK 
    ELSE NVL(FC_AVG13_WEEK_QTY,0)  + 0.5*SAFETY_STOCK 
  END STOCK_TH,
  CASE
    WHEN AVG26_USAGE_QTY > NVL(FC_AVG13_WEEK_QTY,0)
    THEN AVG26_USAGE_QTY*4
    ELSE NVL(FC_AVG13_WEEK_QTY,0)*4
  END LO_TH
FROM RALO_BASE_DATA WHERE STRATEGY_GRP = '40';





