




SELECT * FROM INV_SAP_PP_SERVICE_LEVELS_0204 WHERE PLANTID = '5071';


CREATE TABLE INV_SAP_PP_SERVICE_LEVELS_0204 AS
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_SERVICE_LEVELS@ROCKWELL_DW_DBLINK WHERE PLANTID = '5071'; 