-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Description:
--
--  This file just use for test new functions, procedures, package..
--
-- Revision History:
--
--    Date        Developer         Description
--    ---------   ---------------   -------------------------------------------
--    2014-12-24  Moyue           	Initial testing area.
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------

--Create testing table
DROP TABLE EMPLOYEE;
CREATE TABLE EMPLOYEE
  (
    ID     NUMBER(10) NOT NULL ,
    SALARY NUMBER(8, 2) DEFAULT 0 NOT NULL ,
    NAME   VARCHAR(20) NOT NULL
  );
  
SELECT * FROM EMPLOYEE;

DECLARE
   T_NAME VARCHAR(200);
   T_SQL VARCHAR(200);
   T_SQL_C VARCHAR(200);
   UPDATE_COUNT number;
BEGIN

  UPDATE_COUNT :=   SQL%ROWCOUNT;
  SYS.DBMS_OUTPUT.PUT_LINE('as');
  SYS.DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);
END;


DECLARE
  RECORD_COUNT NUMBER;
BEGIN
  RECORD_COUNT := 0;
  SELECT COUNT(*) INTO RECORD_COUNT FROM INV_SAP_PP_OPTIMIZATION;
  SYS.DBMS_OUTPUT.PUT_LINE(RECORD_COUNT);
END;



BEGIN 

APAFC_MSG_PRINT(121);
END;
INSERT INTO EMPLOYEE VALUES(1,22,TEST)


analyze table INV_SAP_PP_OPTIMIZATION estimate  statistics sample 40 percent

se
    SELECT COUNT(*)
    FROM INV_SAP_PP_OPTIMIZATION
    
    
    
    
   CREATE OR REPLACE PROCEDURE APAFC_REFH_WKLY_SOHST_test
IS
  STEP_NAME          VARCHAR2(100);
  PROCESS_TERMINATED EXCEPTION;
BEGIN
  STEP_NAME := 'Refresh SO Hst Data by weekly. Tue 11:30AM..';
  --TRUNCATE TABLE.
   APAFC_TRUNCATE('INV_SAP_SALES_HST_bk1'); -- SOHST
  APAFC_SCRIPT_EXE_IMMEDIATE('INSERT INTO INV_SAP_SALES_HST_bk1  
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('||5040||', '||5050||', '||5100||', '||5110||', '||5120||', '||5160||', '||5190||', '||5200||','||5070||','||5140||')');

   COMMIT;
EXCEPTION
WHEN OTHERS THEN
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Execute Error:');
  DBMS_OUTPUT.PUT_LINE(SUBSTR(DBMS_UTILITY.FORMAT_ERROR_STACK,1,200)||SUBSTR(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,1,200));
  RAISE PROCESS_TERMINATED;
END APAFC_REFH_WKLY_SOHST_test; 
    
    create table INV_SAP_SALES_HST_LC_tes
    as select * from INV_SAP_SALES_HST_LC
    select * from INV_SAP_SALES_HST_LC_tes where id = 'PN-C40778_5200';
    
    begin
   
  
  --CREATION DATE&LAST_GI_DATE
  APAFC_CREATE_INDEX('INDEX_LC_SOHST_CD','INV_SAP_SALES_HST_LC','CREATION_DATE');
	APAFC_CREATE_INDEX('INDEX_LC_SOHST_LSTGID','INV_SAP_SALES_HST_LC','LAST_GI_DATE');
    end;

    
    
    select * from INV_SAP_SALES_HST;
    
    create table INV_SAP_SALES_HST_bk1 as
    select * from INV_SAP_SALES_HST_bk;
    
    
    
    
    INV_SAP_SALES_HST_LC_TEST_bk
drop table INV_SAP_SALES_HST_LC_TEST;
CREATE TABLE INV_SAP_SALES_HST_BK AS
SELECT * from INV_SAP_SALES_HST;


INSERT INTO INV_SAP_SALES_HST_LC_TEST_bk SELECT * FROM INV_SAP_SALES_HST_LC_TEST
INSERT INTO INV_SAP_SALES_HST_LC_TEST SELECT * FROM INV_SAP_SALES_HST_LC_TEST_bk
SELECT * FROM INV_SAP_SALES_HST_LC;
DECLARE
te varchar2(2000);
BEGIN
APAFC_INSERT('INV_SAP_SALES_HST_LC_TEST_bk','INV_SAP_SALES_HST_LC_TEST');
end;



begin
  APAFC_DROP('INDEX_LC_SOHST_ID','INDEX');
  APAFC_DROP('INDEX_DSTR_STATS_ID','INDEX');
  APAFC_DROP('INDEX_DSTR_QSLIST_ID','INDEX');
end;  
  

	APAFC_CREATE_INDEX('INDEX_LC_SOHST_ID','INV_SAP_SALES_HST_LC','ID');
	APAFC_CREATE_INDEX('INDEX_DSTR_STATS_ID','INV_SAP_DSTR_STATS','ID');
	APAFC_CREATE_INDEX('INDEX_DSTR_QSLIST_ID','INV_SAP_DSTR_QSTATSLIST','ID');
	
  --Material
	APAFC_CREATE_INDEX('INDEX_LC_SOHST_MATL','INV_SAP_SALES_HST_LC','MATERIAL');
	APAFC_CREATE_INDEX('INDEX_DSTR_QSLIST_MATL','INV_SAP_DSTR_QSTATSLIST','MATERIAL');
	
	--So number
	APAFC_CREATE_INDEX('INDEX_LC_SOHST_SOD','INV_SAP_SALES_HST_LC','SALES_DOC');
	
	--PLANTID
	APAFC_CREATE_INDEX('INDEX_LC_SOHST_PLT','INV_SAP_SALES_HST_LC','PLANT');
	
	--SOLDTOPARTY
	APAFC_CREATE_INDEX('INDEX_LC_SOHST_STP','INV_SAP_SALES_HST_LC','SOLD_TO_PARTY');
	APAFC_CREATE_INDEX('INDEX_DSTR_QSLIST_STP','INV_SAP_DSTR_QSTATSLIST','SOLD_TO_NAME');

  APAFC_CREATE_INDEX('INDEX_LC_SOHST_CD','INV_SAP_SALES_HST_LC','CREATION_DATE');
  APAFC_CREATE_INDEX('INDEX_LC_SOHST_LSTGID','INV_SAP_SALES_HST_LC','LAST_GI_DATE');
end;

select * from INV_SAP_SHIP_SOLD_TO_PARTYID where SHIP_SOLD_TOPARTY = '596212';



begin
APAFC_CREATE_INDEX('INDEX_LC_SOHST_CD','INV_SAP_SALES_HST_LC','CREATION_DATE');
end;


begin
APAFC_REFH_WKLY_SOHST_LC;
end;


DECLARE
CHK_EXIST_LC NUMBER;
CHK_EXIST_LC1 NUMBER;
begin
SELECT COUNT(*) INTO CHK_EXIST_LC FROM USER_TABLES WHERE TABLE_NAME = 'INV_2SAP_SALES_HST_LC';
CHK_EXIST_LC1 := 0;
IF CHK_EXIST_LC > 0&& CHK_EXIST_LC1 = 0 THEN
APAFC_MSG_PRINT(CHK_EXIST_LC);
ELSE
APAFC_MSG_PRINT('NO EXIST!');
END IF;
end;

select count(*) from user_tables where table_name='INV_SAP_SALES_HST22_LC'; 
SELECT 
    LPAD(SHIP_SOLD_TOPARTY,10,'0'),
    SOLD_TO_PARTY_NAME,
    SOLD_TO_CITY,
    SOLD_TO_POSTAL_CODE,
    SOLD_TO_COUNTRY
    FROM INV_SAP_SHIP_SOLD_TO_PARTYID WHERE SHIP_TO_PARTY_NAME IS NULL


select count(*) from INV_SAP_SHIP_SOLD_TO where SHIP_SOLD_TO_PARTY = '0000596212';

select object_name(object_id) tableName,name,type_desc from SYSTEM.indexes where name='INDEX_LC_SOHST_ID'



select object_name(object_id) tableName,name,type_desc from sys.indexes where object_name(object_id)='stu'

SELECT * FROM sys.indexes;

select COUNT(*) from user_indexes

DECLARE
CHK_EXIST_LC NUMBER;
begin
SELECT COUNT(*) INTO CHK_EXIST_LC FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_ID';

IF CHK_EXIST_LC > 0 THEN
APAFC_MSG_PRINT(CHK_EXIST_LC);
ELSE
APAFC_MSG_PRINT('NO EXIST!');
END IF;
end;

DECLARE
STEP_NAME varchar2(2000);
COUNT_LC NUMBER;
COUNT_DSTRS NUMBER;
COUNT_DSTRQ NUMBER;

COUNT_IDX_SOHST_ID NUMBER;
COUNT_IDX_STATS_ID NUMBER;
COUNT_IDX_QSLIST_ID NUMBER;
COUNT_IDX_SOHST_MATL NUMBER;
COUNT_IDX_QSLIST_MATL NUMBER;
COUNT_IDX_SOHST_PLT NUMBER;
COUNT_IDX_SOHST_STP NUMBER;
COUNT_IDX_QSLIST_STP NUMBER;
COUNT_IDX_SOHST_CD NUMBER;
COUNT_IDX_SOHST_LSTGID NUMBER;
COUNT_IDX_SOHST_SOD NUMBER;

CHK_TABLES_EXIST NUMBER;
CHK_INDEX_EXIST NUMBER;

BEGIN
	STEP_NAME := 'So hst local version init';
  
  --Check tables&index exist.
  SELECT COUNT(*) INTO COUNT_LC FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_SALES_HST_LC';
  SELECT COUNT(*) INTO COUNT_DSTRS FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_DSTR_STATS';
  SELECT COUNT(*) INTO COUNT_DSTRQ FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_DSTR_QSTATSLIST';
  
  SELECT COUNT(*) INTO COUNT_IDX_SOHST_ID FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_ID';
  SELECT COUNT(*) INTO COUNT_IDX_STATS_ID FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_DSTR_STATS_ID';
  SELECT COUNT(*) INTO COUNT_IDX_QSLIST_ID FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_DSTR_QSLIST_ID';
  SELECT COUNT(*) INTO COUNT_IDX_SOHST_MATL FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_MATL';
  SELECT COUNT(*) INTO COUNT_IDX_QSLIST_MATL FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_DSTR_QSLIST_MATL';
  SELECT COUNT(*) INTO COUNT_IDX_SOHST_SOD FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_SOD';
  SELECT COUNT(*) INTO COUNT_IDX_SOHST_PLT FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_PLT';
  SELECT COUNT(*) INTO COUNT_IDX_SOHST_STP FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_STP';
  SELECT COUNT(*) INTO COUNT_IDX_QSLIST_STP FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_DSTR_QSLIST_STP';
  SELECT COUNT(*) INTO COUNT_IDX_SOHST_CD FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_CD';
  SELECT COUNT(*) INTO COUNT_IDX_SOHST_LSTGID FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_LS1TGID';
  
  CHK_TABLES_EXIST := COUNT_LC*COUNT_DSTRS*COUNT_DSTRQ;
  CHK_INDEX_EXIST := COUNT_IDX_SOHST_ID*COUNT_IDX_STATS_ID*COUNT_IDX_QSLIST_ID*COUNT_IDX_SOHST_MATL*COUNT_IDX_QSLIST_MATL*COUNT_IDX_SOHST_SOD*COUNT_IDX_SOHST_PLT*COUNT_IDX_SOHST_STP*COUNT_IDX_QSLIST_STP*COUNT_IDX_SOHST_CD*COUNT_IDX_SOHST_LSTGID;
  
  APAFC_MSG_PRINT(CHK_TABLES_EXIST);
  APAFC_MSG_PRINT(CHK_INDEX_EXIST);

END;

select * from INV_SAP_SALES_HST_LC_TES;
DECLARE
COUNT_LC NUMBER;
BEGIN 

  SELECT COUNT(*) INTO COUNT_LC FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_SALES_HST_LC_TES';

  IF COUNT_LC > 0 THEN
    APAFC_DROP('INV_SAP_SALES_HST_LC_TES','TABLE');
    COMMIT;
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE  INV_SAP_SALES_HST_LC_TES AS SELECT * FROM INV_SAP_SALES_HST_LC'); -- SOHST VIEW TO TABLE.
    COMMIT;
  ELSE
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE  INV_SAP_SALES_HST_LC_TES AS SELECT * FROM INV_SAP_SALES_HST_LC'); -- SOHST VIEW TO TABLE.
    COMMIT;
  END IF;
END;


begin
APAFC_DROP('INV_SAP_SALES_HST_LC_TES','TABLE');
end;


begin

	APAFC_CREATE_INDEX('INDEX_LC_SOHST_MATL11','INV_SAP_SALES_HST_LC_TES','MATERIAL');

end;









COUNT_IDX_SOHST_MATL NUMBER;
COUNT_IDX_QSLIST_MATL NUMBER;
COUNT_IDX_SOHST_PLT NUMBER;
COUNT_IDX_SOHST_STP NUMBER;
COUNT_IDX_QSLIST_STP NUMBER;
COUNT_IDX_SOHST_CD NUMBER;
COUNT_IDX_SOHST_LSTGID NUMBER;
COUNT_IDX_SOHST_SOD NUMBER;






  SELECT COUNT(*) INTO COUNT_IDX_SOHST_MATL FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_MATL';
  SELECT COUNT(*) INTO COUNT_IDX_QSLIST_MATL FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_DSTR_QSLIST_MATL';
  SELECT COUNT(*) INTO COUNT_IDX_SOHST_SOD FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_SOD';
  SELECT COUNT(*) INTO COUNT_IDX_SOHST_PLT FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_PLT';
  SELECT COUNT(*) INTO COUNT_IDX_SOHST_STP FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_STP';
  SELECT COUNT(*) INTO COUNT_IDX_QSLIST_STP FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_DSTR_QSLIST_STP';
  SELECT COUNT(*) INTO COUNT_IDX_SOHST_CD FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_CD';
  SELECT COUNT(*) INTO COUNT_IDX_SOHST_LSTGID FROM USER_INDEXES WHERE INDEX_NAME = 'INDEX_LC_SOHST_LSTGID';


DECLARE
COUNT_LC NUMBER;
BEGIN
SELECT COUNT(*) INTO COUNT_LC FROM INV_SAP_SALES_HS11T;
APAFC_MSG_PRINT(COUNT_LC);
END;


  IF COUNT_SOLDTO > 0 THEN
    IF CHK_SOLDTO > 0 THEN
      APAFC_TRUNCATE('INV_SAP_SHIP_SOLD_TO'); -- SOHST
      COMMIT;
        APAFC_SCRIPT_EXE_IMMEDIATE(INSERT_INV_SS_A);
        APAFC_SCRIPT_EXE_IMMEDIATE(INSERT_INV_SS_B);
      COMMIT;
    ELSE
        APAFC_SCRIPT_EXE_IMMEDIATE(INSERT_INV_SS_A);
        APAFC_SCRIPT_EXE_IMMEDIATE(INSERT_INV_SS_B);
      COMMIT;
    END IF;
  ELSE
    APAFC_SCRIPT_EXE_IMMEDIATE(SOLDTO_INIT);
      COMMIT;
      APAFC_SCRIPT_EXE_IMMEDIATE(INSERT_INV_SS_A);
      APAFC_SCRIPT_EXE_IMMEDIATE(INSERT_INV_SS_B);
      COMMIT;
  END IF;


  IF COUNT_PARTYID > 0 THEN
    IF CHK_PARTYID > 0 THEN
		APAFC_TRUNCATE('INV_SAP_SHIP_SOLD_TO_PARTYID'); -- SOHST
      COMMIT;
        APAFC_SCRIPT_EXE_IMMEDIATE('INSERT INTO INV_SAP_SHIP_SOLD_TO_PARTYID SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SHIP_SOLD_TO_PARTYID@ROCKWELL_DW_DBLINK');
      COMMIT;
    ELSE
      APAFC_SCRIPT_EXE_IMMEDIATE('INSERT INTO INV_SAP_SHIP_SOLD_TO_PARTYID SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SHIP_SOLD_TO_PARTYID@ROCKWELL_DW_DBLINK');
      COMMIT;
    END IF;
  ELSE
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE INV_SAP_SHIP_SOLD_TO_PARTYID AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SHIP_SOLD_TO_PARTYID@ROCKWELL_DW_DBLINK');
    COMMIT;
  END IF;



DECLARE
  STEP_NAME          VARCHAR2(100);
  PROCESS_TERMINATED EXCEPTION;
  INSERT_INV_SS_A  VARCHAR2(1000);
  INSERT_INV_SS_B  VARCHAR2(1000);
--  CHK_PARTYID NUMBER;
--  CHK_SOLDTO NUMBER;
  COUNT_PARTYID NUMBER;
  COUNT_SOLDTO NUMBER;
  
BEGIN
APAFC_REFH_WKLY_SHIPSOLDTO;

END;

select count(*) from INV_SAP_SHIP_SOLD_TO where SHIP_SOLD_TO_PARTY_NAME = 'Offshore Industries Sdn Bhd'

select * from INV_SAP_SHIP_SOLD_TO_PARTYID where SHIP_TO_PARTY_NAME = 'Offshore Industries Sdn Bhd'
select count(*) from (select distinct * from INV_SAP_SHIP_SOLD_TO)

select * from INV_SAP_DSTR_QSTATSLIST WHERE ID = 'MVD-ENG SERVICES_5200';



declare 
start_t varchar2(1000);

begin
 TIMER.start_timer;
 dbms_output.put_line('this is a test');
  dbms_lock.sleep(2);
 TIMER.show_elapsed('test program',start_t);
 APAFC_MSG_PRINT(start_t);
end;


DECLARE
C_TIME_GAP varchar2(1000);
BEGIN
select to_char(sysdate,'yyyy-MM-dd HH24:mi:ss') into C_TIME_GAP from dual;
APAFC_MSG_PRINT(C_TIME_GAP);
END;


select to_char(sysdate,'yyyy-MM-dd HH24:mi:ss') from dual;