-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Project Name : APAFC
-- Version : 1.0
-- Description:
-- Table Init
-- Revision History:
--    Date        Developer         Description
--    ---------   ---------------   ----------------------------------------------------
--    2014-4-16   Moyue           	large Order Capture...
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------

--Dig Inv for non-stock item(have free-stock), item value > 10K.
--Want to check demand from AP and global open sto, not ship yet.
--See the oppotini...