-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Project Name : APAFC
-- Version : 1.0
-- Description:
-- Table Init
-- Revision History:
--    Date        Developer         Description
--    ---------   ---------------   ----------------------------------------------------
--    2015-12-03    Moyue           SO risk analysis
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------


SELECT
SO_HST_365.ID,
SO_HST_365.PLANT,
SO_HST_365.MATERIAL,
SO_HST_365.CATALOG#,
SO_HST_365.SALES_DOC,
SO_HST_365.ITEM,
SO_HST_365.ORDER_TIME_SPAN,
SO_HST_365.COMMITTED_DATE,
SO_HST_365.CONFIRM_DELI_DATE,
SO_HST_365.CREATION_DATE,
SO_HST_365.REQUIRE_DELI_DATE,
SO_HST_365.SO_TYPE,
SO_HST_365.ORDER_QTY,
SO_HST_365.OPEN_QTY,
NVL(FREE_OH.FREE_OH_QTY + SO_HST_365.OPEN_QTY, 0) AS OH_STATUS
FROM
(
SELECT
ID,
PLANT,
MATERIAL,
CATALOG#,
SALES_DOC,
ITEM,
ORDER_TIME_SPAN,
COMMITTED_DATE,
CONFIRM_DELI_DATE,
CREATION_DATE,
REQUIRE_DELI_DATE,
SO_TYPE,
ORDER_QTY,
OPEN_QTY
FROM
(
SELECT MATERIALID
  ||'_'
  ||PLANTID                                    AS ID,
  PLANTID                                      AS PLANT,
  MATERIALID                                   AS MATERIAL,
  CATALOGID                                    AS CATALOG#,
  SALESDOC                                     AS SALES_DOC,
  SALESDOCITEM                                 AS ITEM,
  NVL(REQUIREDDELIVERYDATE-LINECREATIONDATE,0) AS ORDER_TIME_SPAN,
  TO_CHAR(COMMITTEDDATE,'MM/DD/YYYY')          AS COMMITTED_DATE,
  TO_CHAR(CONFIRMEDDELIVERYDATE,'MM/DD/YYYY')  AS CONFIRM_DELI_DATE,
  TO_CHAR(LINECREATIONDATE,'MM/DD/YYYY')       AS CREATION_DATE,
  TO_CHAR(REQUIREDDELIVERYDATE,'MM/DD/YYYY')   AS REQUIRE_DELI_DATE,
  SALESDOCTYPE                                 AS SO_TYPE,
  ORDERQTY                                     AS ORDER_QTY,
  OPENQTY                                      AS OPEN_QTY
FROM INV_SAP_SALES_HST
WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140') AND OPENQTY > 0
)WHERE ORDER_TIME_SPAN > 365
)SO_HST_365
LEFT JOIN
(
SELECT 
OH_QTY.ID AS ID,
NVL(OH_QTY.OH_QTY-SO_OPEN.TOT_OPEN_QTY, 0) AS FREE_OH_QTY
FROM
(
SELECT ID,
      OH_QTY
    FROM INV_SAP_PP_OPT_X
    )OH_QTY
LEFT JOIN
(
SELECT MATERIALID
  ||'_'
  ||PLANTID AS ID,
  MATERIALID,
  PLANTID,
  NVL(SUM(OPENQTY),0) AS TOT_OPEN_QTY
FROM INV_SAP_SALES_HST WHERE OPENQTY > 0
GROUP BY MATERIALID,
  PLANTID
)SO_OPEN
ON SO_OPEN.ID = OH_QTY.ID
)FREE_OH
ON FREE_OH.ID = SO_HST_365.ID


------------------------------------------------------------------------------------------------------------------------
--V1.0
DROP VIEW VIEW_INV_SAP_RISK_BUY;
CREATE VIEW VIEW_INV_SAP_RISK_BUY AS
  SELECT REQ_AP_SGU.REQ_ID         AS REQ_ID,
  REQ_AP_SGU.REQ_PLANT           AS REQ_PLANT,
  REQ_AP_SGU.REQ_MATERIAL        AS REQ_MATERIAL,
  REQ_AP_SGU.REQ_CATALOG_DASH    AS REQ_CATALOG_DASH,
  REQ_AP_SGU.REQ_AVG26_USAGE_QTY AS REQ_AVG26_USAGE_QTY,
  REQ_AP_SGU.REQ_DELIVERY_UNIT   AS REQ_DELIVERY_UNIT,
  REQ_AP_SGU.REQ_D_CHAIN_DES     AS REQ_D_CHAIN_DES,
  REQ_AP_SGU.REQ_STRATEGY_GRP    AS REQ_STRATEGY_GRP,
  REQ_AP_SGU.LOT_ROUNDING_VALUE    AS LOT_ROUNDING_VALUE,
  REQ_AP_SGU.MRP_TYPE            AS MRP_TYPE,
  REQ_AP_SGU.MATL_TYPE           AS MATL_TYPE,
  REQ_AP_SGU.REQ_VENDOR_ITEM     AS REQ_VENDOR_ITEM,
  REQ_AP_SGU.APT_AVG26_USAGE_QTY AS APT_AVG26_USAGE_QTY,
  REQ_AP_SGU.REQ_UNIT_COST       AS REQ_UNIT_COST,
  REQ_AP_SGU.AP_SG_CHECK         AS AP_SG_CHECK,
  VENDOR.AVG26_USAGE_QTY         AS VEN_AVG26_USG_QTY,
  VENDOR.STRATEGY_GRP            AS VEN_STRATEGY_GRP
FROM
  (SELECT REQ_AP_USG.REQ_ID        AS REQ_ID,
    REQ_AP_USG.REQ_PLANT           AS REQ_PLANT,
    REQ_AP_USG.REQ_MATERIAL        AS REQ_MATERIAL,
    REQ_AP_USG.REQ_CATALOG_DASH    AS REQ_CATALOG_DASH,
    REQ_AP_USG.REQ_AVG26_USAGE_QTY AS REQ_AVG26_USAGE_QTY,
    REQ_AP_USG.REQ_DELIVERY_UNIT   AS REQ_DELIVERY_UNIT,
    REQ_AP_USG.REQ_D_CHAIN_DES     AS REQ_D_CHAIN_DES,
    REQ_AP_USG.REQ_STRATEGY_GRP    AS REQ_STRATEGY_GRP,
    REQ_AP_USG.LOT_ROUNDING_VALUE    AS LOT_ROUNDING_VALUE,
    REQ_AP_USG.MRP_TYPE            AS MRP_TYPE,
    REQ_AP_USG.MATL_TYPE           AS MATL_TYPE,
    REQ_AP_USG.REQ_UNIT_COST       AS REQ_UNIT_COST,
    REQ_AP_USG.REQ_VENDOR_ITEM     AS REQ_VENDOR_ITEM,
    REQ_AP_USG.APT_AVG26_USAGE_QTY AS APT_AVG26_USAGE_QTY,
    AP_SG.SG_CHECK                 AS AP_SG_CHECK
  FROM
    (SELECT REQ_PLANT.ID              AS REQ_ID,
      REQ_PLANT.PLANT                 AS REQ_PLANT,
      REQ_PLANT.MATERIAL              AS REQ_MATERIAL,
      REQ_PLANT.CATALOG_DASH          AS REQ_CATALOG_DASH,
      REQ_PLANT.AVG26_USAGE_QTY       AS REQ_AVG26_USAGE_QTY,
      REQ_PLANT.DELIVERY_UNIT         AS REQ_DELIVERY_UNIT,
      REQ_PLANT.D_CHAIN_DES           AS REQ_D_CHAIN_DES,
      REQ_PLANT.STRATEGY_GRP          AS REQ_STRATEGY_GRP,
      REQ_PLANT.LOT_ROUNDING_VALUE    AS LOT_ROUNDING_VALUE,
      REQ_PLANT.MRP_TYPE              AS MRP_TYPE,
      REQ_PLANT.MATL_TYPE             AS MATL_TYPE,
      REQ_PLANT.UNIT_COST             AS REQ_UNIT_COST,
      REQ_PLANT.VENDOR_ITEM           AS REQ_VENDOR_ITEM,
      AP_USAGE.TOT_AP_AVG26_USAGE_QTY AS APT_AVG26_USAGE_QTY
    FROM
      (SELECT PP_OPT.ID        AS ID,
        PP_OPT.PLANT           AS PLANT,
        PP_OPT.MATERIAL        AS MATERIAL,
        PP_OPT.CATALOG_DASH    AS CATALOG_DASH,
        PP_OPT.AVG26_USAGE_QTY AS AVG26_USAGE_QTY,
        PP_OPT.DELIVERY_UNIT   AS DELIVERY_UNIT,
        PP_OPT.D_CHAIN_BLK     AS D_CHAIN_BLK,
        D_CH.DES               AS D_CHAIN_DES,
        PP_OPT.STRATEGY_GRP    AS STRATEGY_GRP,
        PP_OPT.LOT_ROUNDING_VALUE    AS LOT_ROUNDING_VALUE,
        PP_OPT.MATL_TYPE       AS MATL_TYPE,
        PP_OPT.MRP_TYPE        AS MRP_TYPE,
        PP_OPT.UNIT_COST       AS UNIT_COST,
        PP_OPT.VENDOR_ITEM     AS VENDOR_ITEM
      FROM
        (SELECT ID,
          PLANT,
          MATERIAL,
          CATALOG_DASH,
          AVG26_USAGE_QTY,
          DELIVERY_UNIT,
          D_CHAIN_BLK,
          STRATEGY_GRP,
          LOT_ROUNDING_VALUE,
          MATL_TYPE,
          MRP_TYPE,
          UNIT_COST,
          VENDOR_ITEM
        FROM INV_SAP_PP_OPT_X
        )PP_OPT
      LEFT JOIN
        ( SELECT D_CHAIN,DES FROM INV_SAP_PP_DCHAIN
        )D_CH
      ON D_CH.D_CHAIN = PP_OPT.D_CHAIN_BLK
      )REQ_PLANT
    LEFT JOIN
      (SELECT MATERIAL,
        NVL(SUM(AVG26_USAGE_QTY),0) AS TOT_AP_AVG26_USAGE_QTY
      FROM INV_SAP_PP_OPT_X
      WHERE PLANT IN ('5040', '5100', '5200','5070','5140')
      GROUP BY MATERIAL
      )AP_USAGE
    ON AP_USAGE.MATERIAL = REQ_PLANT.MATERIAL
    )REQ_AP_USG
  LEFT JOIN
    (SELECT ID,
      CASE
        WHEN SG_CHECK = 'YES'
        THEN '40'
        ELSE 'Z4'
      END SG_CHECK
    FROM INV_SAP_SR_SGCHECK
    )AP_SG
  ON AP_SG.ID = REQ_AP_USG.REQ_ID
  )REQ_AP_SGU
LEFT JOIN
  (SELECT ID,
    AVG26_USAGE_QTY,
    STRATEGY_GRP
  FROM INV_SAP_PP_OPT_X
  WHERE PLANT IN ('1090','1180')
  )VENDOR
ON VENDOR.ID = REQ_AP_SGU.REQ_VENDOR_ITEM;


SELECT * FROM INV_SAP_PP_MVKE WHERE MATERIALID = '80026-975-20-R'
--Catalog Version
SELECT SRB.PLANT,
  V_SRB.REQ_MATERIAL,
  SRB.RB_MATL,
  NVL(SRB.RB_QTY,0),
  nvl(V_SRB.REQ_UNIT_COST,0),
  CEIL(NVL(SRB.RB_QTY,0)*NVL(V_SRB.REQ_UNIT_COST,0)) AS REQ_VAL,
  V_SRB.MRP_TYPE,
  V_SRB.REQ_D_CHAIN_BLK,
  V_SRB.REQ_STRATEGY_GRP,
  NVL(V_SRB.USAGE_3MM,0),
  NVL(V_SRB.AP_SG_CHECK,0),
  NVL(V_SRB.AP_USAGE_2MM,0),
  NVL(V_SRB.VEN_STRATEGY_GRP,0),
  NVL(V_SRB.VEN_USAGE_1MM,0)
FROM
  (SELECT REPLACE(RB_MATL, '-')
    ||'_'
    ||PLANT AS ID,
    PLANT,
    RB_MATL,
    RB_QTY
  FROM INV_SAP_RISK_BUY
  WHERE RB_MATL NOT IN ('#')
  )SRB
LEFT JOIN
  (SELECT REPLACE(REQ_CATALOG_DASH, '-')
    ||'_'
    ||REQ_PLANT AS ID,
    REQ_PLANT,
    REQ_MATERIAL,
    REQ_CATALOG_DASH,
    CEIL(REQ_AVG26_USAGE_QTY*12) AS USAGE_3MM,
    MRP_TYPE,
    REQ_D_CHAIN_BLK,
    REQ_STRATEGY_GRP,
    REQ_VENDOR_ITEM,
    CEIL(APT_AVG26_USAGE_QTY*8) AS AP_USAGE_2MM,
    AP_SG_CHECK,
    REQ_UNIT_COST,
    CEIL(VEN_AVG26_USG_QTY*4) AS VEN_USAGE_1MM,
    VEN_STRATEGY_GRP
  FROM VIEW_INV_SAP_RISK_BUY
  )V_SRB
ON SRB.ID = V_SRB.ID;

--Materials Version
SELECT SRB.PLANT,
  V_SRB.REQ_MATERIAL,
  V_SRB.REQ_CATALOG_DASH,
  NVL(SRB.RB_QTY,0),
  nvl(V_SRB.REQ_UNIT_COST,0),
  CEIL(NVL(SRB.RB_QTY,0)*NVL(V_SRB.REQ_UNIT_COST,0)) AS REQ_VAL,
  V_SRB.MRP_TYPE,
  V_SRB.REQ_D_CHAIN_BLK,
  V_SRB.REQ_STRATEGY_GRP,
  NVL(V_SRB.USAGE_3MM,0),
  NVL(V_SRB.AP_SG_CHECK,0),
  NVL(V_SRB.AP_USAGE_2MM,0),
  NVL(V_SRB.VEN_STRATEGY_GRP,0),
  NVL(V_SRB.VEN_USAGE_1MM,0)
FROM
  (SELECT RB_MATL
    ||'_'
    ||PLANT AS ID,
    PLANT,
    RB_MATL,
    RB_QTY
  FROM INV_SAP_RISK_BUY
  WHERE RB_MATL NOT IN ('#')
  )SRB
LEFT JOIN
  (SELECT REQ_MATERIAL
    ||'_'
    ||REQ_PLANT AS ID,
    REQ_PLANT,
    REQ_MATERIAL,
    REQ_CATALOG_DASH,
    CEIL(REQ_AVG26_USAGE_QTY*12) AS USAGE_3MM,
    MRP_TYPE,
    REQ_D_CHAIN_BLK,
    REQ_STRATEGY_GRP,
    REQ_VENDOR_ITEM,
    CEIL(APT_AVG26_USAGE_QTY*8) AS AP_USAGE_2MM,
    AP_SG_CHECK,
    REQ_UNIT_COST,
    CEIL(VEN_AVG26_USG_QTY*4) AS VEN_USAGE_1MM,
    VEN_STRATEGY_GRP
  FROM VIEW_INV_SAP_RISK_BUY
  )V_SRB
ON SRB.ID = V_SRB.ID;

--V1.1
DROP VIEW VIEW_INV_SAP_RISK_BUY;
CREATE VIEW VIEW_INV_SAP_RISK_BUY AS
SELECT REQ_AP_SGU.REQ_ID         AS REQ_ID,
  REQ_AP_SGU.REQ_PLANT           AS REQ_PLANT,
  REQ_AP_SGU.REQ_MATERIAL        AS REQ_MATERIAL,
  REQ_AP_SGU.REQ_CATALOG_DASH    AS REQ_CATALOG_DASH,
  REQ_AP_SGU.REQ_AVG26_USAGE_QTY AS REQ_AVG26_USAGE_QTY,
  REQ_AP_SGU.REQ_DELIVERY_UNIT   AS REQ_DELIVERY_UNIT,
  REQ_AP_SGU.REQ_D_CHAIN_DES     AS REQ_D_CHAIN_DES,
  REQ_AP_SGU.REQ_STRATEGY_GRP    AS REQ_STRATEGY_GRP,
  REQ_AP_SGU.LOT_ROUNDING_VALUE    AS LOT_ROUNDING_VALUE,
  REQ_AP_SGU.MRP_TYPE            AS MRP_TYPE,
  REQ_AP_SGU.MATL_TYPE           AS MATL_TYPE,
  REQ_AP_SGU.REQ_VENDOR_ITEM     AS REQ_VENDOR_ITEM,
  REQ_AP_SGU.APT_AVG26_USAGE_QTY AS APT_AVG26_USAGE_QTY,
  REQ_AP_SGU.REQ_UNIT_COST       AS REQ_UNIT_COST,
  REQ_AP_SGU.AP_SG_CHECK         AS AP_SG_CHECK,
  VENDOR.AVG26_USAGE_QTY         AS VEN_AVG26_USG_QTY,
  VENDOR.STRATEGY_GRP            AS VEN_STRATEGY_GRP
FROM
  (SELECT REQ_AP_USG.REQ_ID        AS REQ_ID,
    REQ_AP_USG.REQ_PLANT           AS REQ_PLANT,
    REQ_AP_USG.REQ_MATERIAL        AS REQ_MATERIAL,
    REQ_AP_USG.REQ_CATALOG_DASH    AS REQ_CATALOG_DASH,
    REQ_AP_USG.REQ_AVG26_USAGE_QTY AS REQ_AVG26_USAGE_QTY,
    REQ_AP_USG.REQ_DELIVERY_UNIT   AS REQ_DELIVERY_UNIT,
    REQ_AP_USG.REQ_D_CHAIN_DES     AS REQ_D_CHAIN_DES,
    REQ_AP_USG.REQ_STRATEGY_GRP    AS REQ_STRATEGY_GRP,
    REQ_AP_USG.LOT_ROUNDING_VALUE    AS LOT_ROUNDING_VALUE,
    REQ_AP_USG.MRP_TYPE            AS MRP_TYPE,
    REQ_AP_USG.MATL_TYPE           AS MATL_TYPE,
    REQ_AP_USG.REQ_UNIT_COST       AS REQ_UNIT_COST,
    REQ_AP_USG.REQ_VENDOR_ITEM     AS REQ_VENDOR_ITEM,
    REQ_AP_USG.APT_AVG26_USAGE_QTY AS APT_AVG26_USAGE_QTY,
    AP_SG.SG_CHECK                 AS AP_SG_CHECK
  FROM
    (SELECT REQ_PLANT.ID              AS REQ_ID,
      REQ_PLANT.PLANT                 AS REQ_PLANT,
      REQ_PLANT.MATERIAL              AS REQ_MATERIAL,
      REQ_PLANT.CATALOG_DASH          AS REQ_CATALOG_DASH,
      REQ_PLANT.AVG26_USAGE_QTY       AS REQ_AVG26_USAGE_QTY,
      REQ_PLANT.DELIVERY_UNIT         AS REQ_DELIVERY_UNIT,
      REQ_PLANT.D_CHAIN_DES           AS REQ_D_CHAIN_DES,
      REQ_PLANT.STRATEGY_GRP          AS REQ_STRATEGY_GRP,
      REQ_PLANT.LOT_ROUNDING_VALUE    AS LOT_ROUNDING_VALUE,
      REQ_PLANT.MRP_TYPE              AS MRP_TYPE,
      REQ_PLANT.MATL_TYPE             AS MATL_TYPE,
      REQ_PLANT.UNIT_COST             AS REQ_UNIT_COST,
      REQ_PLANT.VENDOR_ITEM           AS REQ_VENDOR_ITEM,
      AP_USAGE.TOT_AP_AVG26_USAGE_QTY AS APT_AVG26_USAGE_QTY
    FROM
      (SELECT PP_OPT.ID        AS ID,
        PP_OPT.PLANT           AS PLANT,
        PP_OPT.MATERIAL        AS MATERIAL,
        PP_OPT.CATALOG_DASH    AS CATALOG_DASH,
        PP_OPT.AVG26_USAGE_QTY AS AVG26_USAGE_QTY,
        PP_OPT.DELIVERY_UNIT   AS DELIVERY_UNIT,
        PP_OPT.D_CHAIN_BLK     AS D_CHAIN_BLK,
        D_CH.DES               AS D_CHAIN_DES,
        PP_OPT.STRATEGY_GRP    AS STRATEGY_GRP,
        PP_OPT.LOT_ROUNDING_VALUE    AS LOT_ROUNDING_VALUE,
        PP_OPT.MATL_TYPE       AS MATL_TYPE,
        PP_OPT.MRP_TYPE        AS MRP_TYPE,
        PP_OPT.UNIT_COST       AS UNIT_COST,
        PP_OPT.VENDOR_ITEM     AS VENDOR_ITEM
      FROM
        (SELECT ID,
          PLANT,
          MATERIAL,
          CATALOG_DASH,
          AVG26_USAGE_QTY,
          DELIVERY_UNIT,
          D_CHAIN_BLK,
          STRATEGY_GRP,
          LOT_ROUNDING_VALUE,
          MATL_TYPE,
          MRP_TYPE,
          UNIT_COST,
          VENDOR_ITEM
        FROM INV_SAP_PP_OPT_X
        )PP_OPT
      LEFT JOIN
        ( SELECT D_CHAIN,DES FROM INV_SAP_PP_DCHAIN
        )D_CH
      ON D_CH.D_CHAIN = PP_OPT.D_CHAIN_BLK
      )REQ_PLANT
    LEFT JOIN
      (SELECT MATERIAL,
        NVL(SUM(AVG26_USAGE_QTY),0) AS TOT_AP_AVG26_USAGE_QTY
      FROM INV_SAP_PP_OPT_X
      WHERE PLANT IN ('5040', '5100', '5200','5070','5140')
      GROUP BY MATERIAL
      )AP_USAGE
    ON AP_USAGE.MATERIAL = REQ_PLANT.MATERIAL
    )REQ_AP_USG
  LEFT JOIN
    (SELECT ID,
      CASE
        WHEN SG_CHECK = 'YES'
        THEN '40'
        ELSE 'Z4'
      END SG_CHECK
    FROM INV_SAP_SR_SGCHECK
    )AP_SG
  ON AP_SG.ID = REQ_AP_USG.REQ_ID
  )REQ_AP_SGU
LEFT JOIN
  (SELECT ID,
    AVG26_USAGE_QTY,
    STRATEGY_GRP
  FROM INV_SAP_PP_OPT_X
  WHERE PLANT IN ('1090','1180')
  )VENDOR
ON VENDOR.ID = REQ_AP_SGU.REQ_VENDOR_ITEM;


SELECT LOT_ROUNDING_VALUE FROM INV_SAP_PP_OPT_X;

---------
--1.Add the Matl type in the view. 
--2.Add D-chain block status in the result. Just like ZN_Sliver. Collect the information from the SAP.
--3.Add the summary tab on the report
--4.Remove the D-chain status in the logic.
--5.The logic chart need to update, remove the D-chain status impact. Change to the other result.
--6.Add the Trim funtion in VBA.

DROP VIEW VIEW_INV_SAP_RISK_BUY;
CREATE VIEW VIEW_INV_SAP_RISK_BUY AS
SELECT REQ_AP_SGU.REQ_ID         AS REQ_ID,
  REQ_AP_SGU.REQ_PLANT           AS REQ_PLANT,
  REQ_AP_SGU.REQ_MATERIAL        AS REQ_MATERIAL,
  REQ_AP_SGU.REQ_CATALOG_DASH    AS REQ_CATALOG_DASH,
  REQ_AP_SGU.REQ_AVG26_USAGE_QTY AS REQ_AVG26_USAGE_QTY,
  REQ_AP_SGU.REQ_DELIVERY_UNIT   AS REQ_DELIVERY_UNIT,
  REQ_AP_SGU.REQ_D_CHAIN_DES     AS REQ_D_CHAIN_DES,
  REQ_AP_SGU.REQ_STRATEGY_GRP    AS REQ_STRATEGY_GRP,
  REQ_AP_SGU.MRP_TYPE            AS MRP_TYPE,
  REQ_AP_SGU.MATL_TYPE           AS MATL_TYPE,
  REQ_AP_SGU.REQ_VENDOR_ITEM     AS REQ_VENDOR_ITEM,
  REQ_AP_SGU.APT_AVG26_USAGE_QTY AS APT_AVG26_USAGE_QTY,
  REQ_AP_SGU.REQ_UNIT_COST       AS REQ_UNIT_COST,
  REQ_AP_SGU.AP_SG_CHECK         AS AP_SG_CHECK,
  VENDOR.AVG26_USAGE_QTY         AS VEN_AVG26_USG_QTY,
  VENDOR.STRATEGY_GRP            AS VEN_STRATEGY_GRP
FROM
  (SELECT REQ_AP_USG.REQ_ID        AS REQ_ID,
    REQ_AP_USG.REQ_PLANT           AS REQ_PLANT,
    REQ_AP_USG.REQ_MATERIAL        AS REQ_MATERIAL,
    REQ_AP_USG.REQ_CATALOG_DASH    AS REQ_CATALOG_DASH,
    REQ_AP_USG.REQ_AVG26_USAGE_QTY AS REQ_AVG26_USAGE_QTY,
    REQ_AP_USG.REQ_DELIVERY_UNIT   AS REQ_DELIVERY_UNIT,
    REQ_AP_USG.REQ_D_CHAIN_DES     AS REQ_D_CHAIN_DES,
    REQ_AP_USG.REQ_STRATEGY_GRP    AS REQ_STRATEGY_GRP,
    REQ_AP_USG.MRP_TYPE            AS MRP_TYPE,
    REQ_AP_USG.MATL_TYPE           AS MATL_TYPE,
    REQ_AP_USG.REQ_UNIT_COST       AS REQ_UNIT_COST,
    REQ_AP_USG.REQ_VENDOR_ITEM     AS REQ_VENDOR_ITEM,
    REQ_AP_USG.APT_AVG26_USAGE_QTY AS APT_AVG26_USAGE_QTY,
    AP_SG.SG_CHECK                 AS AP_SG_CHECK
  FROM
    (SELECT REQ_PLANT.ID              AS REQ_ID,
      REQ_PLANT.PLANT                 AS REQ_PLANT,
      REQ_PLANT.MATERIAL              AS REQ_MATERIAL,
      REQ_PLANT.CATALOG_DASH          AS REQ_CATALOG_DASH,
      REQ_PLANT.AVG26_USAGE_QTY       AS REQ_AVG26_USAGE_QTY,
      REQ_PLANT.DELIVERY_UNIT         AS REQ_DELIVERY_UNIT,
      REQ_PLANT.D_CHAIN_DES           AS REQ_D_CHAIN_DES,
      REQ_PLANT.STRATEGY_GRP          AS REQ_STRATEGY_GRP,
      REQ_PLANT.MRP_TYPE              AS MRP_TYPE,
      REQ_PLANT.MATL_TYPE             AS MATL_TYPE,
      REQ_PLANT.UNIT_COST             AS REQ_UNIT_COST,
      REQ_PLANT.VENDOR_ITEM           AS REQ_VENDOR_ITEM,
      AP_USAGE.TOT_AP_AVG26_USAGE_QTY AS APT_AVG26_USAGE_QTY
    FROM
      (SELECT PP_OPT.ID        AS ID,
        PP_OPT.PLANT           AS PLANT,
        PP_OPT.MATERIAL        AS MATERIAL,
        PP_OPT.CATALOG_DASH    AS CATALOG_DASH,
        PP_OPT.AVG26_USAGE_QTY AS AVG26_USAGE_QTY,
        PP_OPT.DELIVERY_UNIT   AS DELIVERY_UNIT,
        PP_OPT.D_CHAIN_BLK     AS D_CHAIN_BLK,
        D_CH.DES               AS D_CHAIN_DES,
        PP_OPT.STRATEGY_GRP    AS STRATEGY_GRP,
        PP_OPT.MATL_TYPE       AS MATL_TYPE,
        PP_OPT.MRP_TYPE        AS MRP_TYPE,
        PP_OPT.UNIT_COST       AS UNIT_COST,
        PP_OPT.VENDOR_ITEM     AS VENDOR_ITEM
      FROM
        (SELECT ID,
          PLANT,
          MATERIAL,
          CATALOG_DASH,
          AVG26_USAGE_QTY,
          DELIVERY_UNIT,
          D_CHAIN_BLK,
          STRATEGY_GRP,
          MATL_TYPE,
          MRP_TYPE,
          UNIT_COST,
          VENDOR_ITEM
        FROM INV_SAP_PP_OPT_X
        )PP_OPT
      LEFT JOIN
        ( SELECT D_CHAIN,DES FROM INV_SAP_PP_DCHAIN
        )D_CH
      ON D_CH.D_CHAIN = PP_OPT.D_CHAIN_BLK
      )REQ_PLANT
    LEFT JOIN
      (SELECT MATERIAL,
        NVL(SUM(AVG26_USAGE_QTY),0) AS TOT_AP_AVG26_USAGE_QTY
      FROM INV_SAP_PP_OPT_X
      WHERE PLANT IN ('5040', '5100', '5200','5070','5140')
      GROUP BY MATERIAL
      )AP_USAGE
    ON AP_USAGE.MATERIAL = REQ_PLANT.MATERIAL
    )REQ_AP_USG
  LEFT JOIN
    (SELECT ID,
      CASE
        WHEN SG_CHECK = 'YES'
        THEN '40'
        ELSE 'Z4'
      END SG_CHECK
    FROM INV_SAP_SR_SGCHECK
    )AP_SG
  ON AP_SG.ID = REQ_AP_USG.REQ_ID
  )REQ_AP_SGU
LEFT JOIN
  (SELECT ID,
    AVG26_USAGE_QTY,
    STRATEGY_GRP
  FROM INV_SAP_PP_OPT_X
  WHERE PLANT IN ('1090','1180')
  )VENDOR
ON VENDOR.ID = REQ_AP_SGU.REQ_VENDOR_ITEM;


--Catalog Version
SELECT SRB.PLANT,
  V_SRB.REQ_MATERIAL,
  SRB.RB_MATL,
  NVL(SRB.RB_QTY,0),
  nvl(V_SRB.REQ_UNIT_COST,0),
  CEIL(NVL(SRB.RB_QTY,0)*NVL(V_SRB.REQ_UNIT_COST,0)) AS REQ_VAL,
  V_SRB.MRP_TYPE,
  V_SRB.MATL_TYPE,
  V_SRB.REQ_D_CHAIN_DES,
  V_SRB.REQ_STRATEGY_GRP,
  NVL(V_SRB.USAGE_3MM,0),
  NVL(V_SRB.AP_SG_CHECK,0),
  NVL(V_SRB.AP_USAGE_2MM,0),
  NVL(V_SRB.VEN_STRATEGY_GRP,0),
  NVL(V_SRB.VEN_USAGE_1MM,0)
FROM
  (SELECT REPLACE(RB_MATL, '-')
    ||'_'
    ||PLANT AS ID,
    PLANT,
    RB_MATL,
    RB_QTY
  FROM INV_SAP_RISK_BUY
  WHERE RB_MATL NOT IN ('#')
  )SRB
LEFT JOIN
  (SELECT REPLACE(REQ_CATALOG_DASH, '-')
    ||'_'
    ||REQ_PLANT AS ID,
    REQ_PLANT,
    REQ_MATERIAL,
    REQ_CATALOG_DASH,
    REQ_DELIVERY_UNIT,
    CEIL(REQ_AVG26_USAGE_QTY*12) AS USAGE_3MM,
    MRP_TYPE,
    MATL_TYPE,
    REQ_D_CHAIN_DES,
    REQ_STRATEGY_GRP,
    REQ_VENDOR_ITEM,
    CEIL(APT_AVG26_USAGE_QTY*8) AS AP_USAGE_2MM,
    AP_SG_CHECK,
    REQ_UNIT_COST,
    CEIL(VEN_AVG26_USG_QTY*4) AS VEN_USAGE_1MM,
    VEN_STRATEGY_GRP
  FROM VIEW_INV_SAP_RISK_BUY
  )V_SRB
ON SRB.ID = V_SRB.ID;

--Materials Version
SELECT SRB.PLANT,
  V_SRB.REQ_MATERIAL,
  V_SRB.REQ_CATALOG_DASH,
  NVL(SRB.RB_QTY,0),
  nvl(V_SRB.REQ_UNIT_COST,0),
  CEIL(NVL(SRB.RB_QTY,0)*NVL(V_SRB.REQ_UNIT_COST,0)) AS REQ_VAL,
  V_SRB.MRP_TYPE,
  V_SRB.MATL_TYPE,
  V_SRB.REQ_D_CHAIN_DES,
  V_SRB.REQ_STRATEGY_GRP,
  NVL(V_SRB.USAGE_3MM,0),
  NVL(V_SRB.AP_SG_CHECK,0),
  NVL(V_SRB.AP_USAGE_2MM,0),
  NVL(V_SRB.VEN_STRATEGY_GRP,0),
  NVL(V_SRB.VEN_USAGE_1MM,0)
FROM
  (SELECT RB_MATL
    ||'_'
    ||PLANT AS ID,
    PLANT,
    RB_MATL,
    RB_QTY
  FROM INV_SAP_RISK_BUY
  WHERE RB_MATL NOT IN ('#')
  )SRB
LEFT JOIN
  (SELECT REQ_MATERIAL
    ||'_'
    ||REQ_PLANT AS ID,
    REQ_PLANT,
    REQ_MATERIAL,
    REQ_CATALOG_DASH,
    CEIL(REQ_AVG26_USAGE_QTY*12) AS USAGE_3MM,
    MRP_TYPE,
    MATL_TYPE,
    REQ_D_CHAIN_DES,
    REQ_STRATEGY_GRP,
    REQ_VENDOR_ITEM,
    CEIL(APT_AVG26_USAGE_QTY*8) AS AP_USAGE_2MM,
    AP_SG_CHECK,
    REQ_UNIT_COST,
    CEIL(VEN_AVG26_USG_QTY*4) AS VEN_USAGE_1MM,
    VEN_STRATEGY_GRP
  FROM VIEW_INV_SAP_RISK_BUY
  )V_SRB
ON SRB.ID = V_SRB.ID;

------------------------------------------------------------------------------------------------------------------------
--ADD Selection from the Vendor
--Material
SELECT 
  PP_D.PLANT           AS PLANT,
  PP_D.MATERIAL        AS MATERIAL,
  PP_D.CATALOG_DASH    AS CATALOG_DASH,
  SRB.RB_QTY           AS RB_QTY,
  PP_D.UNIT_COST       AS UNIT_COST,
  CEIL(NVL(SRB.RB_QTY,0)*NVL(PP_D.UNIT_COST,0)) AS REQ_VAL,
  PP_D.MATL_TYPE       AS MATL_TYPE,
  PP_D.MRP_TYPE        AS MRP_TYPE,
  PP_D.D_CHAIN_DES     AS D_CHAIN_DES,
  PP_D.STRATEGY_GRP    AS STRATEGY_GRP,
  NVL(PP_D.Q4_USAGE,0)        AS Q4_USAGE,
  NVL(PP_D.Q1_LINES,0)        AS Q1_LINES,
  NVL(PP_D.Q2_LINES,0)        AS Q2_LINES,
  NVL(PP_D.Q3_LINES,0)        AS Q3_LINES,
  NVL(PP_D.Q4_LINES,0)        AS Q4_LINES,
  PP_D.ULTIMATE_SOURCE AS ULTIMATE_SOURCE
FROM
  (SELECT RB_MATL
    ||'_'
    ||PLANT AS ID,
    RB_QTY
  FROM INV_SAP_RISK_BUY
  WHERE RB_MATL NOT IN ('#')
  )SRB
LEFT JOIN
  (SELECT PP_OPT.ID     AS ID, 
    PP_OPT.PLANT     AS PLANT,
    PP_OPT.MATERIAL        AS MATERIAL,
    PP_OPT.CATALOG_DASH    AS CATALOG_DASH,
    D_CH.DES               AS D_CHAIN_DES,
    PP_OPT.STRATEGY_GRP    AS STRATEGY_GRP,
    PP_OPT.MATL_TYPE       AS MATL_TYPE,
    PP_OPT.MRP_TYPE        AS MRP_TYPE,
    PP_OPT.UNIT_COST       AS UNIT_COST,
    PP_OPT.Q4_USAGE        AS Q4_USAGE,
    PP_OPT.Q1_LINES        AS Q1_LINES,
    PP_OPT.Q2_LINES        AS Q2_LINES,
    PP_OPT.Q3_LINES        AS Q3_LINES,
    PP_OPT.Q4_LINES        AS Q4_LINES,
    PP_OPT.ULTIMATE_SOURCE AS ULTIMATE_SOURCE
  FROM
    (SELECT ID,
      PLANT,
      MATERIAL,
      CATALOG_DASH,
      D_CHAIN_BLK,
      STRATEGY_GRP,
      MATL_TYPE,
      MRP_TYPE,
      UNIT_COST,
      NVL(AVG13_USAGE_QTY*13,0) AS Q4_USAGE,
      Q1_LINES,
      Q2_LINES,
      Q3_LINES,
      Q4_LINES,
      ULTIMATE_SOURCE
    FROM INV_SAP_PP_OPT_X 
    WHERE PLANT IN ('1090','1180') AND ID = '332045_1090'
    )PP_OPT
  LEFT JOIN
    ( SELECT D_CHAIN,DES FROM INV_SAP_PP_DCHAIN
    )D_CH
  ON D_CH.D_CHAIN  = PP_OPT.D_CHAIN_BLK
  )PP_D 
  ON PP_D.ID = SRB.ID;

--Catalog
SELECT 
  PP_D.PLANT           AS PLANT,
  PP_D.MATERIAL        AS MATERIAL,
  PP_D.CATALOG_DASH    AS CATALOG_DASH,
  SRB.RB_QTY           AS RB_QTY,
  PP_D.UNIT_COST       AS UNIT_COST,
  CEIL(NVL(SRB.RB_QTY,0)*NVL(PP_D.UNIT_COST,0)) AS REQ_VAL,
  PP_D.MATL_TYPE       AS MATL_TYPE,
  PP_D.MRP_TYPE        AS MRP_TYPE,
  PP_D.D_CHAIN_DES     AS D_CHAIN_DES,
  PP_D.STRATEGY_GRP    AS STRATEGY_GRP,
  NVL(PP_D.Q4_USAGE,0)        AS Q4_USAGE,
  NVL(PP_D.Q1_LINES,0)        AS Q1_LINES,
  NVL(PP_D.Q2_LINES,0)        AS Q2_LINES,
  NVL(PP_D.Q3_LINES,0)        AS Q3_LINES,
  NVL(PP_D.Q4_LINES,0)        AS Q4_LINES,
  PP_D.ULTIMATE_SOURCE AS ULTIMATE_SOURCE
FROM
  (SELECT RB_MATL
    ||'_'
    ||PLANT AS ID,
    RB_QTY
  FROM INV_SAP_RISK_BUY
  WHERE RB_MATL NOT IN ('#')
  )SRB
LEFT JOIN
  (SELECT REPLACE(PP_OPT.CATALOG_DASH, '-')
    ||'_'
    ||PP_OPT.PLANT      AS ID, 
    PP_OPT.PLANT     AS PLANT,
    PP_OPT.MATERIAL        AS MATERIAL,
    PP_OPT.CATALOG_DASH    AS CATALOG_DASH,
    D_CH.DES               AS D_CHAIN_DES,
    PP_OPT.STRATEGY_GRP    AS STRATEGY_GRP,
    PP_OPT.MATL_TYPE       AS MATL_TYPE,
    PP_OPT.MRP_TYPE        AS MRP_TYPE,
    PP_OPT.UNIT_COST       AS UNIT_COST,
    PP_OPT.Q4_USAGE        AS Q4_USAGE,
    PP_OPT.Q1_LINES        AS Q1_LINES,
    PP_OPT.Q2_LINES        AS Q2_LINES,
    PP_OPT.Q3_LINES        AS Q3_LINES,
    PP_OPT.Q4_LINES        AS Q4_LINES,
    PP_OPT.ULTIMATE_SOURCE AS ULTIMATE_SOURCE
  FROM
    (SELECT ID,
      PLANT,
      MATERIAL,
      CATALOG_DASH,
      D_CHAIN_BLK,
      STRATEGY_GRP,
      MATL_TYPE,
      MRP_TYPE,
      UNIT_COST,
      NVL(AVG13_USAGE_QTY*13,0) AS Q4_USAGE,
      Q1_LINES,
      Q2_LINES,
      Q3_LINES,
      Q4_LINES,
      ULTIMATE_SOURCE
    FROM INV_SAP_PP_OPT_X
    WHERE PLANT IN ('1090','1180')
    )PP_OPT
  LEFT JOIN
    (SELECT D_CHAIN,DES FROM INV_SAP_PP_DCHAIN
    )D_CH
  ON D_CH.D_CHAIN  = PP_OPT.D_CHAIN_BLK
  )PP_D 
  ON PP_D.ID = SRB.ID;
  
  
SELECT SRB.PLANT,
  V_SRB.REQ_MATERIAL,
  SRB.RB_MATL,
  NVL(SRB.RB_QTY,0),
  nvl(V_SRB.REQ_UNIT_COST,0),
  CEIL(NVL(SRB.RB_QTY,0)*NVL(V_SRB.REQ_UNIT_COST,0)) AS REQ_VAL,
  V_SRB.MRP_TYPE,
  V_SRB.MATL_TYPE,
  V_SRB.REQ_D_CHAIN_DES,
  V_SRB.REQ_STRATEGY_GRP,
  NVL(V_SRB.USAGE_3MM,0),
  NVL(V_SRB.AP_SG_CHECK,0),
  NVL(V_SRB.AP_USAGE_2MM,0),
  NVL(V_SRB.VEN_STRATEGY_GRP,0),
  NVL(V_SRB.VEN_USAGE_1MM,0)
FROM
  (SELECT REPLACE(RB_MATL, '-')
    ||'_'
    ||PLANT AS ID,
    PLANT,
    RB_MATL,
    RB_QTY
  FROM INV_SAP_RISK_BUY
  WHERE RB_MATL NOT IN ('#')
  )SRB
LEFT JOIN
  (SELECT REPLACE(REQ_CATALOG_DASH, '-')
    ||'_'
    ||REQ_PLANT AS ID,
    REQ_PLANT,
    REQ_MATERIAL,
    REQ_CATALOG_DASH,
    CEIL(REQ_AVG26_USAGE_QTY*12) AS USAGE_3MM,
    MRP_TYPE,
    MATL_TYPE,
    REQ_D_CHAIN_DES,
    REQ_STRATEGY_GRP,
    REQ_VENDOR_ITEM,
    CEIL(APT_AVG26_USAGE_QTY*8) AS AP_USAGE_2MM,
    AP_SG_CHECK,
    REQ_UNIT_COST,
    CEIL(VEN_AVG26_USG_QTY*4) AS VEN_USAGE_1MM,
    VEN_STRATEGY_GRP
  FROM VIEW_INV_SAP_RISK_BUY
  )V_SRB
ON SRB.ID = V_SRB.ID;
