-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Project Name : APAFC
-- Version : 1.0
-- Description:
-- Table Init
-- Revision History:
--    Date        Developer         Description
--    ---------   ---------------   ----------------------------------------------------
--    2015-8-6  Moyue           	  5150.
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------

--Shipment data

--1. SO HST Value 2014.10-2015.7
SELECT * FROM INV_SAP_SALES_HST_LC WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140') AND LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 378) AND TO_CHAR(SYSDATE -14);


--2. Ship from DC
--1. Complete Order Calculation
DROP VIEW VIEW_INV_SAP_AOP_DDC;
CREATE VIEW VIEW_INV_SAP_AOP_DDC AS
SELECT 
  LIFNR_VENDORNO,
  PLANTID,
  MATERIALID,
  EBELNPURCHDOCNO,
  EBELPPURCHITEMNO,
  TOTALRECIEVEDYQTY,
  WAERS_CURRENCYKEY,
  NETWRNETORDERVALUE,
  BUDATPOSTINGDATE,
  STRATEGY_GRP,
  UNIT_COST,
  PO_SO_SA_FLAG,
  DELIVERYCOMPLETE
FROM INV_SAP_PP_PO_HISTORY_ALL
WHERE BUDATPOSTINGDATE BETWEEN TO_CHAR(SYSDATE - 378) AND TO_CHAR(SYSDATE -14)
AND TOTALRECIEVEDYQTY IS NOT NULL
AND PO_SO_SA_FLAG     IN ('STO')
AND DELIVERYCOMPLETE  IS NOT NULL
AND LIFNR_VENDORNO IN ('V5040','V5050', 'V5100', 'V5110', 'V5120', 'V5160', 'V5190', 'V5200','V5070','V5140');


SELECT * FROM VIEW_INV_SAP_AOP_DDC WHERE EBELNPURCHDOCNO = '6600036842' AND EBELPPURCHITEMNO = '230';


-- Partial Shippment
DROP VIEW VIEW_INV_SAP_AOP_DDC_P;
CREATE VIEW VIEW_INV_SAP_AOP_DDC_P AS
SELECT 
  PO_STO.LIFNR_VENDORNO,
  PO_STO.PLANTID,
  PO_STO.MATERIALID,
  P_PO_STO.EBELNPURCHDOCNO,
  PO_STO.EBELPPURCHITEMNO,
  PO_STO.MENGESCHEDULEDQTY,
  PO_STO.WEMNGRECEIVEDQTY,
  PO_STO.WAERS_CURRENCYKEY,
  PO_STO.NETWRNETORDERVALUE,
  PO_STO.SLFDTSTATDELIVERYDATE,
  PO_STO.BUDATPOSTINGDATE,
  PO_STO.STRATEGY_GRP,
  PO_STO.UNIT_COST,
  PO_STO.PO_SO_SA_FLAG,
  PO_STO.DELIVERYCOMPLETE
FROM
(
SELECT DISTINCT EBELNPURCHDOCNO
FROM INV_SAP_PP_PO_HISTORY_ALL
WHERE ETENRPURCHDELIVSCHLINESA = '1' AND TOTALRECIEVEDYQTY IS NULL  
AND PO_SO_SA_FLAG       IN ('STO')
AND LIFNR_VENDORNO IN ('V5040','V5050', 'V5100', 'V5110', 'V5120', 'V5160', 'V5190', 'V5200','V5070','V5140')
)P_PO_STO
LEFT JOIN
(SELECT 
  LIFNR_VENDORNO,
  PLANTID,
  MATERIALID,
  EBELNPURCHDOCNO,
  EBELPPURCHITEMNO,
  MENGESCHEDULEDQTY,
  WEMNGRECEIVEDQTY,
  WAERS_CURRENCYKEY,
  NETWRNETORDERVALUE,
  SLFDTSTATDELIVERYDATE,
  BUDATPOSTINGDATE,
  STRATEGY_GRP,
  UNIT_COST,
  PO_SO_SA_FLAG,
  DELIVERYCOMPLETE
FROM INV_SAP_PP_PO_HISTORY_ALL
)PO_STO
ON PO_STO.EBELNPURCHDOCNO = P_PO_STO.EBELNPURCHDOCNO;


SELECT *
FROM VIEW_INV_SAP_AOP_DDC_P
WHERE DELIVERYCOMPLETE IS NOT NULL
AND SLFDTSTATDELIVERYDATE BETWEEN TO_CHAR(SYSDATE - 316) AND TO_CHAR(SYSDATE - 13)
AND MENGESCHEDULEDQTY = '0'


SELECT * FROM VIEW_INV_SAP_AOP_DDC_P  WHERE EBELNPURCHDOCNO = '6600036842' AND DELIVERYCOMPLETE IS NOT NULL
AND SLFDTSTATDELIVERYDATE BETWEEN TO_CHAR(SYSDATE - 316) AND TO_CHAR(SYSDATE - 13)
AND MENGESCHEDULEDQTY = '0';
------------------------------------------------------------------------------------------------------------------------


--Receiving Data

SELECT * FROM INV_SAP_PP_PO_HISTORY_ALL  WHERE EBELNPURCHDOCNO = '6600036842' AND EBELPPURCHITEMNO = '20';

--1. Complete Order Calculation

CREATE VIEW VIEW_INV_SAP_AOP_STO_COMPLETE AS
SELECT PLANTID,
  MATERIALID,
  EBELNPURCHDOCNO,
  EBELPPURCHITEMNO,
  TOTALRECIEVEDYQTY,
  WAERS_CURRENCYKEY,
  NETWRNETORDERVALUE,
  BUDATPOSTINGDATE,
  STRATEGY_GRP,
  UNIT_COST,
  PO_SO_SA_FLAG,
  DELIVERYCOMPLETE
FROM INV_SAP_PP_PO_HISTORY_ALL
WHERE BUDATPOSTINGDATE BETWEEN TO_CHAR(SYSDATE - 378) AND TO_CHAR(SYSDATE -14)
AND TOTALRECIEVEDYQTY IS NOT NULL
AND PO_SO_SA_FLAG     IN ('STO')
AND DELIVERYCOMPLETE  IS NOT NULL
AND PLANTID           IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');



--1.1 Partial Shippment
DROP VIEW VIEW_INV_SAP_AOP_STO_P;
CREATE VIEW VIEW_INV_SAP_AOP_STO_P AS
SELECT PO_STO.PLANTID,
  PO_STO.MATERIALID,
  P_PO_STO.EBELNPURCHDOCNO,
  PO_STO.EBELPPURCHITEMNO,
  PO_STO.MENGESCHEDULEDQTY,
  PO_STO.WEMNGRECEIVEDQTY,
  PO_STO.WAERS_CURRENCYKEY,
  PO_STO.NETWRNETORDERVALUE,
  PO_STO.SLFDTSTATDELIVERYDATE,
  PO_STO.BUDATPOSTINGDATE,
  PO_STO.STRATEGY_GRP,
  PO_STO.UNIT_COST,
  PO_STO.PO_SO_SA_FLAG,
  PO_STO.DELIVERYCOMPLETE
FROM
(
SELECT DISTINCT EBELNPURCHDOCNO
FROM INV_SAP_PP_PO_HISTORY_ALL
WHERE TOTALRECIEVEDYQTY IS NULL AND ETENRPURCHDELIVSCHLINESA = '1'
AND PO_SO_SA_FLAG       IN ('STO')
AND PLANTID             IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
)P_PO_STO
LEFT JOIN
(SELECT PLANTID,
  MATERIALID,
  EBELNPURCHDOCNO,
  EBELPPURCHITEMNO,
  MENGESCHEDULEDQTY,
  WEMNGRECEIVEDQTY,
  WAERS_CURRENCYKEY,
  NETWRNETORDERVALUE,
  SLFDTSTATDELIVERYDATE,
  BUDATPOSTINGDATE,
  STRATEGY_GRP,
  UNIT_COST,
  PO_SO_SA_FLAG,
  DELIVERYCOMPLETE
FROM INV_SAP_PP_PO_HISTORY_ALL
)PO_STO
ON PO_STO.EBELNPURCHDOCNO = P_PO_STO.EBELNPURCHDOCNO;


SELECT count(*)
FROM VIEW_INV_SAP_AOP_STO_P
WHERE DELIVERYCOMPLETE IS NOT NULL
AND SLFDTSTATDELIVERYDATE BETWEEN TO_CHAR(SYSDATE - 381) AND TO_CHAR(SYSDATE - 321)
AND MENGESCHEDULEDQTY = '0'


--2. 3rd Party
SELECT PLANTID,
  MATERIALID,
  EBELNPURCHDOCNO,
  EBELPPURCHITEMNO,
  TOTALRECIEVEDYQTY,
  WAERS_CURRENCYKEY,
  NETWRNETORDERVALUE,
  BUDATPOSTINGDATE,
  STRATEGY_GRP,
  UNIT_COST,
  PO_SO_SA_FLAG,
  DELIVERYCOMPLETE
FROM INV_SAP_PP_PO_HISTORY_ALL
WHERE BUDATPOSTINGDATE BETWEEN TO_CHAR(SYSDATE - 381) AND TO_CHAR(SYSDATE - 17)
AND BSART_PURCHDOCTYPE = 'ZNB'
AND PLANTID           IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
AND DELIVERYCOMPLETE  IS NOT NULL
AND TOTALRECIEVEDYQTY IS NOT NULL



--Monitor the vendor shippment status..

SELECT * FROM
(
SELECT 
  STO.ID, 
  STO.LIFNR_VENDORNO,
  STO.PLANTID,
  STO.MATERIALID,
  STO.EBELNPURCHDOCNO,
  STO.ETENRPURCHDELIVSCHLINESA,
  STO.BEDATSCHEDULELINEORDERDATE,
  STO.BUDATPOSTINGDATE,
  OPT.STRATEGY_GRP
FROM
(
SELECT 
  MATERIALID ||'_'||substr(LIFNR_VENDORNO, 2, 4) AS ID, 
  LIFNR_VENDORNO,
  PLANTID,
  MATERIALID,
  EBELNPURCHDOCNO,
  ETENRPURCHDELIVSCHLINESA,
  BEDATSCHEDULELINEORDERDATE,
  BUDATPOSTINGDATE
FROM INV_SAP_PP_PO_HISTORY_ALL
WHERE BUDATPOSTINGDATE BETWEEN TO_CHAR(SYSDATE - 180) AND TO_CHAR(SYSDATE)
AND TOTALRECIEVEDYQTY IS NOT NULL
AND PO_SO_SA_FLAG     IN ('STO')
AND DELIVERYCOMPLETE  IS NOT NULL
AND LIFNR_VENDORNO IN ('V1090') 
AND PLANTID           IN ('5100')
AND ETENRPURCHDELIVSCHLINESA = '1'
)STO
LEFT JOIN
(
SELECT ID, STRATEGY_GRP FROM INV_SAP_PP_OPT_X
)OPT
ON OPT.ID = STO.ID)
WHERE STRATEGY_GRP = '40'

select * from INV_SAP_PP_PO_HISTORY_ALL;


SELECT * FROM
(
SELECT 
  STO.ID, 
  STO.LIFNR_VENDORNO,
  STO.PLANTID,
  STO.MATERIALID,
  STO.EBELNPURCHDOCNO,
  STO.ETENRPURCHDELIVSCHLINESA,
  STO.BEDATSCHEDULELINEORDERDATE,
  STO.BUDATPOSTINGDATE,
  OPT.STRATEGY_GRP
FROM
(
SELECT 
  MATERIALID ||'_'||substr(LIFNR_VENDORNO, 2, 4) AS ID, 
  LIFNR_VENDORNO,
  PLANTID,
  MATERIALID,
  EBELNPURCHDOCNO,
  ETENRPURCHDELIVSCHLINESA,
  BEDATSCHEDULELINEORDERDATE,
  BUDATPOSTINGDATE
FROM INV_SAP_PP_PO_HISTORY_ALL
WHERE BUDATPOSTINGDATE BETWEEN TO_CHAR(SYSDATE - 48) AND TO_CHAR(SYSDATE - 18)
AND TOTALRECIEVEDYQTY IS NOT NULL
AND PO_SO_SA_FLAG     IN ('STO')
AND DELIVERYCOMPLETE  IS NOT NULL
AND LIFNR_VENDORNO IN ('V5200') 
AND PLANTID           IN ('5120', '5160', '5190')
AND ETENRPURCHDELIVSCHLINESA = '1'
)STO
LEFT JOIN
(
SELECT ID, STRATEGY_GRP FROM INV_SAP_PP_OPT_X
)OPT
ON OPT.ID = STO.ID)
WHERE STRATEGY_GRP = '40';


SELECT * FROM
(
SELECT 
  STO.ID, 
  STO.LIFNR_VENDORNO,
  STO.PLANTID,
  STO.MATERIALID,
  STO.EBELNPURCHDOCNO,
  STO.ETENRPURCHDELIVSCHLINESA,
  STO.BEDATSCHEDULELINEORDERDATE,
  STO.BUDATPOSTINGDATE,
  OPT.STRATEGY_GRP
FROM
(
SELECT 
  MATERIALID ||'_'||substr(LIFNR_VENDORNO, 2, 4) AS ID, 
  LIFNR_VENDORNO,
  PLANTID,
  MATERIALID,
  EBELNPURCHDOCNO,
  ETENRPURCHDELIVSCHLINESA,
  BEDATSCHEDULELINEORDERDATE,
  BUDATPOSTINGDATE
FROM INV_SAP_PP_PO_HISTORY_ALL
WHERE BUDATPOSTINGDATE BETWEEN TO_CHAR(SYSDATE - 48) AND TO_CHAR(SYSDATE - 18)
AND TOTALRECIEVEDYQTY IS NOT NULL
AND PO_SO_SA_FLAG     IN ('STO')
AND DELIVERYCOMPLETE  IS NOT NULL
AND LIFNR_VENDORNO IN ('V1180','V1090') 
AND PLANTID           IN ('5040', '5050', '5070','5110', '5140', '5200','5100')
AND ETENRPURCHDELIVSCHLINESA = '1'
)STO
LEFT JOIN
(
SELECT ID, STRATEGY_GRP FROM INV_SAP_PP_OPT_X
)OPT
ON OPT.ID = STO.ID)
WHERE STRATEGY_GRP = '40'





------------------------------------------------------------------------------------------------------------------------
--Demand
--SO

(
SELECT
ID||'_'||TO_CHAR(MAX_REQUEST_DATE,'mm') AS IDM,
TO_CHAR(MAX_REQUEST_DATE,'mm') AS MM,
OPEN_QTY*UNIT_COST AS DE_VALUE
FROM
  (SELECT SO_OPEN.ID         AS ID,
    SO_OPEN.PLANT         AS PLANT,
    SO_OPEN.MATERIAL         AS MATERIAL,
    SO_OPEN.SALESDOC         AS SALESDOC,
    SO_OPEN.OPEN_QTY         AS OPEN_QTY,
    SO_OPEN.MAX_REQUEST_DATE AS MAX_REQUEST_DATE,
    SO_OPEN.LINECREATEDATE   AS LINECREATEDATE,
    PP.MATL_TYPE             AS MATL_TYPE,
    PP.UNIT_COST             AS UNIT_COST
  FROM
    (SELECT MATERIAL
      ||'_'
      ||PLANT AS ID,
      MATERIAL,
      PLANT,
      SALESDOC,
      OPEN_QTY,
      LINECREATEDATE,
      MAX_REQUEST_DATE
    FROM INV_SAP_SALES_VBAK_VBAP_VBUP
    WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
    AND OPEN_QTY >0
    )SO_OPEN
  LEFT JOIN
    (SELECT ID, MATL_TYPE, UNIT_COST FROM INV_SAP_PP_OPT_X
    )PP
  ON PP.ID = SO_OPEN.ID
  )
WHERE MATL_TYPE IN ('ZTG','ZFG') AND MAX_REQUEST_DATE BETWEEN TO_CHAR(SYSDATE - 14) AND TO_CHAR(SYSDATE + 260)
)
--Demand STO
UNION
(
(SELECT LID||'_'||TO_CHAR(COMMITTED_DATE_MAX,'mm') AS IDM,
  TO_CHAR(COMMITTED_DATE_MAX,'mm') AS MM,
  PO_QTY*UNIT_COST AS DE_VALUE
FROM
  (SELECT STO_DEMD_OPEN.LID          AS LID,
    STO_DEMD_OPEN.MATERIALID         AS MATERIALID,
    STO_DEMD_OPEN.PLANTID            AS PLANTID,
    STO_DEMD_OPEN.SHIPPING_PLANT     AS SHIPPING_PLANT,
    STO_DEMD_OPEN.PO_QTY             AS PO_QTY,
    STO_DEMD_OPEN.COMMITTED_DATE_MAX AS COMMITTED_DATE_MAX,
    PP_ITEM.MATL_TYPE                AS MATL_TYPE,
    PP_ITEM.UNIT_COST                AS UNIT_COST
  FROM
    (SELECT MATERIALID
      ||'_'
      ||PLANTID AS LID,
      MATERIALID,
      PLANTID,
      PO_QTY,
      MAX(COMMITTED_DATE) AS COMMITTED_DATE_MAX,
      SHIPPING_PLANT
    FROM
      (SELECT PLANTID,
        GREATEST ( MENGESCHEDULEDQTY_BASE_UOM - ( NVL ( MENGESCHEDULEDQTY_BASE_UOM / MENGESCHEDULEDQTY, 0) * NVL ( GREATEST (WEMNGRECEIVEDQTY, WAMNGISSUEDQTY), 0)), 0) AS PO_QTY,
        MATERIALID,
        COMMITTED_DATE,
        TO_NUMBER (
        CASE
          WHEN LIFNR_VENDORNO LIKE 'V%'
          AND LENGTH (LIFNR_VENDORNO) = 5
          THEN SUBSTR (LIFNR_VENDORNO, 2, 4)
          WHEN LENGTH (LIFNR_VENDORNO) > 5
          THEN '0'
          ELSE TO_CHAR (LIFNR_VENDORNO)
        END) SHIPPING_PLANT
      FROM INV_SAP_PP_PO_HISTORY_ALL
      WHERE PO_SO_SA_FLAG IN ('STO')
      AND PLANTID         IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
      AND ( DELIVERYCOMPLETE NOT LIKE 'X%'
      OR DELIVERYCOMPLETE   IS NULL)
      AND MENGESCHEDULEDQTY <> 0
      AND LAST_SHIP_DATE    IS NULL
      )
    GROUP BY MATERIALID,
      PLANTID,
      PO_QTY,
      SHIPPING_PLANT
    )STO_DEMD_OPEN
  LEFT JOIN
    (SELECT ID, MATL_TYPE, UNIT_COST FROM INV_SAP_PP_OPT_X
    )PP_ITEM
  ON PP_ITEM.ID = STO_DEMD_OPEN.LID
  )
WHERE MATL_TYPE IN ('ZTG','ZFG') AND COMMITTED_DATE_MAX BETWEEN TO_CHAR(SYSDATE - 14) AND TO_CHAR(SYSDATE + 260))
UNION
(
SELECT 
ID||'_'||TO_CHAR(PDATU_DELIV_ORDFINISHDATE,'mm') AS IDM,
TO_CHAR(PDATU_DELIV_ORDFINISHDATE,'mm') AS MM,
PLAN_VALUE AS DE_VALUE
FROM
(
SELECT VF.ID,
VF.MATERIALID,
VF.PLANTID,
VF.PLNMG_PLANNEDQUANTITY*PP.UNIT_COST AS PLAN_VALUE,
VF.PDATU_DELIV_ORDFINISHDATE,
VF.BEDAEP_REQUIREMENTSTYPE,
PP.MATL_TYPE
FROM
  (SELECT MATERIALID
    ||'_'
    ||PLANTID                 AS ID,
    MATERIALID                AS MATERIALID,
    PLANTID                   AS PLANTID,
    PLNMG_PLANNEDQUANTITY     AS PLNMG_PLANNEDQUANTITY,
    BEDAEP_REQUIREMENTSTYPE   AS BEDAEP_REQUIREMENTSTYPE,
    PDATU_DELIV_ORDFINISHDATE AS PDATU_DELIV_ORDFINISHDATE
  FROM INV_SAP_PP_FRCST_PBIM_PBED
  WHERE VERSBP_VERSION = '00'
  )VF
LEFT JOIN
  (SELECT ID, MATL_TYPE, UNIT_COST FROM INV_SAP_PP_OPT_X
  )PP
ON PP.ID = VF.ID
)WHERE MATL_TYPE IN ('ZTG','ZFG') AND PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(SYSDATE - 14) AND TO_CHAR(SYSDATE + 260)))


--Supply

--Plan Order


(SELECT
ID||'_'||TO_CHAR(DATEDELIVERY,'mm') AS IDM,
TO_CHAR(DATEDELIVERY,'mm') AS MM,
PPO_VALUE AS OPEN_VALUE
FROM
(
SELECT
VF.ID AS ID,
VF.MATERIALID AS MATERIALID,
VF.PLANTID AS PLANTID,
VF.DATEDELIVERY AS DATEDELIVERY,
VF.PO_OPENQTY*PP.UNIT_COST AS PPO_VALUE,
PP.MATL_TYPE AS MATL_TYPE
FROM 
(
SELECT MATERIALID
        ||'_'
        ||PLANTID AS ID,
        MATERIALID,
        PLANTID,
        DATEDELIVERY,
        PONUMBER,
        PO_OPENQTY
      FROM INV_SAP_IO_INPUTS_DAILY
      WHERE INPUT_TYPE = 'PLAN_PD_PO_CONVERT'
      AND PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
)VF
LEFT JOIN
  (SELECT ID, MATL_TYPE, UNIT_COST FROM INV_SAP_PP_OPT_X
  )PP
  ON PP.ID = VF.ID
)WHERE MATL_TYPE IN ('ZTG','ZFG') AND DATEDELIVERY BETWEEN TO_CHAR(SYSDATE - 14) AND TO_CHAR(SYSDATE + 260))
UNION
(
SELECT
  ID||'_'||TO_CHAR(EINDTPURCHITEMDELIVDATE,'mm') AS IDM,
  TO_CHAR(EINDTPURCHITEMDELIVDATE,'mm') AS MM,
  STO_OPEN_VALUE AS OPEN_VALUE
FROM
  (SELECT 
    STO_OPEN.ID        AS ID,
    STO_OPEN.MATERIALID        AS MATERIALID,
    STO_OPEN.PLANTID                 AS PLANTID,
    STO_OPEN.PO_QTY*PP.UNIT_COST     AS STO_OPEN_VALUE,
    STO_OPEN.EINDTPURCHITEMDELIVDATE AS EINDTPURCHITEMDELIVDATE,
    PP.MATL_TYPE                     AS MATL_TYPE
  FROM
    (SELECT MATERIALID
      ||'_'
      || PLANTID AS ID,
      PLANTID,
      GREATEST ( MENGESCHEDULEDQTY_BASE_UOM - ( NVL ( MENGESCHEDULEDQTY_BASE_UOM / MENGESCHEDULEDQTY, 0) * NVL ( GREATEST (WEMNGRECEIVEDQTY, WAMNGISSUEDQTY), 0)), 0) AS PO_QTY,
      MATERIALID,
      TO_NUMBER (
      CASE
        WHEN LIFNR_VENDORNO LIKE 'V%'
        AND LENGTH (LIFNR_VENDORNO) = 5
        THEN SUBSTR (LIFNR_VENDORNO, 2, 4)
        WHEN LENGTH (LIFNR_VENDORNO) > 5
        THEN '0'
        ELSE TO_CHAR (LIFNR_VENDORNO)
      END) SHIPPING_PLANT,
      EINDTPURCHITEMDELIVDATE
    FROM INV_SAP_PP_PO_HISTORY
    WHERE PO_SO_SA_FLAG IN ('STO')
    AND ( DELIVERYCOMPLETE NOT LIKE 'X%'
    OR DELIVERYCOMPLETE   IS NULL)
    AND MENGESCHEDULEDQTY <> 0
    AND LAST_SHIP_DATE    IS NULL
    )STO_OPEN
  LEFT JOIN
    (SELECT ID, MATL_TYPE, UNIT_COST FROM INV_SAP_PP_OPT_X
    )PP
  ON PP.ID = STO_OPEN.ID
  )
WHERE MATL_TYPE IN ('ZTG','ZFG') AND EINDTPURCHITEMDELIVDATE BETWEEN TO_CHAR(SYSDATE - 14) AND TO_CHAR(SYSDATE + 260));