-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Project Name : APAFC
-- Version : 1.0
-- Description:
-- Table Init
-- Revision History:
--    Date        Developer         Description
--    ---------   ---------------   ----------------------------------------------------
--    2014-12-24  Moyue           	SCHEDULE RETURN.
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
   
CREATE OR REPLACE PROCEDURE APAFC_SR_BGDATA
IS
STEP_NAME VARCHAR2(100);
PROCESS_TERMINATED EXCEPTION;
COUNT_SGCHK NUMBER;
CHK_SGCHK NUMBER;
SGCHK_INIT VARCHAR2(1000);

BEGIN
	STEP_NAME := 'SG check in AP...';
  
	SGCHK_INIT := 'CREATE TABLE INV_SAP_SR_SGCHECK
	(
	ID       VARCHAR2(100),
	MATERIAL VARCHAR2(100),
	SG_CHECK VARCHAR2(100)
	)';
 
	SELECT COUNT(*) INTO COUNT_SGCHK FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_SR_SGCHECK';
	SELECT COUNT(*) INTO CHK_SGCHK FROM INV_SAP_SR_SGCHECK;
  
	IF COUNT_SGCHK > 0 THEN
	IF CHK_SGCHK > 0 THEN
	  APAFC_TRUNCATE('INV_SAP_SR_SGCHECK');
	  COMMIT;
		APAFC_INSERT('VIEW_INV_SAP_SGC_5140','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5040','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5050','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5100','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5110','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5120','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5160','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5190','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5070','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5200','INV_SAP_SR_SGCHECK');
	  COMMIT;
	ELSE
		APAFC_INSERT('VIEW_INV_SAP_SGC_5140','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5040','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5050','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5100','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5110','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5120','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5160','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5190','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5070','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5200','INV_SAP_SR_SGCHECK');
	  COMMIT;
	END IF;
	ELSE
		APAFC_SCRIPT_EXE_IMMEDIATE(SGCHK_INIT);
		COMMIT;
		APAFC_INSERT('VIEW_INV_SAP_SGC_5140','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5040','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5050','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5100','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5110','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5120','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5160','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5190','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5070','INV_SAP_SR_SGCHECK');
		APAFC_INSERT('VIEW_INV_SAP_SGC_5200','INV_SAP_SR_SGCHECK');
	  COMMIT;
	END IF;  
 
EXCEPTION
WHEN OTHERS THEN
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Execute Error:');
  DBMS_OUTPUT.PUT_LINE(SUBSTR(DBMS_UTILITY.FORMAT_ERROR_STACK,1,200)||SUBSTR(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,1,200));
  RAISE PROCESS_TERMINATED;
END APAFC_SOHST_LC_INIT;

--Catalog Version
DROP VIEW VIEW_INV_SAP_SCH_RECA;
CREATE VIEW VIEW_INV_SAP_SCH_RECA AS
SELECT RE_BSVSTGSR.ID            AS ID,
  RE_BSVSTGSR.CUST_RE_PLANT      AS CUST_RE_PLANT,
  RE_BSVSTGSR.CUST_RE_MATL       AS CUST_RE_MATL,
  RE_BSVSTGSR.CUST_RE_QTY        AS CUST_RE_QTY,
  RE_BSVSTGSR.CUST_RE_SER        AS CUST_RE_SER,
  RE_BSVSTGSR.CUST_RE_PRICE      AS CUST_RE_PRICE,
  RE_BSVSTGSR.CUST_RE_AMOUNT     AS CUST_RE_AMOUNT,
  RE_BSVSTGSR.SOG                 AS SOG,
  RE_BSVSTGSR.CUST_REMARK        AS CUST_REMARK,
  RE_BSVSTGSR.RE_MATERIAL        AS RE_MATERIAL,
  RE_BSVSTGSR.RE_PLANT           AS RE_PLANT,
  RE_BSVSTGSR.RE_D_CHAIN_BLK     AS RE_D_CHAIN_BLK,
  RE_BSVSTGSR.RE_UNIT_COST       AS RE_UNIT_COST,
  RE_BSVSTGSR.RE_DELIVERY_UNIT   AS RE_DELIVERY_UNIT,
  RE_BSVSTGSR.RE_STRATEGY_GRP    AS RE_STRATEGY_GRP,
  RE_BSVSTGSR.RE_OH_QTY          AS RE_OH_QTY,
  RE_BSVSTGSR.RE_VENDOR          AS RE_VENDOR,
  RE_BSVSTGSR.RE_MATL_TYPE       AS RE_MATL_TYPE,
  RE_BSVSTGSR.RE_VENDOR_ITEM     AS RE_VENDOR_ITEM,
  RE_BSVSTGSR.RE_ULTIMATE_SOURCE AS RE_ULTIMATE_SOURCE,
  RE_BSVSTGSR.VP_STRATEGY_GRP    AS VP_STRATEGY_GRP,
  RE_BSVSTGSR.VP_OH_QTY          AS VP_OH_QTY,
  RE_BSVSTGSR.VP_Q4_SUM          AS VP_Q4_SUM,
  RE_BSVSTGSR.Q1_SHIP_QTY        AS Q1_SHIP_QTY,
  RE_BSVSTGSR.Q2_SHIP_QTY        AS Q2_SHIP_QTY,
  RE_BSVSTGSR.Q3_SHIP_QTY        AS Q3_SHIP_QTY,
  RE_BSVSTGSR.Q4_SHIP_QTY        AS Q4_SHIP_QTY,
  RE_BSVSTGSR.Q1_LN_QTY          AS Q1_LN_QTY,
  RE_BSVSTGSR.Q2_LN_QTY          AS Q2_LN_QTY,
  RE_BSVSTGSR.Q3_LN_QTY          AS Q3_LN_QTY,
  RE_BSVSTGSR.Q4_LN_QTY          AS Q4_LN_QTY,
  DSTR_STATS.MAX_DIS_NAME        AS MAX_DIS_NAME,
  DSTR_STATS.MAX_DIS_USAGE_QTY   AS MAX_DIS_USAGE_QTY,
  DSTR_STATS.TOT_USAGE_QTY       AS TOT_USAGE_QTY,
  DSTR_STATS.PER_BIGGEST         AS PER_BIGGEST,
  DSTR_STATS.DISTRIBUTOR_COUNT   AS DISTRIBUTOR_COUNT,
  RE_BSVSTGSR.ALLOW_RETURN_FLG   AS ALLOW_RETURN_FLG,
  RE_BSVSTGSR.SG_CHECK           AS SG_CHECK,
  RE_BSVSTGSR.SERISES            AS SERISES,
  RE_BSVSTGSR.EX_TO_USD          AS EX_TO_USD
FROM
  (SELECT RE_BSVSTGS.ID           AS ID,
    RE_BSVSTGS.CUST_RE_PLANT      AS CUST_RE_PLANT,
    RE_BSVSTGS.CUST_RE_MATL       AS CUST_RE_MATL,
    RE_BSVSTGS.CUST_RE_QTY        AS CUST_RE_QTY,
    RE_BSVSTGS.CUST_RE_SER        AS CUST_RE_SER,
    RE_BSVSTGS.CUST_RE_PRICE      AS CUST_RE_PRICE,
    RE_BSVSTGS.CUST_RE_AMOUNT     AS CUST_RE_AMOUNT,
    RE_BSVSTGS.SOG                 AS SOG,
    RE_BSVSTGS.CUST_REMARK        AS CUST_REMARK,
    RE_BSVSTGS.RE_MATERIAL        AS RE_MATERIAL,
    RE_BSVSTGS.RE_PLANT           AS RE_PLANT,
    RE_BSVSTGS.RE_D_CHAIN_BLK     AS RE_D_CHAIN_BLK,
    RE_BSVSTGS.RE_UNIT_COST       AS RE_UNIT_COST,
    RE_BSVSTGS.RE_DELIVERY_UNIT   AS RE_DELIVERY_UNIT,
    RE_BSVSTGS.RE_STRATEGY_GRP    AS RE_STRATEGY_GRP,
    RE_BSVSTGS.RE_OH_QTY          AS RE_OH_QTY,
    RE_BSVSTGS.RE_VENDOR          AS RE_VENDOR,
    RE_BSVSTGS.RE_MATL_TYPE       AS RE_MATL_TYPE,
    RE_BSVSTGS.RE_VENDOR_ITEM     AS RE_VENDOR_ITEM,
    RE_BSVSTGS.RE_ULTIMATE_SOURCE AS RE_ULTIMATE_SOURCE,
    RE_BSVSTGS.VP_STRATEGY_GRP    AS VP_STRATEGY_GRP,
    RE_BSVSTGS.VP_OH_QTY          AS VP_OH_QTY,
    RE_BSVSTGS.VP_Q4_SUM          AS VP_Q4_SUM,
    RE_BSVSTGS.Q1_SHIP_QTY        AS Q1_SHIP_QTY,
    RE_BSVSTGS.Q2_SHIP_QTY        AS Q2_SHIP_QTY,
    RE_BSVSTGS.Q3_SHIP_QTY        AS Q3_SHIP_QTY,
    RE_BSVSTGS.Q4_SHIP_QTY        AS Q4_SHIP_QTY,
    RE_BSVSTGS.Q1_LN_QTY          AS Q1_LN_QTY,
    RE_BSVSTGS.Q2_LN_QTY          AS Q2_LN_QTY,
    RE_BSVSTGS.Q3_LN_QTY          AS Q3_LN_QTY,
    RE_BSVSTGS.Q4_LN_QTY          AS Q4_LN_QTY,
    RE_BSVSTGS.ALLOW_RETURN_FLG   AS ALLOW_RETURN_FLG,
    RE_BSVSTGS.SG_CHECK           AS SG_CHECK,
    RE_BSVSTGS.SERISES            AS SERISES,
    EX_RATE.CUR_USD               AS EX_TO_USD
  FROM
    (SELECT RE_BSVSTG.ID           AS ID,
      RE_BSVSTG.CUST_RE_PLANT      AS CUST_RE_PLANT,
      RE_BSVSTG.CUST_RE_MATL       AS CUST_RE_MATL,
      RE_BSVSTG.CUST_RE_QTY        AS CUST_RE_QTY,
      RE_BSVSTG.CUST_RE_SER        AS CUST_RE_SER,
      RE_BSVSTG.CUST_RE_PRICE      AS CUST_RE_PRICE,
      RE_BSVSTG.CUST_RE_AMOUNT     AS CUST_RE_AMOUNT,
      RE_BSVSTG.SOG                 AS SOG,
      RE_BSVSTG.CUST_REMARK        AS CUST_REMARK,
      RE_BSVSTG.CUST_RE_CURRENCY   AS CUST_RE_CURRENCY,
      RE_BSVSTG.RE_MATERIAL        AS RE_MATERIAL,
      RE_BSVSTG.RE_PLANT           AS RE_PLANT,
      RE_BSVSTG.RE_D_CHAIN_BLK     AS RE_D_CHAIN_BLK,
      RE_BSVSTG.RE_UNIT_COST       AS RE_UNIT_COST,
      RE_BSVSTG.RE_DELIVERY_UNIT   AS RE_DELIVERY_UNIT,
      RE_BSVSTG.RE_STRATEGY_GRP    AS RE_STRATEGY_GRP,
      RE_BSVSTG.RE_OH_QTY          AS RE_OH_QTY,
      RE_BSVSTG.RE_VENDOR          AS RE_VENDOR,
      RE_BSVSTG.RE_MATL_TYPE       AS RE_MATL_TYPE,
      RE_BSVSTG.RE_VENDOR_ITEM     AS RE_VENDOR_ITEM,
      RE_BSVSTG.RE_ULTIMATE_SOURCE AS RE_ULTIMATE_SOURCE,
      RE_BSVSTG.VP_STRATEGY_GRP    AS VP_STRATEGY_GRP,
      RE_BSVSTG.VP_OH_QTY          AS VP_OH_QTY,
      RE_BSVSTG.VP_Q4_SUM          AS VP_Q4_SUM,
      RE_BSVSTG.Q1_SHIP_QTY        AS Q1_SHIP_QTY,
      RE_BSVSTG.Q2_SHIP_QTY        AS Q2_SHIP_QTY,
      RE_BSVSTG.Q3_SHIP_QTY        AS Q3_SHIP_QTY,
      RE_BSVSTG.Q4_SHIP_QTY        AS Q4_SHIP_QTY,
      RE_BSVSTG.Q1_LN_QTY          AS Q1_LN_QTY,
      RE_BSVSTG.Q2_LN_QTY          AS Q2_LN_QTY,
      RE_BSVSTG.Q3_LN_QTY          AS Q3_LN_QTY,
      RE_BSVSTG.Q4_LN_QTY          AS Q4_LN_QTY,
      RE_BSVSTG.ALLOW_RETURN_FLG   AS ALLOW_RETURN_FLG,
      RE_BSVSTG.SG_CHECK           AS SG_CHECK,
      MATL_S.SERISES               AS SERISES
    FROM
      (SELECT RE_BSVST.ID           AS ID,
        RE_BSVST.CUST_RE_PLANT      AS CUST_RE_PLANT,
        RE_BSVST.CUST_RE_MATL       AS CUST_RE_MATL,
        RE_BSVST.CUST_RE_QTY        AS CUST_RE_QTY,
        RE_BSVST.CUST_RE_SER        AS CUST_RE_SER,
        RE_BSVST.CUST_RE_PRICE      AS CUST_RE_PRICE,
        RE_BSVST.CUST_RE_AMOUNT     AS CUST_RE_AMOUNT,
        RE_BSVST.SOG                 AS SOG,
        RE_BSVST.CUST_REMARK        AS CUST_REMARK,
        RE_BSVST.CUST_RE_CURRENCY   AS CUST_RE_CURRENCY,
        RE_BSVST.RE_MATERIAL        AS RE_MATERIAL,
        RE_BSVST.RE_PLANT           AS RE_PLANT,
        RE_BSVST.RE_D_CHAIN_BLK     AS RE_D_CHAIN_BLK,
        RE_BSVST.RE_UNIT_COST       AS RE_UNIT_COST,
        RE_BSVST.RE_DELIVERY_UNIT   AS RE_DELIVERY_UNIT,
        RE_BSVST.RE_STRATEGY_GRP    AS RE_STRATEGY_GRP,
        RE_BSVST.RE_OH_QTY          AS RE_OH_QTY,
        RE_BSVST.RE_VENDOR          AS RE_VENDOR,
        RE_BSVST.RE_MATL_TYPE       AS RE_MATL_TYPE,
        RE_BSVST.RE_VENDOR_ITEM     AS RE_VENDOR_ITEM,
        RE_BSVST.RE_ULTIMATE_SOURCE AS RE_ULTIMATE_SOURCE,
        RE_BSVST.VP_STRATEGY_GRP    AS VP_STRATEGY_GRP,
        RE_BSVST.VP_OH_QTY          AS VP_OH_QTY,
        RE_BSVST.VP_Q4_SUM          AS VP_Q4_SUM,
        RE_BSVST.Q1_SHIP_QTY        AS Q1_SHIP_QTY,
        RE_BSVST.Q2_SHIP_QTY        AS Q2_SHIP_QTY,
        RE_BSVST.Q3_SHIP_QTY        AS Q3_SHIP_QTY,
        RE_BSVST.Q4_SHIP_QTY        AS Q4_SHIP_QTY,
        RE_BSVST.Q1_LN_QTY          AS Q1_LN_QTY,
        RE_BSVST.Q2_LN_QTY          AS Q2_LN_QTY,
        RE_BSVST.Q3_LN_QTY          AS Q3_LN_QTY,
        RE_BSVST.Q4_LN_QTY          AS Q4_LN_QTY,
        RE_BSVST.ALLOW_RETURN_FLG   AS ALLOW_RETURN_FLG,
        SG_CH.SG_CHECK              AS SG_CHECK
      FROM
        (SELECT RE_BSVS.ID           AS ID,
          RE_BSVS.CUST_RE_PLANT      AS CUST_RE_PLANT,
          RE_BSVS.CUST_RE_MATL       AS CUST_RE_MATL,
          RE_BSVS.CUST_RE_QTY        AS CUST_RE_QTY,
          RE_BSVS.CUST_RE_SER        AS CUST_RE_SER,
          RE_BSVS.CUST_RE_PRICE      AS CUST_RE_PRICE,
          RE_BSVS.CUST_RE_AMOUNT     AS CUST_RE_AMOUNT,
          RE_BSVS.SOG                AS SOG,
          RE_BSVS.CUST_REMARK        AS CUST_REMARK,
          RE_BSVS.CUST_RE_CURRENCY   AS CUST_RE_CURRENCY,
          RE_BSVS.RE_MATERIAL        AS RE_MATERIAL,
          RE_BSVS.RE_PLANT           AS RE_PLANT,
          RE_BSVS.RE_D_CHAIN_BLK     AS RE_D_CHAIN_BLK,
          RE_BSVS.RE_UNIT_COST       AS RE_UNIT_COST,
          RE_BSVS.RE_DELIVERY_UNIT   AS RE_DELIVERY_UNIT,
          RE_BSVS.RE_STRATEGY_GRP    AS RE_STRATEGY_GRP,
          RE_BSVS.RE_OH_QTY          AS RE_OH_QTY,
          RE_BSVS.RE_VENDOR          AS RE_VENDOR,
          RE_BSVS.RE_MATL_TYPE       AS RE_MATL_TYPE,
          RE_BSVS.RE_VENDOR_ITEM     AS RE_VENDOR_ITEM,
          RE_BSVS.RE_ULTIMATE_SOURCE AS RE_ULTIMATE_SOURCE,
          RE_BSVS.VP_STRATEGY_GRP    AS VP_STRATEGY_GRP,
          RE_BSVS.VP_OH_QTY          AS VP_OH_QTY,
          RE_BSVS.VP_Q4_SUM          AS VP_Q4_SUM,
          RE_BSVS.Q1_SHIP_QTY        AS Q1_SHIP_QTY,
          RE_BSVS.Q2_SHIP_QTY        AS Q2_SHIP_QTY,
          RE_BSVS.Q3_SHIP_QTY        AS Q3_SHIP_QTY,
          RE_BSVS.Q4_SHIP_QTY        AS Q4_SHIP_QTY,
          RE_BSVS.Q1_LN_QTY          AS Q1_LN_QTY,
          RE_BSVS.Q2_LN_QTY          AS Q2_LN_QTY,
          RE_BSVS.Q3_LN_QTY          AS Q3_LN_QTY,
          RE_BSVS.Q4_LN_QTY          AS Q4_LN_QTY,
          ST.ALLOWED_SCHED_RTRN      AS ALLOW_RETURN_FLG
        FROM
          (SELECT RE_BSV.ID           AS ID,
            RE_BSV.RE_MATERIAL||'_'||RE_BSV.SOG AS SOG_ID,
            RE_BSV.CUST_RE_PLANT      AS CUST_RE_PLANT,
            RE_BSV.CUST_RE_MATL       AS CUST_RE_MATL,
            RE_BSV.CUST_RE_QTY        AS CUST_RE_QTY,
            RE_BSV.CUST_RE_SER        AS CUST_RE_SER,
            RE_BSV.CUST_RE_PRICE      AS CUST_RE_PRICE,
            RE_BSV.CUST_RE_AMOUNT     AS CUST_RE_AMOUNT,
            RE_BSV.SOG                AS SOG,
            RE_BSV.CUST_REMARK        AS CUST_REMARK,
            RE_BSV.CUST_RE_CURRENCY   AS CUST_RE_CURRENCY,
            RE_BSV.RE_MATERIAL        AS RE_MATERIAL,
            RE_BSV.RE_PLANT           AS RE_PLANT,
            RE_BSV.RE_D_CHAIN_BLK     AS RE_D_CHAIN_BLK,
            RE_BSV.RE_UNIT_COST       AS RE_UNIT_COST,
            RE_BSV.RE_DELIVERY_UNIT   AS RE_DELIVERY_UNIT,
            RE_BSV.RE_STRATEGY_GRP    AS RE_STRATEGY_GRP,
            RE_BSV.RE_OH_QTY          AS RE_OH_QTY,
            RE_BSV.RE_VENDOR          AS RE_VENDOR,
            RE_BSV.RE_MATL_TYPE       AS RE_MATL_TYPE,
            RE_BSV.RE_VENDOR_ITEM     AS RE_VENDOR_ITEM,
            RE_BSV.RE_ULTIMATE_SOURCE AS RE_ULTIMATE_SOURCE,
            RE_BSV.VP_STRATEGY_GRP    AS VP_STRATEGY_GRP,
            RE_BSV.VP_OH_QTY          AS VP_OH_QTY,
            RE_BSV.VP_Q4_SUM          AS VP_Q4_SUM,
            SOLNSH.Q1_SHIP_QTY        AS Q1_SHIP_QTY,
            SOLNSH.Q2_SHIP_QTY        AS Q2_SHIP_QTY,
            SOLNSH.Q3_SHIP_QTY        AS Q3_SHIP_QTY,
            SOLNSH.Q4_SHIP_QTY        AS Q4_SHIP_QTY,
            SOLNSH.Q1_LN_QTY          AS Q1_LN_QTY,
            SOLNSH.Q2_LN_QTY          AS Q2_LN_QTY,
            SOLNSH.Q3_LN_QTY          AS Q3_LN_QTY,
            SOLNSH.Q4_LN_QTY          AS Q4_LN_QTY
          FROM
            (SELECT RE_BS.ID                                 AS ID,
              RE_BS.CUST_RE_PLANT                            AS CUST_RE_PLANT,
              RE_BS.CUST_RE_MATL                             AS CUST_RE_MATL,
              RE_BS.CUST_RE_QTY                              AS CUST_RE_QTY,
              RE_BS.CUST_RE_SER                              AS CUST_RE_SER,
              RE_BS.CUST_RE_PRICE                            AS CUST_RE_PRICE,
              RE_BS.CUST_RE_AMOUNT                           AS CUST_RE_AMOUNT,
              RE_BS.SOG                                      AS SOG,
              RE_BS.CUST_REMARK                              AS CUST_REMARK,
              RE_BS.CUST_RE_CURRENCY                         AS CUST_RE_CURRENCY,
              RE_BS.RE_MATERIAL                              AS RE_MATERIAL,
              RE_BS.RE_PLANT                                 AS RE_PLANT,
              RE_BS.RE_D_CHAIN_BLK                           AS RE_D_CHAIN_BLK,
              RE_BS.RE_UNIT_COST                             AS RE_UNIT_COST,
              RE_BS.RE_DELIVERY_UNIT                         AS RE_DELIVERY_UNIT,
              RE_BS.RE_STRATEGY_GRP                          AS RE_STRATEGY_GRP,
              RE_BS.RE_OH_QTY                                AS RE_OH_QTY,
              RE_BS.RE_VENDOR                                AS RE_VENDOR,
              RE_BS.RE_MATL_TYPE                             AS RE_MATL_TYPE,
              RE_BS.RE_VENDOR_ITEM                           AS RE_VENDOR_ITEM,
              RE_BS.RE_ULTIMATE_SOURCE                       AS RE_ULTIMATE_SOURCE,
              VENDOR_PLANT.STRATEGY_GRP                      AS VP_STRATEGY_GRP,
              VENDOR_PLANT.OH_QTY                            AS VP_OH_QTY,
              CEIL(NVL(VENDOR_PLANT.AVG13_USAGE_QTY,0) * 13) AS VP_Q4_SUM
            FROM
              (SELECT RETURN_PLANT.ID               AS ID,
                SCHED_RE.PLANT                      AS CUST_RE_PLANT,
                SCHED_RE.RETURN_MATL                AS CUST_RE_MATL,
                SCHED_RE.RETURN_QTY                 AS CUST_RE_QTY,
                SCHED_RE.RETURN_SER                 AS CUST_RE_SER,
                SCHED_RE.RETURN_PRICE               AS CUST_RE_PRICE,
                SCHED_RE.RETURN_AMOUNT              AS CUST_RE_AMOUNT,
                SCHED_RE.SOG                        AS SOG,
                SCHED_RE.REMARK                     AS CUST_REMARK,
                SCHED_RE.RETURN_CURRENCY            AS CUST_RE_CURRENCY,
                RETURN_PLANT.MATERIAL               AS RE_MATERIAL,
                RETURN_PLANT.PLANT                  AS RE_PLANT,
                RETURN_PLANT.D_CHAIN_BLK            AS RE_D_CHAIN_BLK,
                RETURN_PLANT.UNIT_COST              AS RE_UNIT_COST,
                RETURN_PLANT.DELIVERY_UNIT    AS RE_DELIVERY_UNIT,
                RETURN_PLANT.STRATEGY_GRP           AS RE_STRATEGY_GRP,
                RETURN_PLANT.OH_QTY                 AS RE_OH_QTY,
                SUBSTR(RETURN_PLANT.VENDOR_KEY,0,4) AS RE_VENDOR,
                RETURN_PLANT.MATL_TYPE              AS RE_MATL_TYPE,
                RETURN_PLANT.VENDOR_ITEM            AS RE_VENDOR_ITEM,
                RETURN_PLANT.ULTIMATE_SOURCE        AS RE_ULTIMATE_SOURCE
              FROM
                (SELECT TRIM(REPLACE(RETURN_MATL, '-'))
                  ||'_'
                  ||PLANT AS TMP_ID,
                  PLANT,
                  SOG,
                  RETURN_MATL,
                  RETURN_QTY,
                  RETURN_SER,
                  RETURN_PRICE,
                  RETURN_AMOUNT,
                  REMARK,
                  RETURN_CURRENCY
                FROM INV_SAP_SCHED_RE_UL
                WHERE PLANT NOT     IN ('#')
                AND RETURN_MATL NOT IN ('#')
                )SCHED_RE
              LEFT JOIN
                (SELECT ID,
                  TMP_ID,
                  MATERIAL,
                  CATALOG_DASH,
                  CATALOG_NO_DASH,
                  PLANT,
                  D_CHAIN_BLK,
                  UNIT_COST,
                  DELIVERY_UNIT,
                  STRATEGY_GRP,
                  OH_QTY,
                  VENDOR_KEY,
                  MATL_TYPE,
                  VENDOR_ITEM,
                  ULTIMATE_SOURCE
                FROM INV_SAP_PP_OPT_X
                )RETURN_PLANT
              ON RETURN_PLANT.TMP_ID = SCHED_RE.TMP_ID
              )RE_BS
            LEFT JOIN
              ( SELECT ID, STRATEGY_GRP, OH_QTY, AVG13_USAGE_QTY FROM INV_SAP_PP_OPT_X
              )VENDOR_PLANT
            ON VENDOR_PLANT.ID = RE_BS.RE_VENDOR_ITEM
            )RE_BSV
          LEFT JOIN
            (SELECT ID,
              MATERIAL,
              PLANT,
              Q1_SHIP_QTY,
              Q2_SHIP_QTY,
              Q3_SHIP_QTY,
              Q4_SHIP_QTY,
              Q1_LN_QTY,
              Q2_LN_QTY,
              Q3_LN_QTY,
              Q4_LN_QTY
            FROM VIEW_INV_SAP_AP_SOLNSH_STAT
            )SOLNSH
          ON SOLNSH.ID = RE_BSV.ID
          )RE_BSVS
        LEFT JOIN
          (SELECT MATERIALID
            ||'_'
            ||SALES_ORG AS ID,
            ALLOWED_SCHED_RTRN
          FROM INV_SAP_PP_MVKE
          )ST
        ON ST.ID = RE_BSVS.SOG_ID
        )RE_BSVST
      LEFT JOIN
        (SELECT ID, SG_CHECK FROM INV_SAP_SR_SGCHECK
        )SG_CH
      ON SG_CH.ID = RE_BSVST.ID
      )RE_BSVSTG
    LEFT JOIN
      (SELECT MATERIAL, SERISES FROM INV_SAP_MATLSE_SRCH
      )MATL_S
    ON MATL_S.MATERIAL = RE_BSVSTG.RE_MATERIAL
    )RE_BSVSTGS
  LEFT JOIN
    ( SELECT CUR_USD,CUR_TYPE,PLANT FROM INV_SAP_EXCHANGE_RATE
    )EX_RATE
  ON EX_RATE.CUR_TYPE = RE_BSVSTGS.CUST_RE_CURRENCY
  )RE_BSVSTGSR
LEFT JOIN
  (SELECT ID,
    MAX_DIS_NAME,
    MAX_DIS_USAGE_QTY,
    TOT_USAGE_QTY,
    ROUND(PERSENTAGE,4) AS PER_BIGGEST,
    DISTRIBUTOR_COUNT
  FROM INV_SAP_DSTR_STATS
  )DSTR_STATS
ON RE_BSVSTGSR.ID = DSTR_STATS.ID; 
  

DROP VIEW VIEW_INV_SAP_SCH_REMATL;
CREATE VIEW VIEW_INV_SAP_SCH_REMATL AS
SELECT RE_BSVSTGSR.ID            AS ID,
  RE_BSVSTGSR.CUST_RE_PLANT      AS CUST_RE_PLANT,
  RE_BSVSTGSR.CUST_RE_MATL       AS CUST_RE_MATL,
  RE_BSVSTGSR.CUST_RE_QTY        AS CUST_RE_QTY,
  RE_BSVSTGSR.CUST_RE_SER        AS CUST_RE_SER,
  RE_BSVSTGSR.CUST_RE_PRICE      AS CUST_RE_PRICE,
  RE_BSVSTGSR.CUST_RE_AMOUNT     AS CUST_RE_AMOUNT,
  RE_BSVSTGSR.SOG                AS SOG,
  RE_BSVSTGSR.CUST_REMARK        AS CUST_REMARK,
  RE_BSVSTGSR.RE_MATERIAL        AS RE_MATERIAL,
  RE_BSVSTGSR.RE_PLANT           AS RE_PLANT,
  RE_BSVSTGSR.RE_D_CHAIN_BLK     AS RE_D_CHAIN_BLK,
  RE_BSVSTGSR.RE_UNIT_COST       AS RE_UNIT_COST,
  RE_BSVSTGSR.RE_DELIVERY_UNIT   AS RE_DELIVERY_UNIT,
  RE_BSVSTGSR.RE_STRATEGY_GRP    AS RE_STRATEGY_GRP,
  RE_BSVSTGSR.RE_OH_QTY          AS RE_OH_QTY,
  RE_BSVSTGSR.RE_VENDOR          AS RE_VENDOR,
  RE_BSVSTGSR.RE_MATL_TYPE       AS RE_MATL_TYPE,
  RE_BSVSTGSR.RE_VENDOR_ITEM     AS RE_VENDOR_ITEM,
  RE_BSVSTGSR.RE_ULTIMATE_SOURCE AS RE_ULTIMATE_SOURCE,
  RE_BSVSTGSR.VP_STRATEGY_GRP    AS VP_STRATEGY_GRP,
  RE_BSVSTGSR.VP_OH_QTY          AS VP_OH_QTY,
  RE_BSVSTGSR.VP_Q4_SUM          AS VP_Q4_SUM,
  RE_BSVSTGSR.Q1_SHIP_QTY        AS Q1_SHIP_QTY,
  RE_BSVSTGSR.Q2_SHIP_QTY        AS Q2_SHIP_QTY,
  RE_BSVSTGSR.Q3_SHIP_QTY        AS Q3_SHIP_QTY,
  RE_BSVSTGSR.Q4_SHIP_QTY        AS Q4_SHIP_QTY,
  RE_BSVSTGSR.Q1_LN_QTY          AS Q1_LN_QTY,
  RE_BSVSTGSR.Q2_LN_QTY          AS Q2_LN_QTY,
  RE_BSVSTGSR.Q3_LN_QTY          AS Q3_LN_QTY,
  RE_BSVSTGSR.Q4_LN_QTY          AS Q4_LN_QTY,
  DSTR_STATS.MAX_DIS_NAME        AS MAX_DIS_NAME,
  DSTR_STATS.MAX_DIS_USAGE_QTY   AS MAX_DIS_USAGE_QTY,
  DSTR_STATS.TOT_USAGE_QTY       AS TOT_USAGE_QTY,
  DSTR_STATS.PER_BIGGEST         AS PER_BIGGEST,
  DSTR_STATS.DISTRIBUTOR_COUNT   AS DISTRIBUTOR_COUNT,
  RE_BSVSTGSR.ALLOW_RETURN_FLG   AS ALLOW_RETURN_FLG,
  RE_BSVSTGSR.SG_CHECK           AS SG_CHECK,
  RE_BSVSTGSR.SERISES            AS SERISES,
  RE_BSVSTGSR.EX_TO_USD          AS EX_TO_USD
FROM
  (SELECT RE_BSVSTGS.ID           AS ID,
    RE_BSVSTGS.CUST_RE_PLANT      AS CUST_RE_PLANT,
    RE_BSVSTGS.CUST_RE_MATL       AS CUST_RE_MATL,
    RE_BSVSTGS.CUST_RE_QTY        AS CUST_RE_QTY,
    RE_BSVSTGS.CUST_RE_SER        AS CUST_RE_SER,
    RE_BSVSTGS.CUST_RE_PRICE      AS CUST_RE_PRICE,
    RE_BSVSTGS.CUST_RE_AMOUNT     AS CUST_RE_AMOUNT,
    RE_BSVSTGS.SOG                AS SOG,
    RE_BSVSTGS.CUST_REMARK        AS CUST_REMARK,
    RE_BSVSTGS.RE_MATERIAL        AS RE_MATERIAL,
    RE_BSVSTGS.RE_PLANT           AS RE_PLANT,
    RE_BSVSTGS.RE_D_CHAIN_BLK     AS RE_D_CHAIN_BLK,
    RE_BSVSTGS.RE_UNIT_COST       AS RE_UNIT_COST,
    RE_BSVSTGS.RE_DELIVERY_UNIT   AS RE_DELIVERY_UNIT,
    RE_BSVSTGS.RE_STRATEGY_GRP    AS RE_STRATEGY_GRP,
    RE_BSVSTGS.RE_OH_QTY          AS RE_OH_QTY,
    RE_BSVSTGS.RE_VENDOR          AS RE_VENDOR,
    RE_BSVSTGS.RE_MATL_TYPE       AS RE_MATL_TYPE,
    RE_BSVSTGS.RE_VENDOR_ITEM     AS RE_VENDOR_ITEM,
    RE_BSVSTGS.RE_ULTIMATE_SOURCE AS RE_ULTIMATE_SOURCE,
    RE_BSVSTGS.VP_STRATEGY_GRP    AS VP_STRATEGY_GRP,
    RE_BSVSTGS.VP_OH_QTY          AS VP_OH_QTY,
    RE_BSVSTGS.VP_Q4_SUM          AS VP_Q4_SUM,
    RE_BSVSTGS.Q1_SHIP_QTY        AS Q1_SHIP_QTY,
    RE_BSVSTGS.Q2_SHIP_QTY        AS Q2_SHIP_QTY,
    RE_BSVSTGS.Q3_SHIP_QTY        AS Q3_SHIP_QTY,
    RE_BSVSTGS.Q4_SHIP_QTY        AS Q4_SHIP_QTY,
    RE_BSVSTGS.Q1_LN_QTY          AS Q1_LN_QTY,
    RE_BSVSTGS.Q2_LN_QTY          AS Q2_LN_QTY,
    RE_BSVSTGS.Q3_LN_QTY          AS Q3_LN_QTY,
    RE_BSVSTGS.Q4_LN_QTY          AS Q4_LN_QTY,
    RE_BSVSTGS.ALLOW_RETURN_FLG   AS ALLOW_RETURN_FLG,
    RE_BSVSTGS.SG_CHECK           AS SG_CHECK,
    RE_BSVSTGS.SERISES            AS SERISES,
    EX_RATE.CUR_USD               AS EX_TO_USD
  FROM
    (SELECT RE_BSVSTG.ID           AS ID,
      RE_BSVSTG.CUST_RE_PLANT      AS CUST_RE_PLANT,
      RE_BSVSTG.CUST_RE_MATL       AS CUST_RE_MATL,
      RE_BSVSTG.CUST_RE_QTY        AS CUST_RE_QTY,
      RE_BSVSTG.CUST_RE_SER        AS CUST_RE_SER,
      RE_BSVSTG.CUST_RE_PRICE      AS CUST_RE_PRICE,
      RE_BSVSTG.CUST_RE_AMOUNT     AS CUST_RE_AMOUNT,
      RE_BSVSTG.SOG                AS SOG,
      RE_BSVSTG.CUST_REMARK        AS CUST_REMARK,
      RE_BSVSTG.CUST_RE_CURRENCY   AS CUST_RE_CURRENCY,
      RE_BSVSTG.RE_MATERIAL        AS RE_MATERIAL,
      RE_BSVSTG.RE_PLANT           AS RE_PLANT,
      RE_BSVSTG.RE_D_CHAIN_BLK     AS RE_D_CHAIN_BLK,
      RE_BSVSTG.RE_UNIT_COST       AS RE_UNIT_COST,
      RE_BSVSTG.RE_DELIVERY_UNIT   AS RE_DELIVERY_UNIT,
      RE_BSVSTG.RE_STRATEGY_GRP    AS RE_STRATEGY_GRP,
      RE_BSVSTG.RE_OH_QTY          AS RE_OH_QTY,
      RE_BSVSTG.RE_VENDOR          AS RE_VENDOR,
      RE_BSVSTG.RE_MATL_TYPE       AS RE_MATL_TYPE,
      RE_BSVSTG.RE_VENDOR_ITEM     AS RE_VENDOR_ITEM,
      RE_BSVSTG.RE_ULTIMATE_SOURCE AS RE_ULTIMATE_SOURCE,
      RE_BSVSTG.VP_STRATEGY_GRP    AS VP_STRATEGY_GRP,
      RE_BSVSTG.VP_OH_QTY          AS VP_OH_QTY,
      RE_BSVSTG.VP_Q4_SUM          AS VP_Q4_SUM,
      RE_BSVSTG.Q1_SHIP_QTY        AS Q1_SHIP_QTY,
      RE_BSVSTG.Q2_SHIP_QTY        AS Q2_SHIP_QTY,
      RE_BSVSTG.Q3_SHIP_QTY        AS Q3_SHIP_QTY,
      RE_BSVSTG.Q4_SHIP_QTY        AS Q4_SHIP_QTY,
      RE_BSVSTG.Q1_LN_QTY          AS Q1_LN_QTY,
      RE_BSVSTG.Q2_LN_QTY          AS Q2_LN_QTY,
      RE_BSVSTG.Q3_LN_QTY          AS Q3_LN_QTY,
      RE_BSVSTG.Q4_LN_QTY          AS Q4_LN_QTY,
      RE_BSVSTG.ALLOW_RETURN_FLG   AS ALLOW_RETURN_FLG,
      RE_BSVSTG.SG_CHECK           AS SG_CHECK,
      MATL_S.SERISES               AS SERISES
    FROM
      (SELECT RE_BSVST.ID           AS ID,
        RE_BSVST.CUST_RE_PLANT      AS CUST_RE_PLANT,
        RE_BSVST.CUST_RE_MATL       AS CUST_RE_MATL,
        RE_BSVST.CUST_RE_QTY        AS CUST_RE_QTY,
        RE_BSVST.CUST_RE_SER        AS CUST_RE_SER,
        RE_BSVST.CUST_RE_PRICE      AS CUST_RE_PRICE,
        RE_BSVST.CUST_RE_AMOUNT     AS CUST_RE_AMOUNT,
        RE_BSVST.SOG                AS SOG,
        RE_BSVST.CUST_REMARK        AS CUST_REMARK,
        RE_BSVST.CUST_RE_CURRENCY   AS CUST_RE_CURRENCY,
        RE_BSVST.RE_MATERIAL        AS RE_MATERIAL,
        RE_BSVST.RE_PLANT           AS RE_PLANT,
        RE_BSVST.RE_D_CHAIN_BLK     AS RE_D_CHAIN_BLK,
        RE_BSVST.RE_UNIT_COST       AS RE_UNIT_COST,
        RE_BSVST.RE_DELIVERY_UNIT   AS RE_DELIVERY_UNIT,
        RE_BSVST.RE_STRATEGY_GRP    AS RE_STRATEGY_GRP,
        RE_BSVST.RE_OH_QTY          AS RE_OH_QTY,
        RE_BSVST.RE_VENDOR          AS RE_VENDOR,
        RE_BSVST.RE_MATL_TYPE       AS RE_MATL_TYPE,
        RE_BSVST.RE_VENDOR_ITEM     AS RE_VENDOR_ITEM,
        RE_BSVST.RE_ULTIMATE_SOURCE AS RE_ULTIMATE_SOURCE,
        RE_BSVST.VP_STRATEGY_GRP    AS VP_STRATEGY_GRP,
        RE_BSVST.VP_OH_QTY          AS VP_OH_QTY,
        RE_BSVST.VP_Q4_SUM          AS VP_Q4_SUM,
        RE_BSVST.Q1_SHIP_QTY        AS Q1_SHIP_QTY,
        RE_BSVST.Q2_SHIP_QTY        AS Q2_SHIP_QTY,
        RE_BSVST.Q3_SHIP_QTY        AS Q3_SHIP_QTY,
        RE_BSVST.Q4_SHIP_QTY        AS Q4_SHIP_QTY,
        RE_BSVST.Q1_LN_QTY          AS Q1_LN_QTY,
        RE_BSVST.Q2_LN_QTY          AS Q2_LN_QTY,
        RE_BSVST.Q3_LN_QTY          AS Q3_LN_QTY,
        RE_BSVST.Q4_LN_QTY          AS Q4_LN_QTY,
        RE_BSVST.ALLOW_RETURN_FLG   AS ALLOW_RETURN_FLG,
        SG_CH.SG_CHECK              AS SG_CHECK
      FROM
        (SELECT RE_BSVS.ID           AS ID,
          RE_BSVS.CUST_RE_PLANT      AS CUST_RE_PLANT,
          RE_BSVS.CUST_RE_MATL       AS CUST_RE_MATL,
          RE_BSVS.CUST_RE_QTY        AS CUST_RE_QTY,
          RE_BSVS.CUST_RE_SER        AS CUST_RE_SER,
          RE_BSVS.CUST_RE_PRICE      AS CUST_RE_PRICE,
          RE_BSVS.CUST_RE_AMOUNT     AS CUST_RE_AMOUNT,
          RE_BSVS.SOG                AS SOG,
          RE_BSVS.CUST_REMARK        AS CUST_REMARK,
          RE_BSVS.CUST_RE_CURRENCY   AS CUST_RE_CURRENCY,
          RE_BSVS.RE_MATERIAL        AS RE_MATERIAL,
          RE_BSVS.RE_PLANT           AS RE_PLANT,
          RE_BSVS.RE_D_CHAIN_BLK     AS RE_D_CHAIN_BLK,
          RE_BSVS.RE_UNIT_COST       AS RE_UNIT_COST,
          RE_BSVS.RE_DELIVERY_UNIT   AS RE_DELIVERY_UNIT,
          RE_BSVS.RE_STRATEGY_GRP    AS RE_STRATEGY_GRP,
          RE_BSVS.RE_OH_QTY          AS RE_OH_QTY,
          RE_BSVS.RE_VENDOR          AS RE_VENDOR,
          RE_BSVS.RE_MATL_TYPE       AS RE_MATL_TYPE,
          RE_BSVS.RE_VENDOR_ITEM     AS RE_VENDOR_ITEM,
          RE_BSVS.RE_ULTIMATE_SOURCE AS RE_ULTIMATE_SOURCE,
          RE_BSVS.VP_STRATEGY_GRP    AS VP_STRATEGY_GRP,
          RE_BSVS.VP_OH_QTY          AS VP_OH_QTY,
          RE_BSVS.VP_Q4_SUM          AS VP_Q4_SUM,
          RE_BSVS.Q1_SHIP_QTY        AS Q1_SHIP_QTY,
          RE_BSVS.Q2_SHIP_QTY        AS Q2_SHIP_QTY,
          RE_BSVS.Q3_SHIP_QTY        AS Q3_SHIP_QTY,
          RE_BSVS.Q4_SHIP_QTY        AS Q4_SHIP_QTY,
          RE_BSVS.Q1_LN_QTY          AS Q1_LN_QTY,
          RE_BSVS.Q2_LN_QTY          AS Q2_LN_QTY,
          RE_BSVS.Q3_LN_QTY          AS Q3_LN_QTY,
          RE_BSVS.Q4_LN_QTY          AS Q4_LN_QTY,
          ST.ALLOWED_SCHED_RTRN      AS ALLOW_RETURN_FLG
        FROM
          (SELECT RE_BSV.ID           AS ID,
            RE_BSV.CUST_RE_MATL||'_'||RE_BSV.SOG AS SOG_ID,
            RE_BSV.CUST_RE_PLANT      AS CUST_RE_PLANT,
            RE_BSV.CUST_RE_MATL       AS CUST_RE_MATL,
            RE_BSV.CUST_RE_QTY        AS CUST_RE_QTY,
            RE_BSV.CUST_RE_SER        AS CUST_RE_SER,
            RE_BSV.CUST_RE_PRICE      AS CUST_RE_PRICE,
            RE_BSV.CUST_RE_AMOUNT     AS CUST_RE_AMOUNT,
            RE_BSV.SOG                 AS SOG,
            RE_BSV.CUST_REMARK        AS CUST_REMARK,
            RE_BSV.CUST_RE_CURRENCY   AS CUST_RE_CURRENCY,
            RE_BSV.RE_MATERIAL        AS RE_MATERIAL,
            RE_BSV.RE_PLANT           AS RE_PLANT,
            RE_BSV.RE_D_CHAIN_BLK     AS RE_D_CHAIN_BLK,
            RE_BSV.RE_UNIT_COST       AS RE_UNIT_COST,
            RE_BSV.RE_DELIVERY_UNIT   AS RE_DELIVERY_UNIT,
            RE_BSV.RE_STRATEGY_GRP    AS RE_STRATEGY_GRP,
            RE_BSV.RE_OH_QTY          AS RE_OH_QTY,
            RE_BSV.RE_VENDOR          AS RE_VENDOR,
            RE_BSV.RE_MATL_TYPE       AS RE_MATL_TYPE,
            RE_BSV.RE_VENDOR_ITEM     AS RE_VENDOR_ITEM,
            RE_BSV.RE_ULTIMATE_SOURCE AS RE_ULTIMATE_SOURCE,
            RE_BSV.VP_STRATEGY_GRP    AS VP_STRATEGY_GRP,
            RE_BSV.VP_OH_QTY          AS VP_OH_QTY,
            RE_BSV.VP_Q4_SUM          AS VP_Q4_SUM,
            SOLNSH.Q1_SHIP_QTY        AS Q1_SHIP_QTY,
            SOLNSH.Q2_SHIP_QTY        AS Q2_SHIP_QTY,
            SOLNSH.Q3_SHIP_QTY        AS Q3_SHIP_QTY,
            SOLNSH.Q4_SHIP_QTY        AS Q4_SHIP_QTY,
            SOLNSH.Q1_LN_QTY          AS Q1_LN_QTY,
            SOLNSH.Q2_LN_QTY          AS Q2_LN_QTY,
            SOLNSH.Q3_LN_QTY          AS Q3_LN_QTY,
            SOLNSH.Q4_LN_QTY          AS Q4_LN_QTY
          FROM
            (SELECT RE_BS.ID                                 AS ID,
              RE_BS.CUST_RE_PLANT                            AS CUST_RE_PLANT,
              RE_BS.CUST_RE_MATL                             AS CUST_RE_MATL,
              RE_BS.CUST_RE_QTY                              AS CUST_RE_QTY,
              RE_BS.CUST_RE_SER                              AS CUST_RE_SER,
              RE_BS.CUST_RE_PRICE                            AS CUST_RE_PRICE,
              RE_BS.CUST_RE_AMOUNT                           AS CUST_RE_AMOUNT,
              RE_BS.SOG                                      AS SOG,
              RE_BS.CUST_REMARK                              AS CUST_REMARK,
              RE_BS.CUST_RE_CURRENCY                         AS CUST_RE_CURRENCY,
              RE_BS.RE_MATERIAL                              AS RE_MATERIAL,
              RE_BS.RE_PLANT                                 AS RE_PLANT,
              RE_BS.RE_D_CHAIN_BLK                           AS RE_D_CHAIN_BLK,
              RE_BS.RE_UNIT_COST                             AS RE_UNIT_COST,
              RE_BS.RE_DELIVERY_UNIT                         AS RE_DELIVERY_UNIT,
              RE_BS.RE_STRATEGY_GRP                          AS RE_STRATEGY_GRP,
              RE_BS.RE_OH_QTY                                AS RE_OH_QTY,
              RE_BS.RE_VENDOR                                AS RE_VENDOR,
              RE_BS.RE_MATL_TYPE                             AS RE_MATL_TYPE,
              RE_BS.RE_VENDOR_ITEM                           AS RE_VENDOR_ITEM,
              RE_BS.RE_ULTIMATE_SOURCE                       AS RE_ULTIMATE_SOURCE,
              VENDOR_PLANT.STRATEGY_GRP                      AS VP_STRATEGY_GRP,
              VENDOR_PLANT.OH_QTY                            AS VP_OH_QTY,
              CEIL(NVL(VENDOR_PLANT.AVG13_USAGE_QTY,0) * 13) AS VP_Q4_SUM
            FROM
              (SELECT RETURN_PLANT.ID               AS ID,
                SCHED_RE.PLANT                      AS CUST_RE_PLANT,
                SCHED_RE.RETURN_MATL                AS CUST_RE_MATL,
                SCHED_RE.RETURN_QTY                 AS CUST_RE_QTY,
                SCHED_RE.RETURN_SER                 AS CUST_RE_SER,
                SCHED_RE.RETURN_PRICE               AS CUST_RE_PRICE,
                SCHED_RE.RETURN_AMOUNT              AS CUST_RE_AMOUNT,
                SCHED_RE.SOG                        AS SOG,
                SCHED_RE.REMARK                     AS CUST_REMARK,
                SCHED_RE.RETURN_CURRENCY            AS CUST_RE_CURRENCY,
                RETURN_PLANT.MATERIAL               AS RE_MATERIAL,
                RETURN_PLANT.PLANT                  AS RE_PLANT,
                RETURN_PLANT.D_CHAIN_BLK            AS RE_D_CHAIN_BLK,
                RETURN_PLANT.UNIT_COST              AS RE_UNIT_COST,
                RETURN_PLANT.DELIVERY_UNIT     AS RE_DELIVERY_UNIT,
                RETURN_PLANT.STRATEGY_GRP           AS RE_STRATEGY_GRP,
                RETURN_PLANT.OH_QTY                 AS RE_OH_QTY,
                SUBSTR(RETURN_PLANT.VENDOR_KEY,0,4) AS RE_VENDOR,
                RETURN_PLANT.MATL_TYPE              AS RE_MATL_TYPE,
                RETURN_PLANT.VENDOR_ITEM            AS RE_VENDOR_ITEM,
                RETURN_PLANT.ULTIMATE_SOURCE        AS RE_ULTIMATE_SOURCE
              FROM
                (SELECT TRIM(RETURN_MATL)
                  ||'_'
                  ||PLANT AS ID,
                  PLANT,
                  RETURN_MATL,
                  RETURN_QTY,
                  RETURN_SER,
                  RETURN_PRICE,
                  RETURN_AMOUNT,
                  SOG,
                  REMARK,
                  RETURN_CURRENCY
                FROM INV_SAP_SCHED_RE_UL
                WHERE PLANT NOT     IN ('#')
                AND RETURN_MATL NOT IN ('#')
                )SCHED_RE
              LEFT JOIN
                (SELECT ID,
                  MATERIAL,
                  CATALOG_DASH,
                  CATALOG_NO_DASH,
                  PLANT,
                  D_CHAIN_BLK,
                  UNIT_COST,
                  DELIVERY_UNIT,
                  STRATEGY_GRP,
                  OH_QTY,
                  VENDOR_KEY,
                  MATL_TYPE,
                  VENDOR_ITEM,
                  ULTIMATE_SOURCE
                FROM INV_SAP_PP_OPT_X
                )RETURN_PLANT
              ON RETURN_PLANT.ID = SCHED_RE.ID
              )RE_BS
            LEFT JOIN
              ( SELECT ID, STRATEGY_GRP, OH_QTY, AVG13_USAGE_QTY FROM INV_SAP_PP_OPT_X
              )VENDOR_PLANT
            ON VENDOR_PLANT.ID = RE_BS.RE_VENDOR_ITEM
            )RE_BSV
          LEFT JOIN
            (SELECT ID,
              MATERIAL,
              PLANT,
              Q1_SHIP_QTY,
              Q2_SHIP_QTY,
              Q3_SHIP_QTY,
              Q4_SHIP_QTY,
              Q1_LN_QTY,
              Q2_LN_QTY,
              Q3_LN_QTY,
              Q4_LN_QTY
            FROM VIEW_INV_SAP_AP_SOLNSH_STAT
            )SOLNSH
          ON SOLNSH.ID = RE_BSV.ID
          )RE_BSVS
        LEFT JOIN
          (SELECT MATERIALID
            ||'_'
            ||SALES_ORG AS ID,
            ALLOWED_SCHED_RTRN
          FROM INV_SAP_PP_MVKE
          )ST
        ON ST.ID = RE_BSVS.SOG_ID
        )RE_BSVST
      LEFT JOIN
        (SELECT ID, SG_CHECK FROM INV_SAP_SR_SGCHECK
        )SG_CH
      ON SG_CH.ID = RE_BSVST.ID
      )RE_BSVSTG
    LEFT JOIN
      (SELECT MATERIAL, SERISES FROM INV_SAP_MATLSE_SRCH
      )MATL_S
    ON MATL_S.MATERIAL = RE_BSVSTG.RE_MATERIAL
    )RE_BSVSTGS
  LEFT JOIN
    ( SELECT CUR_USD,CUR_TYPE,PLANT FROM INV_SAP_EXCHANGE_RATE
    )EX_RATE
  ON EX_RATE.CUR_TYPE = RE_BSVSTGS.CUST_RE_CURRENCY
  )RE_BSVSTGSR
LEFT JOIN
  (SELECT ID,
    MAX_DIS_NAME,
    MAX_DIS_USAGE_QTY,
    TOT_USAGE_QTY,
    ROUND(PERSENTAGE,4) AS PER_BIGGEST,
    DISTRIBUTOR_COUNT
  FROM INV_SAP_DSTR_STATS
  )DSTR_STATS
ON RE_BSVSTGSR.ID = DSTR_STATS.ID; 
