-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Project Name : APAFC
-- Version : 1.0
-- Description:
-- Table Init
-- Revision History:
--    Date        Developer         Description
--    ---------   ---------------   ----------------------------------------------------
--    2015-6-25  Moyue           	  Inv Report
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------

select * from VIEW_INV_REP_WK ;
SELECT DISTINCT REC_DATE_USG FROM INV_SAP_PP_SO_13WKUSG WHERE REC_DATE_USG BETWEEN TO_CHAR(SYSDATE- 8) AND TO_CHAR(SYSDATE + 2);
SELECT (SYSDATE - 1) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 92) AND TO_CHAR(SYSDATE-1) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL


CREATE TABLE INV_SAP_PP_SO_13WKUSG_bk AS SELECT * FROM INV_SAP_PP_SO_13WKUSG;
CREATE TABLE INV_SAP_PP_SO_13WKUSG AS SELECT * FROM INV_SAP_PP_SO_13WKUSG_bk;
DROP TABLE INV_SAP_PP_SO_13WKUSG;

INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT SYSDATE AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 91) AND TO_CHAR(SYSDATE) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;

INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 1) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 92) AND TO_CHAR(SYSDATE-1) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;

INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 6) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 97) AND TO_CHAR(SYSDATE - 6) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 13) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 104) AND TO_CHAR(SYSDATE - 13) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 20) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 111) AND TO_CHAR(SYSDATE - 20) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 27) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 118) AND TO_CHAR(SYSDATE - 27) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 34) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 125) AND TO_CHAR(SYSDATE - 34) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 41) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 132) AND TO_CHAR(SYSDATE - 41) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 48) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 139) AND TO_CHAR(SYSDATE - 48) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 55) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 146) AND TO_CHAR(SYSDATE - 55) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 62) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 153) AND TO_CHAR(SYSDATE - 62) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 69) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 160) AND TO_CHAR(SYSDATE - 69) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 76) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 167) AND TO_CHAR(SYSDATE - 76) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 83) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 174) AND TO_CHAR(SYSDATE - 83) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 90) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 181) AND TO_CHAR(SYSDATE - 90) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 97) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 188) AND TO_CHAR(SYSDATE - 97) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 104) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 195) AND TO_CHAR(SYSDATE - 104) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 111) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 202) AND TO_CHAR(SYSDATE - 111) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 118) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 209) AND TO_CHAR(SYSDATE - 118) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 125) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 216) AND TO_CHAR(SYSDATE - 125) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 132) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 223) AND TO_CHAR(SYSDATE - 132) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 139) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 230) AND TO_CHAR(SYSDATE - 139) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 146) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 237) AND TO_CHAR(SYSDATE - 146) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 153) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 244) AND TO_CHAR(SYSDATE - 153) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 160) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 251) AND TO_CHAR(SYSDATE - 160) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 167) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 258) AND TO_CHAR(SYSDATE - 167) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 174) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 265) AND TO_CHAR(SYSDATE - 174) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 181) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 272) AND TO_CHAR(SYSDATE - 181) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 188) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 279) AND TO_CHAR(SYSDATE - 188) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 195) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 286) AND TO_CHAR(SYSDATE - 195) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 202) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 293) AND TO_CHAR(SYSDATE - 202) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 209) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 300) AND TO_CHAR(SYSDATE - 209) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 216) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 307) AND TO_CHAR(SYSDATE - 216) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 223) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 314) AND TO_CHAR(SYSDATE - 223) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 230) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 321) AND TO_CHAR(SYSDATE - 230) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 237) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 328) AND TO_CHAR(SYSDATE - 237) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 244) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 335) AND TO_CHAR(SYSDATE - 244) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 251) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 342) AND TO_CHAR(SYSDATE - 251) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 258) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 349) AND TO_CHAR(SYSDATE - 258) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 265) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 356) AND TO_CHAR(SYSDATE - 265) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 272) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 363) AND TO_CHAR(SYSDATE - 272) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 279) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 370) AND TO_CHAR(SYSDATE - 279) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 286) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 377) AND TO_CHAR(SYSDATE - 286) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 293) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 384) AND TO_CHAR(SYSDATE - 293) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 300) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 391) AND TO_CHAR(SYSDATE - 300) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 307) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 398) AND TO_CHAR(SYSDATE - 307) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 314) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 405) AND TO_CHAR(SYSDATE - 314) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 321) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 412) AND TO_CHAR(SYSDATE - 321) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 328) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 419) AND TO_CHAR(SYSDATE - 328) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 335) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 426) AND TO_CHAR(SYSDATE - 335) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 342) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 433) AND TO_CHAR(SYSDATE - 342) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 349) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 440) AND TO_CHAR(SYSDATE - 349) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 356) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 447) AND TO_CHAR(SYSDATE - 356) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;
INSERT INTO INV_SAP_PP_SO_13WKUSG SELECT (SYSDATE - 363) AS REC_DATE_USG,ID,MATERIAL,SUM(ORDER_QTY) AS WK13_USAGE_QTY FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 454) AND TO_CHAR(SYSDATE - 363) AND OPEN_QTY = 0 GROUP BY ID, MATERIAL;



















SELECT INVTO.REC_DATE,
  INVTO.PLANTID,
  INVTO.MATERIAL,
  INVTO.CATALOG_DASH,
  INVTO.STRATEGY_GRP,
  INVTO.SAFETY_STOCK,
  INVTO.UNIT_COST,
  INVTO.MATL_TYPE,
  INVTO.OH_QTY,
  INVTO.MIN_INV,
  INVTO.TARGET_INV,
  INVTO.MAX_INV,
  INVTO.OH_VAL,
  CEIL(NVL(INVTO.OH_VAL,0) - NVL(INVTO.UNIT_COST,0)*NVL(INV_PRE.PRE_OH_WK1, 0)) AS DIFF,
  INVTO.MIN_INV_VAL,
  INVTO.TARGET_INV_VAL,
  INVTO.MAX_INV_VAL,
  INVTO.OVER_MAX_VAL,
  CEIL(NVL(INVTO.UNIT_COST,0)*NVL(INV_PRE.PRE_OH_WK1, 0)) AS PRE_OH_WK1_VAL,
  INV_PRE.PRE_OH_WK1,
  INV_PRE.PRE_OH_WK2,
  INV_PRE.PRE_OH_WK3,
  INV_PRE.PRE_OH_WK4,
  INV_PRE.PRE_OH_WK5,
  INV_PRE.PRE_OH_WK6,
  INV_PRE.PRE_OH_WK7,
  INV_PRE.PRE_OH_WK8,
  INV_PRE.PRE_OH_WK9,
  INV_PRE.PRE_OH_WK10,
  INV_PRE.PRE_OH_WK11,
  INV_PRE.PRE_OH_WK12
FROM
  (SELECT ID,
    REC_DATE,
    PLANTID,
    MATERIAL,
    CATALOG_DASH,
    SAFETY_STOCK,
    UNIT_COST,
    STRATEGY_GRP,
    MATL_TYPE,
    OH_QTY,
    MIN_INV,
    TARGET_INV,
    MAX_INV,
    OH_VAL,
    MIN_INV_VAL,
    TARGET_INV_VAL,
    MAX_INV_VAL,
    OVER_MAX_VAL
  FROM INV_SAP_INV_REC
  WHERE REC_DATE BETWEEN TO_CHAR(SYSDATE) AND TO_CHAR(SYSDATE + 1)
  AND OH_QTY <> 0
  )INVTO
LEFT JOIN
  (SELECT ID,
    SUM(PRE_OH_WEEK1)  AS PRE_OH_WK1,
    SUM(PRE_OH_WEEK2)  AS PRE_OH_WK2,
    SUM(PRE_OH_WEEK3)  AS PRE_OH_WK3,
    SUM(PRE_OH_WEEK4)  AS PRE_OH_WK4,
    SUM(PRE_OH_WEEK5)  AS PRE_OH_WK5,
    SUM(PRE_OH_WEEK6)  AS PRE_OH_WK6,
    SUM(PRE_OH_WEEK7)  AS PRE_OH_WK7,
    SUM(PRE_OH_WEEK8)  AS PRE_OH_WK8,
    SUM(PRE_OH_WEEK9)  AS PRE_OH_WK9,
    SUM(PRE_OH_WEEK10) AS PRE_OH_WK10,
    SUM(PRE_OH_WEEK11) AS PRE_OH_WK11,
    SUM(PRE_OH_WEEK12) AS PRE_OH_WK12
  FROM
    (SELECT ID,
      CASE
        WHEN PRE_REC_DATE BETWEEN TO_CHAR(SYSDATE - 7) AND TO_CHAR(SYSDATE - 6)
        THEN PRE_OH_VAL
        ELSE 0
      END PRE_OH_WEEK1,
      CASE
        WHEN PRE_REC_DATE BETWEEN TO_CHAR(SYSDATE - 14) AND TO_CHAR(SYSDATE - 13)
        THEN PRE_OH_VAL
        ELSE 0
      END PRE_OH_WEEK2,
      CASE
        WHEN PRE_REC_DATE BETWEEN TO_CHAR(SYSDATE - 21) AND TO_CHAR(SYSDATE - 20)
        THEN PRE_OH_VAL
        ELSE 0
      END PRE_OH_WEEK3,
      CASE
        WHEN PRE_REC_DATE BETWEEN TO_CHAR(SYSDATE - 28) AND TO_CHAR(SYSDATE - 27)
        THEN PRE_OH_VAL
        ELSE 0
      END PRE_OH_WEEK4,
      CASE
        WHEN PRE_REC_DATE BETWEEN TO_CHAR(SYSDATE - 35) AND TO_CHAR(SYSDATE - 34)
        THEN PRE_OH_VAL
        ELSE 0
      END PRE_OH_WEEK5,
      CASE
        WHEN PRE_REC_DATE BETWEEN TO_CHAR(SYSDATE - 42) AND TO_CHAR(SYSDATE - 41)
        THEN PRE_OH_VAL
        ELSE 0
      END PRE_OH_WEEK6,
      CASE
        WHEN PRE_REC_DATE BETWEEN TO_CHAR(SYSDATE - 49) AND TO_CHAR(SYSDATE - 48)
        THEN PRE_OH_VAL
        ELSE 0
      END PRE_OH_WEEK7,
      CASE
        WHEN PRE_REC_DATE BETWEEN TO_CHAR(SYSDATE - 56) AND TO_CHAR(SYSDATE - 55)
        THEN PRE_OH_VAL
        ELSE 0
      END PRE_OH_WEEK8,
      CASE
        WHEN PRE_REC_DATE BETWEEN TO_CHAR(SYSDATE - 63) AND TO_CHAR(SYSDATE - 62)
        THEN PRE_OH_VAL
        ELSE 0
      END PRE_OH_WEEK9,
      CASE
        WHEN PRE_REC_DATE BETWEEN TO_CHAR(SYSDATE - 70) AND TO_CHAR(SYSDATE - 69)
        THEN PRE_OH_VAL
        ELSE 0
      END PRE_OH_WEEK10,
      CASE
        WHEN PRE_REC_DATE BETWEEN TO_CHAR(SYSDATE - 77) AND TO_CHAR(SYSDATE - 76)
        THEN PRE_OH_VAL
        ELSE 0
      END PRE_OH_WEEK11,
      CASE
        WHEN PRE_REC_DATE BETWEEN TO_CHAR(SYSDATE - 84) AND TO_CHAR(SYSDATE - 83)
        THEN PRE_OH_VAL
        ELSE 0
      END PRE_OH_WEEK12
    FROM
      (SELECT ID,
        PRE_REC_DATE,
        PRE_OH_VAL
      FROM
        (SELECT ID,
          REC_DATE              AS PRE_REC_DATE,
          TO_CHAR(REC_DATE,'D') AS REC_DATE_WK,
          OH_QTY                AS PRE_OH_VAL
        FROM INV_SAP_INV_REC
        WHERE OH_QTY <> 0
        )
      WHERE REC_DATE_WK = '4'
      )
    )
  GROUP BY ID
  )INV_PRE
ON INV_PRE.ID = INVTO.ID
