-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Project Name : APAFC
-- Version : 1.0
-- Description:
-- Table Init
-- Revision History:
--    Date        Developer         Description
--    ---------   ---------------   ----------------------------------------------------
--    2015-5-7    Moyue           	Stock Out Report.
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------

DROP VIEW VIEW_INV_SAP_STOCK_OUT_REP_FX;
CREATE VIEW VIEW_INV_SAP_STOCK_OUT_REP_FX AS
SELECT OPT_MTL_CATA.REC_DATE,
  OPT_MTL_CATA.PLANT,
  OPT_MTL_CATA.MATERIAL,
  OPT_MTL_CATA.CATALOG_STRING1,
  OPT_MTL_CATA.PROD_BU,
  OPT_MTL_CATA.MRP_CONTROLLER,
  OPT_MTL_CATA.STRATEGY_GRP,
  OPT_MTL_CATA.SAFETY_STOCK,
  OPT_MTL_CATA.MATL_TYPE,
  OPT_MTL_CATA.MRP_TYPE,
  NVL(INV_REC.OH_QTY,0) AS OH_QTY
FROM
  (SELECT INV_OPT.RID        AS RID,
    INV_OPT.ID               AS ID,
    INV_OPT.REC_DATE         AS REC_DATE,
    INV_OPT.PLANT            AS PLANT,
    INV_OPT.MATERIAL         AS MATERIAL,
    INV_OPT.MRP_CONTROLLER   AS MRP_CONTROLLER,
    INV_OPT.PROD_BU          AS PROD_BU,
    INV_OPT.STRATEGY_GRP     AS STRATEGY_GRP,
    INV_OPT.SAFETY_STOCK     AS SAFETY_STOCK,
    INV_OPT.MATL_TYPE        AS MATL_TYPE,
    INV_OPT.MRP_TYPE         AS MRP_TYPE,
    MTL_CATA.CATALOG_STRING1 AS CATALOG_STRING1
  FROM
    (SELECT REC_DATE
      ||'_'
      ||ID AS RID,
      REC_DATE,
      ID,
      PROD_BU,
      MATERIAL,
      PLANT,
      MRP_CONTROLLER,
      STRATEGY_GRP,
      SAFETY_STOCK,
      MATL_TYPE,
      MRP_TYPE
    FROM INV_PPXST_JANFEB_2016 --Need to change when table vol is too big...
    )INV_OPT
  LEFT JOIN
    ( SELECT CATALOG_STRING1, MATERIALID FROM INV_SAP_MATERIAL_CATALOG
    )MTL_CATA
  ON INV_OPT.MATERIAL = MTL_CATA.MATERIALID
  )OPT_MTL_CATA
LEFT JOIN
  (SELECT REC_DATE
    ||'_'
    ||MATERIAL
    ||'_'
    ||PLANTID AS RID,
    OH_QTY
  FROM INV_SAP_INV_REC
  )INV_REC
ON INV_REC.RID = OPT_MTL_CATA.RID;
INV_PPXST_ND_2015
INV_PPXST_JANFEB_2016
--Mon
SELECT *
FROM VIEW_INV_SAP_STOCK_OUT_REP_FX
WHERE REC_DATE BETWEEN TO_CHAR(SYSDATE - 7) AND TO_CHAR(SYSDATE -6)
AND STRATEGY_GRP = '40'
AND MATL_TYPE IN ('ZTG','ZFG')
AND MRP_TYPE IN ('PD')
AND PLANT IN ('5040','5100','5110','5070','5200','5140');
--Tue
SELECT *
FROM VIEW_INV_SAP_STOCK_OUT_REP_FX
WHERE REC_DATE BETWEEN TO_CHAR(SYSDATE - 6) AND TO_CHAR(SYSDATE -5)
AND STRATEGY_GRP = '40'
AND MATL_TYPE IN ('ZTG','ZFG')
AND MRP_TYPE IN ('PD')
AND PLANT IN ('5040','5100','5110','5070','5200','5140');
--Wed
SELECT *
FROM VIEW_INV_SAP_STOCK_OUT_REP_FX
WHERE REC_DATE BETWEEN TO_CHAR(SYSDATE - 5) AND TO_CHAR(SYSDATE -4)
AND STRATEGY_GRP = '40'
AND MATL_TYPE IN ('ZTG','ZFG')
AND MRP_TYPE IN ('PD')
AND PLANT IN ('5040','5100','5110','5070','5200','5140');
--Thu
SELECT *
FROM VIEW_INV_SAP_STOCK_OUT_REP_FX
WHERE REC_DATE BETWEEN TO_CHAR(SYSDATE - 4) AND TO_CHAR(SYSDATE -3)
AND STRATEGY_GRP = '40'
AND MATL_TYPE IN ('ZTG','ZFG')
AND MRP_TYPE IN ('PD')
AND PLANT IN ('5040','5100','5110','5070','5200','5140');
--Fri
SELECT *
FROM VIEW_INV_SAP_STOCK_OUT_REP_FX
WHERE REC_DATE BETWEEN TO_CHAR(SYSDATE - 3) AND TO_CHAR(SYSDATE -2)
AND STRATEGY_GRP = '40'
AND MATL_TYPE IN ('ZTG','ZFG')
AND MRP_TYPE IN ('PD')
AND PLANT IN ('5040','5100','5110','5070','5200','5140');


--Stock Out Report
SELECT DISTINCT ID_MRP.ID,
  ID_MRP.PLANT,
  ID_MRP.MATERIAL,
  ID_MRP.MRP_CONTROLLER
FROM
  (SELECT DISTINCT PLANT
    ||'_'
    ||MATERIAL AS ID,
    PLANT,
    MATERIAL,
    MRP_CONTROLLER
  FROM VIEW_INV_SAP_STOCK_OUT_REP_FX
  WHERE REC_DATE BETWEEN TO_CHAR(SYSDATE - 7) AND TO_CHAR(SYSDATE -3)
  AND STRATEGY_GRP = '40'
  AND MATL_TYPE   IN ('ZTG','ZFG')
  AND MRP_TYPE    IN ('PD')
  AND PLANT       IN ('5040','5100','5110','5070','5200','5140')
  )ID_MRP
LEFT JOIN
  (SELECT ID, COMMENTS, PLANNER, LAST_UPDATE_DATE FROM INV_SAP_STKOUT_COMMENTS where last_update_date between to_char(sysdate-3) and to_char(sysdate + 3)
  )COMT
ON COMT.ID = ID_MRP.ID;

--Upload Reprot data into the Database.
INSERT
INTO INV_SAP_STOCK_OUT_REPSTORE
  (
    UPLOADDATE,
    ID,
    PLANT,
    MATERIAL,
    MRP_CONTROLLER,
    MON,
    TUE,
    WED,
    THU,
    FRI
  )
  VALUES
  (
    SYSDATE,
    'ID_1',
    'PLANT_1',
    'MATERIAL_1',
    'MRP_CONTROLLER_1',
    'MON_1',
    'TUE_1',
    'WED_1',
    'THU_1',
    'FRI_1'
  );



