-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Project Name : APAFC
-- Version : 1.0
-- Description:
-- Table Init
-- Revision History:
--    Date        Developer         Description
--    ---------   ---------------   ----------------------------------------------------
--    2015-8-6  Moyue           	INV PP OPT.
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------


--Archive Table : INV_SAP_PP_OPT_X_STORE -- Store data before Nov-2015
--Current Table : INV_PPXST_ND_2015
---Job Script:
DECLARE
  INSERT_TABLE_INV_OPT VARCHAR2(5000);
BEGIN
  INSERT_TABLE_INV_OPT :=
  'INSERT INTO INV_PPXST_ND_2015      
SELECT SYSDATE AS REC_DATE, ID,      
TMP_ID,      
LAST_REVIEW,      
MATERIAL,      
CATALOG_DASH,      
CATALOG_NO_DASH,      
PLANT,      
SALES_ORG,      
PLANTID_DESC,      
MAT_DESC,      
SAFETY_STOCK,      
OH_QTY,      
UNIT,      
UNIT_COST,      
OH_QTY_INTRANSIT,      
PROD_BU,      
PROD_FAM,      
PROD_HIERARCHY,      
PROC_TYPE,      
STRATEGY_GRP,      
MRP_TYPE,      
PROD_SCHEDULER,      
PLANT_SP_MATL_STA,      
VENDOR_KEY,      
VENDOR_ITEM,      
MIN_INV,      
TARGET_INV,      
MAX_INV,      
LOT_SIZE_QTY,      
LOT_ROUNDING_VALUE,      
LOT_SIZE_DISLS,      
LOT_MIN_BUY,      
AVG52_USAGE_QTY,      
STDEV52_USAGE,      
AVG26_USAGE_QTY,      
STDEV26_USAGE,      
AVG13_USAGE_QTY,      
STDEV13_USAGE,      
Q1_LINES,      
Q2_LINES,      
Q3_LINES,      
Q4_LINES,      
Q1_FREQ_COUNT,      
Q2_FREQ_COUNT,      
Q3_FREQ_COUNT,      
Q4_FREQ_COUNT,      
EXCHANGE_RATE,      
LEVEL_TYPE,      
OUT_QTY_W01,      
OUT_QTY_W02,      
OUT_QTY_W03,      
OUT_QTY_W04,      
OUT_QTY_W05,      
OUT_QTY_W06,      
OUT_QTY_W07,      
OUT_QTY_W08,      
OUT_QTY_W09,      
OUT_QTY_W10,      
OUT_QTY_W11,      
OUT_QTY_W12,      
OUT_QTY_W13,      
OUT_QTY_W14,      
OUT_QTY_W15,      
OUT_QTY_W16,      
OUT_QTY_W17,      
OUT_QTY_W18,      
OUT_QTY_W19,      
OUT_QTY_W20,      
OUT_QTY_W21,      
OUT_QTY_W22,      
OUT_QTY_W23,      
OUT_QTY_W24,      
OUT_QTY_W25,      
OUT_QTY_W26,      
IN_QTY_W01,      
IN_QTY_W02,      
IN_QTY_W03,      
IN_QTY_W04,      
IN_QTY_W05,      
IN_QTY_W06,      
IN_QTY_W07,      
IN_QTY_W08,      
IN_QTY_W09,      
IN_QTY_W10,      
IN_QTY_W11,      
IN_QTY_W12,      
IN_QTY_W13,      
IN_QTY_W14,      
IN_QTY_W15,      
IN_QTY_W16,      
IN_QTY_W17,      
IN_QTY_W18,      
IN_QTY_W19,      
IN_QTY_W20,      
IN_QTY_W21,      
IN_QTY_W22,      
IN_QTY_W23,      
IN_QTY_W24,      
IN_QTY_W25,      
IN_QTY_W26,      
MATERIAL_LEVEL_VALUE,      
MRP_CONTROLLER,      
MRP_CONTROLLER_KEY,      
PURCH_GROUP,      
PURCH_GROUP_KEY,      
PROD_SCHED_KEY,      
RECORDER_POINT,      
LEAD_TIME,      
PDT,      
GRT,      
SALES_ORG_COUNT,      
DIRECT_SHIP_PLANT,      
DELIVERY_PLANT,      
DMI_MANAGED,      
ABC,      
AVG_MONTHLY_DEM,      
STDEV_MONTHLY_DEM,      
DIST_CHL,      
D_CHAIN_BLK,      
DELIVERY_UNIT,      
ISSUE_UOM_NUMERATOR,      
PO_UOM_NUMERATOR,      
MATL_TYPE,      
CURRENT_SERIES,      
ULTIMATE_SOURCE      
FROM INV_SAP_PP_OPT_X WHERE PLANT IN  ('
  ||5040||', '||5050||', '||5100||', '||5110||', '||5120||', '||5160||', '||5190||', '||5200||','||5070||','||5140||','||5180||','||5150||','||5130||','||1090||')';
  EXECUTE IMMEDIATE INSERT_TABLE_INV_OPT;
END;

SELECT * FROM INV_SAP_PP_OPT_X;