-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Project Name : APAFC
-- Version : 1.0
-- Description:
-- Table Init
-- Revision History:
--    Date        Developer         Description
--    ---------   ---------------   ----------------------------------------------------
--    2015-5-7    Moyue           	Stock Out Report.
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------


DROP VIEW VIEW_INV_SAP_STOCK_OUT_REP;
CREATE VIEW VIEW_INV_SAP_STOCK_OUT_REP AS
SELECT 
INV_OPT_REC.REC_DATE,
INV_OPT_REC.PLANT,
INV_OPT_REC.MATERIAL,
MTL_CATA.CATALOG_STRING1,
INV_OPT_REC.SBU,
INV_OPT_REC.MRP_CONTROLLER,
INV_OPT_REC.STRATEGY_GRP,
INV_OPT_REC.SAFETY_STOCK,
INV_OPT_REC.MATL_TYPE,
INV_OPT_REC.MRP_TYPE,
INV_OPT_REC.OH_QTY
FROM
(
SELECT INV_REC.REC_DATE AS REC_DATE,
  INV_REC.PLANTID AS PLANT,
  INV_REC.MATERIAL AS MATERIAL,
  INV_OPT.MRP_CONTROLLER AS MRP_CONTROLLER,
  INV_OPT.SBU AS SBU,
  INV_REC.STRATEGY_GRP AS STRATEGY_GRP,
  INV_REC.SAFETY_STOCK AS SAFETY_STOCK,
  INV_OPT.MATL_TYPE_MTART AS MATL_TYPE,
  INV_OPT.MRP_TYPE AS MRP_TYPE,
  INV_REC.OH_QTY AS OH_QTY
FROM
  (SELECT REC_DATE,
    MATERIAL
    ||'_'
    ||PLANTID AS ID,
    PLANTID,
    MATERIAL,
    STRATEGY_GRP,
    CATALOG_DASH,
    SAFETY_STOCK,
    OH_QTY
  FROM INV_SAP_INV_REC
  )INV_REC
LEFT JOIN
  (SELECT MATERIALID
    ||'_'
    ||(PLANTID - 1) AS ID,
    SUBSTR(PROD_BU,0,3) AS SBU,
    MRP_CONTROLLER,
    MATL_TYPE_MTART,
    MRP_TYPE
    FROM INV_SAP_PP_OPTIMIZATION
  )INV_OPT
ON INV_OPT.ID = INV_REC.ID
)INV_OPT_REC
LEFT JOIN
(
SELECT CATALOG_STRING1, MATERIALID FROM INV_SAP_MATERIAL_CATALOG
)MTL_CATA
ON MTL_CATA.MATERIALID = INV_OPT_REC.MATERIAL;



DROP VIEW VIEW_INV_SAP_STOCK_OUT_REP_FX;
CREATE VIEW VIEW_INV_SAP_STOCK_OUT_REP_FX AS
SELECT 
  OPT_MTL_CATA.REC_DATE,
  OPT_MTL_CATA.PLANT,
  OPT_MTL_CATA.MATERIAL,
  OPT_MTL_CATA.CATALOG_STRING1,
  OPT_MTL_CATA.PROD_BU,
  OPT_MTL_CATA.MRP_CONTROLLER,
  OPT_MTL_CATA.STRATEGY_GRP,
  OPT_MTL_CATA.SAFETY_STOCK,
  OPT_MTL_CATA.MATL_TYPE,
  OPT_MTL_CATA.MRP_TYPE,
  NVL(INV_REC.OH_QTY,0) AS OH_QTY
FROM
  (
  SELECT 
    INV_OPT.RID  AS RID,
    INV_OPT.ID  AS ID,
    INV_OPT.REC_DATE  AS REC_DATE,
    INV_OPT.PLANT         AS PLANT,
    INV_OPT.MATERIAL      AS MATERIAL,
    INV_OPT.MRP_CONTROLLER  AS MRP_CONTROLLER,
    INV_OPT.PROD_BU             AS PROD_BU,
    INV_OPT.STRATEGY_GRP    AS STRATEGY_GRP,
    INV_OPT.SAFETY_STOCK      AS SAFETY_STOCK,
    INV_OPT.MATL_TYPE AS MATL_TYPE,
    INV_OPT.MRP_TYPE        AS MRP_TYPE,
    MTL_CATA.CATALOG_STRING1  AS CATALOG_STRING1
  FROM
    (SELECT 
      REC_DATE||'_'||ID AS RID,
      REC_DATE,
      ID,
      PROD_BU,
      MATERIAL,
      PLANT,
      MRP_CONTROLLER,
      STRATEGY_GRP,
      SAFETY_STOCK,
      MATL_TYPE,
      MRP_TYPE
    FROM INV_PPXST_ND_2015
    )INV_OPT
    LEFT JOIN
  ( SELECT CATALOG_STRING1, MATERIALID FROM INV_SAP_MATERIAL_CATALOG
  )MTL_CATA
  ON INV_OPT.MATERIAL = MTL_CATA.MATERIALID
  )OPT_MTL_CATA
  LEFT JOIN
    (SELECT REC_DATE||'_'||MATERIAL||'_'||PLANTID AS RID,
      OH_QTY
    FROM INV_SAP_INV_REC
    )INV_REC
    ON INV_REC.RID = OPT_MTL_CATA.RID;



CREATE TABLE INV_SAP_PP_OPT_STCKOUT AS
SELECT SYSDATE,
  ID,
  PROD_BU,
  MATERIAL,
  PLANT,
  MRP_CONTROLLER,
  STRATEGY_GRP,
  SAFETY_STOCK,
  MRP_TYPE
FROM INV_SAP_PP_OPT_X
WHERE STRATEGY_GRP = '40'
AND MATL_TYPE     IN ('ZTG','ZFG')
AND MRP_TYPE      IN ('PD')
AND PLANT         IN ('5040','5100','5110','5070','5200','5140');

SELECT COUNT(*) FROM INV_SAP_PP_OPT_X_STORE;
SELECT * FROM VIEW_INV_SAP_STOCK_OUT_REP_FX WHERE MATERIAL = '1794-IT8 A' AND PLANT = '5040'
SELECT * FROM VIEW_INV_SAP_STOCK_OUT_REP_FX WHERE MATERIAL = '1794-IT8 A' AND PLANTID = '5040'

SELECT *
FROM VIEW_INV_SAP_STOCK_OUT_REP_FX
WHERE REC_DATE BETWEEN TO_CHAR(SYSDATE - 7) AND TO_CHAR(SYSDATE -6)
AND STRATEGY_GRP = '40'
AND MATL_TYPE IN ('ZTG','ZFG')
AND MRP_TYPE IN ('PD')
AND PLANT IN ('5040','5100','5110','5070','5200','5140');

SELECT *
FROM VIEW_INV_SAP_STOCK_OUT_REP_FX
WHERE REC_DATE BETWEEN TO_CHAR(SYSDATE - 6) AND TO_CHAR(SYSDATE -5)
AND STRATEGY_GRP = '40'
AND MATL_TYPE IN ('ZTG','ZFG')
AND MRP_TYPE IN ('PD')
AND PLANT IN ('5040','5100','5110','5070','5200','5140')"

SELECT *
FROM VIEW_INV_SAP_STOCK_OUT_REP_FX
WHERE REC_DATE BETWEEN TO_CHAR(SYSDATE - 5) AND TO_CHAR(SYSDATE -4)
AND STRATEGY_GRP = '40'
AND MATL_TYPE IN ('ZTG','ZFG')
AND MRP_TYPE IN ('PD')
AND PLANT IN ('5040','5100','5110','5070','5200','5140');


SELECT *
FROM VIEW_INV_SAP_STOCK_OUT_REP_FX
WHERE REC_DATE BETWEEN TO_CHAR(SYSDATE - 4) AND TO_CHAR(SYSDATE -3)
AND STRATEGY_GRP = '40'
AND MATL_TYPE IN ('ZTG','ZFG')
AND MRP_TYPE IN ('PD')
AND PLANT IN ('5040','5100','5110','5070','5200','5140');

SELECT *
FROM VIEW_INV_SAP_STOCK_OUT_REP_FX
WHERE REC_DATE BETWEEN TO_CHAR(SYSDATE - 3) AND TO_CHAR(SYSDATE -2)
AND STRATEGY_GRP = '40'
AND MATL_TYPE IN ('ZTG','ZFG')
AND MRP_TYPE IN ('PD')
AND PLANT IN ('5040','5100','5110','5070','5200','5140');

SELECT *
FROM VIEW_INV_SAP_STOCK_OUT_REP_FX
WHERE REC_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1))
AND STRATEGY_GRP = '40'
AND MATL_TYPE IN ('ZTG','ZFG')
AND MRP_TYPE IN ('PD')
AND PLANT IN ('5040','5100','5110','5070','5200','5140');

---Rep
--Comments

CREATE TABLE INV_SAP_STKOUT_COMMENTS_TMP AS SELECT * FROM INV_SAP_SVD_COMMENTS_TMP;
CREATE TABLE INV_SAP_STKOUT_COMMENTS AS SELECT * FROM INV_SAP_STKOUT_COMMENTS_TMP;

DROP TABLE INV_SAP_STKOUT_COMMENTS;

TRUNCATE TABLE INV_SAP_STKOUT_COMMENTS;
TRUNCATE TABLE INV_SAP_STKOUT_COMMENTS_TMP;

delete FROM INV_SAP_STKOUT_COMMENTS where id = '5140_855PB-B24ME422 A';
SELECT * FROM INV_SAP_STKOUT_COMMENTS_TMP;


SELECT *
FROM
  (SELECT ID,
    COMMENTS,
    PLANNER,
    TO_CHAR(LAST_UPDATE_DATE, 'iw') AS WK
  FROM INV_SAP_STKOUT_COMMENTS
  )
WHERE WK = TO_CHAR(SYSDATE, 'iw') - 1

select TO_CHAR(trunc(add_months(sysdate,-1),'mm'),'iw') first_day,last_day(add_months(sysdate,-1)) last_day from dual;
TO_CHAR(LAST_UPDATE_DATE,'iw')

SELECT 
 STOCKOUT.UPDATE_WK, STOCKOUT.ID,
  STOCKOUT.PLANT,
  STOCKOUT.MATERIAL,
  STOCKOUT.MRP_CONTROLLER,
  STOCKOUT.MON,
  STOCKOUT.TUE,
  STOCKOUT.WED,
  STOCKOUT.THU,
  STOCKOUT.FRI,
  COMT.PLANNER, COMT.COMMENTS
FROM
  (SELECT TO_CHAR(UPLOADDATE,'iw') AS UPDATE_WK,
    ID,
    PLANT,
    MATERIAL,
    MRP_CONTROLLER,
    MON,
    TUE,
    WED,
    THU,
    FRI
  FROM INV_SAP_STOCK_OUT_REPSTORE WHERE UPLOADDATE BETWEEN trunc(add_months(sysdate,-1),'mm') AND last_day(add_months(sysdate,-1))
  )STOCKOUT
LEFT JOIN
  (SELECT ID, COMMENTS, PLANNER, TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK FROM INV_SAP_STKOUT_COMMENTS
  )COMT
ON COMT.ID = STOCKOUT.ID AND COMT.CM_UPDATE_WK = STOCKOUT.UPDATE_WK

SELECT ID, COMMENTS, PLANNER,CM_UPDATE_WK
FROM(
SELECT ID,
  COMMENTS,
  PLANNER,
  TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
FROM INV_SAP_STKOUT_COMMENTS
WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1))
) WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw')

SELECT
MM_ID_OTT.ID,
  MM_ID_OTT.PLANNER,
  MM_ID_OTT.WK_ONE_COMMENTS,
  MM_ID_OTT.WK_TWO_COMMENTS,
  MM_ID_OTT.WK_THREE_COMMENTS,
  WK_FOUR.COMMENTS AS WK_FOUR_COMMENTS
FROM
(
SELECT
MM_ID_OT.ID,
  MM_ID_OT.PLANNER,
  MM_ID_OT.WK_ONE_COMMENTS,
  MM_ID_OT.WK_TWO_COMMENTS,
  WK_THREE.COMMENTS AS WK_THREE_COMMENTS
FROM
(
SELECT MM_ID_ONE.ID,
  MM_ID_ONE.PLANNER,
  MM_ID_ONE.WK_ONE_COMMENTS,
  WK_TWO.COMMENTS AS WK_TWO_COMMENTS
FROM
  (SELECT MM_ID.ID,
    MM_ID.PLANNER,
    WK_ONE.COMMENTS AS WK_ONE_COMMENTS
  FROM
    (SELECT ID,
      PLANNER
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1))
    )MM_ID
  LEFT JOIN
    (SELECT ID,
      COMMENTS
    FROM
      (SELECT ID,
        COMMENTS,
        TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
      FROM INV_SAP_STKOUT_COMMENTS
      WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1))
      )
    WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw')
    )WK_ONE
  ON WK_ONE.ID = MM_ID.ID
  )MM_ID_ONE
LEFT JOIN
  (SELECT ID,
    COMMENTS
  FROM
    (SELECT ID,
      COMMENTS,
      TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1))
    )
  WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw') + 1
  )WK_TWO
ON MM_ID_ONE.ID = WK_TWO.ID
)MM_ID_OT
LEFT JOIN
  (SELECT ID,
    COMMENTS
  FROM
    (SELECT ID,
      COMMENTS,
      TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1))
    )
  WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw') + 2
  )WK_THREE
ON MM_ID_OT.ID = WK_THREE.ID
)MM_ID_OTT
LEFT JOIN
  (SELECT ID,
    COMMENTS
  FROM
    (SELECT ID,
      COMMENTS,
      TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1))
    )
  WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw') + 2
  )WK_FOUR
ON MM_ID_OTT.ID = WK_FOUR.ID;

--Upload to tmp	
INSERT
INTO INV_SAP_STKOUT_COMMENTS_TMP
  (
    ID,
    LAST_COMMENT_DATE,
    COMMENTS,
    PLANNER,
    LAST_UPDATE_DATE
  )
  VALUES
  (
    'ID_1',
    SYSDATE,
    'COMMENTS_1',
    'PLANNER_1',
    SYSDATE
  )
  
--Merge into standard	
MERGE INTO INV_SAP_STKOUT_COMMENTS SVD_COM USING
(SELECT ID,
  COMMENTS,
  PLANNER,
  LAST_UPDATE_DATE
FROM INV_SAP_STKOUT_COMMENTS_TMP
) TMP ON ( SVD_COM.ID=TMP.ID)
WHEN MATCHED THEN
  UPDATE
  SET SVD_COM.COMMENTS            = TMP.COMMENTS,
    SVD_COM.PLANNER             = TMP.PLANNER,
    SVD_COM.LAST_UPDATE_DATE    = TMP.LAST_UPDATE_DATE WHEN NOT MATCHED THEN
  INSERT VALUES
    (
      TMP.ID,
      TMP.COMMENTS,
      TMP.PLANNER,
      TMP.LAST_UPDATE_DATE
    )


SELECT 
  ID_MRP.ID,
  ID_MRP.PLANT,
  ID_MRP.MATERIAL,
  ID_MRP.MRP_CONTROLLER
  FROM
  (SELECT DISTINCT PLANT
    ||'_'
    ||MATERIAL AS ID,
    PLANT,
    MATERIAL,
    MRP_CONTROLLER
  FROM VIEW_INV_SAP_STOCK_OUT_REP
  WHERE REC_DATE BETWEEN TO_CHAR(SYSDATE - 7) AND TO_CHAR(SYSDATE -3)
  AND STRATEGY_GRP = '40'
  AND MATL_TYPE   IN ('ZTG','ZFG')
  AND MRP_TYPE    IN ('PD')
  AND PLANT       IN ('5040','5100','5110','5070','5200','5140')
  )ID_MRP
LEFT JOIN
  (SELECT ID, COMMENTS, PLANNER, LAST_UPDATE_DATE FROM INV_SAP_STKOUT_COMMENTS
  )COMT
ON COMT.ID = ID_MRP.ID

SELECT * FROM INV_SAP_STKOUT_COMMENTS;

DROP TABLE INV_SAP_STOCK_OUT_REPSTORE;
TRUNCATE TABLE INV_SAP_STOCK_OUT_REPSTORE; 
SELECT count(*) FROM INV_SAP_STOCK_OUT_REPSTORE;

CREATE TABLE INV_SAP_STOCK_OUT_REPSTORE AS
SELECT
  SYSDATE AS UPLOADDATE,
  ID,
  PLANT,
  MATERIAL,
  MRP_CONTROLLER,
  MRP_CONTROLLER AS MON,
  MRP_CONTROLLER AS TUE,
  MRP_CONTROLLER AS WED,
  MRP_CONTROLLER AS THU,
  MRP_CONTROLLER AS FRI
  FROM
  (SELECT DISTINCT PLANT
    ||'_'
    ||MATERIAL AS ID,
    PLANT,
    MATERIAL,
    MRP_CONTROLLER
  FROM VIEW_INV_SAP_STOCK_OUT_REP
  WHERE REC_DATE BETWEEN TO_CHAR(SYSDATE - 7) AND TO_CHAR(SYSDATE -3)
  AND STRATEGY_GRP = '40'
  AND MATL_TYPE   IN ('ZTG','ZFG')
  AND MRP_TYPE    IN ('PD')
  AND PLANT       IN ('5040','5100','5110','5070','5200','5140')
  );


--Upload to tmp	
INSERT
INTO INV_SAP_STOCK_OUT_REPSTORE
  (
  UPLOADDATE,
  ID,
  PLANT,
  MATERIAL,
  MRP_CONTROLLER,
  MON,
  TUE,
  WED,
  THU,
  FRI
  )
  VALUES
  (
    SYSDATE,
    'ID_1',
    'PLANT_1',
    'MATERIAL_1',
    'MRP_CONTROLLER_1',
    'MON_1',
    'TUE_1',
    'WED_1',
    'THU_1',
    'FRI_1'
  )
  
INSERT
INTO INV_SAP_STOCK_OUT_REPSTORE
  (
  UPLOADDATE,
  ID,
  PLANT,
  MATERIAL,
  MRP_CONTROLLER,
  MON,
  TUE,
  WED,
  THU,
  FRI
  )
  VALUES
  (
    SYSDATE,
    '5200_PN-198906',
    '5200',
    'PN-198906',
    '002-NAING-TUN-MOE',
    'OKAY',
    '',
    '',
    'OKAY',
    'OKAY'
  )
  
  
  SELECT * FROM INV_SAP_STOCK_OUT_REPSTORE WHERE UPLOADDATE BETWEEN SYSDATE - 1 AND SYSDATE
  
SELECT STOCKOUT.UPDATE_WK,
  STOCKOUT.ID,
  STOCKOUT.PLANT,
  STOCKOUT.MATERIAL,
  STOCKOUT.MRP_CONTROLLER,
  STOCKOUT.MON,
  STOCKOUT.TUE,
  STOCKOUT.WED,
  STOCKOUT.THU,
  STOCKOUT.FRI,
  COMT.COMMENTS,
  COMT.PLANNER,
  COMT.CM_UPDATE_WK
FROM
  (SELECT TO_CHAR(UPLOADDATE,'iw') AS UPDATE_WK,
    ID,
    PLANT,
    MATERIAL,
    MRP_CONTROLLER,
    MON,
    TUE,
    WED,
    THU,
    FRI
  FROM INV_SAP_STOCK_OUT_REPSTORE
  )STOCKOUT
LEFT JOIN
  (SELECT ID, COMMENTS, PLANNER, TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK FROM INV_SAP_STKOUT_COMMENTS
  )COMT
ON COMT.ID = STOCKOUT.ID AND COMT.CM_UPDATE_WK = STOCKOUT.UPDATE_WK;


SELECT 
  STOCKOUT.UPDATE_WK,
  STOCKOUT.ID,
  STOCKOUT.PLANT,
  STOCKOUT.MATERIAL,
  STOCKOUT.MRP_CONTROLLER,
  STOCKOUT.MON,
  STOCKOUT.TUE,
  STOCKOUT.WED,
  STOCKOUT.THU,
  STOCKOUT.FRI,
  COMT.PLANNER, COMT.COMMENTS
FROM
  (SELECT TO_CHAR(UPLOADDATE,'iw') AS UPDATE_WK,
    ID,
    PLANT,
    MATERIAL,
    MRP_CONTROLLER,
    MON,
    TUE,
    WED,
    THU,
    FRI
  FROM INV_SAP_STOCK_OUT_REPSTORE
  )STOCKOUT
LEFT JOIN
  (SELECT ID, COMMENTS, PLANNER, TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK FROM INV_SAP_STKOUT_COMMENTS
  )COMT
ON COMT.ID = STOCKOUT.ID AND COMT.CM_UPDATE_WK = STOCKOUT.UPDATE_WK

CREATE TABLE INV_SAP_STKOUT_COMMENTS_0928_1 AS
SELECT * FROM INV_SAP_STKOUT_COMMENTS;

DROP TABLE INV_SAP_STKOUT_COMMENTS;
CREATE TABLE INV_SAP_STKOUT_COMMENTS AS
SELECT * FROM INV_SAP_STKOUT_COMMENTS_0928;


UPDATE INV_SAP_STKOUT_COMMENTS SET COMMENTS = 'Low Forecast' WHERE COMMENTS = 'Other Causals' AND LAST_UPDATE_DATE < TO_CHAR(SYSDATE - 4);

SELECT COUNT(*) FROM INV_SAP_STKOUT_COMMENTS WHERE LAST_UPDATE_DATE > TO_CHAR(SYSDATE - 2);
DELETE FROM INV_SAP_STKOUT_COMMENTS WHERE LAST_UPDATE_DATE > TO_CHAR(SYSDATE - 2);

SELECT ID, COMMENTS, PLANNER, LAST_UPDATE_DATE FROM INV_SAP_STKOUT_COMMENTS WHERE LAST_UPDATE_DATE > TO_CHAR(SYSDATE - 3);

INSERT INTO INV_SAP_STKOUT_COMMENTS(ID, COMMENTS, PLANNER, LAST_UPDATE_DATE) SELECT ID, COMMENTS, PLANNER, LAST_UPDATE_DATE - 3 FROM INV_SAP_STKOUT_COMMENTS_0928_1 WHERE LAST_UPDATE_DATE > TO_CHAR(SYSDATE - 2) 






DELETE FROM INV_SAP_STOCK_OUT_REPSTORE WHERE UPLOADDATE BETWEEN SYSDATE - 2 AND SYSDATE;



SELECT distinct REC_DATE FROM INV_PPXST_ND_2015;


SELECT
MM_ID_OTT.ID,
  MM_ID_OTT.PLANNER,
  MM_ID_OTT.WK_ONE_COMMENTS,
  MM_ID_OTT.WK_TWO_COMMENTS,
  MM_ID_OTT.WK_THREE_COMMENTS,
  WK_FOUR.COMMENTS AS WK_FOUR_COMMENTS
FROM
(
SELECT
MM_ID_OT.ID,
  MM_ID_OT.PLANNER,
  MM_ID_OT.WK_ONE_COMMENTS,
  MM_ID_OT.WK_TWO_COMMENTS,
  WK_THREE.COMMENTS AS WK_THREE_COMMENTS
FROM
(
SELECT MM_ID_ONE.ID,
  MM_ID_ONE.PLANNER,
  MM_ID_ONE.WK_ONE_COMMENTS,
  WK_TWO.COMMENTS AS WK_TWO_COMMENTS
FROM
  (SELECT MM_ID.ID,
    MM_ID.PLANNER,
    WK_ONE.COMMENTS AS WK_ONE_COMMENTS
  FROM
    (SELECT ID,
      PLANNER
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1))
    )MM_ID
  LEFT JOIN
    (SELECT ID,
      COMMENTS
    FROM
      (SELECT ID,
        COMMENTS,
        TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
      FROM INV_SAP_STKOUT_COMMENTS
      WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1))
      )
    WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw')
    )WK_ONE
  ON WK_ONE.ID = MM_ID.ID
  )MM_ID_ONE
LEFT JOIN
  (SELECT ID,
    COMMENTS
  FROM
    (SELECT ID,
      COMMENTS,
      TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1))
    )
  WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw') + 1
  )WK_TWO
ON MM_ID_ONE.ID = WK_TWO.ID
)MM_ID_OT
LEFT JOIN
  (SELECT ID,
    COMMENTS
  FROM
    (SELECT ID,
      COMMENTS,
      TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1))
    )
  WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw') + 2
  )WK_THREE
ON MM_ID_OT.ID = WK_THREE.ID
)MM_ID_OTT
LEFT JOIN
  (SELECT ID,
    COMMENTS
  FROM
    (SELECT ID,
      COMMENTS,
      TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1))
    )
  WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw') + 3
  )WK_FOUR
ON MM_ID_OTT.ID = WK_FOUR.ID






SELECT ID,
CM_UPDATE_WK,
    COMMENTS
  FROM
    (SELECT ID,
      COMMENTS,
      TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1))
    )
  WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw') + 1

CREATE VIEW AS
SELECT
MM_ID_OTT.ID,
  MM_ID_OTT.PLANNER,
  MM_ID_OTT.WK_ONE_COMMENTS,
  MM_ID_OTT.WK_TWO_COMMENTS,
  MM_ID_OTT.WK_THREE_COMMENTS,
  WK_FOUR.COMMENTS AS WK_FOUR_COMMENTS
FROM
(
SELECT
MM_ID_OT.ID,
  MM_ID_OT.PLANNER,
  MM_ID_OT.WK_ONE_COMMENTS,
  MM_ID_OT.WK_TWO_COMMENTS,
  WK_THREE.COMMENTS AS WK_THREE_COMMENTS
FROM
(
SELECT MM_ID_ONE.ID,
  MM_ID_ONE.PLANNER,
  MM_ID_ONE.WK_ONE_COMMENTS,
  WK_TWO.COMMENTS AS WK_TWO_COMMENTS
FROM
  (SELECT MM_ID.ID,
    MM_ID.PLANNER,
    WK_ONE.COMMENTS AS WK_ONE_COMMENTS
  FROM
    (SELECT ID,
      PLANNER
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1))
    )MM_ID
  LEFT JOIN
    (SELECT ID,
      COMMENTS
    FROM
      (SELECT ID,
        COMMENTS,
        TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
      FROM INV_SAP_STKOUT_COMMENTS
      WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1))
      )
    WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw') + 1
    )WK_ONE
  ON WK_ONE.ID = MM_ID.ID
  )MM_ID_ONE
LEFT JOIN
  (SELECT ID,
    COMMENTS
  FROM
    (SELECT ID,
      COMMENTS,
      TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1))
    )
  WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw') + 2
  )WK_TWO
ON MM_ID_ONE.ID = WK_TWO.ID
)MM_ID_OT
LEFT JOIN
  (SELECT ID,
    COMMENTS,CM_UPDATE_WK
  FROM
    (SELECT ID,
      COMMENTS,
      TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1))
    )
  WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw')
  )WK_THREE
ON MM_ID_OT.ID = WK_THREE.ID
)MM_ID_OTT
LEFT JOIN
  (SELECT ID,
    COMMENTS
  FROM
    (SELECT ID,
      COMMENTS,
      TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1))
    )
  WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw') + 4
  )WK_FOUR
ON MM_ID_OTT.ID = WK_FOUR.ID



SELECT ID,
      COMMENTS,
      TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1)) and id = '5040_PN-200838'


SELECT * FROM INV_SAP_STKOUT_COMMENTS WHERE ID = '5040_PN-200838'
SELECT *
FROM VIEW_INV_SAP_STOCK_OUT_REP_FX
WHERE REC_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND LAST_DAY(ADD_MONTHS(sysdate,-1))
AND STRATEGY_GRP = '40'
AND MATL_TYPE IN ('ZTG','ZFG')
AND MRP_TYPE IN ('PD')
AND PLANT IN ('5040','5100','5110','5070','5200','5140')




























SELECT
MM_ID_OTT.ID,
  MM_ID_OTT.PLANNER,
  MM_ID_OTT.WK_ONE_COMMENTS,
  MM_ID_OTT.WK_TWO_COMMENTS,
  MM_ID_OTT.WK_THREE_COMMENTS,
  WK_FOUR.COMMENTS AS WK_FOUR_COMMENTS
FROM
(
SELECT
MM_ID_OT.ID,
  MM_ID_OT.PLANNER,
  MM_ID_OT.WK_ONE_COMMENTS,
  MM_ID_OT.WK_TWO_COMMENTS,
  WK_THREE.COMMENTS AS WK_THREE_COMMENTS
FROM
(
SELECT MM_ID_ONE.ID,
  MM_ID_ONE.PLANNER,
  MM_ID_ONE.WK_ONE_COMMENTS,
  WK_TWO.COMMENTS AS WK_TWO_COMMENTS
FROM
  (SELECT MM_ID.ID,
    MM_ID.PLANNER,
    WK_ONE.COMMENTS AS WK_ONE_COMMENTS
  FROM
    (SELECT ID,
      PLANNER
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND TO_CHAR(SYSDATE)
    )MM_ID
  LEFT JOIN
    (SELECT ID,
      COMMENTS,CM_UPDATE_WK
    FROM
      (SELECT ID,
        COMMENTS,
        TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
      FROM INV_SAP_STKOUT_COMMENTS
      WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND TO_CHAR(SYSDATE)
      )
    WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw') + 2
    )WK_ONE
  ON WK_ONE.ID = MM_ID.ID
  )MM_ID_ONE
LEFT JOIN
  (SELECT ID,
    COMMENTS
  FROM
    (SELECT ID,
      COMMENTS,
      TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND TO_CHAR(SYSDATE)
    )
  WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw') + 3
  )WK_TWO
ON MM_ID_ONE.ID = WK_TWO.ID
)MM_ID_OT
LEFT JOIN
  (SELECT ID,
    COMMENTS
  FROM
    (SELECT ID,
      COMMENTS,
      TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND TO_CHAR(SYSDATE)
    )
  WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw') + 4
  )WK_THREE
ON MM_ID_OT.ID = WK_THREE.ID
)MM_ID_OTT
LEFT JOIN
  (SELECT ID,
    COMMENTS
  FROM
    (SELECT ID,
      COMMENTS,
      TO_CHAR(LAST_UPDATE_DATE,'iw') AS CM_UPDATE_WK
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND TO_CHAR(SYSDATE)
    )
  WHERE CM_UPDATE_WK = TO_CHAR(TRUNC(ADD_MONTHS(sysdate,-1),'mm'),'iw') + 5
  )WK_FOUR
ON MM_ID_OTT.ID = WK_FOUR.ID



SELECT *
    FROM INV_SAP_STKOUT_COMMENTS
    WHERE LAST_UPDATE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-1),'mm') AND TO_CHAR(SYSDATE)
    
    
    
    
    
    
    
    
MERGE INTO INV_SAP_STKOUT_COMMENTS SVD_COM USING
(SELECT 
  IDD,
  ID,
  COMMENTS,
  PLANNER,
  LAST_UPDATE_DATE
FROM INV_SAP_STKOUT_COMMENTS_TMP
) TMP ON (SVD_COM.IDD=TMP.IDD)
WHEN MATCHED THEN
  UPDATE
  SET 
    SVD_COM.COMMENTS            = TMP.COMMENTS,
    SVD_COM.PLANNER             = TMP.PLANNER,
    SVD_COM.LAST_UPDATE_DATE    = TMP.LAST_UPDATE_DATE WHEN NOT MATCHED THEN
  INSERT VALUES
    (
      TMP.IDD,
      TMP.ID,
      TMP.COMMENTS,
      TMP.PLANNER,
      TMP.LAST_UPDATE_DATE
    )


SELECT * FROM INV_SAP_STKOUT_COMMENTS WHERE ID = '5040_PN-285042';
SELECT * FROM INV_SAP_STKOUT_COMMENTS_TMP WHERE ID = '5070_80026-230-01-R';
DROP TABLE INV_SAP_STKOUT_COMMENTS;
CREATE TABLE INV_SAP_STKOUT_COMMENTS  AS
SELECT
ID||'_'||LAST_UPDATE_DATE AS IDD,
ID,
COMMENTS,
  PLANNER,
  LAST_UPDATE_DATE
FROM INV_SAP_STKOUT_COMMENTS_BK;

DROP TABLE INV_SAP_STKOUT_COMMENTS_TMP;
create table INV_SAP_STKOUT_COMMENTS_TMP as select * from INV_SAP_STKOUT_COMMENTS;

TRUNCATE TABLE INV_SAP_STKOUT_COMMENTS_TMP;


INSERT
INTO INV_SAP_STKOUT_COMMENTS_T
  (
    IDD,
    ID,
    COMMENTS,
    PLANNER,
    LAST_UPDATE_DATE
  )
  VALUES
  (
    '5070_80026-230-01-R_08-NOV-15',
    '5070_80026-230-01-R',
    'COMMENTS_1',
    'PLANNER_1',
    '04-AUG-15'
  )
  SELECT * FROM INV_SAP_STKOUT_COMMENTS_T WHERE LAST_UPDATE_DATE > TO_CHAR(SYSDATE - 100)
  
  
"INSERT
INTO INV_SAP_STKOUT_COMMENTS_T
  (
    IDD,
    ID,
    COMMENTS,
    PLANNER,
    LAST_UPDATE_DATE
  )
  VALUES
  ('5040_0041-5076_04-AUG-15','5040_0041-5076','Large Sales Order','Gloria wenwen Huang','04-AUG-15' )"


select * from INV_SAP_STKOUT_COMMENTS_BK;
select * from INV_SAP_STKOUT_COMMENTS WHERE LAST_UPDATE_DATE > TO_CHAR(SYSDATE - 2)

TRUNCATE TABLE INV_SAP_STKOUT_COMMENTS_T;
CREATE TABLE INV_SAP_STKOUT_COMMENTS_T AS SELECT * FROM INV_SAP_STKOUT_COMMENTS
SELECT * FROM INV_SAP_STOCK_OUT_REPSTORE WHERE MON = 'StockOut' or MON = 'StockOut' or MON = 'StockOut' or MON = 'StockOut' or MON = 'StockOut' and UPLOADDATE > TO_CHAR(SYSDATE - 50)















