-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Project Name : APAFC
-- Version : 1.0
-- Description:
-- Table Init
-- Revision History:
--    Date        Developer         Description
--    ---------   ---------------   ----------------------------------------------------
--    2014-5-22   Moyue           	JQS&CDC
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
DROP VIEW VIEW_INV_SAP_JQSCDC_PL;

SELECT * FROM VIEW_INV_SAP_JQSCDC_PL;

CREATE VIEW VIEW_INV_SAP_JQSCDC_PL AS
SELECT 
JQS_PLST.MATERIAL AS MATERIAL,
PLAN_ORD.PLANTID AS PLANT,
PLAN_ORD.DATEDELIVERY AS DATEDELIVERY,
PLAN_ORD.PONUMBER AS PONUMBER,
PLAN_ORD.OPEN_PLAN_QTY AS OPEN_PLAN_QTY
FROM
  (SELECT MATERIAL FROM INV_SAP_JQS_PARTLIST
  )JQS_PLST
LEFT JOIN
(
SELECT    
  MATERIALID,
  PLANTID,
  DATEDELIVERY,
  PONUMBER,
  PO_OPENQTY AS OPEN_PLAN_QTY
  FROM INV_SAP_IO_INPUTS_DAILY
  WHERE DATEDELIVERY < TO_CHAR(sysdate + 182)
)PLAN_ORD
ON PLAN_ORD.MATERIALID = JQS_PLST.MATERIAL;

SELECT * FROM INV_SAP_IO_INPUTS_DAILY;

----JQS CDC STO VIEW 
SELECT * FROM VIEW_INV_SAP_JQS_CDC_STO;
DROP VIEW VIEW_INV_SAP_JQS_CDC_STO;
CREATE VIEW VIEW_INV_SAP_JQS_CDC_STO AS
SELECT
PLANTID,
MATERIAL,
SHIPPING_PLANT,
EBELNPURCHDOCNO,
COMMITTED_DATE_MAX,
PO_QTY
FROM
(
SELECT 
JQS_PLST.MATERIAL AS MATERIAL,
OPEN_PO.PLANTID AS PLANTID,
OPEN_PO.SHIPPING_PLANT AS SHIPPING_PLANT,
OPEN_PO.EBELNPURCHDOCNO AS EBELNPURCHDOCNO,
OPEN_PO.COMMITTED_DATE_MAX AS COMMITTED_DATE_MAX,
OPEN_PO.PO_QTY AS PO_QTY
FROM
(SELECT MATERIAL FROM INV_SAP_JQS_PARTLIST)JQS_PLST
LEFT JOIN
(SELECT 
MATERIALID,
PLANTID,
PO_QTY,
EBELNPURCHDOCNO,
MAX(COMMITTED_DATE) AS COMMITTED_DATE_MAX,
SHIPPING_PLANT
FROM
(
SELECT
PLANTID,
GREATEST ( MENGESCHEDULEDQTY_BASE_UOM - ( NVL ( MENGESCHEDULEDQTY_BASE_UOM / MENGESCHEDULEDQTY, 0) * NVL ( GREATEST (WEMNGRECEIVEDQTY, WAMNGISSUEDQTY), 0)), 0) AS PO_QTY,
 MATERIALID,
 COMMITTED_DATE,
 EBELNPURCHDOCNO,
  TO_NUMBER (
  CASE
    WHEN LIFNR_VENDORNO LIKE 'V%'
    AND LENGTH (LIFNR_VENDORNO) = 5
    THEN SUBSTR (LIFNR_VENDORNO, 2, 4)
    WHEN LENGTH (LIFNR_VENDORNO) > 5
    THEN '0'
    ELSE TO_CHAR (LIFNR_VENDORNO)
  END) SHIPPING_PLANT
  FROM INV_SAP_PP_PO_HISTORY_ALL WHERE
   PO_SO_SA_FLAG                                                IN ('STO')
AND ( DELIVERYCOMPLETE NOT LIKE 'X%'
OR DELIVERYCOMPLETE   IS NULL)
AND MENGESCHEDULEDQTY <> 0
AND LAST_SHIP_DATE    IS NULL
)
GROUP BY
MATERIALID,
PLANTID,
EBELNPURCHDOCNO,
PO_QTY,
SHIPPING_PLANT
)OPEN_PO
ON OPEN_PO.MATERIALID = JQS_PLST.MATERIAL
) WHERE SHIPPING_PLANT = '1090';







SELECT *
FROM
  (SELECT MATERIAL FROM INV_SAP_JQS_PARTLIST
  )JQS_PLST
LEFT JOIN
  (SELECT *
  FROM INV_SAP_PP_PO_HISTORY_ALL
  WHERE LIFNR_VENDORNO   = 'V1090' AND BEDATSCHEDULELINEORDERDATE BETWEEN TO_CHAR(SYSDATE - 400) AND TO_CHAR(SYSDATE)
  )OPEN_PO
ON OPEN_PO.MATERIALID = JQS_PLST.MATERIAL;



SELECT *
FROM
  (SELECT MATERIAL FROM INV_SAP_JQS_PARTLIST
  )JQS_PLST
LEFT JOIN
  (SELECT * FROM INV_SAP_SALES_HST_LC WHERE LAST_GI_DATE BETWEEN TO_CHAR(SYSDATE - 400) AND TO_CHAR(SYSDATE)
  )OPEN_PO
ON OPEN_PO.MATERIAL = JQS_PLST.MATERIAL;



SELECT *
FROM
  (SELECT MATERIAL FROM INV_SAP_JQS_PARTLIST
  )JQS_PLST
LEFT JOIN
  (SELECT * FROM INV_SAP_PP_OPT_X WHERE PLANT = '5010'
  )OPEN_PO
ON OPEN_PO.MATERIAL = JQS_PLST.MATERIAL;
