-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Project Name : APAFC
-- Version : 1.0
-- Description:
-- Table Init
-- Revision History:
--    Date        Developer         Description
--    ---------   ---------------   ----------------------------------------------------
--    2014-3-17   Moyue           	Delivery Issues.
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------

--Vendor Chain

CREATE TABLE INV_SAP_VENDOR_PLANT_INFO AS
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_VENDOR_PLANT_INFO@ROCKWELL_DW_DBLINK;

--Tables
-- INV_SAP_VENDOR_PLANT_INFO
-- INV_SAP_SALES_VBAK_VBAP_VBUP
-- INV_SAP_INVENTORY_BY_PLANT
-- INV_SAP_PP_PO_HISTORY
-- INV_SAP_PP_OPTIMIZATION

CREATE OR REPLACE PROCEDURE APAFC_REFH_DAILY_DELISUE
IS
STEP_NAME VARCHAR2(100);
PROCESS_TERMINATED EXCEPTION;

CHK_LS_1 NUMBER;
CHK_LS_2 NUMBER;
CHK_LS_3 NUMBER;
CHK_LS_4 NUMBER;

BEGIN
	STEP_NAME := 'Delivery Issues local version';

	SELECT COUNT(*) INTO CHK_LS_1 FROM USER_TABLES WHERE TABLE_NAME = 'INV_DIG_VD_BLK_1';
  SELECT COUNT(*) INTO CHK_LS_2 FROM USER_TABLES WHERE TABLE_NAME = 'INV_DIG_VD_BLK_2';
  SELECT COUNT(*) INTO CHK_LS_3 FROM USER_TABLES WHERE TABLE_NAME = 'INV_DIG_VD_BLK_3';
  SELECT COUNT(*) INTO CHK_LS_4 FROM USER_TABLES WHERE TABLE_NAME = 'INV_DIG_VD_BLK_4';
  
  IF CHK_LS_1 > 0 THEN
    APAFC_TRUNCATE('INV_DIG_VD_BLK_1'); -- SOHST
     COMMIT;
    APAFC_INSERT('VIEW_INV_DIG_VD_BLK_1','INV_DIG_VD_BLK_1');
    COMMIT;
  ELSE
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE INV_DIG_VD_BLK_1 AS SELECT * FROM VIEW_INV_DIG_VD_BLK_1');
    COMMIT;
  END IF;
	
  IF CHK_LS_2 > 0 THEN
    APAFC_TRUNCATE('INV_DIG_VD_BLK_2'); -- SOHST
     COMMIT;
    APAFC_INSERT('VIEW_INV_DIG_VD_BLK_2','INV_DIG_VD_BLK_2');
    COMMIT;
  ELSE
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE INV_DIG_VD_BLK_2 AS SELECT * FROM VIEW_INV_DIG_VD_BLK_2');
    COMMIT;
  END IF;
  
  IF CHK_LS_3 > 0 THEN
    APAFC_TRUNCATE('INV_DIG_VD_BLK_3'); -- SOHST
     COMMIT;
    APAFC_INSERT('VIEW_INV_DIG_VD_BLK_3','INV_DIG_VD_BLK_3');
    COMMIT;
  ELSE
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE INV_DIG_VD_BLK_3 AS SELECT * FROM VIEW_INV_DIG_VD_BLK_3');
    COMMIT;
  END IF;
  
  
  IF CHK_LS_4 > 0 THEN
    APAFC_TRUNCATE('INV_DIG_VD_BLK_4'); -- SOHST
     COMMIT;
    APAFC_INSERT('VIEW_INV_DIG_VD_BLK_4','INV_DIG_VD_BLK_4');
    COMMIT;
  ELSE
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE INV_DIG_VD_BLK_4 AS SELECT * FROM VIEW_INV_DIG_VD_BLK_4');
    COMMIT;
  END IF;
  
EXCEPTION
WHEN OTHERS THEN
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Execute Error:');
  DBMS_OUTPUT.PUT_LINE(SUBSTR(DBMS_UTILITY.FORMAT_ERROR_STACK,1,200)||SUBSTR(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,1,200));
  RAISE PROCESS_TERMINATED;
END APAFC_REFH_DAILY_DELISUE;

BEGIN
APAFC_REFH_DAILY_DELISUE;
END;


CREATE TABLE INV_DIG_VD_BLK_1 AS
SELECT * FROM VIEW_INV_DIG_VD_BLK_1;
CREATE TABLE INV_DIG_VD_BLK_2 AS
SELECT * FROM VIEW_INV_DIG_VD_BLK_2;
CREATE TABLE INV_DIG_VD_BLK_3 AS
SELECT * FROM VIEW_INV_DIG_VD_BLK_3;
CREATE TABLE INV_DIG_VD_BLK_4 AS
SELECT * FROM VIEW_INV_DIG_VD_BLK_4;


CREATE TABLE INV_SAP_DELIVERY_ISSUES AS
SELECT
DISTINCT
VD_BLK_1.MATERIALID AS MATERIAL,
VD_BLK_1.PLANTID AS PLANT,
VD_BLK_1.EXPECTED_SHIP_PLANT_1 AS EXPECTED_SHIP_PLANT_1,
VD_BLK_1.MRP_TYPE AS ESP_MRP_TYPE_1,
VD_BLK_1.STRATEGY_GRP AS ESP_STRATEGY_GRP_1,
VD_BLK_1.D_CHAIN_BLK AS ESP_D_CHAIN_BLK_1,
VD_BLK_1.SP_MATL_STAT_MMSTA AS ESP_SP_MATL_STAT_MMSTA_1,

VD_BLK_2.EXPECTED_SHIP_PLANT_2 AS EXPECTED_SHIP_PLANT_2,
VD_BLK_2.MRP_TYPE AS ESP_MRP_TYPE_2,
VD_BLK_2.STRATEGY_GRP AS ESP_STRATEGY_GRP_2,
VD_BLK_2.D_CHAIN_BLK AS ESP_D_CHAIN_BLK_2,
VD_BLK_2.SP_MATL_STAT_MMSTA AS ESP_SP_MATL_STAT_MMSTA_2,

VD_BLK_3.EXPECTED_SHIP_PLANT_3 AS EXPECTED_SHIP_PLANT_3,
VD_BLK_3.MRP_TYPE AS ESP_MRP_TYPE_3,
VD_BLK_3.STRATEGY_GRP AS ESP_STRATEGY_GRP_3,
VD_BLK_3.D_CHAIN_BLK AS ESP_D_CHAIN_BLK_3,
VD_BLK_3.SP_MATL_STAT_MMSTA AS ESP_SP_MATL_STAT_MMSTA_3,

VD_BLK_4.EXPECTED_SHIP_PLANT_4 AS EXPECTED_SHIP_PLANT_4,
VD_BLK_4.MRP_TYPE AS ESP_MRP_TYPE_4,
VD_BLK_4.STRATEGY_GRP AS ESP_STRATEGY_GRP_4,
VD_BLK_4.D_CHAIN_BLK AS ESP_D_CHAIN_BLK_4,
VD_BLK_4.SP_MATL_STAT_MMSTA AS ESP_SP_MATL_STAT_MMSTA_4,

SYSDATE AS TIME_STAMP

FROM INV_DIG_VD_BLK_1 VD_BLK_1,
    INV_DIG_VD_BLK_2 VD_BLK_2,
    INV_DIG_VD_BLK_3 VD_BLK_3,
    INV_DIG_VD_BLK_4 VD_BLK_4
WHERE VD_BLK_1.REC_ID = VD_BLK_2.REC_ID AND
VD_BLK_2.REC_ID = VD_BLK_3.REC_ID AND
VD_BLK_3.REC_ID = VD_BLK_4.REC_ID AND
((VD_BLK_1.D_CHAIN_BLK IS NOT NULL AND VD_BLK_1.D_CHAIN_BLK NOT IN ('ZG','ZN'))OR
(VD_BLK_2.D_CHAIN_BLK IS NOT NULL AND VD_BLK_2.D_CHAIN_BLK NOT IN ('ZG','ZN'))OR
(VD_BLK_3.D_CHAIN_BLK IS NOT NULL AND VD_BLK_3.D_CHAIN_BLK NOT IN ('ZG','ZN'))OR
(VD_BLK_4.D_CHAIN_BLK IS NOT NULL AND VD_BLK_4.D_CHAIN_BLK NOT IN ('ZG','ZN')))AND
(VD_BLK_1.SP_MATL_STAT_MMSTA NOT IN('ZG','ZA','ZN') OR
VD_BLK_2.SP_MATL_STAT_MMSTA NOT IN('ZG','ZA','ZN') OR
VD_BLK_3.SP_MATL_STAT_MMSTA NOT IN('ZG','ZA','ZN') OR
VD_BLK_4.SP_MATL_STAT_MMSTA NOT IN('ZG','ZA','ZN'));


--1. EXTRACT THE ALL MATERIALS FROM OPEN SO FILTER ND PART.
--
SELECT 
ID,
MATERIAL,
OPEN_QTY,
MRP_TYPE,
STRATEGY_GRP,
LEADTIME_WEEKS
FROM
(
SELECT 
OPEN_SO_MATL.ID AS ID,
OPEN_SO_MATL.MATERIAL AS MATERIAL,
OPEN_SO_MATL.OPEN_QTY AS OPEN_QTY,
PP_ITEM.MRP_TYPE AS MRP_TYPE,
PP_ITEM.STRATEGY_GRP AS STRATEGY_GRP,
PP_ITEM.LEADTIME_WEEKS AS LEADTIME_WEEKS
FROM
(SELECT MATERIAL||'_'||PLANT AS ID, MATERIAL, OPEN_QTY,MAX_REQUEST_DATE FROM INV_SAP_SALES_VBAK_VBAP_VBUP)OPEN_SO_MATL
LEFT JOIN
(SELECT MATERIALID||'_'||PLANTID AS ID, MATERIALID,PLANTID,MRP_TYPE,STRATEGY_GRP,LEADTIME_WEEKS FROM INV_SAP_PP_OPTIMIZATION )PP_ITEM
ON PP_ITEM.ID = OPEN_SO_MATL.ID
)
WHERE MRP_TYPE = 'ND';

SELECT * FROM INV_SAP_SALES_VBAK_VBAP_VBUP

SELECT * FROM
()OPEN_SO_MATL
LEFT JOIN
(SELECT MATERIALID||'_'||EXPECTED_SHIP_PLANT_1 AS ID,
SPC_PROC_KEY_SOBSL_VE_1,
VENDOR_NAME_VE_1,
EXPECTED_SHIP_PLANT_1
 FROM INV_SAP_VENDOR_PLANT_INFO)VENDOR_INFO_1
ON VENDOR_INFO.ID = OPEN_SO_MATL.ID


---INV DATA - OPEN SO DATA
SELECT 
OH_INV.ID AS ID,
OH_INV.OH_QTY AS OH_QTY,
OPEN_SO_QTY.OPEN_QTY AS OPEN_SO_QTY
FROM
(SELECT MATERIALID||'_'||PLANTID AS ID, OH_QTY FROM INV_SAP_INVENTORY_BY_PLANT)OH_INV
LEFT JOIN
(SELECT MATERIAL||'_'||PLANT AS ID, MATERIAL,OPEN_QTY,MAX_REQUEST_DATE FROM INV_SAP_SALES_VBAK_VBAP_VBUP)OPEN_SO_QTY
ON 
OH_INV.ID = OPEN_SO_QTY.ID


--1. ND ITEM
SELECT * FROM 
(
SELECT 
OPEN_STO_MTL.ID AS ID,
OPEN_STO_MTL.MATERIALID AS MATERIAL,
OPEN_STO_MTL.PLANTID AS PLANTID,
PP_ITEM.MRP_TYPE AS MRP_TYPE,
PP_ITEM.STRATEGY_GRP AS STRATEGY_GRP,
PP_ITEM.LEADTIME_WEEKS AS LEADTIME_WEEKS
FROM
(SELECT DISTINCT MATERIALID||'_'||PLANTID AS ID,MATERIALID,PLANTID FROM INV_SAP_PP_PO_HISTORY WHERE PO_SO_SA_FLAG = 'STO' AND DELIVERYCOMPLETE = 'X0')OPEN_STO_MTL
LEFT JOIN
(SELECT MATERIALID||'_'||PLANTID AS ID, MATERIALID,PLANTID,MRP_TYPE,STRATEGY_GRP,LEADTIME_WEEKS FROM INV_SAP_PP_OPTIMIZATION )PP_ITEM
ON PP_ITEM.ID = OPEN_STO_MTL.ID
) WHERE MRP_TYPE = 'ND';

DROP VIEW VIEW_INV_DIG_VENDOR_1;
DROP VIEW VIEW_INV_DIG_VENDOR_2;
DROP VIEW VIEW_INV_DIG_VENDOR_3;
DROP VIEW VIEW_INV_DIG_VENDOR_4;

CREATE VIEW VIEW_INV_DIG_VENDOR_1 AS
SELECT 
MTL_VEND_INFO_1.REC_ID AS REC_ID,
MTL_VEND_INFO_1.MATERIALID AS MATERIALID,
MTL_VEND_INFO_1.PLANTID AS PLANTID,
MTL_VEND_INFO_1.EXPECTED_SHIP_PLANT_1 AS EXPECTED_SHIP_PLANT_1,
MTL_VEND_INFO_1.DELI_ID AS DELI_ID,
PP_ITEM.MRP_TYPE AS MRP_TYPE,
PP_ITEM.STRATEGY_GRP AS STRATEGY_GRP
FROM 
(
SELECT 
OPEN_STO_MTL.REC_ID AS REC_ID,
OPEN_STO_MTL.MATERIALID AS MATERIALID,
OPEN_STO_MTL.PLANTID AS PLANTID,
INV_VENDOR_INFO_1.EXPECTED_SHIP_PLANT_1 AS EXPECTED_SHIP_PLANT_1,
INV_VENDOR_INFO_1.DELI_ID AS DELI_ID
FROM 
(SELECT DISTINCT MATERIALID
  ||'_'
  ||PLANTID AS REC_ID,
  MATERIALID,
  PLANTID
FROM INV_SAP_PP_PO_HISTORY
WHERE PO_SO_SA_FLAG  = 'STO'
AND ( DELIVERYCOMPLETE NOT LIKE 'X%'
OR DELIVERYCOMPLETE   IS NULL)
)OPEN_STO_MTL 
LEFT JOIN
(SELECT MATERIALID
  ||'_'
  ||PLANTID AS REC_ID,
  MATERIALID
  ||'_'
  ||EXPECTED_SHIP_PLANT_1 AS DELI_ID,
  SPC_PROC_KEY_SOBSL_VE_1,
  VENDOR_NAME_VE_1,
  EXPECTED_SHIP_PLANT_1
FROM INV_SAP_VENDOR_PLANT_INFO
)INV_VENDOR_INFO_1
ON INV_VENDOR_INFO_1.REC_ID = OPEN_STO_MTL.REC_ID
)MTL_VEND_INFO_1
LEFT JOIN
(SELECT MATERIALID||'_'||PLANTID AS ID,MRP_TYPE,STRATEGY_GRP FROM INV_SAP_PP_OPTIMIZATION )PP_ITEM
ON PP_ITEM.ID = MTL_VEND_INFO_1.DELI_ID;
 

--VIEW_INV_DIG_VENDOR_2
CREATE VIEW VIEW_INV_DIG_VENDOR_2 AS
SELECT 
MTL_VEND_INFO_2.REC_ID AS REC_ID,
MTL_VEND_INFO_2.MATERIALID AS MATERIALID,
MTL_VEND_INFO_2.PLANTID AS PLANTID,
MTL_VEND_INFO_2.EXPECTED_SHIP_PLANT_2 AS EXPECTED_SHIP_PLANT_2,
MTL_VEND_INFO_2.DELI_ID AS DELI_ID,
PP_ITEM.MRP_TYPE AS MRP_TYPE,
PP_ITEM.STRATEGY_GRP AS STRATEGY_GRP
FROM 
(
SELECT 
OPEN_STO_MTL.REC_ID AS REC_ID,
OPEN_STO_MTL.MATERIALID AS MATERIALID,
OPEN_STO_MTL.PLANTID AS PLANTID,
INV_VENDOR_INFO_2.EXPECTED_SHIP_PLANT_2 AS EXPECTED_SHIP_PLANT_2,
INV_VENDOR_INFO_2.DELI_ID AS DELI_ID
FROM 
(SELECT DISTINCT MATERIALID
  ||'_'
  ||PLANTID AS REC_ID,
  MATERIALID,
  PLANTID
FROM INV_SAP_PP_PO_HISTORY
WHERE PO_SO_SA_FLAG  = 'STO'
AND ( DELIVERYCOMPLETE NOT LIKE 'X%'
OR DELIVERYCOMPLETE   IS NULL)
)OPEN_STO_MTL 
LEFT JOIN
(SELECT MATERIALID
  ||'_'
  ||PLANTID AS REC_ID,
  MATERIALID
  ||'_'
  ||EXPECTED_SHIP_PLANT_2 AS DELI_ID,
  SPC_PROC_KEY_SOBSL_VE_2,
  VENDORS_VENDOR_NAME_2,
  EXPECTED_SHIP_PLANT_2
FROM INV_SAP_VENDOR_PLANT_INFO
)INV_VENDOR_INFO_2
ON INV_VENDOR_INFO_2.REC_ID = OPEN_STO_MTL.REC_ID
)MTL_VEND_INFO_2
LEFT JOIN
(SELECT MATERIALID||'_'||PLANTID AS ID,MRP_TYPE,STRATEGY_GRP FROM INV_SAP_PP_OPTIMIZATION )PP_ITEM
ON PP_ITEM.ID = MTL_VEND_INFO_2.DELI_ID;
 

--VIEW_INV_DIG_VENDOR_3
CREATE VIEW VIEW_INV_DIG_VENDOR_3 AS
SELECT 
MTL_VEND_INFO_3.REC_ID AS REC_ID,
MTL_VEND_INFO_3.MATERIALID AS MATERIALID,
MTL_VEND_INFO_3.PLANTID AS PLANTID,
MTL_VEND_INFO_3.EXPECTED_SHIP_PLANT_3 AS EXPECTED_SHIP_PLANT_3,
MTL_VEND_INFO_3.DELI_ID AS DELI_ID,
PP_ITEM.MRP_TYPE AS MRP_TYPE,
PP_ITEM.STRATEGY_GRP AS STRATEGY_GRP
FROM 
(
SELECT 
OPEN_STO_MTL.REC_ID AS REC_ID,
OPEN_STO_MTL.MATERIALID AS MATERIALID,
OPEN_STO_MTL.PLANTID AS PLANTID,
INV_VENDOR_INFO_3.EXPECTED_SHIP_PLANT_3 AS EXPECTED_SHIP_PLANT_3,
INV_VENDOR_INFO_3.DELI_ID AS DELI_ID
FROM 
(SELECT DISTINCT MATERIALID
  ||'_'
  ||PLANTID AS REC_ID,
  MATERIALID,
  PLANTID
FROM INV_SAP_PP_PO_HISTORY
WHERE PO_SO_SA_FLAG  = 'STO'
AND ( DELIVERYCOMPLETE NOT LIKE 'X%'
OR DELIVERYCOMPLETE   IS NULL)
)OPEN_STO_MTL 
LEFT JOIN
(SELECT MATERIALID
  ||'_'
  ||PLANTID AS REC_ID,
  MATERIALID
  ||'_'
  ||EXPECTED_SHIP_PLANT_3 AS DELI_ID,
  SPC_PROC_KEY_SOBSL_VE_3,
  VENDORS_VENDOR_NAME_3,
  EXPECTED_SHIP_PLANT_3
FROM INV_SAP_VENDOR_PLANT_INFO
)INV_VENDOR_INFO_3
ON INV_VENDOR_INFO_3.REC_ID = OPEN_STO_MTL.REC_ID
)MTL_VEND_INFO_3
LEFT JOIN
(SELECT MATERIALID||'_'||PLANTID AS ID,MRP_TYPE,STRATEGY_GRP FROM INV_SAP_PP_OPTIMIZATION )PP_ITEM
ON PP_ITEM.ID = MTL_VEND_INFO_3.DELI_ID;


--VIEW_INV_DIG_VENDOR_4
CREATE VIEW VIEW_INV_DIG_VENDOR_4 AS
SELECT 
MTL_VEND_INFO_4.REC_ID AS REC_ID,
MTL_VEND_INFO_4.MATERIALID AS MATERIALID,
MTL_VEND_INFO_4.PLANTID AS PLANTID,
MTL_VEND_INFO_4.EXPECTED_SHIP_PLANT_4 AS EXPECTED_SHIP_PLANT_4,
MTL_VEND_INFO_4.DELI_ID AS DELI_ID,
PP_ITEM.MRP_TYPE AS MRP_TYPE,
PP_ITEM.STRATEGY_GRP AS STRATEGY_GRP
FROM 
(
SELECT 
OPEN_STO_MTL.REC_ID AS REC_ID,
OPEN_STO_MTL.MATERIALID AS MATERIALID,
OPEN_STO_MTL.PLANTID AS PLANTID,
INV_VENDOR_INFO_4.EXPECTED_SHIP_PLANT_4 AS EXPECTED_SHIP_PLANT_4,
INV_VENDOR_INFO_4.DELI_ID AS DELI_ID
FROM 
(SELECT DISTINCT MATERIALID
  ||'_'
  ||PLANTID AS REC_ID,
  MATERIALID,
  PLANTID
FROM INV_SAP_PP_PO_HISTORY
WHERE PO_SO_SA_FLAG  = 'STO'
AND ( DELIVERYCOMPLETE NOT LIKE 'X%'
OR DELIVERYCOMPLETE   IS NULL)
)OPEN_STO_MTL 
LEFT JOIN
(SELECT MATERIALID
  ||'_'
  ||PLANTID AS REC_ID,
  MATERIALID
  ||'_'
  ||EXPECTED_SHIP_PLANT_4 AS DELI_ID,
  SPC_PROC_KEY_SOBSL_VE_4,
  VENDORS_VENDOR_NAME_4,
  EXPECTED_SHIP_PLANT_4
FROM INV_SAP_VENDOR_PLANT_INFO
)INV_VENDOR_INFO_4
ON INV_VENDOR_INFO_4.REC_ID = OPEN_STO_MTL.REC_ID
)MTL_VEND_INFO_4
LEFT JOIN
(SELECT MATERIALID||'_'||PLANTID AS ID,MRP_TYPE,STRATEGY_GRP FROM INV_SAP_PP_OPTIMIZATION )PP_ITEM
ON PP_ITEM.ID = MTL_VEND_INFO_4.DELI_ID;







SELECT ID,
MATERIAL,
PLANT,
FREE_TO_USE,
SUM_PO_QTY,
FREE_QTY FROM VIEW_INV_SAP_FRTU_STOCK WHERE MATERIAL = 'PN-129535' AND PLANT = '5040';

DROP VIEW VIEW_INV_DIG_VD_BLK_1;
DROP VIEW VIEW_INV_DIG_VD_BLK_2;
DROP VIEW VIEW_INV_DIG_VD_BLK_3;
DROP VIEW VIEW_INV_DIG_VD_BLK_4;

--VIEW_INV_DIG_VD_BLK_1
CREATE VIEW VIEW_INV_DIG_VD_BLK_1 AS
SELECT 
OPEN_STO_MTL_V.REC_ID AS REC_ID,
OPEN_STO_MTL_V.MATERIALID AS MATERIALID,
OPEN_STO_MTL_V.PLANTID AS PLANTID,
OPEN_STO_MTL_V.EXPECTED_SHIP_PLANT_1 AS EXPECTED_SHIP_PLANT_1,
OPEN_STO_MTL_V.DELI_ID AS DELI_ID,
OPEN_STO_MTL_V.MRP_TYPE AS MRP_TYPE,
OPEN_STO_MTL_V.STRATEGY_GRP AS STRATEGY_GRP,
OPEN_STO_MTL_V.SP_MATL_STAT_MMSTA AS SP_MATL_STAT_MMSTA,
MTL_BLOCK.SALES_ORG AS SALES_ORG,
MTL_BLOCK.D_CHAIN_BLK AS D_CHAIN_BLK,
MTL_BLOCK.DIRECT_SHIP_PLANT AS DIRECT_SHIP_PLANT,
MTL_BLOCK.PLANT AS PLANT
FROM
(
SELECT 
MTL_VEND_INFO_1.REC_ID AS REC_ID,
MTL_VEND_INFO_1.MATERIALID AS MATERIALID,
MTL_VEND_INFO_1.PLANTID AS PLANTID,
MTL_VEND_INFO_1.EXPECTED_SHIP_PLANT_1 AS EXPECTED_SHIP_PLANT_1,
MTL_VEND_INFO_1.DELI_ID AS DELI_ID,
PP_ITEM.MRP_TYPE AS MRP_TYPE,
PP_ITEM.STRATEGY_GRP AS STRATEGY_GRP,
PP_ITEM.SP_MATL_STAT_MMSTA AS SP_MATL_STAT_MMSTA
FROM 
(
SELECT 
OPEN_STO_MTL.REC_ID AS REC_ID,
OPEN_STO_MTL.MATERIALID AS MATERIALID,
OPEN_STO_MTL.PLANTID AS PLANTID,
INV_VENDOR_INFO_1.EXPECTED_SHIP_PLANT_1 AS EXPECTED_SHIP_PLANT_1,
INV_VENDOR_INFO_1.DELI_ID AS DELI_ID
FROM 
(SELECT DISTINCT MATERIALID
  ||'_'
  ||PLANTID AS REC_ID,
  MATERIALID,
  PLANTID
FROM INV_SAP_PP_PO_HISTORY
WHERE PO_SO_SA_FLAG  = 'STO'
AND ( DELIVERYCOMPLETE NOT LIKE 'X%'
OR DELIVERYCOMPLETE IS NULL)
AND LAST_SHIP_DATE    IS NULL
)OPEN_STO_MTL 
LEFT JOIN
(SELECT MATERIALID
  ||'_'
  ||PLANTID AS REC_ID,
  MATERIALID
  ||'_'
  ||EXPECTED_SHIP_PLANT_1 AS DELI_ID,
  SPC_PROC_KEY_SOBSL_VE_1,
  VENDOR_NAME_VE_1,
  EXPECTED_SHIP_PLANT_1
FROM INV_SAP_VENDOR_PLANT_INFO
)INV_VENDOR_INFO_1
ON INV_VENDOR_INFO_1.REC_ID = OPEN_STO_MTL.REC_ID
)MTL_VEND_INFO_1
LEFT JOIN
(SELECT MATERIALID||'_'||PLANTID AS ID,MRP_TYPE,STRATEGY_GRP, SP_MATL_STAT_MMSTA FROM INV_SAP_PP_OPTIMIZATION )PP_ITEM
ON PP_ITEM.ID = MTL_VEND_INFO_1.DELI_ID
)OPEN_STO_MTL_V
LEFT JOIN
(
SELECT
MTL_DELI_BLK.MATERIALID||'_'||SOG_PLANT.DELIVERY_PLANT AS DELI_ID,
MTL_DELI_BLK.MATERIALID AS MATERIALID,
MTL_DELI_BLK.SALES_ORG AS SALES_ORG,
MTL_DELI_BLK.D_CHAIN_BLK AS D_CHAIN_BLK,
MTL_DELI_BLK.DIRECT_SHIP_PLANT AS DIRECT_SHIP_PLANT,
SOG_PLANT.DELIVERY_PLANT AS PLANT
FROM 
(
SELECT DISTINCT
    MATERIALID,
    SALES_ORG,
    D_CHAIN_BLK,
    DIRECT_SHIP_PLANT
  FROM INV_SAP_PP_MVKE
)MTL_DELI_BLK 
LEFT JOIN
(
SELECT DELIVERY_PLANT,SALES_ORG FROM INV_SAP_SALES_ZDELV_PLANT WHERE SALES_ORG NOT IN ('2000','4004',
'4005',
'4006',
'4008',
'4009',
'4011',
'4013',
'4014',
'4019',
'4021',
'4022',
'4023',
'4024',
'4025',
'4026',
'4027',
'4028',
'4030',
'4100',
'4106',
'4122',
'5012',
'5019'
)
)SOG_PLANT
ON SOG_PLANT.SALES_ORG = MTL_DELI_BLK.SALES_ORG
)MTL_BLOCK
ON MTL_BLOCK.DELI_ID = OPEN_STO_MTL_V.DELI_ID;

--VIEW_INV_DIG_VD_BLK_2
CREATE VIEW VIEW_INV_DIG_VD_BLK_2 AS
SELECT 
OPEN_STO_MTL_V.REC_ID AS REC_ID,
OPEN_STO_MTL_V.MATERIALID AS MATERIALID,
OPEN_STO_MTL_V.PLANTID AS PLANTID,
OPEN_STO_MTL_V.EXPECTED_SHIP_PLANT_2 AS EXPECTED_SHIP_PLANT_2,
OPEN_STO_MTL_V.DELI_ID AS DELI_ID,
OPEN_STO_MTL_V.MRP_TYPE AS MRP_TYPE,
OPEN_STO_MTL_V.STRATEGY_GRP AS STRATEGY_GRP,
OPEN_STO_MTL_V.SP_MATL_STAT_MMSTA AS SP_MATL_STAT_MMSTA,
MTL_BLOCK.SALES_ORG AS SALES_ORG,
MTL_BLOCK.D_CHAIN_BLK AS D_CHAIN_BLK,
MTL_BLOCK.DIRECT_SHIP_PLANT AS DIRECT_SHIP_PLANT,
MTL_BLOCK.PLANT AS PLANT
FROM
(
SELECT 
MTL_VEND_INFO_2.REC_ID AS REC_ID,
MTL_VEND_INFO_2.MATERIALID AS MATERIALID,
MTL_VEND_INFO_2.PLANTID AS PLANTID,
MTL_VEND_INFO_2.EXPECTED_SHIP_PLANT_2 AS EXPECTED_SHIP_PLANT_2,
MTL_VEND_INFO_2.DELI_ID AS DELI_ID,
PP_ITEM.MRP_TYPE AS MRP_TYPE,
PP_ITEM.STRATEGY_GRP AS STRATEGY_GRP,
PP_ITEM.SP_MATL_STAT_MMSTA AS SP_MATL_STAT_MMSTA
FROM 
(
SELECT 
OPEN_STO_MTL.REC_ID AS REC_ID,
OPEN_STO_MTL.MATERIALID AS MATERIALID,
OPEN_STO_MTL.PLANTID AS PLANTID,
INV_VENDOR_INFO_2.EXPECTED_SHIP_PLANT_2 AS EXPECTED_SHIP_PLANT_2,
INV_VENDOR_INFO_2.DELI_ID AS DELI_ID
FROM 
(SELECT DISTINCT MATERIALID
  ||'_'
  ||PLANTID AS REC_ID,
  MATERIALID,
  PLANTID
FROM INV_SAP_PP_PO_HISTORY
WHERE PO_SO_SA_FLAG  = 'STO'
AND ( DELIVERYCOMPLETE NOT LIKE 'X%'
OR DELIVERYCOMPLETE   IS NULL)
)OPEN_STO_MTL 
LEFT JOIN
(SELECT MATERIALID
  ||'_'
  ||PLANTID AS REC_ID,
  MATERIALID
  ||'_'
  ||EXPECTED_SHIP_PLANT_2 AS DELI_ID,
  SPC_PROC_KEY_SOBSL_VE_2,
  VENDORS_VENDOR_NAME_2,
  EXPECTED_SHIP_PLANT_2
FROM INV_SAP_VENDOR_PLANT_INFO
)INV_VENDOR_INFO_2
ON INV_VENDOR_INFO_2.REC_ID = OPEN_STO_MTL.REC_ID
)MTL_VEND_INFO_2
LEFT JOIN
(SELECT MATERIALID||'_'||PLANTID AS ID,MRP_TYPE,STRATEGY_GRP, SP_MATL_STAT_MMSTA FROM INV_SAP_PP_OPTIMIZATION )PP_ITEM
ON PP_ITEM.ID = MTL_VEND_INFO_2.DELI_ID
)OPEN_STO_MTL_V
LEFT JOIN
(
SELECT
MTL_DELI_BLK.MATERIALID||'_'||SOG_PLANT.DELIVERY_PLANT AS DELI_ID,
MTL_DELI_BLK.MATERIALID AS MATERIALID,
MTL_DELI_BLK.SALES_ORG AS SALES_ORG,
MTL_DELI_BLK.D_CHAIN_BLK AS D_CHAIN_BLK,
MTL_DELI_BLK.DIRECT_SHIP_PLANT AS DIRECT_SHIP_PLANT,
SOG_PLANT.DELIVERY_PLANT AS PLANT
FROM 
(
SELECT DISTINCT
    MATERIALID,
    SALES_ORG,
    D_CHAIN_BLK,
    DIRECT_SHIP_PLANT
  FROM INV_SAP_PP_MVKE
)MTL_DELI_BLK 
LEFT JOIN
(
SELECT DELIVERY_PLANT,SALES_ORG FROM INV_SAP_SALES_ZDELV_PLANT WHERE SALES_ORG NOT IN ('2000','4004',
'4005',
'4006',
'4008',
'4009',
'4011',
'4013',
'4014',
'4019',
'4021',
'4022',
'4023',
'4024',
'4025',
'4026',
'4027',
'4028',
'4030',
'4100',
'4106',
'4122',
'5012',
'5019'
)
)SOG_PLANT
ON SOG_PLANT.SALES_ORG = MTL_DELI_BLK.SALES_ORG
)MTL_BLOCK
ON MTL_BLOCK.DELI_ID = OPEN_STO_MTL_V.DELI_ID;

--VIEW_INV_DIG_VD_BLK_3
CREATE VIEW VIEW_INV_DIG_VD_BLK_3 AS
SELECT 
OPEN_STO_MTL_V.REC_ID AS REC_ID,
OPEN_STO_MTL_V.MATERIALID AS MATERIALID,
OPEN_STO_MTL_V.PLANTID AS PLANTID,
OPEN_STO_MTL_V.EXPECTED_SHIP_PLANT_3 AS EXPECTED_SHIP_PLANT_3,
OPEN_STO_MTL_V.DELI_ID AS DELI_ID,
OPEN_STO_MTL_V.MRP_TYPE AS MRP_TYPE,
OPEN_STO_MTL_V.STRATEGY_GRP AS STRATEGY_GRP,
OPEN_STO_MTL_V.SP_MATL_STAT_MMSTA AS SP_MATL_STAT_MMSTA,
MTL_BLOCK.SALES_ORG AS SALES_ORG,
MTL_BLOCK.D_CHAIN_BLK AS D_CHAIN_BLK,
MTL_BLOCK.DIRECT_SHIP_PLANT AS DIRECT_SHIP_PLANT,
MTL_BLOCK.PLANT AS PLANT
FROM
(
SELECT 
MTL_VEND_INFO_3.REC_ID AS REC_ID,
MTL_VEND_INFO_3.MATERIALID AS MATERIALID,
MTL_VEND_INFO_3.PLANTID AS PLANTID,
MTL_VEND_INFO_3.EXPECTED_SHIP_PLANT_3 AS EXPECTED_SHIP_PLANT_3,
MTL_VEND_INFO_3.DELI_ID AS DELI_ID,
PP_ITEM.MRP_TYPE AS MRP_TYPE,
PP_ITEM.STRATEGY_GRP AS STRATEGY_GRP,
PP_ITEM.SP_MATL_STAT_MMSTA AS SP_MATL_STAT_MMSTA
FROM 
(
SELECT 
OPEN_STO_MTL.REC_ID AS REC_ID,
OPEN_STO_MTL.MATERIALID AS MATERIALID,
OPEN_STO_MTL.PLANTID AS PLANTID,
INV_VENDOR_INFO_3.EXPECTED_SHIP_PLANT_3 AS EXPECTED_SHIP_PLANT_3,
INV_VENDOR_INFO_3.DELI_ID AS DELI_ID
FROM 
(SELECT DISTINCT MATERIALID
  ||'_'
  ||PLANTID AS REC_ID,
  MATERIALID,
  PLANTID
FROM INV_SAP_PP_PO_HISTORY
WHERE PO_SO_SA_FLAG  = 'STO'
AND ( DELIVERYCOMPLETE NOT LIKE 'X%'
OR DELIVERYCOMPLETE   IS NULL)
)OPEN_STO_MTL 
LEFT JOIN
(SELECT MATERIALID
  ||'_'
  ||PLANTID AS REC_ID,
  MATERIALID
  ||'_'
  ||EXPECTED_SHIP_PLANT_3 AS DELI_ID,
  SPC_PROC_KEY_SOBSL_VE_3,
  VENDORS_VENDOR_NAME_3,
  EXPECTED_SHIP_PLANT_3
FROM INV_SAP_VENDOR_PLANT_INFO
)INV_VENDOR_INFO_3
ON INV_VENDOR_INFO_3.REC_ID = OPEN_STO_MTL.REC_ID
)MTL_VEND_INFO_3
LEFT JOIN
(SELECT MATERIALID||'_'||PLANTID AS ID,MRP_TYPE,STRATEGY_GRP, SP_MATL_STAT_MMSTA FROM INV_SAP_PP_OPTIMIZATION )PP_ITEM
ON PP_ITEM.ID = MTL_VEND_INFO_3.DELI_ID
)OPEN_STO_MTL_V
LEFT JOIN
(
SELECT
MTL_DELI_BLK.MATERIALID||'_'||SOG_PLANT.DELIVERY_PLANT AS DELI_ID,
MTL_DELI_BLK.MATERIALID AS MATERIALID,
MTL_DELI_BLK.SALES_ORG AS SALES_ORG,
MTL_DELI_BLK.D_CHAIN_BLK AS D_CHAIN_BLK,
MTL_DELI_BLK.DIRECT_SHIP_PLANT AS DIRECT_SHIP_PLANT,
SOG_PLANT.DELIVERY_PLANT AS PLANT
FROM 
(
SELECT DISTINCT
    MATERIALID,
    SALES_ORG,
    D_CHAIN_BLK,
    DIRECT_SHIP_PLANT
  FROM INV_SAP_PP_MVKE
)MTL_DELI_BLK 
LEFT JOIN
(
SELECT DELIVERY_PLANT,SALES_ORG FROM INV_SAP_SALES_ZDELV_PLANT WHERE SALES_ORG NOT IN ('2000','4004',
'4005',
'4006',
'4008',
'4009',
'4011',
'4013',
'4014',
'4019',
'4021',
'4022',
'4023',
'4024',
'4025',
'4026',
'4027',
'4028',
'4030',
'4100',
'4106',
'4122',
'5012',
'5019'
)
)SOG_PLANT
ON SOG_PLANT.SALES_ORG = MTL_DELI_BLK.SALES_ORG
)MTL_BLOCK
ON MTL_BLOCK.DELI_ID = OPEN_STO_MTL_V.DELI_ID;

--VIEW_INV_DIG_VD_BLK_4
SELECT * FROM VIEW_INV_DIG_VD_BLK_4 WHERE MATERIALID = 'PN-88469'
CREATE VIEW VIEW_INV_DIG_VD_BLK_4 AS
SELECT 
OPEN_STO_MTL_V.REC_ID AS REC_ID,
OPEN_STO_MTL_V.MATERIALID AS MATERIALID,
OPEN_STO_MTL_V.PLANTID AS PLANTID,
OPEN_STO_MTL_V.EXPECTED_SHIP_PLANT_4 AS EXPECTED_SHIP_PLANT_4,
OPEN_STO_MTL_V.DELI_ID AS DELI_ID,
OPEN_STO_MTL_V.MRP_TYPE AS MRP_TYPE,
OPEN_STO_MTL_V.STRATEGY_GRP AS STRATEGY_GRP,
OPEN_STO_MTL_V.SP_MATL_STAT_MMSTA AS SP_MATL_STAT_MMSTA,
MTL_BLOCK.SALES_ORG AS SALES_ORG,
MTL_BLOCK.D_CHAIN_BLK AS D_CHAIN_BLK,
MTL_BLOCK.DIRECT_SHIP_PLANT AS DIRECT_SHIP_PLANT,
MTL_BLOCK.PLANT AS PLANT
FROM
(
SELECT 
MTL_VEND_INFO_4.REC_ID AS REC_ID,
MTL_VEND_INFO_4.MATERIALID AS MATERIALID,
MTL_VEND_INFO_4.PLANTID AS PLANTID,
MTL_VEND_INFO_4.EXPECTED_SHIP_PLANT_4 AS EXPECTED_SHIP_PLANT_4,
MTL_VEND_INFO_4.DELI_ID AS DELI_ID,
PP_ITEM.MRP_TYPE AS MRP_TYPE,
PP_ITEM.STRATEGY_GRP AS STRATEGY_GRP,
PP_ITEM.SP_MATL_STAT_MMSTA AS SP_MATL_STAT_MMSTA
FROM 
(
SELECT 
OPEN_STO_MTL.REC_ID AS REC_ID,
OPEN_STO_MTL.MATERIALID AS MATERIALID,
OPEN_STO_MTL.PLANTID AS PLANTID,
INV_VENDOR_INFO_4.EXPECTED_SHIP_PLANT_4 AS EXPECTED_SHIP_PLANT_4,
INV_VENDOR_INFO_4.DELI_ID AS DELI_ID
FROM 
(SELECT DISTINCT MATERIALID
  ||'_'
  ||PLANTID AS REC_ID,
  MATERIALID,
  PLANTID
FROM INV_SAP_PP_PO_HISTORY
WHERE PO_SO_SA_FLAG  = 'STO'
AND ( DELIVERYCOMPLETE NOT LIKE 'X%'
OR DELIVERYCOMPLETE   IS NULL)
)OPEN_STO_MTL 
LEFT JOIN
(SELECT MATERIALID
  ||'_'
  ||PLANTID AS REC_ID,
  MATERIALID
  ||'_'
  ||EXPECTED_SHIP_PLANT_4 AS DELI_ID,
  SPC_PROC_KEY_SOBSL_VE_4,
  VENDORS_VENDOR_NAME_4,
  EXPECTED_SHIP_PLANT_4
FROM INV_SAP_VENDOR_PLANT_INFO
)INV_VENDOR_INFO_4
ON INV_VENDOR_INFO_4.REC_ID = OPEN_STO_MTL.REC_ID
)MTL_VEND_INFO_4
LEFT JOIN
(SELECT MATERIALID||'_'||PLANTID AS ID,MRP_TYPE,STRATEGY_GRP, SP_MATL_STAT_MMSTA FROM INV_SAP_PP_OPTIMIZATION )PP_ITEM
ON PP_ITEM.ID = MTL_VEND_INFO_4.DELI_ID
)OPEN_STO_MTL_V
LEFT JOIN
(
SELECT
MTL_DELI_BLK.MATERIALID||'_'||SOG_PLANT.DELIVERY_PLANT AS DELI_ID,
MTL_DELI_BLK.MATERIALID AS MATERIALID,
MTL_DELI_BLK.SALES_ORG AS SALES_ORG,
MTL_DELI_BLK.D_CHAIN_BLK AS D_CHAIN_BLK,
MTL_DELI_BLK.DIRECT_SHIP_PLANT AS DIRECT_SHIP_PLANT,
SOG_PLANT.DELIVERY_PLANT AS PLANT
FROM 
(
SELECT DISTINCT
    MATERIALID,
    SALES_ORG,
    D_CHAIN_BLK,
    DIRECT_SHIP_PLANT
  FROM INV_SAP_PP_MVKE 
)MTL_DELI_BLK 
LEFT JOIN
(
SELECT DELIVERY_PLANT,SALES_ORG FROM INV_SAP_SALES_ZDELV_PLANT WHERE SALES_ORG NOT IN ('2000','4004',
'4005',
'4006',
'4008',
'4009',
'4011',
'4013',
'4014',
'4019',
'4021',
'4022',
'4023',
'4024',
'4025',
'4026',
'4027',
'4028',
'4030',
'4100',
'4106',
'4122',
'5012',
'5019'
)
)SOG_PLANT
ON SOG_PLANT.SALES_ORG = MTL_DELI_BLK.SALES_ORG
)MTL_BLOCK
ON MTL_BLOCK.DELI_ID = OPEN_STO_MTL_V.DELI_ID;


DROP TABLE INV_DIG_VD_BLK_1;
DROP TABLE INV_DIG_VD_BLK_2;
DROP TABLE INV_DIG_VD_BLK_3;
DROP TABLE INV_DIG_VD_BLK_4;
CREATE TABLE INV_DIG_VD_BLK_1 AS
SELECT * FROM VIEW_INV_DIG_VD_BLK_1;
CREATE TABLE INV_DIG_VD_BLK_2 AS
SELECT * FROM VIEW_INV_DIG_VD_BLK_2;
CREATE TABLE INV_DIG_VD_BLK_3 AS
SELECT * FROM VIEW_INV_DIG_VD_BLK_3;
CREATE TABLE INV_DIG_VD_BLK_4 AS
SELECT * FROM VIEW_INV_DIG_VD_BLK_4;

---RESULT
SELECT
DISTINCT
VD_BLK_1.REC_ID,
VD_BLK_1.MATERIALID,
VD_BLK_1.PLANTID,
VD_BLK_1.EXPECTED_SHIP_PLANT_1,
VD_BLK_1.MRP_TYPE,
VD_BLK_1.STRATEGY_GRP,
VD_BLK_1.D_CHAIN_BLK,
VD_BLK_1.SP_MATL_STAT_MMSTA,
VD_BLK_2.EXPECTED_SHIP_PLANT_2,
VD_BLK_2.MRP_TYPE,
VD_BLK_2.STRATEGY_GRP,
VD_BLK_2.D_CHAIN_BLK,
VD_BLK_2.SP_MATL_STAT_MMSTA,
VD_BLK_3.EXPECTED_SHIP_PLANT_3,
VD_BLK_3.MRP_TYPE,
VD_BLK_3.STRATEGY_GRP,
VD_BLK_3.D_CHAIN_BLK,
VD_BLK_3.SP_MATL_STAT_MMSTA,
VD_BLK_4.EXPECTED_SHIP_PLANT_4,
VD_BLK_4.MRP_TYPE,
VD_BLK_4.STRATEGY_GRP,
VD_BLK_4.D_CHAIN_BLK,
VD_BLK_4.SP_MATL_STAT_MMSTA
FROM INV_DIG_VD_BLK_1 VD_BLK_1,
    INV_DIG_VD_BLK_2 VD_BLK_2,
    INV_DIG_VD_BLK_3 VD_BLK_3,
    INV_DIG_VD_BLK_4 VD_BLK_4
WHERE VD_BLK_1.REC_ID = VD_BLK_2.REC_ID AND
VD_BLK_2.REC_ID = VD_BLK_3.REC_ID AND
VD_BLK_3.REC_ID = VD_BLK_4.REC_ID AND
((VD_BLK_1.D_CHAIN_BLK IS NOT NULL AND VD_BLK_1.D_CHAIN_BLK NOT IN ('ZG','ZN'))OR
(VD_BLK_2.D_CHAIN_BLK IS NOT NULL AND VD_BLK_2.D_CHAIN_BLK NOT IN ('ZG','ZN'))OR
(VD_BLK_3.D_CHAIN_BLK IS NOT NULL AND VD_BLK_3.D_CHAIN_BLK NOT IN ('ZG','ZN'))OR
(VD_BLK_4.D_CHAIN_BLK IS NOT NULL AND VD_BLK_4.D_CHAIN_BLK NOT IN ('ZG','ZN')))AND
(VD_BLK_1.SP_MATL_STAT_MMSTA NOT IN('ZG','ZA','ZN') OR
VD_BLK_2.SP_MATL_STAT_MMSTA NOT IN('ZG','ZA','ZN') OR
VD_BLK_3.SP_MATL_STAT_MMSTA NOT IN('ZG','ZA','ZN') OR
VD_BLK_4.SP_MATL_STAT_MMSTA NOT IN('ZG','ZA','ZN'));



