-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- Project Name : APAFC
-- Version : 1.0
-- Description:
-- Table Init
-- Revision History:
--    Date        Developer         Description
--    ---------   ---------------   ----------------------------------------------------
--    2014-1-27  Moyue           	Weekly table update for mvk and item master.
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE APAFC_ITEM_SOG AUTHID CURRENT_USER
IS
STEP_NAME VARCHAR2(100);
PROCESS_TERMINATED EXCEPTION;
COUNT_MVK NUMBER;
COUNT_ITEM_SOG_X NUMBER;
COUNT_ITEM_SOG_ALL NUMBER;
BEGIN
	STEP_NAME := 'Weekly item, mvk, sog_x update...';
  
  --Remove the dash.
  APAFC_REMOVE_DASH;
  
	SELECT COUNT(*) INTO COUNT_MVK FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_PP_MVKE';
	SELECT COUNT(*) INTO COUNT_ITEM_SOG_X FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_ITEM_SOG_X';
	SELECT COUNT(*) INTO COUNT_ITEM_SOG_ALL FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_ITEM_SOG_ALL';
  
  --Update mvk table.
  IF COUNT_MVK > 0 THEN
    APAFC_TRUNCATE('INV_SAP_PP_MVKE');
	  COMMIT;
		APAFC_SCRIPT_EXE_IMMEDIATE('INSERT INTO INV_SAP_PP_MVKE SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE@ROCKWELL_DW_DBLINK');
    COMMIT;
  ELSE
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE INV_SAP_PP_MVKE AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE@ROCKWELL_DW_DBLINK');
    COMMIT;
  END IF;

  IF COUNT_ITEM_SOG_X > 0 THEN
    APAFC_TRUNCATE('INV_SAP_ITEM_SOG_X');
	  COMMIT;
		APAFC_INSERT('VIEW_INV_SAP_ITEM_SOG_X','INV_SAP_ITEM_SOG_X');
    COMMIT;
  ELSE
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE INV_SAP_ITEM_SOG_X AS SELECT * FROM VIEW_INV_SAP_ITEM_SOG_X');
    COMMIT;
  END IF;
  
  
  IF COUNT_ITEM_SOG_ALL > 0 THEN
    APAFC_TRUNCATE('INV_SAP_ITEM_SOG_ALL');
	  COMMIT;
		APAFC_INSERT('VIEW_INV_SAP_ITEM_SOG_ALL','INV_SAP_ITEM_SOG_ALL');
    COMMIT;
  ELSE
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE INV_SAP_ITEM_SOG_ALL AS SELECT * FROM VIEW_INV_SAP_ITEM_SOG_ALL');
    COMMIT;
  END IF;
 
EXCEPTION
WHEN OTHERS THEN
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Execute Error:');
  DBMS_OUTPUT.PUT_LINE(SUBSTR(DBMS_UTILITY.FORMAT_ERROR_STACK,1,200)||SUBSTR(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,1,200));
  RAISE PROCESS_TERMINATED;
END APAFC_ITEM_SOG;
	
CREATE OR REPLACE PROCEDURE APAFC_ITEM_CATALOG AUTHID CURRENT_USER
IS
STEP_NAME VARCHAR2(100);
PROCESS_TERMINATED EXCEPTION;
COUNT_NODASH_MTL NUMBER;
COUNT_ITEM_CATA NUMBER;
BEGIN
	STEP_NAME := 'Weekly Item-Catalog table update...';
  
	SELECT COUNT(*) INTO COUNT_NODASH_MTL FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_NODASH_MAT_CATA';
	SELECT COUNT(*) INTO COUNT_ITEM_CATA FROM USER_TABLES WHERE TABLE_NAME = 'INV_SAP_MATERIAL_CATALOG';
  
  IF COUNT_ITEM_CATA > 0 THEN
    APAFC_DROP('INV_SAP_MATERIAL_CATALOG','TABLE');
    COMMIT;
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE INV_SAP_MATERIAL_CATALOG AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG@ROCKWELL_DW_DBLINK');
    COMMIT;
  ELSE
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE INV_SAP_MATERIAL_CATALOG AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG@ROCKWELL_DW_DBLINK');
    COMMIT;
  END IF;
  
  IF COUNT_NODASH_MTL > 0 THEN
    APAFC_DROP('INV_SAP_NODASH_MAT_CATA','TABLE');
    COMMIT;
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE INV_SAP_NODASH_MAT_CATA AS SELECT * FROM INV_SAP_MATERIAL_CATALOG');
    COMMIT;
  ELSE
    APAFC_SCRIPT_EXE_IMMEDIATE('CREATE TABLE INV_SAP_NODASH_MAT_CATA AS SELECT * FROM INV_SAP_MATERIAL_CATALOG');
    COMMIT;
  END IF;
  COMMIT;
EXCEPTION
WHEN OTHERS THEN
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Execute Error:');
  DBMS_OUTPUT.PUT_LINE(SUBSTR(DBMS_UTILITY.FORMAT_ERROR_STACK,1,200)||SUBSTR(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,1,200));
  RAISE PROCESS_TERMINATED;
END APAFC_ITEM_CATALOG;

CREATE OR REPLACE PROCEDURE APAFC_REMOVE_DASH AUTHID CURRENT_USER
IS
  CURSOR cur
  IS
    SELECT a.CATALOG_STRING1,
      b.ROWID ROW_ID
    FROM INV_SAP_MATERIAL_CATALOG a,
      INV_SAP_NODASH_MAT_CATA b
    WHERE a.MATERIALID = b.MATERIALID
    ORDER BY b.ROWID; 
  V_COUNTER NUMBER;
BEGIN
  V_COUNTER := 0;
  FOR row IN cur
  LOOP
    UPDATE INV_SAP_NODASH_MAT_CATA
    SET CATALOG_STRING2 = REPLACE(row.CATALOG_STRING1, '-')
    WHERE ROWID         = row.ROW_ID;
    V_COUNTER          := V_COUNTER + 1;
    IF (V_COUNTER      >= 1000) THEN
      COMMIT;
      V_COUNTER := 0;
    END IF;
  END LOOP;
  COMMIT;
END APAFC_REMOVE_DASH;
    
    
truncate table INV_SAP_MATERIAL_CATALOG;
drop table INV_SAP_MATERIAL_CATALOG;
drop table INV_SAP_NODASH_MAT_CATA;
drop table INV_SAP_ITEM_SOG_ALL;
drop table INV_SAP_ITEM_SOG_X;
drop table INV_SAP_PP_MVKE;
select * from INV_SAP_ITEM_SOG_X;


begin
APAFC_REMOVE_DASH;
end;